import { createFoundationLesson } from "./lesson-factory";

export const lesson11 = createFoundationLesson({
  id: "1.1", moduleId: "module-01", title: "Why Spanish Nouns Have Gender", displayTitle: "A Spanish noun brings a grammatical category with it.",
  dek: "Gender is part of how the noun behaves inside a phrase. It is not a claim that every object is male or female.",
  goal: "Treat grammatical gender as a noun category and use an article to identify a noun as masculine or feminine.", durationMinutes: 24, concepts: ["noun_gender", "articles_definite"],
  opening: { eyebrow: "The hidden information", heading: "Learn the noun with the small word beside it.", paragraphs: ["English often lets a noun stand alone without changing nearby words. Spanish noun phrases are more connected: the noun belongs to a grammatical gender, and articles and many adjectives respond to that category.", "El libro is masculine; la mesa is feminine. The physical objects are not being described as male or female. Libro and mesa simply belong to two grammatical classes.", "Gender becomes useful because it predicts the form of other words. Learning el libro instead of isolated libro stores the category where you can hear and see it."], spanish: [{ text: "el libro", translation: "the book" }, { text: "la mesa", translation: "the table" }, { text: "el problema", translation: "the problem" }, { text: "la mano", translation: "the hand" }] },
  prediction: { eyebrow: "Read the phrase", heading: "The phrase is la mesa.", context: "The article la carries grammatical information about mesa.", prompt: "What does la tell you?", options: [{ id: "feminine", label: "Mesa is grammatically feminine" }, { id: "person", label: "The table is a woman" }, { id: "plural", label: "There is more than one table" }], correctOptionId: "feminine", correctFeedback: "La marks a singular feminine noun phrase. The category controls grammar; it does not assign biological sex to the object.", incorrectFeedback: "Read la as grammatical evidence: singular feminine. It does not describe the object as female." },
  model: { eyebrow: "A phrase-level system", heading: "The noun is the center; nearby words coordinate with it.", paragraphs: ["A noun names a person, place, thing, or idea. In Spanish, the lexical entry includes gender. You will often see that information through el for masculine singular or la for feminine singular.", "The article is not the gender itself; it reveals the noun’s category in this phrase. That distinction matters because other determiners can replace el or la while the noun keeps its gender.", "Some endings provide strong patterns, but no single ending decides every noun. Treat a noun’s article as part of the word you are learning."], points: [{ label: "NOUN", title: "libro", description: "Names the thing and carries masculine gender." }, { label: "ARTICLE", title: "el", description: "Marks the phrase as definite, masculine, and singular." }, { label: "PHRASE", title: "el libro", description: "Packages both pieces into one identifiable unit." }] },
  contrast: { eyebrow: "Grammar, not biology", heading: "Natural gender and grammatical gender are different systems.", sides: [{ label: "PERSON", question: "Can meaning align with gender?", description: "Words for people may reflect the person being described.", examples: [{ text: "el hermano", translation: "the brother" }, { text: "la hermana", translation: "the sister" }] }, { label: "OBJECT / IDEA", question: "Is the category grammatical?", description: "Objects and abstract ideas still belong to a noun class.", examples: [{ text: "la ciudad", translation: "the city" }, { text: "el tiempo", translation: "time / weather" }] }], note: "Do not search for a masculine or feminine quality in an object. Learn how the Spanish noun behaves." },
  guided: { eyebrow: "Use article evidence", heading: "You encounter el mapa in a sentence.", prompt: "What can you safely conclude from el?", options: [{ id: "masculine", label: "Mapa is masculine singular here" }, { id: "o-rule", label: "Every word ending in a is feminine" }, { id: "male-map", label: "The map is biologically male" }], correctOptionId: "masculine", correctFeedback: "El directly reveals a masculine singular noun phrase, even though mapa ends in a.", incorrectFeedback: "The article gives stronger evidence than an ending guess: el mapa is masculine singular." },
  sort: { eyebrow: "Read the article", heading: "Sort complete noun phrases by grammatical gender.", prompt: "Place each phrase under the category shown by its article.", buckets: [{ id: "masculine", label: "MASCULINE", hint: "el" }, { id: "feminine", label: "FEMININE", hint: "la" }], items: [{ id: "book", label: "el libro", answer: "masculine" }, { id: "city", label: "la ciudad", answer: "feminine" }, { id: "map", label: "el mapa", answer: "masculine" }, { id: "hand", label: "la mano", answer: "feminine" }, { id: "problem", label: "el problema", answer: "masculine" }, { id: "house", label: "la casa", answer: "feminine" }] },
  builder: { eyebrow: "Build the unit", heading: "Keep the noun and its gender signal together.", prompt: "Build the complete phrase: the book.", tokens: ["el", "libro"], correctOrder: ["el", "libro"], answer: "el libro", feedback: "El marks libro as a definite masculine singular noun phrase." },
  reading: { eyebrow: "Gender in a scene", heading: "Articles make the nouns easier to track.", instructions: "Listen or read, then identify the noun phrase that answers each question.", sentences: [{ id: "r1", text: "El libro está en la mesa.", translation: "The book is on the table." }, { id: "r2", text: "La mochila está en el carro.", translation: "The backpack is in the car." }, { id: "r3", text: "El mapa está en la mochila.", translation: "The map is in the backpack." }], questions: [{ id: "q1", prompt: "Which feminine noun phrase names the surface?", options: [{ id: "mesa", label: "la mesa" }, { id: "libro", label: "el libro" }], correctOptionId: "mesa", feedback: "La identifies mesa as feminine singular.", conceptIds: ["noun_gender", "articles_definite"] }, { id: "q2", prompt: "Which a-ending noun is masculine?", options: [{ id: "mapa", label: "el mapa" }, { id: "mochila", label: "la mochila" }], correctOptionId: "mapa", feedback: "El mapa shows why the complete phrase is better evidence than the final letter alone.", conceptIds: ["noun_gender"] }] },
  recall: { eyebrow: "Retrieve the article", heading: "Complete each learned noun phrase.", prompt: "Type el or la from memory.", items: [{ id: "libro", before: "", after: " libro", accepted: ["el"], answer: "el", conceptIds: ["noun_gender", "articles_definite"], feedback: "El libro is masculine singular." }, { id: "mesa", before: "", after: " mesa", accepted: ["la"], answer: "la", conceptIds: ["noun_gender", "articles_definite"], feedback: "La mesa is feminine singular." }, { id: "mapa", before: "", after: " mapa", accepted: ["el"], answer: "el", conceptIds: ["noun_gender", "articles_definite"], feedback: "El mapa is a useful exception to an overgeneralized ending guess." }] },
  production: { eyebrow: "Store complete phrases", heading: "Write three noun observations.", prompt: "Write three separate short ideas. Include el libro, la mesa, and one additional complete noun phrase from the lesson.", requirements: ["Use el libro", "Use la mesa", "Use another el or la phrase", "Write three separate ideas"], example: "El libro está aquí. La mesa está en casa. El mapa está en la mochila.", minimumCharacters: 55, evaluation: { minimumIdeas: 3, requiredGroups: [{ accepted: ["el libro"], missingFeedback: "Add the complete phrase el libro." }, { accepted: ["la mesa"], missingFeedback: "Add the complete phrase la mesa." }, { accepted: ["el mapa", "la casa", "la ciudad", "la mochila", "el carro"], missingFeedback: "Add one more complete noun phrase from the lesson." }], successFeedback: "You used articles as part of the noun phrases rather than treating gender as an abstract label." } },
  summary: { eyebrow: "Keep the principle", heading: "Gender belongs to the grammar of the noun.", message: "Learn a new noun with an article. The complete phrase gives you evidence that an isolated ending may not.", ideas: [{ label: "EL", question: "Which category?", uses: ["masculine", "singular"] }, { label: "LA", question: "Which category?", uses: ["feminine", "singular"] }, { label: "NOUN PHRASE", question: "What should I store?", uses: ["article + noun", "usable grammar"] }] },
  completion: { title: "Gender is now a grammatical system, not an object label.", message: "Next, you will use strong patterns without turning them into unreliable guesses." },
});

export const lesson12 = createFoundationLesson({
  id: "1.2", moduleId: "module-01", title: "Gender Patterns Without Guessing", displayTitle: "Use endings as evidence—not as permission to guess.",
  dek: "Several noun endings strongly predict gender. Exceptions still belong with the article you learned.",
  goal: "Use high-value noun-ending patterns while prioritizing article evidence and remembering common exceptions.", durationMinutes: 25, concepts: ["noun_gender", "gender_patterns", "articles_definite"],
  opening: { eyebrow: "Probabilities with boundaries", heading: "A pattern is useful when you know how far to trust it.", paragraphs: ["Many nouns ending in -o are masculine and many ending in -a are feminine. That is a productive first pattern, not a universal law.", "Other endings provide stronger families: nouns ending in -ción, -sión, and -dad are usually feminine. Many Greek-origin nouns ending in -ma are masculine.", "When an article is present, it outranks your guess. When learning a new word, store the noun with its article so the exception becomes ordinary memory rather than a surprise."], spanish: [{ text: "el libro", translation: "the book" }, { text: "la casa", translation: "the house" }, { text: "la nación", translation: "the nation" }, { text: "la ciudad", translation: "the city" }, { text: "el problema", translation: "the problem" }] },
  prediction: { eyebrow: "A strong family", heading: "The new word is conversación.", context: "It ends in -ción.", prompt: "Which article is the strongest prediction?", options: [{ id: "la", label: "la" }, { id: "el", label: "el" }], correctOptionId: "la", correctFeedback: "Nouns ending in -ción are characteristically feminine: la conversación.", incorrectFeedback: "Treat -ción as a strong feminine pattern: la conversación." },
  model: { eyebrow: "Build a ranked strategy", heading: "Direct evidence first, ending patterns second.", paragraphs: ["If you see el or la, use it. The phrase has already told you the category. If no article appears, a high-value ending can support a prediction while you confirm the noun.", "The broad -o/-a pattern helps with many common nouns: el libro, la casa. The -ción/-sión/-dad families give strong feminine evidence: la canción, la decisión, la ciudad.", "The -ma family prevents a common overcorrection: el problema, el sistema, el programa. Learn la mano and el día as individual high-frequency exceptions."], points: [{ label: "-O / -A", title: "useful first clue", description: "el libro, la casa—then confirm" }, { label: "-CIÓN / -SIÓN / -DAD", title: "strong feminine families", description: "la canción, la decisión, la ciudad" }, { label: "-MA", title: "often masculine Greek-origin nouns", description: "el problema, el sistema, el programa" }, { label: "LEXICAL", title: "learn the exception", description: "la mano, el día" }] },
  contrast: { eyebrow: "Clue versus answer", heading: "An ending predicts; an article identifies.", sides: [{ label: "PREDICTION", question: "No article available?", description: "Use a strong pattern provisionally and verify when possible.", examples: [{ text: "una conversación", translation: "a conversation" }] }, { label: "DIRECT EVIDENCE", question: "Article visible?", description: "Let the actual phrase override a surface guess.", examples: [{ text: "el problema", translation: "the problem" }, { text: "la mano", translation: "the hand" }] }], note: "Good learners use patterns aggressively and revise them quickly when direct evidence appears." },
  guided: { eyebrow: "Respect the article", heading: "You read el problema.", context: "Problema ends in -a, but the phrase includes el.", prompt: "Which description is accurate?", options: [{ id: "masculine", label: "A masculine noun in a common -ma family" }, { id: "mistake", label: "The article must be a typo" }, { id: "feminine", label: "A feminine noun because it ends in a" }], correctOptionId: "masculine", correctFeedback: "El provides direct evidence, and problema belongs to the common masculine -ma family.", incorrectFeedback: "Do not reject direct phrase evidence to protect a broad pattern. The phrase is el problema." },
  sort: { eyebrow: "Strengthen the families", heading: "Sort by the pattern or exception you should remember.", prompt: "Place each complete noun under its most useful learning family.", buckets: [{ id: "broad", label: "BROAD -O / -A", hint: "useful, confirm it" }, { id: "feminine-family", label: "FEMININE FAMILY", hint: "-ción, -sión, -dad" }, { id: "masculine-ma", label: "MASCULINE -MA", hint: "common Greek-origin group" }, { id: "individual", label: "LEARN INDIVIDUALLY", hint: "high-frequency exception" }], items: [{ id: "libro", label: "el libro", answer: "broad" }, { id: "casa", label: "la casa", answer: "broad" }, { id: "nacion", label: "la nación", answer: "feminine-family" }, { id: "ciudad", label: "la ciudad", answer: "feminine-family" }, { id: "sistema", label: "el sistema", answer: "masculine-ma" }, { id: "mano", label: "la mano", answer: "individual" }] },
  builder: { eyebrow: "Build from strong evidence", heading: "Make the definite phrase.", prompt: "Build: the important problem.", tokens: ["el", "problema"], correctOrder: ["el", "problema"], answer: "el problema", feedback: "Problema is masculine despite its -a ending; el keeps that evidence attached." },
  reading: { eyebrow: "Patterns in context", heading: "A city presents a practical problem.", instructions: "Read or listen, then identify the evidence behind each noun.", sentences: [{ id: "r1", text: "La ciudad tiene un problema.", translation: "The city has a problem." }, { id: "r2", text: "El sistema necesita una decisión.", translation: "The system needs a decision." }, { id: "r3", text: "La solución está en el programa.", translation: "The solution is in the program." }], questions: [{ id: "q1", prompt: "Which pair belongs to strong feminine ending families?", options: [{ id: "city-decision", label: "la ciudad / una decisión" }, { id: "system-program", label: "el sistema / el programa" }], correctOptionId: "city-decision", feedback: "-dad and -sión are high-value feminine patterns.", conceptIds: ["gender_patterns"] }, { id: "q2", prompt: "Which pair shows masculine -ma nouns?", options: [{ id: "system-program", label: "el sistema / el programa" }, { id: "solution-city", label: "la solución / la ciudad" }], correctOptionId: "system-program", feedback: "Sistema and programa belong to the common masculine -ma family.", conceptIds: ["gender_patterns", "noun_gender"] }] },
  recall: { eyebrow: "Retrieve the category", heading: "Complete the learned phrase.", prompt: "Type el or la.", items: [{ id: "city", before: "", after: " ciudad", accepted: ["la"], answer: "la", conceptIds: ["gender_patterns"], feedback: "-dad is a strong feminine pattern: la ciudad." }, { id: "system", before: "", after: " sistema", accepted: ["el"], answer: "el", conceptIds: ["gender_patterns"], feedback: "Sistema is a common masculine -ma noun." }, { id: "hand", before: "", after: " mano", accepted: ["la"], answer: "la", conceptIds: ["noun_gender"], feedback: "La mano is a frequent exception worth learning as a complete phrase." }] },
  production: { eyebrow: "Use the ranked strategy", heading: "Write three complete noun phrases in context.", prompt: "Write one sentence with a -ción/-sión/-dad noun, one with a masculine -ma noun, and one with la mano.", requirements: ["Use a feminine ending family", "Use el problema, el sistema, or el programa", "Use la mano", "Write three separate ideas"], example: "La ciudad es grande. El problema es importante. La mano está aquí.", minimumCharacters: 60, evaluation: { minimumIdeas: 3, requiredGroups: [{ accepted: ["la ciudad", "la nación", "la canción", "la decisión", "la solución"], missingFeedback: "Add a complete phrase from a strong feminine ending family." }, { accepted: ["el problema", "el sistema", "el programa"], missingFeedback: "Add a masculine -ma phrase." }, { accepted: ["la mano"], missingFeedback: "Add the high-frequency exception la mano." }], successFeedback: "You used two productive patterns and one stored exception with the correct article evidence." } },
  summary: { eyebrow: "Keep the hierarchy", heading: "Use patterns without becoming trapped by them.", message: "Prefer direct article evidence. Use strong endings to predict when necessary, and store exceptions as complete phrases.", ideas: [{ label: "DIRECT", question: "Is an article present?", uses: ["trust the phrase"] }, { label: "PATTERN", question: "Which ending family?", uses: ["-ción / -dad", "-ma"] }, { label: "MEMORY", question: "Is it an exception?", uses: ["la mano", "el día"] }] },
  completion: { title: "Your gender predictions now have boundaries.", message: "Next, articles will express not only gender but also number and whether a noun is being introduced or identified." },
});

export const lesson13 = createFoundationLesson({
  id: "1.3", moduleId: "module-01", title: "Un, Una, Los & Las", displayTitle: "Articles tell the listener how to find the noun.",
  dek: "Spanish articles coordinate gender and number while also signaling whether you are introducing something or pointing to an identifiable set.",
  goal: "Choose un, una, el, la, los, or las from reference, gender, and number.", durationMinutes: 26, concepts: ["articles_indefinite", "articles_definite", "noun_gender", "noun_number"],
  opening: { eyebrow: "More than a translation", heading: "An article packages three decisions before the noun arrives.", paragraphs: ["Un and una typically introduce one non-specific member of a category: un libro, una mesa. El and la point to a singular noun the listener can identify in context.", "Los and las are the plural definite forms. They identify a set: los libros, las mesas. Spanish does not use a plural form of un/una in exactly every place English uses some, so this lesson centers the clearest contrast.", "Each article agrees with the noun’s grammatical gender and number. Reference chooses the article family; the noun chooses the matching form."], spanish: [{ text: "un libro", translation: "a book" }, { text: "una mesa", translation: "a table" }, { text: "el libro", translation: "the book" }, { text: "la mesa", translation: "the table" }, { text: "los libros", translation: "the books" }, { text: "las mesas", translation: "the tables" }] },
  prediction: { eyebrow: "Introduce one thing", heading: "I need a book—no particular book has been identified.", prompt: "Which noun phrase introduces one book?", options: [{ id: "un", label: "un libro" }, { id: "el", label: "el libro" }, { id: "los", label: "los libros" }], correctOptionId: "un", correctFeedback: "Un introduces one non-specific masculine noun: un libro.", incorrectFeedback: "The message introduces one book rather than pointing to an identified book or a plural set." },
  model: { eyebrow: "A three-part decision", heading: "Reference first; agreement second.", paragraphs: ["Ask whether you are introducing one thing or identifying a known thing or set. That decision separates un/una from el/la/los/las.", "Then read the noun’s gender: libro is masculine, mesa is feminine. Finally read number: singular or plural.", "The article combines the answers. Los is not simply the plural of el in spelling; it is the masculine plural definite article. Las does the same work for feminine plural phrases."], points: [{ label: "INTRODUCE ONE", title: "un / una", description: "un libro, una mesa" }, { label: "IDENTIFY ONE", title: "el / la", description: "el libro, la mesa" }, { label: "IDENTIFY A SET", title: "los / las", description: "los libros, las mesas" }] },
  contrast: { eyebrow: "Reference changes across a conversation", heading: "Introduce first; identify afterward.", sides: [{ label: "NEW", question: "Does the listener know which one?", description: "Use an indefinite article to bring one member into the conversation.", examples: [{ text: "Hay un libro en la mesa.", translation: "There is a book on the table." }] }, { label: "IDENTIFIED", question: "Can both speakers now find it?", description: "After introduction, a definite article can point back to the same noun.", examples: [{ text: "El libro es azul.", translation: "The book is blue." }] }], note: "The noun did not change gender. The conversation changed how identifiable the referent is." },
  guided: { eyebrow: "Coordinate the set", heading: "The listener can identify several tables.", context: "Mesas is feminine plural.", prompt: "Which article identifies the set?", options: [{ id: "las", label: "las mesas" }, { id: "los", label: "los mesas" }, { id: "una", label: "una mesas" }], correctOptionId: "las", correctFeedback: "Las agrees with feminine plural mesas and marks the set as identifiable.", incorrectFeedback: "The phrase needs feminine, plural, and definite together: las mesas." },
  sort: { eyebrow: "Read the article job", heading: "Sort phrases by how they present the noun.", prompt: "Place each complete phrase under its reference job.", buckets: [{ id: "introduce", label: "INTRODUCE ONE", hint: "un / una" }, { id: "identify-one", label: "IDENTIFY ONE", hint: "el / la" }, { id: "identify-set", label: "IDENTIFY A SET", hint: "los / las" }], items: [{ id: "un-book", label: "un libro", answer: "introduce" }, { id: "una-house", label: "una casa", answer: "introduce" }, { id: "the-map", label: "el mapa", answer: "identify-one" }, { id: "the-city", label: "la ciudad", answer: "identify-one" }, { id: "the-books", label: "los libros", answer: "identify-set" }, { id: "the-tables", label: "las mesas", answer: "identify-set" }] },
  builder: { eyebrow: "Build the identified set", heading: "Coordinate feminine plural agreement.", prompt: "Build: the houses.", tokens: ["las", "casas"], correctOrder: ["las", "casas"], answer: "las casas", feedback: "Las and casas both carry feminine plural information." },
  reading: { eyebrow: "Reference develops", heading: "A small scene turns a new noun into a known one.", instructions: "Follow what is introduced and what becomes identifiable.", sentences: [{ id: "r1", text: "Hay una mochila en la mesa.", translation: "There is a backpack on the table." }, { id: "r2", text: "La mochila tiene un libro.", translation: "The backpack has a book." }, { id: "r3", text: "El libro tiene dos mapas.", translation: "The book has two maps." }, { id: "r4", text: "Los mapas son nuevos.", translation: "The maps are new." }], questions: [{ id: "q1", prompt: "Why does mochila change from una to la?", options: [{ id: "known", label: "It becomes identifiable in the conversation" }, { id: "gender", label: "It changes gender" }], correctOptionId: "known", feedback: "Una introduces the backpack; la points back to the now-identified backpack.", conceptIds: ["articles_indefinite", "articles_definite"] }, { id: "q2", prompt: "Which phrase identifies a masculine plural set?", options: [{ id: "maps", label: "los mapas" }, { id: "bag", label: "la mochila" }], correctOptionId: "maps", feedback: "Los is masculine plural definite and agrees with mapas.", conceptIds: ["articles_definite", "noun_number"] }] },
  recall: { eyebrow: "Retrieve all three decisions", heading: "Complete the article from context.", prompt: "Type the missing Spanish article.", items: [{ id: "new-table", before: "Necesito ", after: " mesa. (a table)", accepted: ["una"], answer: "una", conceptIds: ["articles_indefinite", "noun_gender"], feedback: "Una introduces one feminine noun." }, { id: "known-book", before: "", after: " libro está aquí. (the book)", accepted: ["el"], answer: "El", conceptIds: ["articles_definite", "noun_gender"], feedback: "El identifies one masculine noun." }, { id: "known-houses", before: "", after: " casas son grandes. (the houses)", accepted: ["las"], answer: "Las", conceptIds: ["articles_definite", "noun_number"], feedback: "Las identifies a feminine plural set." }] },
  production: { eyebrow: "Move from new to known", heading: "Introduce two nouns, then point back to them.", prompt: "Write at least four ideas: introduce one masculine noun with un, one feminine noun with una, then identify each with el or la. Include one plural definite phrase with los or las.", requirements: ["Use un and el", "Use una and la", "Use los or las", "Write four separate ideas"], example: "Hay un libro. El libro es nuevo. Hay una mochila. La mochila es azul. Los objetos están aquí.", minimumCharacters: 85, evaluation: { minimumIdeas: 4, requiredGroups: [{ accepted: ["un libro", "un mapa", "un problema", "un carro"], missingFeedback: "Introduce a masculine noun with un." }, { accepted: ["una mesa", "una casa", "una mochila", "una ciudad"], missingFeedback: "Introduce a feminine noun with una." }, { accepted: ["el libro", "el mapa", "el problema", "el carro", "la mesa", "la casa", "la mochila", "la ciudad"], missingFeedback: "Point back to an identified singular noun with el or la." }, { accepted: ["los libros", "los mapas", "las mesas", "las casas", "las mochilas"], missingFeedback: "Identify a plural set with los or las." }], successFeedback: "Your articles track new, known, singular, and plural referents across a short scene." } },
  summary: { eyebrow: "Keep the decision tree", heading: "Reference chooses the family; the noun chooses the form.", message: "First decide whether the noun is new or identifiable. Then coordinate gender and number.", ideas: [{ label: "UN / UNA", question: "Introducing one?", uses: ["indefinite", "singular"] }, { label: "EL / LA", question: "Identifying one?", uses: ["definite", "singular"] }, { label: "LOS / LAS", question: "Identifying a set?", uses: ["definite", "plural"] }] },
  completion: { title: "Articles now carry reference, gender, and number together.", message: "Next, you will combine those decisions into complete noun phrases without translating piece by piece." },
});

export const lesson14 = createFoundationLesson({
  id: "1.4", moduleId: "module-01", title: "Build Your First Noun Phrases", displayTitle: "Make the whole phrase agree around the noun.",
  dek: "A noun phrase is a coordinated unit: article and noun express reference, gender, and number together.",
  goal: "Build singular and plural noun phrases, form regular noun plurals, and keep article–noun agreement intact.", durationMinutes: 26, concepts: ["noun_phrase", "noun_number", "noun_gender", "articles_definite", "articles_indefinite"],
  opening: { eyebrow: "Coordinate the unit", heading: "Do not solve the article and noun as unrelated blanks.", paragraphs: ["A phrase such as las ciudades works because every visible piece supports the same message: identifiable, feminine, and plural.", "To form regular plurals, add -s after an unstressed vowel: libro → libros, casa → casas. Add -es after many consonants: ciudad → ciudades, profesor → profesores.", "The plural changes the article too. El libro cannot become el libros; the phrase must move together to los libros."], spanish: [{ text: "un libro", translation: "a book" }, { text: "el libro", translation: "the book" }, { text: "los libros", translation: "the books" }, { text: "la ciudad", translation: "the city" }, { text: "las ciudades", translation: "the cities" }] },
  prediction: { eyebrow: "Move the whole phrase", heading: "Change la ciudad to plural.", prompt: "Which phrase is fully coordinated?", options: [{ id: "las-ciudades", label: "las ciudades" }, { id: "la-ciudades", label: "la ciudades" }, { id: "los-ciudads", label: "los ciudads" }], correctOptionId: "las-ciudades", correctFeedback: "Ciudad takes -es after its final consonant, and la changes to plural las.", incorrectFeedback: "Pluralize both parts: feminine plural las + ciudades." },
  model: { eyebrow: "A build sequence", heading: "Start from meaning, then let the noun control the forms.", paragraphs: ["Choose the referent: one new thing, one identified thing, or an identified set. Choose the noun and recall its gender. Then select the article that matches all three decisions.", "If the noun is plural, form its plural spelling. Vowel endings normally add -s; many consonant endings add -es. A written z commonly changes to c before -es, a pattern you will expand later.", "Read the result as one unit. Las casas should feel like a single coordinated phrase, not two independent vocabulary answers."], points: [{ label: "01", title: "Choose the reference", description: "new one, identified one, or identified set" }, { label: "02", title: "Recall noun gender", description: "libro masculine; casa feminine" }, { label: "03", title: "Mark number", description: "-s after vowel; often -es after consonant" }, { label: "04", title: "Match the article", description: "un/una, el/la, los/las" }] },
  contrast: { eyebrow: "Two regular plural paths", heading: "The final sound controls the common plural ending.", sides: [{ label: "VOWEL + S", question: "Does the noun end in a vowel?", description: "Add -s to the noun and pluralize the article.", examples: [{ text: "el libro → los libros", translation: "the book → the books" }, { text: "la casa → las casas", translation: "the house → the houses" }] }, { label: "CONSONANT + ES", question: "Does the noun end in a consonant?", description: "Many nouns add -es, with spelling adjustments where needed.", examples: [{ text: "la ciudad → las ciudades", translation: "the city → the cities" }, { text: "el profesor → los profesores", translation: "the teacher → the teachers" }] }], note: "Plural spelling is part of agreement: the listener should be able to hear number across the phrase." },
  guided: { eyebrow: "Build from the noun", heading: "You mean the identified maps.", context: "Mapa is masculine; mapas is plural.", prompt: "Which phrase expresses the complete meaning?", options: [{ id: "los", label: "los mapas" }, { id: "las", label: "las mapas" }, { id: "el", label: "el mapas" }], correctOptionId: "los", correctFeedback: "Los matches masculine plural mapas.", incorrectFeedback: "Mapa is masculine even though it ends in -a, and the set is plural: los mapas." },
  sort: { eyebrow: "See number across the phrase", heading: "Sort complete phrases by how the noun forms its plural.", prompt: "Place each plural phrase under -s or -es.", buckets: [{ id: "s", label: "ADD -S", hint: "noun ends in a vowel" }, { id: "es", label: "ADD -ES", hint: "noun ends in a consonant" }], items: [{ id: "books", label: "los libros", answer: "s" }, { id: "houses", label: "las casas", answer: "s" }, { id: "maps", label: "los mapas", answer: "s" }, { id: "cities", label: "las ciudades", answer: "es" }, { id: "teachers", label: "los profesores", answer: "es" }, { id: "nations", label: "las naciones", answer: "es" }] },
  builder: { eyebrow: "Build the set", heading: "Coordinate article, noun, and plural spelling.", prompt: "Build: the cities.", tokens: ["las", "ciudades"], correctOrder: ["las", "ciudades"], answer: "las ciudades", feedback: "Ciudad is feminine, its consonant ending takes -es, and the plural article is las." },
  reading: { eyebrow: "Noun phrases carry a scene", heading: "Track one and many without extra explanation.", instructions: "Read or listen, then identify the coordinated phrase.", sentences: [{ id: "r1", text: "Hay una casa en la ciudad.", translation: "There is a house in the city." }, { id: "r2", text: "La casa tiene dos libros.", translation: "The house has two books." }, { id: "r3", text: "Los libros tienen mapas de varias ciudades.", translation: "The books have maps of several cities." }, { id: "r4", text: "Los mapas están en la mesa.", translation: "The maps are on the table." }], questions: [{ id: "q1", prompt: "Which phrase identifies a masculine plural set?", options: [{ id: "maps", label: "los mapas" }, { id: "house", label: "la casa" }], correctOptionId: "maps", feedback: "Los and mapas coordinate masculine plural number.", conceptIds: ["noun_phrase", "noun_number"] }, { id: "q2", prompt: "Which plural noun added -es?", options: [{ id: "cities", label: "ciudades" }, { id: "books", label: "libros" }], correctOptionId: "cities", feedback: "Ciudad ends in a consonant, so its regular plural is ciudades.", conceptIds: ["noun_number"] }] },
  recall: { eyebrow: "Retrieve the complete unit", heading: "Complete each phrase, not just the noun.", prompt: "Type the missing article or plural noun.", items: [{ id: "houses", before: "", after: " casas (the houses)", accepted: ["las"], answer: "las", conceptIds: ["noun_phrase", "noun_gender", "noun_number"], feedback: "Las matches feminine plural casas." }, { id: "cities", before: "las ", after: " (cities)", accepted: ["ciudades"], answer: "ciudades", conceptIds: ["noun_number"], feedback: "Ciudad adds -es and changes the spelling to ciudades." }, { id: "maps", before: "", after: " mapas (the maps)", accepted: ["los"], answer: "los", conceptIds: ["noun_phrase", "noun_gender"], feedback: "Mapa is masculine, so its plural phrase begins with los." }] },
  production: { eyebrow: "Describe a small inventory", heading: "Build four coordinated noun phrases in sentences.", prompt: "Write one introduced singular phrase, one identified singular phrase, one -s plural, and one -es plural.", requirements: ["Use un or una", "Use el or la", "Use a plural noun ending in -s", "Use a plural noun ending in -es"], example: "Hay una casa. La casa es nueva. Los libros están aquí. Las ciudades son grandes.", minimumCharacters: 75, evaluation: { minimumIdeas: 4, requiredGroups: [{ accepted: ["un libro", "un mapa", "una casa", "una mesa", "una ciudad"], missingFeedback: "Introduce one noun with un or una." }, { accepted: ["el libro", "el mapa", "la casa", "la mesa", "la ciudad"], missingFeedback: "Identify one singular noun with el or la." }, { accepted: ["los libros", "los mapas", "las casas", "las mesas"], missingFeedback: "Add an identified plural built with -s." }, { accepted: ["las ciudades", "los profesores", "las naciones"], missingFeedback: "Add an identified plural built with -es." }], successFeedback: "Your four noun phrases coordinate reference, gender, number, and plural spelling." } },
  summary: { eyebrow: "Keep the build order", heading: "A noun phrase moves as one grammatical unit.", message: "Choose the referent, recall gender, form number, and match the article across the complete phrase.", ideas: [{ label: "REFERENCE", question: "New or identified?", uses: ["un / una", "el / la"] }, { label: "NUMBER", question: "One or a set?", uses: ["-s", "-es"] }, { label: "AGREEMENT", question: "Do article and noun match?", uses: ["los libros", "las ciudades"] }] },
  completion: { title: "You can now build coordinated Spanish noun phrases.", message: "Module 2 adds description and makes agreement extend beyond the article." },
});

export const module01Lessons = [lesson11, lesson12, lesson13, lesson14];
