import { createFoundationLesson } from "./lesson-factory";

export const lesson21 = createFoundationLesson({
  id: "2.1", moduleId: "module-02", title: "How Adjectives Work", displayTitle: "An adjective adds a claim about a noun.",
  dek: "Spanish descriptions stay connected to the noun they describe. Meaning comes first; form and position make the connection visible.",
  goal: "Identify the noun an adjective describes and distinguish a naming word from a descriptive word.", durationMinutes: 24, concepts: ["adjective_function", "noun_phrase", "adjective_position"],
  opening: { eyebrow: "Add a second layer", heading: "The noun identifies the category; the adjective narrows the picture.", paragraphs: ["Libro tells you the kind of thing being discussed. Nuevo adds a property: a new book. The adjective does not replace the noun; it describes the noun’s referent.", "In the most useful neutral pattern for this stage, Spanish places many descriptive adjectives after the noun: un libro nuevo, una casa grande.", "The adjective may change form later to match gender and number. Before coordinating endings, always identify which noun the adjective belongs to and what contrast it creates."], spanish: [{ text: "un libro nuevo", translation: "a new book" }, { text: "una casa grande", translation: "a big house" }, { text: "la ciudad moderna", translation: "the modern city" }, { text: "el problema importante", translation: "the important problem" }] },
  prediction: { eyebrow: "Find the job", heading: "The phrase is una casa grande.", prompt: "What does grande do?", options: [{ id: "describe", label: "It describes casa" }, { id: "name", label: "It names a second object" }, { id: "article", label: "It makes the phrase definite" }], correctOptionId: "describe", correctFeedback: "Casa names the thing; grande adds a property of that same house.", incorrectFeedback: "The noun casa names the referent. Grande narrows the picture by describing it." },
  model: { eyebrow: "Read the connection", heading: "Ask one question before touching the adjective: which noun does it describe?", paragraphs: ["Adjectives can describe color, size, condition, origin, evaluation, and many other qualities. Their shared grammatical job is to add information about a noun or subject.", "In el libro interesante, interesante describes libro. In las ciudades modernas, modernas describes ciudades. Agreement will make that connection audible and visible.", "Some adjectives end in -o and have a family of forms. Others end in -e or a consonant and do not mark masculine versus feminine in the same way. Every adjective still agrees where its form allows."], points: [{ label: "NOUN", title: "libro", description: "Names the category or referent." }, { label: "ADJECTIVE", title: "interesante", description: "Adds a property to libro." }, { label: "PHRASE", title: "el libro interesante", description: "Keeps article, noun, and description connected." }] },
  contrast: { eyebrow: "Two word jobs", heading: "Naming and describing are related but not interchangeable.", sides: [{ label: "NOUN", question: "What person, place, thing, or idea?", description: "The noun is the center of the noun phrase.", examples: [{ text: "la ciudad", translation: "the city" }, { text: "el libro", translation: "the book" }] }, { label: "ADJECTIVE", question: "What is that noun like?", description: "The adjective contributes a property or classification.", examples: [{ text: "la ciudad moderna", translation: "the modern city" }, { text: "el libro nuevo", translation: "the new book" }] }], note: "A noun can be implied in some contexts, but first learn the clear full phrase where the connection is visible." },
  guided: { eyebrow: "Trace the description", heading: "Read: las mesas grandes.", prompt: "Which word is the adjective?", options: [{ id: "grandes", label: "grandes" }, { id: "mesas", label: "mesas" }, { id: "las", label: "las" }], correctOptionId: "grandes", correctFeedback: "Mesas names the objects; grandes describes their size.", incorrectFeedback: "Look for the word that answers what the tables are like: grandes." },
  sort: { eyebrow: "Separate the jobs", heading: "Sort words by their role in the phrase.", prompt: "Place each word under noun or adjective.", buckets: [{ id: "noun", label: "NOUN", hint: "names the referent" }, { id: "adjective", label: "ADJECTIVE", hint: "adds a property" }], items: [{ id: "libro", label: "libro", answer: "noun" }, { id: "ciudad", label: "ciudad", answer: "noun" }, { id: "mesa", label: "mesa", answer: "noun" }, { id: "nuevo", label: "nuevo", answer: "adjective" }, { id: "grande", label: "grande", answer: "adjective" }, { id: "interesante", label: "interesante", answer: "adjective" }] },
  builder: { eyebrow: "Build the neutral phrase", heading: "Put the description after the noun.", prompt: "Build: an interesting book.", tokens: ["un", "libro", "interesante"], correctOrder: ["un", "libro", "interesante"], answer: "un libro interesante", feedback: "Libro is the noun phrase center; interesante follows it in the neutral descriptive pattern." },
  reading: { eyebrow: "Descriptions select referents", heading: "Adjectives help a listener distinguish what matters.", instructions: "Read or listen, then connect each adjective to its noun.", sentences: [{ id: "r1", text: "Hay dos libros en la mesa.", translation: "There are two books on the table." }, { id: "r2", text: "El libro nuevo es azul.", translation: "The new book is blue." }, { id: "r3", text: "El libro viejo es rojo.", translation: "The old book is red." }, { id: "r4", text: "La mesa grande está en la cocina.", translation: "The large table is in the kitchen." }], questions: [{ id: "q1", prompt: "Which adjective distinguishes the blue book?", options: [{ id: "new", label: "nuevo" }, { id: "old", label: "viejo" }], correctOptionId: "new", feedback: "El libro nuevo is the book later described as blue.", conceptIds: ["adjective_function"] }, { id: "q2", prompt: "What does grande describe?", options: [{ id: "table", label: "la mesa" }, { id: "kitchen", label: "la cocina" }], correctOptionId: "table", feedback: "Grande is inside la mesa grande and describes the table.", conceptIds: ["adjective_function", "adjective_position"] }] },
  recall: { eyebrow: "Retrieve the descriptor", heading: "Complete the noun phrase from the meaning.", prompt: "Type the missing Spanish adjective.", items: [{ id: "new", before: "un libro ", after: " (new)", accepted: ["nuevo"], answer: "nuevo", conceptIds: ["adjective_function"], feedback: "Nuevo describes libro." }, { id: "large", before: "una casa ", after: " (big)", accepted: ["grande"], answer: "grande", conceptIds: ["adjective_function"], feedback: "Grande follows and describes casa." }, { id: "interesting", before: "el problema ", after: " (interesting)", accepted: ["interesante"], answer: "interesante", conceptIds: ["adjective_function"], feedback: "Interesante adds a property to problema." }] },
  production: { eyebrow: "Create three contrasts", heading: "Describe three different nouns.", prompt: "Write three separate noun-phrase sentences. Use nuevo or nueva, grande, and interesante after the noun they describe.", requirements: ["Use nuevo or nueva", "Use grande", "Use interesante", "Write three separate ideas"], example: "El libro nuevo está aquí. La casa grande es azul. El problema interesante es importante.", minimumCharacters: 70, evaluation: { minimumIdeas: 3, requiredGroups: [{ accepted: ["nuevo", "nueva"], missingFeedback: "Add a noun described by nuevo or nueva." }, { accepted: ["grande"], missingFeedback: "Add a noun described by grande." }, { accepted: ["interesante"], missingFeedback: "Add a noun described by interesante." }], successFeedback: "Each adjective contributes a distinct property to a visible noun phrase." } },
  summary: { eyebrow: "Keep the relationship", heading: "The noun names; the adjective describes.", message: "Find the noun first, then ask what the adjective contributes and where the neutral descriptive pattern places it.", ideas: [{ label: "NOUN", question: "What is being discussed?", uses: ["person", "place", "thing", "idea"] }, { label: "ADJECTIVE", question: "What is it like?", uses: ["quality", "classification"] }, { label: "ORDER", question: "Where does neutral description go?", uses: ["noun + adjective"] }] },
  completion: { title: "You can now see the noun–adjective relationship.", message: "Next, adjective endings will make gender agreement visible." },
});

export const lesson22 = createFoundationLesson({
  id: "2.2", moduleId: "module-02", title: "Gender Agreement", displayTitle: "The adjective reflects the noun it describes.",
  dek: "Agreement does not change the core quality. It changes the adjective form so the grammatical connection stays clear.",
  goal: "Make common -o adjectives agree in gender and recognize adjectives whose singular form does not change for masculine and feminine nouns.", durationMinutes: 25, concepts: ["adjective_gender", "adjective_agreement", "noun_gender"],
  opening: { eyebrow: "A visible connection", heading: "The description belongs to the noun, so its form responds to the noun.", paragraphs: ["Nuevo describes the same general quality in el libro nuevo and la casa nueva. The ending changes because libro is masculine and casa is feminine.", "For common adjectives ending in -o, masculine singular uses -o and feminine singular uses -a. This is agreement, not a separate vocabulary word for each object.", "Adjectives ending in -e, such as interesante or grande, normally keep the same singular form for masculine and feminine nouns. They still participate in agreement; gender is simply not marked by a changed ending."], spanish: [{ text: "el libro nuevo", translation: "the new book" }, { text: "la casa nueva", translation: "the new house" }, { text: "el libro interesante", translation: "the interesting book" }, { text: "la historia interesante", translation: "the interesting story" }] },
  prediction: { eyebrow: "Follow the noun", heading: "Complete: la mesa ___.", context: "The intended adjective is nuevo. Mesa is feminine singular.", prompt: "Which form connects to mesa?", options: [{ id: "nueva", label: "nueva" }, { id: "nuevo", label: "nuevo" }, { id: "nuevos", label: "nuevos" }], correctOptionId: "nueva", correctFeedback: "The common -o adjective changes to -a for a feminine singular noun: la mesa nueva.", incorrectFeedback: "Read the noun before the adjective. Mesa is feminine singular, so nuevo becomes nueva." },
  model: { eyebrow: "Two adjective families", heading: "Agreement depends on the adjective’s form family.", paragraphs: ["An -o adjective often displays a four-form pattern that will later include plural: nuevo, nueva, nuevos, nuevas. In this lesson, focus on singular gender.", "An -e adjective usually has one singular form for both genders: un libro interesante, una historia interesante. Many consonant-ending adjectives also keep one singular gender form, though important subpatterns will appear later.", "Do not change every final letter to a. Grande is not granda. First identify the adjective family; then apply the agreement it actually marks."], points: [{ label: "-O FAMILY", title: "nuevo → nueva", description: "Changes -o to -a with a feminine singular noun." }, { label: "-E FAMILY", title: "interesante", description: "Keeps the same singular form across grammatical gender." }, { label: "CONTROL", title: "the noun", description: "The noun being described determines the required agreement." }] },
  contrast: { eyebrow: "Change versus stability", heading: "Both families agree, but they show it differently.", sides: [{ label: "ENDING CHANGES", question: "Does the adjective end in -o?", description: "Match -o to masculine singular and -a to feminine singular.", examples: [{ text: "el carro rojo", translation: "the red car" }, { text: "la casa roja", translation: "the red house" }] }, { label: "FORM STAYS", question: "Does the adjective end in -e?", description: "Use the same singular form with either noun gender.", examples: [{ text: "el libro grande", translation: "the big book" }, { text: "la mesa grande", translation: "the big table" }] }], note: "Agreement is a relationship, not a command to make every word look identical." },
  guided: { eyebrow: "Protect the adjective family", heading: "Describe la ciudad with interesante.", prompt: "Which phrase is correct?", options: [{ id: "same", label: "la ciudad interesante" }, { id: "a", label: "la ciudad interesanta" }, { id: "o", label: "la ciudad intereso" }], correctOptionId: "same", correctFeedback: "Interesante is an -e adjective and keeps the same singular form with ciudad.", incorrectFeedback: "Do not invent a gender ending. -E adjectives like interesante normally keep one singular form." },
  sort: { eyebrow: "Choose the family first", heading: "Sort adjectives by how singular gender agreement works.", prompt: "Place each adjective under change -o/-a or same singular form.", buckets: [{ id: "change", label: "CHANGE -O / -A", hint: "nuevo / nueva" }, { id: "same", label: "SAME SINGULAR FORM", hint: "grande" }], items: [{ id: "new", label: "nuevo / nueva", answer: "change" }, { id: "red", label: "rojo / roja", answer: "change" }, { id: "small", label: "pequeño / pequeña", answer: "change" }, { id: "large", label: "grande", answer: "same" }, { id: "interesting", label: "interesante", answer: "same" }, { id: "important", label: "importante", answer: "same" }] },
  builder: { eyebrow: "Coordinate the phrase", heading: "Build the feminine singular description.", prompt: "Build: the new house.", tokens: ["la", "casa", "nueva"], correctOrder: ["la", "casa", "nueva"], answer: "la casa nueva", feedback: "La and casa establish feminine singular; nueva makes the adjective agree." },
  reading: { eyebrow: "Agreement distinguishes details", heading: "Two new objects enter the room.", instructions: "Read or listen, then trace each adjective to its noun.", sentences: [{ id: "r1", text: "Hay un libro nuevo y una mochila nueva.", translation: "There is a new book and a new backpack." }, { id: "r2", text: "El libro es rojo.", translation: "The book is red." }, { id: "r3", text: "La mochila es roja.", translation: "The backpack is red." }, { id: "r4", text: "El libro y la mochila son importantes.", translation: "The book and the backpack are important." }], questions: [{ id: "q1", prompt: "Why does nuevo become nueva with mochila?", options: [{ id: "gender", label: "Mochila is feminine singular" }, { id: "position", label: "The adjective comes later" }], correctOptionId: "gender", feedback: "The noun’s grammatical gender controls the -o/-a agreement choice.", conceptIds: ["adjective_gender", "adjective_agreement"] }, { id: "q2", prompt: "Which adjective keeps the same singular gender form?", options: [{ id: "important", label: "importante" }, { id: "red", label: "rojo / roja" }], correctOptionId: "important", feedback: "Importante belongs to the -e family and does not alternate -o/-a.", conceptIds: ["adjective_gender"] }] },
  recall: { eyebrow: "Retrieve the correct form", heading: "Complete each description from the noun.", prompt: "Type the missing adjective form.", items: [{ id: "new-house", before: "la casa ", after: " (new)", accepted: ["nueva"], answer: "nueva", conceptIds: ["adjective_gender", "adjective_agreement"], feedback: "Casa is feminine singular, so nuevo becomes nueva." }, { id: "red-car", before: "el carro ", after: " (red)", accepted: ["rojo"], answer: "rojo", conceptIds: ["adjective_gender"], feedback: "Carro is masculine singular, so the form is rojo." }, { id: "large-table", before: "la mesa ", after: " (big)", accepted: ["grande"], answer: "grande", conceptIds: ["adjective_gender"], feedback: "Grande keeps the same singular form for feminine mesa." }] },
  production: { eyebrow: "Coordinate three descriptions", heading: "Write across both adjective families.", prompt: "Write three separate ideas: a masculine -o adjective, a feminine -a version, and an -e adjective with either noun gender.", requirements: ["Use an -o form", "Use the matching -a form", "Use grande, interesante, or importante", "Write three separate ideas"], example: "El libro es nuevo. La casa es nueva. La ciudad es interesante.", minimumCharacters: 60, evaluation: { minimumIdeas: 3, requiredGroups: [{ accepted: ["nuevo", "rojo", "pequeño"], missingFeedback: "Add a masculine singular -o adjective." }, { accepted: ["nueva", "roja", "pequeña"], missingFeedback: "Add a feminine singular -a adjective." }, { accepted: ["grande", "interesante", "importante"], missingFeedback: "Add an -e adjective that keeps one singular gender form." }], successFeedback: "You coordinated gender across a changing -o/-a family and a stable -e family." } },
  summary: { eyebrow: "Keep the sequence", heading: "Noun first, adjective family second, form last.", message: "Find the noun being described. Identify whether the adjective marks gender, then choose only the form that family allows.", ideas: [{ label: "-O", question: "Masculine singular?", uses: ["nuevo", "rojo"] }, { label: "-A", question: "Feminine singular?", uses: ["nueva", "roja"] }, { label: "-E", question: "Same singular form?", uses: ["grande", "interesante"] }] },
  completion: { title: "Gender agreement now follows the noun instead of a guess.", message: "Next, number will make the entire phrase move into plural together." },
});

export const lesson23 = createFoundationLesson({
  id: "2.3", moduleId: "module-02", title: "Plural Agreement", displayTitle: "Plural meaning should be visible across the phrase.",
  dek: "The article, noun, and adjective coordinate number. One plural marker is not enough when other words also have plural forms.",
  goal: "Make articles, nouns, and adjectives agree in plural number using common -s and -es patterns.", durationMinutes: 25, concepts: ["adjective_number", "adjective_agreement", "noun_number", "noun_phrase"],
  opening: { eyebrow: "Move every responsive word", heading: "Plural agreement is distributed, not attached to one noun ending.", paragraphs: ["El libro nuevo becomes los libros nuevos. The article changes, the noun takes plural -s, and the adjective takes plural -s.", "La ciudad grande becomes las ciudades grandes. Ciudad forms its plural with -es, while grande also takes plural -s because its own final vowel controls its plural spelling.", "Each word forms its own plural, but every result expresses the same number. Do not copy one ending mechanically across the phrase."], spanish: [{ text: "el libro nuevo", translation: "the new book" }, { text: "los libros nuevos", translation: "the new books" }, { text: "la ciudad grande", translation: "the big city" }, { text: "las ciudades grandes", translation: "the big cities" }] },
  prediction: { eyebrow: "Move the full phrase", heading: "Change la casa roja to plural.", prompt: "Which phrase coordinates every word?", options: [{ id: "all", label: "las casas rojas" }, { id: "noun", label: "la casas roja" }, { id: "mixed", label: "las casa rojo" }], correctOptionId: "all", correctFeedback: "Las, casas, and rojas all express feminine plural agreement.", incorrectFeedback: "Pluralize every responsive part: las + casas + rojas." },
  model: { eyebrow: "Three agreement sites", heading: "Let each word form plural according to its own ending.", paragraphs: ["The article uses its stored plural form: el → los, la → las. A vowel-ending noun or adjective normally adds -s: libro → libros, nuevo → nuevos, grande → grandes.", "Many consonant-ending nouns and adjectives add -es: ciudad → ciudades, trabajador → trabajadores. Accent and spelling changes can occur in larger patterns you will learn as needed.", "A mixed-gender group normally uses the masculine plural adjective form in general Latin American Spanish: Ana y Luis son altos. A group composed only of feminine referents uses altas."], points: [{ label: "ARTICLE", title: "los / las", description: "Marks identified plural number and gender." }, { label: "NOUN", title: "libros / ciudades", description: "Forms plural with -s or -es." }, { label: "ADJECTIVE", title: "nuevos / grandes", description: "Forms its own plural and keeps gender where marked." }] },
  contrast: { eyebrow: "One noun or a coordinated group", heading: "Plural can come from a plural noun or from multiple named people.", sides: [{ label: "PLURAL NOUN", question: "Is the noun itself plural?", description: "The complete noun phrase carries plural morphology.", examples: [{ text: "las casas nuevas", translation: "the new houses" }] }, { label: "COMPOUND SUBJECT", question: "Are several singular people joined?", description: "The resulting group takes plural description.", examples: [{ text: "Ana y Luis son altos.", translation: "Ana and Luis are tall." }, { text: "Ana y Marta son altas.", translation: "Ana and Marta are tall." }] }], note: "Number belongs to the referent you are describing, not only to the final noun nearest the adjective." },
  guided: { eyebrow: "Form each plural", heading: "Describe las ciudades with interesante.", prompt: "Which adjective form completes the phrase?", options: [{ id: "plural", label: "interesantes" }, { id: "singular", label: "interesante" }, { id: "invented", label: "interesantas" }], correctOptionId: "plural", correctFeedback: "Interesante does not change for singular gender, but it does change for number: interesantes.", incorrectFeedback: "The adjective must reflect plural ciudades. Add -s to interesante: interesantes." },
  sort: { eyebrow: "Read every agreement feature", heading: "Sort descriptions by singular or plural meaning.", prompt: "Place each complete phrase under the number it expresses.", buckets: [{ id: "singular", label: "SINGULAR", hint: "one referent" }, { id: "plural", label: "PLURAL", hint: "more than one" }], items: [{ id: "book", label: "el libro nuevo", answer: "singular" }, { id: "city", label: "la ciudad grande", answer: "singular" }, { id: "books", label: "los libros nuevos", answer: "plural" }, { id: "cities", label: "las ciudades grandes", answer: "plural" }, { id: "women", label: "Ana y Marta son altas", answer: "plural" }, { id: "people", label: "Ana y Luis son interesantes", answer: "plural" }] },
  builder: { eyebrow: "Coordinate every piece", heading: "Build the feminine plural phrase.", prompt: "Build: the new houses.", tokens: ["las", "casas", "nuevas"], correctOrder: ["las", "casas", "nuevas"], answer: "las casas nuevas", feedback: "The article, noun, and -a adjective all move into feminine plural together." },
  reading: { eyebrow: "Plural in a description", heading: "A neighborhood contains contrasting homes.", instructions: "Read or listen, then identify the form that carries each agreement decision.", sentences: [{ id: "r1", text: "Las casas nuevas son grandes.", translation: "The new houses are big." }, { id: "r2", text: "Las casas viejas son pequeñas.", translation: "The old houses are small." }, { id: "r3", text: "Los edificios modernos son interesantes.", translation: "The modern buildings are interesting." }], questions: [{ id: "q1", prompt: "Which phrase is feminine plural throughout?", options: [{ id: "houses", label: "las casas nuevas" }, { id: "buildings", label: "los edificios modernos" }], correctOptionId: "houses", feedback: "Las, casas, and nuevas all mark feminine plural.", conceptIds: ["adjective_number", "adjective_agreement"] }, { id: "q2", prompt: "Why is interesantes plural?", options: [{ id: "buildings", label: "It describes plural edificios" }, { id: "gender", label: "It marks feminine gender" }], correctOptionId: "buildings", feedback: "Interesante has one singular gender form, but it takes -s for plural edificios.", conceptIds: ["adjective_number"] }] },
  recall: { eyebrow: "Retrieve the whole agreement", heading: "Complete the plural description.", prompt: "Type the missing adjective form.", items: [{ id: "new-books", before: "los libros ", after: " (new)", accepted: ["nuevos"], answer: "nuevos", conceptIds: ["adjective_number", "adjective_agreement"], feedback: "Masculine plural libros takes nuevos." }, { id: "red-houses", before: "las casas ", after: " (red)", accepted: ["rojas"], answer: "rojas", conceptIds: ["adjective_number", "adjective_agreement"], feedback: "Feminine plural casas takes rojas." }, { id: "big-cities", before: "las ciudades ", after: " (big)", accepted: ["grandes"], answer: "grandes", conceptIds: ["adjective_number"], feedback: "Grande takes plural -s: grandes." }] },
  production: { eyebrow: "Describe three sets", heading: "Write plural agreement across adjective families.", prompt: "Write three separate plural descriptions: masculine -os, feminine -as, and a plural -e adjective.", requirements: ["Use a masculine plural -os adjective", "Use a feminine plural -as adjective", "Use grandes, interesantes, or importantes", "Write three separate ideas"], example: "Los libros son nuevos. Las casas son nuevas. Las ciudades son grandes.", minimumCharacters: 65, evaluation: { minimumIdeas: 3, requiredGroups: [{ accepted: ["nuevos", "rojos", "pequeños", "altos"], missingFeedback: "Add a masculine plural -os adjective." }, { accepted: ["nuevas", "rojas", "pequeñas", "altas"], missingFeedback: "Add a feminine plural -as adjective." }, { accepted: ["grandes", "interesantes", "importantes"], missingFeedback: "Add a plural adjective from the -e family." }], successFeedback: "Your descriptions make plural number visible across three adjective patterns." } },
  summary: { eyebrow: "Keep the coordination", heading: "Plural meaning travels across the complete phrase.", message: "Pluralize each responsive word according to its own form while keeping gender agreement intact.", ideas: [{ label: "ARTICLE", question: "Identified set?", uses: ["los", "las"] }, { label: "NOUN", question: "How does this noun pluralize?", uses: ["-s", "-es"] }, { label: "ADJECTIVE", question: "What noun or group does it describe?", uses: ["-os / -as", "-es"] }] },
  completion: { title: "Plural agreement now moves across the full phrase.", message: "Next, word order will show which descriptions are neutral and where emphasis can change." },
});

export const lesson24 = createFoundationLesson({
  id: "2.4", moduleId: "module-02", title: "Spanish Word Order", displayTitle: "Put neutral description where Spanish expects it.",
  dek: "Many descriptive adjectives follow the noun. Moving an adjective can change emphasis or interpretation, so begin with the dependable neutral pattern.",
  goal: "Build neutral article + noun + adjective phrases and recognize that pre-noun placement can add evaluation or conventional meaning.", durationMinutes: 26, concepts: ["adjective_position", "adjective_function", "adjective_agreement", "noun_phrase"],
  opening: { eyebrow: "Order carries a viewpoint", heading: "Spanish does not simply mirror English adjective order.", paragraphs: ["English commonly places descriptive adjectives before the noun: a new book. Spanish commonly places neutral, identifying descriptions after the noun: un libro nuevo.", "Post-noun placement helps classify or distinguish the referent. A libro nuevo contrasts with an older book; una casa grande contrasts with a smaller one.", "Some adjectives appear before nouns for evaluation, emphasis, quantity, or fixed meaning. This lesson builds a reliable production default while teaching you not to treat every alternate order as random."], spanish: [{ text: "un libro nuevo", translation: "a new book" }, { text: "una casa grande", translation: "a big house" }, { text: "una ciudad moderna", translation: "a modern city" }, { text: "un buen libro", translation: "a good book" }] },
  prediction: { eyebrow: "Choose the neutral pattern", heading: "You want to identify a red house.", prompt: "Which order is the dependable neutral description?", options: [{ id: "after", label: "una casa roja" }, { id: "before", label: "una roja casa" }, { id: "english", label: "roja una casa" }], correctOptionId: "after", correctFeedback: "For a neutral color description, place the adjective after the noun: una casa roja.", incorrectFeedback: "Begin with article + noun, then add the neutral color description: una casa roja." },
  model: { eyebrow: "A production default", heading: "Build the referent before adding the description.", paragraphs: ["Start with the article and noun: un libro. Then attach the description: un libro interesante. This order keeps agreement and reference easy to track.", "Color, nationality, material, and many classifying descriptions characteristically follow the noun. Other common adjectives can move before the noun when the speaker presents an evaluation rather than a distinguishing fact.", "For now, produce post-noun descriptive order unless you have learned a specific pre-noun phrase. Recognition can be broader than production from the beginning."], points: [{ label: "01", title: "article + noun", description: "Build the referent: una ciudad." }, { label: "02", title: "agree the adjective", description: "Choose moderna for feminine singular ciudad." }, { label: "03", title: "place after the noun", description: "Produce una ciudad moderna as the neutral phrase." }] },
  contrast: { eyebrow: "Position can shape interpretation", heading: "Before and after are not always interchangeable.", sides: [{ label: "AFTER NOUN", question: "Which one or what kind?", description: "The adjective often classifies or distinguishes the referent.", examples: [{ text: "un amigo viejo", translation: "an elderly / old friend" }, { text: "un libro nuevo", translation: "a new book" }] }, { label: "BEFORE NOUN", question: "What is the speaker’s framing?", description: "Some placements add evaluation or a conventional interpretation.", examples: [{ text: "un viejo amigo", translation: "a longtime friend" }, { text: "un buen libro", translation: "a good book" }] }], note: "You do not need every nuance now. Notice that order can carry meaning, then keep post-noun order as your neutral production base." },
  guided: { eyebrow: "Build before decorating", heading: "Translate: the interesting cities.", context: "Ciudades is feminine plural; interesantes describes the cities neutrally.", prompt: "Which phrase coordinates order and agreement?", options: [{ id: "correct", label: "las ciudades interesantes" }, { id: "english", label: "las interesantes ciudades" }, { id: "mixed", label: "los ciudades interesante" }], correctOptionId: "correct", correctFeedback: "Las ciudades builds the referent, and interesantes follows with plural agreement.", incorrectFeedback: "Use feminine plural las ciudades, then the plural description interesantes." },
  sort: { eyebrow: "Read position by purpose", heading: "Sort phrases into the course’s neutral pattern or a learned pre-noun phrase.", prompt: "Place each phrase under its position type.", buckets: [{ id: "neutral", label: "NEUTRAL POST-NOUN", hint: "identify or classify" }, { id: "learned-before", label: "LEARNED PRE-NOUN", hint: "evaluation or conventional meaning" }], items: [{ id: "red-house", label: "una casa roja", answer: "neutral" }, { id: "modern-city", label: "una ciudad moderna", answer: "neutral" }, { id: "interesting-book", label: "un libro interesante", answer: "neutral" }, { id: "good-book", label: "un buen libro", answer: "learned-before" }, { id: "old-friend", label: "un viejo amigo", answer: "learned-before" }] },
  builder: { eyebrow: "Build the neutral order", heading: "Keep reference, noun, and description visible.", prompt: "Build: the modern cities.", tokens: ["las", "ciudades", "modernas"], correctOrder: ["las", "ciudades", "modernas"], answer: "las ciudades modernas", feedback: "The noun phrase comes first; modernas follows and agrees in feminine plural." },
  reading: { eyebrow: "Order in a description", heading: "A reader can use adjectives to identify the intended place.", instructions: "Read or listen, then determine what each adjective contributes.", sentences: [{ id: "r1", text: "Vivo en una ciudad moderna.", translation: "I live in a modern city." }, { id: "r2", text: "La ciudad tiene edificios nuevos y casas viejas.", translation: "The city has new buildings and old houses." }, { id: "r3", text: "Hay un buen museo en el centro.", translation: "There is a good museum downtown." }], questions: [{ id: "q1", prompt: "Which adjectives use the neutral post-noun pattern?", options: [{ id: "new-old", label: "nuevos / viejas" }, { id: "good", label: "buen" }], correctOptionId: "new-old", feedback: "Edificios nuevos and casas viejas place distinguishing descriptions after their nouns.", conceptIds: ["adjective_position"] }, { id: "q2", prompt: "Which phrase uses a learned evaluation before the noun?", options: [{ id: "museum", label: "un buen museo" }, { id: "city", label: "una ciudad moderna" }], correctOptionId: "museum", feedback: "Buen appears before museo as a common evaluative pattern.", conceptIds: ["adjective_position"] }] },
  recall: { eyebrow: "Retrieve order and agreement", heading: "Complete each neutral phrase.", prompt: "Type the missing adjective after the noun.", items: [{ id: "red-house", before: "una casa ", after: " (red)", accepted: ["roja"], answer: "roja", conceptIds: ["adjective_position", "adjective_agreement"], feedback: "Roja follows casa and agrees in feminine singular." }, { id: "new-books", before: "los libros ", after: " (new)", accepted: ["nuevos"], answer: "nuevos", conceptIds: ["adjective_position", "adjective_agreement"], feedback: "Nuevos follows and agrees with masculine plural libros." }, { id: "modern-cities", before: "las ciudades ", after: " (modern)", accepted: ["modernas"], answer: "modernas", conceptIds: ["adjective_position", "adjective_agreement"], feedback: "Modernas follows and agrees with feminine plural ciudades." }] },
  production: { eyebrow: "Describe a place", heading: "Write four neutral post-noun descriptions.", prompt: "Write four separate ideas about books, houses, a city, or people. Put each descriptive adjective after its noun and make it agree.", requirements: ["Use one masculine singular phrase", "Use one feminine singular phrase", "Use one plural phrase", "Place descriptions after nouns"], example: "Tengo un libro nuevo. Hay una casa roja. La ciudad es moderna. Los edificios son grandes.", minimumCharacters: 85, evaluation: { minimumIdeas: 4, requiredGroups: [{ accepted: ["libro nuevo", "carro rojo", "problema importante"], missingFeedback: "Add a masculine singular noun + adjective phrase." }, { accepted: ["casa nueva", "casa roja", "ciudad moderna", "mesa grande"], missingFeedback: "Add a feminine singular noun + adjective phrase." }, { accepted: ["libros nuevos", "casas nuevas", "ciudades modernas", "edificios grandes"], missingFeedback: "Add a plural noun + adjective phrase." }], successFeedback: "Your descriptions use the neutral Spanish order and coordinate agreement across number and gender." } },
  summary: { eyebrow: "Keep the default", heading: "Build the noun phrase, then add neutral description.", message: "Post-noun placement is a strong production base. Treat pre-noun adjectives as learned patterns whose position may add meaning.", ideas: [{ label: "REFERENT", question: "What noun phrase am I building?", uses: ["article + noun"] }, { label: "DESCRIPTION", question: "What distinguishes it?", uses: ["agree adjective"] }, { label: "POSITION", question: "Neutral or learned framing?", uses: ["after noun", "specific pre-noun phrase"] }] },
  completion: { title: "You can now build neutral Spanish descriptions.", message: "Module 3 turns from things and qualities to the people who carry a sentence and the verb ser." },
});

export const module02Lessons = [lesson21, lesson22, lesson23, lesson24];
