import { createFoundationLesson } from "./lesson-factory";

export const lesson31 = createFoundationLesson({
  id: "3.1", moduleId: "module-03", title: "Who Is Doing It?", displayTitle: "Find the subject before you choose the verb.",
  dek: "Spanish verb forms carry information about who is acting. Subject pronouns clarify or contrast, but they are often unnecessary.",
  goal: "Recognize yo, tú, él, ella, usted, nosotros, ellos, ellas, and ustedes, and connect each subject to person and number.", durationMinutes: 24, concepts: ["subject_pronouns"],
  opening: { eyebrow: "The sentence anchor", heading: "The subject is the person or thing the sentence is about.", paragraphs: ["Before you choose a Spanish verb form, identify who carries the message. Yo means I; tú is the familiar singular you; él and ella mean he and she; usted is a respectful singular you.", "Nosotros means we. Ellos and ellas mean they, with ellas reserved for an all-feminine group. Ustedes is the normal plural you throughout Latin America and the production form Nexo teaches.", "Spanish often omits a subject pronoun because the verb ending already points to the subject. Use the pronoun when it clarifies, contrasts, or emphasizes—not because every English sentence begins with one."], spanish: [{ text: "Yo soy Ana.", translation: "I am Ana." }, { text: "Tú eres estudiante.", translation: "You are a student." }, { text: "Ella es profesora.", translation: "She is a teacher." }, { text: "Nosotros somos amigos.", translation: "We are friends." }, { text: "Ustedes son de México.", translation: "You all are from Mexico." }] },
  prediction: { eyebrow: "Read the group", heading: "The subject is Ana y Marta.", prompt: "Which pronoun can replace this all-feminine group?", options: [{ id: "ellas", label: "ellas" }, { id: "ellos", label: "ellos" }, { id: "nosotros", label: "nosotros" }], correctOptionId: "ellas", correctFeedback: "Ana y Marta is a third-person feminine plural group, so ellas can replace it.", incorrectFeedback: "Neither speaker is included. Two named women form ellas." },
  model: { eyebrow: "Person and number", heading: "Pronouns map the participants in the conversation.", paragraphs: ["First person includes the speaker: yo or nosotros. Second person addresses the listener: tú, usted, or ustedes. Third person refers to someone else: él, ella, ellos, or ellas.", "Usted uses third-person verb forms grammatically even though it addresses the listener. Ustedes also uses the same forms as ellos and ellas. That form relationship will matter immediately with ser.", "Vosotros is common in Spain as an informal plural you. In Foundations you should recognize it, but produce ustedes for general Latin American Spanish."], points: [{ label: "SPEAKER", title: "yo / nosotros", description: "I / we" }, { label: "LISTENER", title: "tú / usted / ustedes", description: "familiar you / respectful you / you all" }, { label: "OTHERS", title: "él / ella / ellos / ellas", description: "he / she / they" }, { label: "RECOGNIZE", title: "vosotros", description: "informal plural you in Spain; not the course production target" }] },
  contrast: { eyebrow: "Two singular forms of you", heading: "Relationship and setting guide tú or usted.", sides: [{ label: "TÚ", question: "Familiar singular you?", description: "Common with friends, family, classmates, children, and many peers, depending on community norms.", examples: [{ text: "Tú eres mi amigo.", translation: "You are my friend." }] }, { label: "USTED", question: "Respectful or formal singular you?", description: "Used for respect, distance, or convention; exact choices vary by region and relationship.", examples: [{ text: "Usted es la profesora.", translation: "You are the teacher." }] }], note: "Usted addresses one listener but pairs with the same verb form used for él and ella." },
  guided: { eyebrow: "Find who is included", heading: "The subject is mi hermano y yo.", prompt: "Which pronoun replaces the group?", options: [{ id: "we", label: "nosotros" }, { id: "they", label: "ellos" }, { id: "you-all", label: "ustedes" }], correctOptionId: "we", correctFeedback: "The speaker is included in mi hermano y yo, so the group is nosotros.", incorrectFeedback: "Any group that includes yo becomes first-person plural: nosotros." },
  sort: { eyebrow: "Map the participants", heading: "Sort subjects by their role in the conversation.", prompt: "Place each subject under speaker, listener, or others.", buckets: [{ id: "speaker", label: "SPEAKER INCLUDED", hint: "yo / nosotros" }, { id: "listener", label: "LISTENER", hint: "tú / usted / ustedes" }, { id: "others", label: "OTHER PEOPLE", hint: "él / ella / ellos / ellas" }], items: [{ id: "yo", label: "yo", answer: "speaker" }, { id: "we", label: "Ana y yo", answer: "speaker" }, { id: "tu", label: "tú", answer: "listener" }, { id: "usted", label: "usted", answer: "listener" }, { id: "ustedes", label: "ustedes", answer: "listener" }, { id: "they", label: "Luis y Marta", answer: "others" }] },
  builder: { eyebrow: "Build the contrast", heading: "Make both participants explicit.", prompt: "Build: You are Luis and I am Ana.", tokens: ["Tú eres Luis", "y", "yo soy Ana."], correctOrder: ["Tú eres Luis", "y", "yo soy Ana."], answer: "Tú eres Luis y yo soy Ana.", feedback: "The explicit pronouns contrast the listener tú with the speaker yo." },
  reading: { eyebrow: "Pronouns in a group", heading: "A teacher identifies everyone in the room.", instructions: "Read or listen, then determine who each subject includes.", sentences: [{ id: "r1", text: "Yo soy la profesora.", translation: "I am the teacher." }, { id: "r2", text: "Ustedes son estudiantes.", translation: "You all are students." }, { id: "r3", text: "Ana y Marta son amigas. Ellas son de Perú.", translation: "Ana and Marta are friends. They are from Peru." }, { id: "r4", text: "Luis y yo somos de México.", translation: "Luis and I are from Mexico." }], questions: [{ id: "q1", prompt: "Which pronoun addresses the whole class?", options: [{ id: "ustedes", label: "ustedes" }, { id: "ellas", label: "ellas" }], correctOptionId: "ustedes", feedback: "Ustedes directly addresses more than one listener in Latin American Spanish.", conceptIds: ["subject_pronouns"] }, { id: "q2", prompt: "Why does Luis y yo mean nosotros?", options: [{ id: "speaker", label: "The speaker is included" }, { id: "male", label: "Luis is masculine" }], correctOptionId: "speaker", feedback: "First-person plural is defined by including the speaker, not by gender alone.", conceptIds: ["subject_pronouns"] }] },
  recall: { eyebrow: "Retrieve the pronoun", heading: "Replace the named subject.", prompt: "Type the subject pronoun that fits.", items: [{ id: "ana", before: "Ana → ", after: "", accepted: ["ella"], answer: "ella", conceptIds: ["subject_pronouns"], feedback: "Ana can be replaced by ella." }, { id: "ana-marta", before: "Ana y Marta → ", after: "", accepted: ["ellas"], answer: "ellas", conceptIds: ["subject_pronouns"], feedback: "An all-feminine third-person group is ellas." }, { id: "luis-yo", before: "Luis y yo → ", after: "", accepted: ["nosotros"], answer: "nosotros", conceptIds: ["subject_pronouns"], feedback: "A group containing the speaker is nosotros." }] },
  production: { eyebrow: "Map a small group", heading: "Write four identity lines with different subjects.", prompt: "Write separate ideas using yo, tú or usted, nosotros, and ustedes or ellos/ellas.", requirements: ["Use yo", "Use tú or usted", "Use nosotros", "Use ustedes, ellos, or ellas"], example: "Yo soy Ana. Tú eres Luis. Nosotros somos amigos. Ellas son estudiantes.", minimumCharacters: 65, evaluation: { minimumIdeas: 4, requiredGroups: [{ accepted: ["yo"], missingFeedback: "Add a line with yo." }, { accepted: ["tú", "tu", "usted"], missingFeedback: "Address one listener with tú or usted." }, { accepted: ["nosotros"], missingFeedback: "Add a group that includes the speaker with nosotros." }, { accepted: ["ustedes", "ellos", "ellas"], missingFeedback: "Add a plural listener or third-person pronoun." }], successFeedback: "You mapped speaker, listener, and other participants across singular and plural subjects." } },
  summary: { eyebrow: "Keep the map", heading: "Person and number select the verb form that comes next.", message: "Find who is included, whether the subject is singular or plural, and whether a listener is familiar or respectful.", ideas: [{ label: "FIRST", question: "Is the speaker included?", uses: ["yo", "nosotros"] }, { label: "SECOND", question: "Am I addressing the listener?", uses: ["tú", "usted", "ustedes"] }, { label: "THIRD", question: "Am I referring to others?", uses: ["él / ella", "ellos / ellas"] }] },
  completion: { title: "You can now locate the person behind a verb form.", message: "Next, ser will turn that subject map into identity statements." },
});

export const lesson32 = createFoundationLesson({
  id: "3.2", moduleId: "module-03", title: "SER: Identity", displayTitle: "Use ser to identify and classify.",
  dek: "Ser connects a subject to the identity or category that tells the listener what the subject is.",
  goal: "Use soy, eres, es, somos, and son with the subjects they encode and build basic identity and classification statements.", durationMinutes: 27, concepts: ["ser_forms", "ser_identity", "ser_classification", "subject_pronouns"],
  opening: { eyebrow: "A verb with a job", heading: "Ser answers who or what the subject is.", paragraphs: ["Ser is one Spanish verb translated with English to be. Its central job here is identity and classification: Soy Ana identifies the speaker; Soy estudiante classifies the speaker.", "The present forms are soy, eres, es, somos, and son. These forms look different because ser is highly irregular; memorize them as a subject map, not as an ending recipe.", "Spanish can omit the subject pronoun when the verb form and context make the subject clear. Soy Ana already points to yo. Somos estudiantes already includes we."], spanish: [{ text: "Soy Ana.", translation: "I am Ana." }, { text: "Eres estudiante.", translation: "You are a student." }, { text: "Ella es profesora.", translation: "She is a teacher." }, { text: "Somos amigos.", translation: "We are friends." }, { text: "Ustedes son estudiantes.", translation: "You all are students." }] },
  prediction: { eyebrow: "Map subject to form", heading: "The subject is nosotros.", prompt: "Which form of ser carries we?", options: [{ id: "somos", label: "somos" }, { id: "son", label: "son" }, { id: "soy", label: "soy" }], correctOptionId: "somos", correctFeedback: "Nosotros selects somos: Somos estudiantes.", incorrectFeedback: "The first-person plural form is somos." },
  model: { eyebrow: "The present map", heading: "Learn ser as five high-frequency form–subject connections.", paragraphs: ["Soy belongs to yo. Eres belongs to familiar singular tú. Es works with él, ella, usted, and one named person or thing.", "Somos belongs to nosotros. Son works with ellos, ellas, ustedes, and any plural named subject.", "The subject pronoun may disappear, but the relationship remains. Context distinguishes son as they are from you all are when no pronoun is stated."], points: [{ label: "YO", title: "soy", description: "Soy Ana. Soy estudiante." }, { label: "TÚ", title: "eres", description: "Eres Luis. Eres mi amigo." }, { label: "ÉL / ELLA / USTED", title: "es", description: "Ella es profesora. Usted es Carlos." }, { label: "NOSOTROS", title: "somos", description: "Somos amigos." }, { label: "ELLOS / USTEDES", title: "son", description: "Ellas son estudiantes. Ustedes son de Perú." }] },
  contrast: { eyebrow: "Two identity jobs", heading: "A name identifies; a category classifies.", sides: [{ label: "IDENTITY", question: "Who is this person?", description: "Ser links a subject to a name or unique identity.", examples: [{ text: "Soy Valeria.", translation: "I am Valeria." }, { text: "Él es Mateo.", translation: "He is Mateo." }] }, { label: "CLASSIFICATION", question: "What is this person or thing?", description: "Ser places the subject in a role or category.", examples: [{ text: "Soy estudiante.", translation: "I am a student." }, { text: "Es una ciudad.", translation: "It is a city." }] }], note: "Both uses answer who or what the subject is. Later, estar will answer how or where an identified subject is." },
  guided: { eyebrow: "Read the listener", heading: "You are speaking respectfully to one person.", context: "The subject is usted.", prompt: "Which form completes Usted ___ la profesora?", options: [{ id: "es", label: "es" }, { id: "eres", label: "eres" }, { id: "son", label: "son" }], correctOptionId: "es", correctFeedback: "Usted addresses one listener but uses third-person singular es.", incorrectFeedback: "The grammatical form for usted matches él and ella: es." },
  sort: { eyebrow: "Automate the map", heading: "Sort subjects under the ser form they select.", prompt: "Place each subject under its present-tense form.", buckets: [{ id: "soy", label: "SOY", hint: "yo" }, { id: "eres", label: "ERES", hint: "tú" }, { id: "es", label: "ES", hint: "one third person / usted" }, { id: "somos", label: "SOMOS", hint: "nosotros" }, { id: "son", label: "SON", hint: "plural third person / ustedes" }], items: [{ id: "yo", label: "yo", answer: "soy" }, { id: "tu", label: "tú", answer: "eres" }, { id: "ana", label: "Ana", answer: "es" }, { id: "usted", label: "usted", answer: "es" }, { id: "we", label: "mi amigo y yo", answer: "somos" }, { id: "class", label: "ustedes", answer: "son" }] },
  builder: { eyebrow: "Build classification", heading: "Let the form carry the subject.", prompt: "Build: We are students.", tokens: ["Somos", "estudiantes."], correctOrder: ["Somos", "estudiantes."], answer: "Somos estudiantes.", feedback: "Somos already carries nosotros; estudiantes classifies the group." },
  reading: { eyebrow: "Identity in context", heading: "A new class introduces itself.", instructions: "Read or listen, then connect each form to its subject.", sentences: [{ id: "r1", text: "Soy Camila y soy estudiante.", translation: "I am Camila and I am a student." }, { id: "r2", text: "Él es Daniel. Es profesor.", translation: "He is Daniel. He is a teacher." }, { id: "r3", text: "Nosotros somos estudiantes.", translation: "We are students." }, { id: "r4", text: "Ustedes son el grupo nuevo.", translation: "You all are the new group." }], questions: [{ id: "q1", prompt: "Which form identifies the speaker as Camila?", options: [{ id: "soy", label: "soy" }, { id: "es", label: "es" }], correctOptionId: "soy", feedback: "Soy encodes first-person singular yo.", conceptIds: ["ser_forms", "ser_identity"] }, { id: "q2", prompt: "Why can Es profesor omit él?", options: [{ id: "context", label: "The context and es keep Daniel as the subject" }, { id: "random", label: "Spanish has no subjects" }], correctOptionId: "context", feedback: "Spanish subjects still exist; the pronoun can be omitted when form and context identify it.", conceptIds: ["ser_forms", "subject_pronouns"] }] },
  recall: { eyebrow: "Retrieve the form", heading: "Complete ser without a chart.", prompt: "Type the form selected by the subject.", items: [{ id: "yo", before: "Yo ", after: " estudiante.", accepted: ["soy"], answer: "soy", conceptIds: ["ser_forms", "ser_classification"], feedback: "Yo selects soy." }, { id: "usted", before: "Usted ", after: " la profesora.", accepted: ["es"], answer: "es", conceptIds: ["ser_forms", "ser_identity"], feedback: "Usted uses third-person singular es." }, { id: "we", before: "Nosotros ", after: " amigos.", accepted: ["somos"], answer: "somos", conceptIds: ["ser_forms", "ser_classification"], feedback: "Nosotros selects somos." }, { id: "you-all", before: "Ustedes ", after: " estudiantes.", accepted: ["son"], answer: "son", conceptIds: ["ser_forms"], feedback: "Ustedes selects son in Latin American Spanish." }] },
  production: { eyebrow: "Introduce a group", heading: "Write five identity or classification lines.", prompt: "Use each ser form once: soy, eres, es, somos, and son. Write separate complete ideas.", requirements: ["Use soy", "Use eres", "Use es", "Use somos", "Use son"], example: "Soy Ana. Eres estudiante. Ella es Marta. Somos amigos. Ustedes son estudiantes.", minimumCharacters: 75, evaluation: { minimumIdeas: 5, requiredGroups: [{ accepted: ["soy"], missingFeedback: "Add soy for yo." }, { accepted: ["eres"], missingFeedback: "Add eres for tú." }, { accepted: ["es"], missingFeedback: "Add es for a singular third person or usted." }, { accepted: ["somos"], missingFeedback: "Add somos for nosotros." }, { accepted: ["son"], missingFeedback: "Add son for a plural subject or ustedes." }], successFeedback: "You retrieved the complete present ser map across identity and classification messages." } },
  summary: { eyebrow: "Keep the map", heading: "Ser connects a subject to who or what it is.", message: "Choose the identity job, find the subject, then retrieve the form. The pronoun can disappear only after the subject is clear.", ideas: [{ label: "SINGULAR", question: "Who is one person?", uses: ["soy", "eres", "es"] }, { label: "PLURAL", question: "Who is the group?", uses: ["somos", "son"] }, { label: "JOB", question: "Identity or category?", uses: ["name", "classification"] }] },
  completion: { title: "The present forms of ser now carry identity.", message: "Next, you will expand those forms into a more complete account of who you are." },
});

export const lesson33 = createFoundationLesson({
  id: "3.3", moduleId: "module-03", title: "Who You Are", displayTitle: "Build identity from more than a name.",
  dek: "Ser can connect you to names, roles, relationships, and descriptive classifications that answer who you are in context.",
  goal: "Combine ser with names, roles, and agreed descriptions while using or omitting subject pronouns deliberately.", durationMinutes: 25, concepts: ["ser_identity", "ser_classification", "ser_forms", "adjective_agreement", "subject_pronouns"],
  opening: { eyebrow: "Layer identity", heading: "A person can be identified from several useful angles.", paragraphs: ["Soy Elena gives a name. Soy estudiante gives a role. Soy una persona tranquila describes the kind of person the speaker is presenting herself as.", "Ser does not claim that a person can never change. It organizes the current statement as identity, classification, or characteristic rather than a state or location.", "Agreement still matters inside the complement. Elena can say Soy tranquila; Mateo can say Soy tranquilo. The ser form follows the subject, and the adjective form follows the person described."], spanish: [{ text: "Soy Elena.", translation: "I am Elena." }, { text: "Soy estudiante.", translation: "I am a student." }, { text: "Soy una persona tranquila.", translation: "I am a calm person." }, { text: "Mateo es creativo.", translation: "Mateo is creative." }, { text: "Elena es creativa.", translation: "Elena is creative." }] },
  prediction: { eyebrow: "Choose the identity form", heading: "Ana speaks about herself.", context: "She wants to say that she is creative.", prompt: "Which sentence coordinates subject, ser, and adjective?", options: [{ id: "soy", label: "Soy creativa." }, { id: "es", label: "Es creativo." }, { id: "son", label: "Son creativa." }], correctOptionId: "soy", correctFeedback: "Ana speaking as yo selects soy, and creativa describes her with feminine singular agreement.", incorrectFeedback: "The speaker uses soy; the adjective describing Ana is creativa." },
  model: { eyebrow: "Two agreement tracks", heading: "The verb and adjective listen to different features of the same subject.", paragraphs: ["The subject selects the ser form through person and number: yo → soy, Ana → es, Ana y Mateo → son. A descriptive adjective selects gender and number: creativa, creativo, creativos.", "A noun classification such as estudiante often has one singular form across gender, while other people nouns may change: amigo/amiga. Learn each category word’s behavior rather than forcing one pattern onto all of them.", "Subject omission is natural when the form and context are clear. Soy estudiante is complete. Add yo when contrasting: Yo soy estudiante; él es profesor."], points: [{ label: "VERB", title: "person + number", description: "yo soy; ella es; ellos son" }, { label: "ADJECTIVE", title: "gender + number", description: "creativo, creativa, creativos, creativas" }, { label: "PRONOUN", title: "clarity or contrast", description: "often omitted; stated when it helps the discourse" }] },
  contrast: { eyebrow: "State versus identity frame", heading: "Ser presents a characteristic as part of who the person is in the message.", sides: [{ label: "ROLE / CATEGORY", question: "What is the person?", description: "Ser connects the subject to a social or conceptual category.", examples: [{ text: "Somos estudiantes.", translation: "We are students." }, { text: "Ella es mi amiga.", translation: "She is my friend." }] }, { label: "CHARACTERISTIC", question: "What kind of person?", description: "Ser presents a defining or classifying description.", examples: [{ text: "Luis es tranquilo.", translation: "Luis is calm." }, { text: "Ana es creativa.", translation: "Ana is creative." }] }], note: "Lesson 4.3 will contrast this identity frame with estar’s state frame without relying on permanent versus temporary." },
  guided: { eyebrow: "Coordinate a group", heading: "Ana and Marta are creative.", prompt: "Which predicate matches the feminine plural subject?", options: [{ id: "correct", label: "son creativas" }, { id: "singular", label: "es creativa" }, { id: "masculine", label: "son creativos" }], correctOptionId: "correct", correctFeedback: "The plural subject selects son; two women are described as creativas.", incorrectFeedback: "Coordinate both tracks: plural son and feminine plural creativas." },
  sort: { eyebrow: "Identify the identity angle", heading: "Sort ser statements by what follows the verb.", prompt: "Place each statement under name, role, or characteristic.", buckets: [{ id: "name", label: "NAME", hint: "unique identity" }, { id: "role", label: "ROLE / RELATION", hint: "category" }, { id: "characteristic", label: "CHARACTERISTIC", hint: "what kind of person" }], items: [{ id: "ana", label: "Soy Ana.", answer: "name" }, { id: "mateo", label: "Él es Mateo.", answer: "name" }, { id: "student", label: "Somos estudiantes.", answer: "role" }, { id: "friend", label: "Ella es mi amiga.", answer: "role" }, { id: "calm", label: "Luis es tranquilo.", answer: "characteristic" }, { id: "creative", label: "Ana es creativa.", answer: "characteristic" }] },
  builder: { eyebrow: "Layer the identity", heading: "Build a coordinated self-description.", prompt: "Build: I am Ana and I am creative.", tokens: ["Soy Ana", "y", "soy creativa."], correctOrder: ["Soy Ana", "y", "soy creativa."], answer: "Soy Ana y soy creativa.", feedback: "Soy carries the first-person subject in both clauses; creativa agrees with Ana." },
  reading: { eyebrow: "Meet a small team", heading: "Each person chooses useful identity details.", instructions: "Read or listen, then identify the grammar behind each description.", sentences: [{ id: "r1", text: "Soy Elena. Soy estudiante y soy creativa.", translation: "I am Elena. I am a student and I am creative." }, { id: "r2", text: "Él es Tomás. Es profesor y es tranquilo.", translation: "He is Tomás. He is a teacher and he is calm." }, { id: "r3", text: "Nosotros somos amigos. Somos personas curiosas.", translation: "We are friends. We are curious people." }], questions: [{ id: "q1", prompt: "Why can Elena omit yo?", options: [{ id: "soy", label: "Soy already identifies first-person singular" }, { id: "no-subject", label: "Spanish sentences never have subjects" }], correctOptionId: "soy", feedback: "The subject is still yo; soy and context make it recoverable.", conceptIds: ["ser_forms", "subject_pronouns"] }, { id: "q2", prompt: "Which phrase coordinates plural agreement?", options: [{ id: "curious", label: "personas curiosas" }, { id: "calm", label: "es tranquilo" }], correctOptionId: "curious", feedback: "Both personas and curiosas are feminine plural within the noun phrase.", conceptIds: ["adjective_agreement", "ser_classification"] }] },
  recall: { eyebrow: "Retrieve two tracks", heading: "Complete the identity statement.", prompt: "Type the missing ser or adjective form.", items: [{ id: "ana-creative", before: "Ana es ", after: ". (creative)", accepted: ["creativa"], answer: "creativa", conceptIds: ["adjective_agreement", "ser_identity"], feedback: "Creativa agrees with feminine singular Ana." }, { id: "we-students", before: "Nosotros ", after: " estudiantes.", accepted: ["somos"], answer: "somos", conceptIds: ["ser_forms", "ser_classification"], feedback: "Nosotros selects somos." }, { id: "women-calm", before: "Ellas son ", after: ". (calm)", accepted: ["tranquilas"], answer: "tranquilas", conceptIds: ["adjective_agreement", "ser_identity"], feedback: "An all-feminine plural subject takes tranquilas." }] },
  production: { eyebrow: "Introduce yourself", heading: "Write a layered four-line identity.", prompt: "Give a name, a role or relationship, a characteristic with agreement, and one contrast involving another person or group.", requirements: ["Use soy with a name", "Use a role or relationship", "Use an agreed characteristic", "Use es, somos, or son for another subject"], example: "Soy Ana. Soy estudiante. Soy creativa y tranquila. Mi amigo es Mateo. Somos amigos.", minimumCharacters: 80, evaluation: { minimumIdeas: 4, requiredGroups: [{ accepted: ["soy"], missingFeedback: "Identify yourself with soy." }, { accepted: ["estudiante", "amigo", "amiga", "profesor", "profesora"], missingFeedback: "Add a role or relationship category." }, { accepted: ["creativo", "creativa", "tranquilo", "tranquila", "curioso", "curiosa"], missingFeedback: "Add a characteristic with an agreed adjective." }, { accepted: ["es", "somos", "son"], missingFeedback: "Add another subject with es, somos, or son." }], successFeedback: "Your introduction layers name, category, characteristic, and relationship while coordinating form and agreement." } },
  summary: { eyebrow: "Keep the two tracks", heading: "Ser form and adjective form answer different agreement questions.", message: "Use ser for the identity frame, match the verb to person and number, and match descriptive forms to gender and number.", ideas: [{ label: "SER", question: "Who is the subject?", uses: ["soy / eres / es", "somos / son"] }, { label: "COMPLEMENT", question: "Name, role, or characteristic?", uses: ["Ana", "estudiante", "creativa"] }, { label: "AGREEMENT", question: "Who is being described?", uses: ["gender", "number"] }] },
  completion: { title: "You can now present a layered identity.", message: "Next, ser + de will connect people and things to origin." },
});

export const lesson34 = createFoundationLesson({
  id: "3.4", moduleId: "module-03", title: "Where You Are From", displayTitle: "Origin uses ser + de.",
  dek: "Origin identifies the place a person or thing comes from. Spanish builds that relationship with a form of ser followed by de.",
  goal: "Express personal and object origin with ser + de, choose the correct ser form, and distinguish origin from current location.", durationMinutes: 25, concepts: ["ser_origin", "ser_forms", "subject_pronouns"],
  opening: { eyebrow: "A relationship of origin", heading: "Where someone is from is not the same message as where someone is now.", paragraphs: ["Soy de México states origin: Mexico is the place the speaker comes from or identifies as home. The pattern is subject + ser + de + place.", "The ser form still follows the subject: eres de, es de, somos de, son de. The preposition de creates the origin relationship.", "Do not use en for this pattern. En will locate someone with estar in Module 4. Origin asks where from; location asks where."], spanish: [{ text: "Soy de México.", translation: "I am from Mexico." }, { text: "Ella es de Colombia.", translation: "She is from Colombia." }, { text: "Somos de Perú.", translation: "We are from Peru." }, { text: "Ustedes son de Argentina.", translation: "You all are from Argentina." }, { text: "El café es de Colombia.", translation: "The coffee is from Colombia." }] },
  prediction: { eyebrow: "Build origin", heading: "Luis comes from Peru.", prompt: "Which connector completes Luis es ___ Perú?", options: [{ id: "de", label: "de" }, { id: "en", label: "en" }, { id: "a", label: "a" }], correctOptionId: "de", correctFeedback: "Origin uses ser + de: Luis es de Perú.", incorrectFeedback: "The relationship is from a place, so Spanish uses de." },
  model: { eyebrow: "A stable frame", heading: "Keep the meaning question attached to the pattern.", paragraphs: ["Ask ¿De dónde eres? to one familiar listener: from where are you? The natural answer begins Soy de… because the speaker becomes yo.", "With usted, ask ¿De dónde es usted? With multiple listeners in Latin America, ask ¿De dónde son ustedes? The question word dónde carries an accent.", "The same structure can express the origin of things: El café es de Colombia. The subject does not need to be a person; it needs an origin relationship."], points: [{ label: "QUESTION", title: "¿De dónde…?", description: "asks the source or origin" }, { label: "VERB", title: "ser form", description: "matches the person or thing with the origin" }, { label: "CONNECTOR", title: "de", description: "links the subject to the place of origin" }] },
  contrast: { eyebrow: "Prepare the Module 4 boundary", heading: "Origin and location ask different questions.", sides: [{ label: "ORIGIN", question: "Where from?", description: "Use ser + de to identify source or homeland.", examples: [{ text: "Ana es de Chile.", translation: "Ana is from Chile." }, { text: "El café es de Colombia.", translation: "The coffee is from Colombia." }] }, { label: "LOCATION", question: "Where now?", description: "Use estar + en to locate an identified subject; Module 4 develops this fully.", examples: [{ text: "Ana está en México.", translation: "Ana is in Mexico." }, { text: "El café está en la mesa.", translation: "The coffee is on the table." }] }], note: "A person can be from one place and in another place. The verb follows the relationship you are expressing." },
  guided: { eyebrow: "Address the group", heading: "You ask several people where they are from.", prompt: "Which complete question fits general Latin American Spanish?", options: [{ id: "ustedes", label: "¿De dónde son ustedes?" }, { id: "tu", label: "¿De dónde eres tú?" }, { id: "location", label: "¿Dónde están ustedes?" }], correctOptionId: "ustedes", correctFeedback: "Ustedes addresses multiple listeners and selects son; de dónde asks origin.", incorrectFeedback: "For several listeners, use ustedes + son, and keep de to ask where from." },
  sort: { eyebrow: "Protect the meaning boundary", heading: "Sort messages by origin or current location.", prompt: "Place each sentence under the question it answers.", buckets: [{ id: "origin", label: "WHERE FROM?", hint: "ser + de" }, { id: "location", label: "WHERE NOW?", hint: "estar + en" }], items: [{ id: "ana-chile", label: "Ana es de Chile.", answer: "origin" }, { id: "coffee", label: "El café es de Colombia.", answer: "origin" }, { id: "we-peru", label: "Somos de Perú.", answer: "origin" }, { id: "ana-mexico", label: "Ana está en México.", answer: "location" }, { id: "book-table", label: "El libro está en la mesa.", answer: "location" }] },
  builder: { eyebrow: "Build the question", heading: "Ask one familiar listener about origin.", prompt: "Build: Where are you from?", tokens: ["¿De dónde", "eres?"], correctOrder: ["¿De dónde", "eres?"], answer: "¿De dónde eres?", feedback: "De asks from, dónde carries the question accent, and eres addresses tú." },
  reading: { eyebrow: "Origin and current place", heading: "Three classmates compare home and location.", instructions: "Read or listen, then separate where each person is from from where they are now.", sentences: [{ id: "r1", text: "Sofía es de Colombia, pero está en México.", translation: "Sofía is from Colombia, but she is in Mexico." }, { id: "r2", text: "Mateo es de Argentina y está en Perú.", translation: "Mateo is from Argentina and is in Peru." }, { id: "r3", text: "Nosotros somos de Chile y estamos en Bogotá.", translation: "We are from Chile and are in Bogotá." }], questions: [{ id: "q1", prompt: "Where is Sofía from?", options: [{ id: "colombia", label: "Colombia" }, { id: "mexico", label: "Mexico" }], correctOptionId: "colombia", feedback: "Es de Colombia marks origin; está en México marks current location.", conceptIds: ["ser_origin"] }, { id: "q2", prompt: "Which phrase expresses the group’s origin?", options: [{ id: "chile", label: "somos de Chile" }, { id: "bogota", label: "estamos en Bogotá" }], correctOptionId: "chile", feedback: "Somos de Chile uses ser + de for origin.", conceptIds: ["ser_origin", "ser_forms"] }] },
  recall: { eyebrow: "Retrieve the origin frame", heading: "Complete ser + de from the subject.", prompt: "Type the missing ser form or connector.", items: [{ id: "yo", before: "Yo ", after: " de México.", accepted: ["soy"], answer: "soy", conceptIds: ["ser_forms", "ser_origin"], feedback: "Yo selects soy: Soy de México." }, { id: "ana", before: "Ana es ", after: " Colombia.", accepted: ["de"], answer: "de", conceptIds: ["ser_origin"], feedback: "De links Ana to her place of origin." }, { id: "we", before: "Nosotros ", after: " de Perú.", accepted: ["somos"], answer: "somos", conceptIds: ["ser_forms", "ser_origin"], feedback: "Nosotros selects somos." }, { id: "you-all", before: "Ustedes ", after: " de Argentina.", accepted: ["son"], answer: "son", conceptIds: ["ser_forms", "ser_origin"], feedback: "Ustedes selects son." }] },
  production: { eyebrow: "Place people in two maps", heading: "Write origins and current locations separately.", prompt: "Write four ideas about two people. Give each person an origin with ser + de and a current location with estar + en.", requirements: ["Use soy/es/somos/son + de", "Name at least two places of origin", "Use está/estoy/estamos + en", "Write four separate ideas"], example: "Soy de México. Estoy en Chicago. Ana es de Colombia. Ana está en Madrid.", minimumCharacters: 75, evaluation: { minimumIdeas: 4, requiredGroups: [{ accepted: ["soy de", "es de", "somos de", "son de"], missingFeedback: "Add an origin statement with ser + de." }, { accepted: ["estoy en", "está en", "esta en", "estamos en", "están en", "estan en"], missingFeedback: "Add a current location with estar + en." }, { accepted: ["méxico", "mexico", "colombia", "perú", "peru", "argentina", "chile"], missingFeedback: "Name a Latin American place in an origin statement." }], successFeedback: "Your writing keeps source and current location as separate relationships." } },
  summary: { eyebrow: "Keep the boundary", heading: "Origin is ser + de; location is estar + en.", message: "Choose from the question the sentence answers. Where from builds identity; where now locates an identified subject.", ideas: [{ label: "ORIGIN", question: "¿De dónde?", uses: ["ser", "de"] }, { label: "LOCATION", question: "¿Dónde?", uses: ["estar", "en"] }, { label: "FORM", question: "Who or what is the subject?", uses: ["soy / es", "somos / son"] }] },
  completion: { title: "You can now express origin without confusing it with location.", message: "Next, profession, nationality, and relationships combine the whole identity system." },
});

export const lesson35 = createFoundationLesson({
  id: "3.5", moduleId: "module-03", title: "Professions, Nationality & Relationships", displayTitle: "Build a complete social identity with ser.",
  dek: "Professions, nationalities, and relationships all use ser, but articles and agreement behave differently inside each pattern.",
  goal: "Use ser with professions without an unnecessary article, make nationality adjectives agree, and express relationships with possessive noun phrases.", durationMinutes: 29, concepts: ["profession_article", "nationality_agreement", "relationships", "ser_forms", "ser_classification", "ser_origin", "adjective_agreement"],
  opening: { eyebrow: "Three identity patterns", heading: "The verb stays ser while the complement changes its grammar.", paragraphs: ["Soy profesora classifies the speaker by profession. In a simple unmodified profession statement after ser, Spanish normally omits un or una even when English says a teacher.", "Soy mexicana expresses nationality with an adjective, so the form agrees with the person described: mexicano, mexicana, mexicanos, mexicanas. Nationality and origin are related but not identical structures.", "Ella es mi amiga expresses a relationship. The possessive mi identifies how the person relates to the speaker; amiga agrees with the person named."], spanish: [{ text: "Soy profesora.", translation: "I am a teacher." }, { text: "Soy mexicana.", translation: "I am Mexican." }, { text: "Soy de México.", translation: "I am from Mexico." }, { text: "Ella es mi amiga.", translation: "She is my friend." }, { text: "Ellos son mis hermanos.", translation: "They are my brothers / siblings." }] },
  prediction: { eyebrow: "Avoid the English article", heading: "María states her profession simply.", prompt: "Which sentence is the course’s neutral pattern?", options: [{ id: "no-article", label: "María es profesora." }, { id: "article", label: "María es una profesora." }, { id: "wrong-ser", label: "María son profesora." }], correctOptionId: "no-article", correctFeedback: "A simple profession classification after ser normally appears without an indefinite article: es profesora.", incorrectFeedback: "For a bare profession after ser, omit the English-style article: María es profesora." },
  model: { eyebrow: "Keep three complement rules", heading: "Profession, nationality, and relationship each organize their own phrase.", paragraphs: ["A bare profession functions as a category after ser: Soy estudiante; Ella es médica. An article may return when the noun phrase is modified or identified, but do not add one automatically from English.", "A nationality is usually an adjective and agrees in gender and number: Luis es colombiano; Ana es colombiana; ellos son colombianos. Nationalities are not capitalized in ordinary Spanish writing.", "A relationship uses a noun phrase, often with a possessive: mi amigo, su hermana, nuestros padres. The relationship noun agrees with the person or people it names."], points: [{ label: "PROFESSION", title: "ser + bare role", description: "Soy estudiante. Ella es profesora." }, { label: "NATIONALITY", title: "ser + agreed adjective", description: "Él es peruano. Ella es peruana." }, { label: "RELATIONSHIP", title: "ser + possessive noun phrase", description: "Él es mi amigo. Ellas son mis hermanas." }] },
  contrast: { eyebrow: "Related meanings, different grammar", heading: "Origin names a place; nationality describes the person.", sides: [{ label: "ORIGIN", question: "Where from?", description: "Use ser + de + place name.", examples: [{ text: "Ana es de Colombia.", translation: "Ana is from Colombia." }, { text: "Somos de Perú.", translation: "We are from Peru." }] }, { label: "NATIONALITY", question: "What nationality?", description: "Use an adjective that agrees with the subject.", examples: [{ text: "Ana es colombiana.", translation: "Ana is Colombian." }, { text: "Somos peruanos.", translation: "We are Peruvian." }] }], note: "Do not insert de before a nationality adjective: es colombiana, but es de Colombia." },
  guided: { eyebrow: "Coordinate nationality", heading: "Ana and Marta are Peruvian.", prompt: "Which predicate matches the all-feminine plural subject?", options: [{ id: "correct", label: "son peruanas" }, { id: "masculine", label: "son peruanos" }, { id: "singular", label: "es peruana" }], correctOptionId: "correct", correctFeedback: "The plural subject selects son, and two women are peruanas.", incorrectFeedback: "Coordinate plural son with feminine plural peruanas." },
  sort: { eyebrow: "Identify the pattern", heading: "Sort ser statements by complement type.", prompt: "Place each sentence under profession, nationality, or relationship.", buckets: [{ id: "profession", label: "PROFESSION", hint: "bare category" }, { id: "nationality", label: "NATIONALITY", hint: "agreed adjective" }, { id: "relationship", label: "RELATIONSHIP", hint: "possessive noun phrase" }], items: [{ id: "teacher", label: "Soy profesora.", answer: "profession" }, { id: "students", label: "Somos estudiantes.", answer: "profession" }, { id: "mexican", label: "Ella es mexicana.", answer: "nationality" }, { id: "peruvian", label: "Ellos son peruanos.", answer: "nationality" }, { id: "friend", label: "Él es mi amigo.", answer: "relationship" }, { id: "sisters", label: "Ellas son mis hermanas.", answer: "relationship" }] },
  builder: { eyebrow: "Build a social identity", heading: "Combine profession and nationality without an extra article.", prompt: "Build: Ana is a Mexican doctor.", tokens: ["Ana", "es", "médica mexicana."], correctOrder: ["Ana", "es", "médica mexicana."], answer: "Ana es médica mexicana.", feedback: "Médica is a bare profession after ser, and mexicana agrees with Ana." },
  reading: { eyebrow: "A family introduces itself", heading: "Each sentence contributes a different identity relationship.", instructions: "Read or listen, then identify the pattern carrying each detail.", sentences: [{ id: "r1", text: "Soy Daniel. Soy colombiano y soy profesor.", translation: "I am Daniel. I am Colombian and I am a teacher." }, { id: "r2", text: "Ana es mi esposa. Ella es médica mexicana.", translation: "Ana is my wife. She is a Mexican doctor." }, { id: "r3", text: "Lucía y Mateo son nuestros hijos. Son estudiantes.", translation: "Lucía and Mateo are our children. They are students." }, { id: "r4", text: "Somos una familia colombiana y mexicana.", translation: "We are a Colombian and Mexican family." }], questions: [{ id: "q1", prompt: "Which word expresses Daniel’s profession?", options: [{ id: "teacher", label: "profesor" }, { id: "colombian", label: "colombiano" }], correctOptionId: "teacher", feedback: "Profesor classifies Daniel by profession; colombiano expresses nationality.", conceptIds: ["profession_article", "nationality_agreement"] }, { id: "q2", prompt: "Which phrase expresses a relationship to the speaker?", options: [{ id: "wife", label: "mi esposa" }, { id: "doctor", label: "médica mexicana" }], correctOptionId: "wife", feedback: "The possessive mi makes esposa a relationship noun phrase.", conceptIds: ["relationships"] }] },
  recall: { eyebrow: "Retrieve the complement grammar", heading: "Complete each identity pattern.", prompt: "Type the missing word or phrase.", items: [{ id: "profession", before: "Ana es ", after: ". (a teacher)", accepted: ["profesora"], answer: "profesora", conceptIds: ["profession_article", "ser_classification"], feedback: "The bare profession appears without una: Ana es profesora." }, { id: "nationality", before: "Ana es ", after: ". (Mexican)", accepted: ["mexicana"], answer: "mexicana", conceptIds: ["nationality_agreement", "adjective_agreement"], feedback: "Mexicana agrees with feminine singular Ana." }, { id: "relationship", before: "Ellas son ", after: ". (my sisters)", accepted: ["mis hermanas"], answer: "mis hermanas", conceptIds: ["relationships", "adjective_agreement"], feedback: "Mis hermanas expresses a plural relationship to the speaker." }, { id: "origin", before: "Somos ", after: " Perú. (from)", accepted: ["de"], answer: "de", conceptIds: ["ser_origin"], feedback: "Origin uses ser + de + place." }] },
  production: { eyebrow: "Create a social portrait", heading: "Introduce yourself and two other people.", prompt: "Write at least five ideas including a profession, an agreed nationality, an origin with de, and two relationships.", requirements: ["Use a bare profession after ser", "Use a nationality adjective with agreement", "Use ser + de for origin", "Use two relationship phrases"], example: "Soy Ana. Soy profesora mexicana y soy de México. Luis es mi amigo. Él es médico colombiano. Marta es mi hermana.", minimumCharacters: 105, evaluation: { minimumIdeas: 5, requiredGroups: [{ accepted: ["soy profesora", "soy profesor", "es profesora", "es profesor", "es médica", "es médico", "somos estudiantes", "son estudiantes"], missingFeedback: "Add a profession after ser without an unnecessary un or una." }, { accepted: ["mexicano", "mexicana", "colombiano", "colombiana", "peruano", "peruana", "argentino", "argentina"], missingFeedback: "Add an agreed nationality adjective." }, { accepted: ["soy de", "es de", "somos de", "son de"], missingFeedback: "Add an origin with ser + de." }, { accepted: ["mi amigo", "mi amiga", "mi hermano", "mi hermana", "mis amigos", "mis amigas", "nuestros hijos", "mi esposo", "mi esposa"], missingFeedback: "Add at least one clear relationship phrase; use a second relationship in another idea." }], successFeedback: "Your portrait coordinates profession, nationality, origin, and relationships inside the ser identity system." } },
  summary: { eyebrow: "Keep the complement rules", heading: "One verb, three identity structures.", message: "Ser establishes the identity frame. The words after it decide whether the phrase needs a bare role, an agreed adjective, or a possessive noun phrase.", ideas: [{ label: "PROFESSION", question: "What role?", uses: ["ser + bare noun", "soy profesora"] }, { label: "NATIONALITY", question: "What nationality?", uses: ["agreed adjective", "es mexicana"] }, { label: "RELATIONSHIP", question: "Who is this person to someone?", uses: ["possessive phrase", "mi amiga"] }] },
  completion: { title: "You can now build a complete social identity with ser.", message: "Module 4 is ready to contrast identity with states, location, and existence." },
});

export const module03Lessons = [lesson31, lesson32, lesson33, lesson34, lesson35];
