import { createCourseLesson } from "./course-lesson-factory";

export const module08LessonDefinitions = [
  createCourseLesson({
    id: "8.1", title: "Stem Changes", displayTitle: "The endings stay regular while a stressed stem vowel changes.",
    dek: "Present-tense stem changes follow stress: e→ie, o→ue, and e→i appear in all emphasized forms except nosotros.",
    goal: "Recognize and apply common present stem changes without changing regular endings.", durationMinutes: 27, concepts: ["stem_change"],
    explain: [
      "Many high-frequency verbs keep regular present endings but change a stem vowel when that syllable is stressed: pensar → pienso, volver → vuelvo, pedir → pido. The change appears in yo, tú, usted/él/ella, and ustedes/ellos/ellas.",
      "Nosotros normally keeps the original stem vowel because stress moves to the ending: pensamos, volvemos, pedimos. Learn a stem-changing verb with its change type and use the infinitive to recover the nosotros form.",
    ],
    examples: [["Pienso en mi familia.", "I think about my family."], ["Volvemos a casa.", "We return home."], ["Ellos piden café.", "They order coffee."]],
    boundary: { heading: "Nosotros is outside the present stem-change pattern.", note: "Stress explains the apparent exception.",
      left: { label: "STRESSED STEM", question: "Is the stem syllable stressed?", description: "Yo and most non-nosotros forms show the change.", example: ["Ella vuelve.", "She returns."] },
      right: { label: "NOSOTROS", question: "Does stress move to the ending?", description: "Keep the infinitive stem vowel in the nosotros form.", example: ["Volvemos.", "We return."] } },
    prediction: { heading: "Conjugate pensar for yo.", context: "Pensar follows the e→ie pattern.", prompt: "Which form combines the changed stem with the regular -o ending?", options: ["pienso", "penso", "pensio"], answer: 0, correct: "Pens- changes to piens- and yo adds -o.", incorrect: "Apply e→ie inside the stem, then add the regular yo ending: pienso." },
    guided: { heading: "Protect the nosotros stem.", context: "Volver is o→ue, but the subject is nosotros.", prompt: "Which form is correct?", options: ["volvemos", "vuelvemos", "vuelven"], answer: 0, correct: "Nosotros keeps volv- and adds -emos.", incorrect: "The present stem change does not occur in nosotros: volvemos." },
    builder: { prompt: "Build: They prefer to study here.", tokens: ["Ellos", "prefieren", "estudiar", "aquí."], correctOrder: ["Ellos", "prefieren", "estudiar", "aquí."], answer: "Ellos prefieren estudiar aquí.", feedback: "Preferir changes e→ie in prefieren; the attached action remains an infinitive." },
    reading: { heading: "Choosing lunch.", sentences: [["Mis amigos quieren comer ahora.", "My friends want to eat now."], ["Yo prefiero esperar.", "I prefer to wait."], ["Ellos piden dos cafés.", "They order two coffees."], ["Después volvemos juntos.", "Afterward we return together."]], question: { prompt: "Why does volvemos keep o?", options: ["Nosotros keeps the original stem vowel", "Volver is regular in every form", "The sentence is negative"], answer: 0, feedback: "Present stem changes normally skip nosotros." } },
    recall: [
      { before: "Yo ", after: " estudiar. (preferir)", answer: "prefiero", feedback: "Preferir changes e→ie in the yo form." },
      { before: "Nosotros ", after: " a casa. (volver)", answer: "volvemos", feedback: "Nosotros keeps the original o and uses -emos." },
      { before: "Ellas ", after: " ayuda. (pedir)", answer: "piden", feedback: "Pedir changes e→i in the stressed plural form piden." },
    ],
    production: { prompt: "Write four present sentences with stem-changing verbs, including one nosotros contrast.", requirements: ["Use at least two change types", "Include one nosotros form without the change", "Keep regular present endings"], example: "Pienso en casa. Ana vuelve tarde. Ellos piden café. Nosotros pedimos té." },
    takeaway: "Change the stressed stem vowel in most present forms, but recover the original stem for nosotros.",
  }),
  createCourseLesson({
    id: "8.2", title: "QUERER & PODER", displayTitle: "Wanting and being able to open a second action.",
    dek: "Querer and poder change their stems, then connect directly to an infinitive.",
    goal: "Express wants, invitations, and ability with querer/poder + infinitive.", durationMinutes: 27, concepts: ["querer_poder", "stem_change"],
    explain: [
      "Querer changes e→ie: quiero, quieres, quiere, queremos, quieren. Poder changes o→ue: puedo, puedes, puede, podemos, pueden. Nosotros keeps the original stem vowel in both verbs.",
      "When another action follows, it remains an infinitive because querer or poder already carries the subject: Quiero viajar; Podemos estudiar. ¿Quieres…? offers an invitation, while ¿Puedes…? asks about ability or makes a request.",
    ],
    examples: [["Quiero aprender español.", "I want to learn Spanish."], ["¿Puedes ayudarme?", "Can you help me?"], ["Podemos hablar mañana.", "We can talk tomorrow."]],
    boundary: { heading: "Querer asks desire; poder asks possibility or ability.", note: "Both may precede an infinitive, but they frame it differently.",
      left: { label: "QUERER", question: "Does someone want the action?", description: "Use querer for desire, preference, or an invitation.", example: ["¿Quieres venir?", "Do you want to come?"] },
      right: { label: "PODER", question: "Is the action possible?", description: "Use poder for ability, permission, or a polite request.", example: ["¿Puedes venir?", "Can you come?"] } },
    prediction: { heading: "Express ability.", context: "The speaker is able to help today.", prompt: "Which form and structure fit?", options: ["Puedo ayudar hoy.", "Quiero poderé hoy.", "Podo ayudar hoy."], answer: 0, correct: "Poder changes to puedo and the second action stays ayudar.", incorrect: "Use the o→ue yo form puedo followed by the infinitive ayudar." },
    guided: { heading: "Invite a friend.", context: "You want to ask whether the friend wants to study.", prompt: "Which question frames desire?", options: ["¿Quieres estudiar?", "¿Puedes querer estudias?", "¿Queremos estudias?"], answer: 0, correct: "Quieres agrees with tú; estudiar remains an infinitive.", incorrect: "Use tú quieres followed directly by the infinitive estudiar." },
    builder: { prompt: "Build: We can practice tomorrow.", tokens: ["Podemos", "practicar", "mañana."], correctOrder: ["Podemos", "practicar", "mañana."], answer: "Podemos practicar mañana.", feedback: "Nosotros uses podemos without a stem change, and practicar remains infinitive." },
    reading: { heading: "An invitation.", sentences: [["—¿Quieres estudiar conmigo?", "Do you want to study with me?"], ["—Sí, pero no puedo hoy.", "Yes, but I cannot today."], ["—¿Podemos estudiar mañana?", "Can we study tomorrow?"], ["—Sí, quiero empezar a las cuatro.", "Yes, I want to start at four."]], question: { prompt: "Why does the first answer use puedo?", options: ["It says today is not possible", "It says the speaker has no desire", "It identifies a location"], answer: 0, feedback: "No puedo hoy expresses that the action is not possible today." } },
    recall: [
      { before: "Yo ", after: " viajar. (querer)", answer: "quiero", feedback: "Querer changes e→ie in quiero." },
      { before: "Tú ", after: " ayudar. (poder)", answer: "puedes", feedback: "Poder changes o→ue in puedes." },
      { before: "Nosotros ", after: " hablar. (poder)", answer: "podemos", feedback: "Nosotros keeps the original stem: podemos." },
    ],
    production: { prompt: "Write a four-line exchange that includes an invitation, an inability, and a new possible plan.", requirements: ["Use querer + infinitive", "Use no poder + infinitive", "Use a nosotros form"], example: "¿Quieres estudiar? Sí, pero no puedo hoy. ¿Podemos hablar mañana? Sí, quiero practicar." },
    takeaway: "Conjugate querer for desire or poder for possibility, then leave the second action in the infinitive.",
  }),
  createCourseLesson({
    id: "8.3", title: "TENER and Common Expressions", displayTitle: "Tener carries possession, age, and everyday states.",
    dek: "Tengo is irregular in yo; the other forms support a family of high-value expressions.",
    goal: "Use tener for possession, age, needs, and common tener + noun expressions.", durationMinutes: 27, concepts: ["tener_expressions"],
    explain: [
      "Tener forms are tengo, tienes, tiene, tenemos, tienen. It changes e→ie in most forms, keeps e in nosotros, and adds g in yo. Beyond possession, Spanish uses tener where English often uses be.",
      "Use tener + number + años for age and tener + noun for conditions: tener hambre, sed, frío, calor, sueño, miedo, razón, prisa, suerte. These nouns do not agree like adjectives because they remain nouns.",
    ],
    examples: [["Tengo veintiún años.", "I am twenty-one years old."], ["Tenemos hambre.", "We are hungry."], ["Ana tiene razón.", "Ana is right."]],
    boundary: { heading: "These conditions are held with tener, not described with estar.", note: "Translate the Spanish structure rather than the English word am/is/are.",
      left: { label: "TENER + NOUN", question: "Is it a conventional tener expression?", description: "Age, hunger, thirst, and similar conditions use tener.", example: ["Tengo sueño.", "I am sleepy."] },
      right: { label: "ESTAR + ADJECTIVE", question: "Is it a descriptive state?", description: "Other states remain adjective descriptions with estar.", example: ["Estoy cansado.", "I am tired."] } },
    prediction: { heading: "State an age.", context: "Lucía is 20 years old.", prompt: "Which Spanish structure is correct?", options: ["Lucía tiene veinte años.", "Lucía es veinte años.", "Lucía está veinte."], answer: 0, correct: "Spanish holds age with tener + number + años.", incorrect: "Use tener for age: tiene veinte años." },
    guided: { heading: "Express hunger.", context: "The subject is nosotros.", prompt: "Which form and noun phrase fit?", options: ["Tenemos hambre.", "Estamos hambre.", "Tienen hambrientos."], answer: 0, correct: "Nosotros uses tenemos, followed by the noun hambre.", incorrect: "Hunger is the fixed expression tener hambre." },
    builder: { prompt: "Build: My friends are in a hurry.", tokens: ["Mis amigos", "tienen", "prisa."], correctOrder: ["Mis amigos", "tienen", "prisa."], answer: "Mis amigos tienen prisa.", feedback: "The plural subject uses tienen; prisa remains a noun." },
    reading: { heading: "Before the trip.", sentences: [["Tengo veintidós años.", "I am twenty-two years old."], ["Hoy tengo mucha prisa.", "Today I am in a big hurry."], ["Mis amigos tienen hambre.", "My friends are hungry."], ["Pero todos tenemos suerte: el autobús está aquí.", "But we are all lucky: the bus is here."]], question: { prompt: "Which form includes the speaker and friends?", options: ["tenemos", "tienen", "tengo"], answer: 0, feedback: "Tenemos is the nosotros form." } },
    recall: [
      { before: "Yo ", after: " frío.", answer: "tengo", feedback: "The irregular yo form is tengo." },
      { before: "Ana ", after: " diecinueve años.", answer: "tiene", feedback: "One third-person subject uses tiene." },
      { before: "Nosotros ", after: " razón.", answer: "tenemos", feedback: "Nosotros keeps the stem vowel: tenemos." },
    ],
    production: { prompt: "Write four connected facts using tener: possession, age, one physical need, and one abstract expression.", requirements: ["Use at least three forms of tener", "Include age with años", "Keep tener-expression nouns unchanged"], example: "Tengo un libro. Tengo veintidós años. Mi amiga tiene hambre. Tenemos suerte." },
    takeaway: "Use tener not only to possess, but also to carry age and conventional noun-based conditions.",
  }),
  createCourseLesson({
    id: "8.4", title: "HACER & PONER", displayTitle: "The yo form adds g; the rest follows a stable pattern.",
    dek: "Hago and pongo anchor two versatile verbs for making, doing, weather, and placing.",
    goal: "Use hacer and poner in common present-time messages and expressions.", durationMinutes: 26, concepts: ["hacer_poner"],
    explain: [
      "Hacer forms are hago, haces, hace, hacemos, hacen; poner forms are pongo, pones, pone, ponemos, ponen. Their main irregularity is the yo form in -go. The remaining present endings follow familiar -er behavior.",
      "Hacer means do or make and appears in weather expressions: hace frío, hace calor, hace buen tiempo. Poner means put or place and also appears in ponerse for changes, which Module 12 will develop.",
    ],
    examples: [["Hago la tarea.", "I do the homework."], ["Hace frío hoy.", "It is cold today."], ["Pongo el libro en la mesa.", "I put the book on the table."]],
    boundary: { heading: "Hacer creates or performs; poner places.", note: "English do and make collapse into hacer, while placement remains poner.",
      left: { label: "HACER", question: "Is something done, made, or expressed as weather?", description: "Use hacer for tasks, creation, and impersonal weather.", example: ["Hacemos la cena.", "We make dinner."] },
      right: { label: "PONER", question: "Is something being placed?", description: "Use poner when an object moves to a location.", example: ["Ponemos la mesa.", "We set the table."] } },
    prediction: { heading: "Choose the irregular yo form.", context: "The speaker does homework every evening.", prompt: "Which form completes Yo ___ la tarea?", options: ["hago", "haco", "hace"], answer: 0, correct: "The yo form of hacer is hago.", incorrect: "Hacer adds g in the yo form: hago." },
    guided: { heading: "Place an object.", context: "The speaker puts a phone on the desk.", prompt: "Which verb and form fit yo?", options: ["Pongo", "Hago", "Pone"], answer: 0, correct: "Pongo is the yo form used to place an object.", incorrect: "Use poner for placement and its yo form pongo." },
    builder: { prompt: "Build: We make dinner and set the table.", tokens: ["Hacemos", "la cena", "y ponemos", "la mesa."], correctOrder: ["Hacemos", "la cena", "y ponemos", "la mesa."], answer: "Hacemos la cena y ponemos la mesa.", feedback: "Both nosotros forms keep regular -emos endings." },
    reading: { heading: "Getting ready at home.", sentences: [["Yo hago la comida.", "I make the food."], ["Mi hermano pone los platos en la mesa.", "My brother puts the plates on the table."], ["Después hacemos café.", "Afterward we make coffee."], ["Hace frío, pero la casa está cómoda.", "It is cold, but the house is comfortable."]], question: { prompt: "Which use of hacer is impersonal?", options: ["Hace frío", "Hago la comida", "Hacemos café"], answer: 0, feedback: "Hace frío is a weather expression without a personal subject." } },
    recall: [
      { before: "Yo ", after: " ejercicio. (hacer)", answer: "hago", feedback: "The irregular yo form is hago." },
      { before: "Ella ", after: " el libro aquí. (poner)", answer: "pone", feedback: "One third-person subject uses pone." },
      { before: "Nosotros ", after: " la cena. (hacer)", answer: "hacemos", feedback: "Nosotros uses hacemos." },
    ],
    production: { prompt: "Describe preparing a meal or workspace with at least two uses each of hacer and poner.", requirements: ["Use hago or pongo once", "Use one plural form", "Distinguish making/doing from placing"], example: "Hago la cena. Mi amigo pone los vasos. Hacemos café y ponemos los libros aquí." },
    takeaway: "Remember hago and pongo as -go yo forms, then use hacer for doing/making and poner for placing.",
  }),
  createCourseLesson({
    id: "8.5", title: "VENIR, SALIR & OÍR", displayTitle: "Movement and hearing share irregular yo forms, not one full pattern.",
    dek: "Vengo, salgo, and oigo are anchors; the rest of each verb must still match its own behavior.",
    goal: "Use venir, salir, and oír for arrival, departure, and hearing in the present.", durationMinutes: 27, concepts: ["venir_salir_oir"],
    explain: [
      "Venir uses vengo in yo and e→ie in most non-nosotros forms: vienes, viene, venimos, vienen. Salir uses salgo in yo but otherwise follows regular -ir endings. Oír uses oigo in yo and adds written accents where needed: oyes, oye, oímos, oyen.",
      "The three verbs share a useful -go yo memory hook, but do not force them into one identical chart. Venir means come toward a reference point; salir means leave or go out; oír means perceive sound.",
    ],
    examples: [["Vengo a las seis.", "I am coming at six."], ["Salimos de casa temprano.", "We leave home early."], ["Oigo música.", "I hear music."]],
    boundary: { heading: "Movement depends on the reference point.", note: "Venir moves toward here/there being discussed; salir moves out from a place.",
      left: { label: "VENIR", question: "Movement toward the reference point?", description: "Use venir for coming.", example: ["¿Vienes a mi casa?", "Are you coming to my house?"] },
      right: { label: "SALIR", question: "Movement out of a place?", description: "Use salir for leaving or going out.", example: ["Salgo de casa.", "I leave home."] } },
    prediction: { heading: "Choose the yo hearing form.", context: "The speaker perceives music.", prompt: "Which form is correct?", options: ["oigo", "oyo", "oí"], answer: 0, correct: "The present yo form of oír is oigo.", incorrect: "Oír uses the irregular yo form oigo." },
    guided: { heading: "Invite a friend toward you.", context: "You are at home and ask a friend whether they are coming.", prompt: "Which question fits the reference point?", options: ["¿Vienes a mi casa?", "¿Sales a mi casa?", "¿Vengo a mi casa?"], answer: 0, correct: "Vienes means you come toward the speaker’s home.", incorrect: "The friend moves toward the speaker’s location, so use venir." },
    builder: { prompt: "Build: We leave at eight and come back at ten.", tokens: ["Salimos", "a las ocho", "y venimos", "a las diez."], correctOrder: ["Salimos", "a las ocho", "y venimos", "a las diez."], answer: "Salimos a las ocho y venimos a las diez.", feedback: "Both nosotros forms use -imos and keep their original stems." },
    reading: { heading: "Concert plans.", sentences: [["—¿Vienes al concierto?", "Are you coming to the concert?"], ["—Sí, salgo de casa a las siete.", "Yes, I leave home at seven."], ["—¿Oyes bien desde tu asiento?", "Can you hear well from your seat?"], ["—Sí, oigo todo.", "Yes, I hear everything."]], question: { prompt: "What happens at seven?", options: ["The person leaves home", "The concert begins", "The person hears music"], answer: 0, feedback: "Salgo de casa a las siete gives the departure time." } },
    recall: [
      { before: "Yo ", after: " a la reunión. (venir)", answer: "vengo", feedback: "The yo form of venir is vengo." },
      { before: "Nosotros ", after: " temprano. (salir)", answer: "salimos", feedback: "The nosotros form is regular: salimos." },
      { before: "Tú ", after: " la música. (oír)", answer: "oyes", feedback: "The tú form of oír is oyes." },
    ],
    production: { prompt: "Write a four-line plan that says when someone comes, leaves, and what they hear.", requirements: ["Use venir and salir with clear reference points", "Use one form of oír", "Include at least two subjects"], example: "Vengo a las seis. Ana sale a las siete. Oímos música. Mis amigos vienen después." },
    takeaway: "Anchor vengo, salgo, and oigo, then conjugate each verb according to its own remaining pattern.",
  }),
  createCourseLesson({
    id: "8.6", title: "SABER vs. CONOCER", displayTitle: "Spanish separates knowing information from knowing through familiarity.",
    dek: "Saber handles facts and abilities; conocer handles people, places, and firsthand familiarity.",
    goal: "Choose saber or conocer from the kind of knowledge being expressed.", durationMinutes: 28, concepts: ["saber_conocer"],
    explain: [
      "Saber forms are sé, sabes, sabe, sabemos, saben. Use saber for facts, answers, and knowing how to perform an action: Sé la respuesta; Sabemos cocinar. Before an action, Spanish uses saber + infinitive without cómo.",
      "Conocer forms are conozco, conoces, conoce, conocemos, conocen. Use conocer for people, places, works, and familiarity through experience. A known person normally takes the personal a: Conozco a Elena.",
    ],
    examples: [["Sé la respuesta.", "I know the answer."], ["Sabemos cocinar.", "We know how to cook."], ["Conozco a tu profesora.", "I know your professor."]],
    boundary: { heading: "Ask what kind of knowledge is claimed.", note: "Both translate as know, but they organize different relationships.",
      left: { label: "SABER", question: "A fact, answer, or ability?", description: "Use saber for information and knowing how to do something.", example: ["Sé dónde está.", "I know where it is."] },
      right: { label: "CONOCER", question: "A person, place, or familiar work?", description: "Use conocer for acquaintance and firsthand familiarity.", example: ["Conozco Bogotá.", "I know Bogotá."] } },
    prediction: { heading: "Express an ability.", context: "The speaker knows how to swim.", prompt: "Which structure is natural?", options: ["Sé nadar.", "Conozco nadar.", "Sé cómo nadando."], answer: 0, correct: "Saber + infinitive expresses knowing how to perform an action.", incorrect: "Use saber followed directly by the infinitive: sé nadar." },
    guided: { heading: "Express acquaintance.", context: "The speaker personally knows Marta.", prompt: "Which sentence fits?", options: ["Conozco a Marta.", "Sé Marta.", "Conozco que Marta."], answer: 0, correct: "Conocer plus personal a expresses acquaintance with a person.", incorrect: "Use conocer for a known person and include personal a." },
    builder: { prompt: "Build: We know where the library is.", tokens: ["Sabemos", "dónde está", "la biblioteca."], correctOrder: ["Sabemos", "dónde está", "la biblioteca."], answer: "Sabemos dónde está la biblioteca.", feedback: "The sentence claims knowledge of information, so it uses saber." },
    reading: { heading: "A guide in Mexico City.", sentences: [["Conozco bien la Ciudad de México.", "I know Mexico City well."], ["Sé dónde están los museos.", "I know where the museums are."], ["Conozco a una guía local.", "I know a local guide."], ["Ella sabe explicar la historia.", "She knows how to explain the history."]], question: { prompt: "Why does the final sentence use sabe?", options: ["It describes an ability", "It names a familiar place", "It introduces a person"], answer: 0, feedback: "Saber + infinitive expresses the guide’s ability to explain." } },
    recall: [
      { before: "Yo ", after: " la respuesta. (know)", answer: "sé", accepted: ["sé", "se"], feedback: "A known answer is information, so use sé." },
      { before: "Nosotros ", after: " Lima. (are familiar with)", answer: "conocemos", feedback: "Familiarity with a place uses conocer." },
      { before: "Ella ", after: " cocinar. (knows how)", answer: "sabe", feedback: "Ability uses saber + infinitive." },
    ],
    production: { prompt: "Write four contrasts about knowledge: a fact, an ability, a familiar person, and a familiar place.", requirements: ["Use saber for fact and ability", "Use conocer for person and place", "Include personal a before the person"], example: "Sé la respuesta y sé cocinar. Conozco a Elena y conozco Bogotá." },
    takeaway: "Use saber for information and abilities; use conocer for people, places, and familiarity through experience.",
  }),
];
