import { createCourseLesson } from "./course-lesson-factory";

export const module11LessonDefinitions = [
  createCourseLesson({
    id: "11.1", title: "To Whom?", displayTitle: "The indirect object identifies the recipient or beneficiary.",
    dek: "A direct object receives the action; an indirect object receives or benefits from that object or action.",
    goal: "Distinguish direct objects from indirect recipients in meaningful sentences.", durationMinutes: 25, concepts: ["indirect_objects", "direct_objects"],
    explain: [
      "In Doy el libro a Ana, el libro is what is given—the direct object. Ana is the person to whom it is given—the indirect object. Ask what? to find the direct object and to whom/for whom? to find the indirect relationship.",
      "The phrase a + person can therefore represent two different roles. Personal a marks a human direct object in Veo a Ana; recipient a introduces an indirect object in Doy el libro a Ana. The verb’s meaning determines the role.",
    ],
    examples: [["Doy el libro a Ana.", "I give the book to Ana."], ["Escribimos un mensaje al profesor.", "We write a message to the professor."], ["Veo a Ana.", "I see Ana."]],
    boundary: { heading: "The same a can mark two different relationships.", note: "Ask what role the person plays in the action.",
      left: { label: "DIRECT PERSON", question: "Does the action act directly on the person?", description: "Personal a marks the human direct object.", example: ["Veo a Ana.", "I see Ana."] },
      right: { label: "RECIPIENT", question: "Does the person receive something?", description: "A introduces the indirect recipient.", example: ["Doy el libro a Ana.", "I give the book to Ana."] } },
    prediction: { heading: "Find the recipient.", context: "The sentence is Marta envía una carta a su madre.", prompt: "Who receives the letter?", options: ["su madre", "una carta", "Marta"], answer: 0, correct: "A su madre names the indirect recipient.", incorrect: "Una carta is what is sent; su madre is the person to whom it is sent." },
    guided: { heading: "Separate the objects.", context: "In Preparamos café para los invitados, café is prepared for someone.", prompt: "What is the beneficiary?", options: ["los invitados", "café", "preparamos"], answer: 0, correct: "Para los invitados names who benefits.", incorrect: "Café is the direct object; los invitados benefit from it." },
    builder: { prompt: "Build: We send the message to the professor.", tokens: ["Enviamos", "el mensaje", "al profesor."], correctOrder: ["Enviamos", "el mensaje", "al profesor."], answer: "Enviamos el mensaje al profesor.", feedback: "El mensaje is sent; al profesor is its recipient." },
    reading: { heading: "A birthday gift.", sentences: [["Compro un regalo para Elena.", "I buy a gift for Elena."], ["Mi hermano escribe una tarjeta para ella.", "My brother writes a card for her."], ["Damos el regalo a Elena por la tarde.", "We give the gift to Elena in the afternoon."], ["Elena prepara café para nosotros.", "Elena makes coffee for us."]], question: { prompt: "What is the direct object in Damos el regalo a Elena?", options: ["el regalo", "Elena", "nosotros"], answer: 0, feedback: "El regalo is what is given; Elena is the recipient." } },
    recall: [
      { before: "Doy el libro ", after: " Ana.", answer: "a", feedback: "A introduces Ana as the recipient." },
      { before: "Escribimos una carta ", after: " profesor.", answer: "al", feedback: "A + el profesor contracts to al." },
      { before: "Preparo comida ", after: " mis amigos.", answer: "para", feedback: "Para introduces who benefits from the food." },
    ],
    production: { prompt: "Write four sentences with something transferred, written, bought, or prepared for a recipient.", requirements: ["Make the direct object explicit", "Name the recipient or beneficiary", "Use both a and para relationships"], example: "Doy un libro a Ana. Envío una carta al profesor. Compro café para Marta. Preparamos comida para ellos." },
    takeaway: "Find what receives the action directly, then ask to whom or for whom to identify the indirect participant.",
  }),
  createCourseLesson({
    id: "11.2", title: "Indirect Object Pronouns", displayTitle: "Me, te, le, nos, and les keep the recipient inside the sentence.",
    dek: "An indirect object pronoun points to who receives or benefits; an a-phrase can clarify that person.",
    goal: "Choose and place indirect object pronouns for recipients and beneficiaries.", durationMinutes: 27, concepts: ["indirect_object_pronouns", "indirect_objects"],
    explain: [
      "The indirect object pronouns are me, te, le, nos, and les. They normally appear before a conjugated verb: Ana me escribe; Le damos el libro; Nos preparan café.",
      "Le and les do not reveal gender, so an a-phrase can clarify or emphasize: Le doy el libro a Elena; Les escribo a mis padres. In standard conversational Spanish, the pronoun is normally retained even when the clarifying phrase appears.",
    ],
    examples: [["Ana me escribe.", "Ana writes to me."], ["Le doy el libro a Elena.", "I give the book to Elena."], ["Nos preparan café.", "They make coffee for us."]],
    boundary: { heading: "The pronoun carries the role; the a-phrase clarifies the identity.", note: "Le alone means to him, her, or you formal.",
      left: { label: "PRONOUN", question: "Who is the recipient grammatically?", description: "Me, te, le, nos, or les marks the indirect relationship.", example: ["Le escribo.", "I write to him/her/you."] },
      right: { label: "CLARIFIER", question: "Which person exactly?", description: "Add a + noun/pronoun for clarity or emphasis.", example: ["Le escribo a Ana.", "I write to Ana."] } },
    prediction: { heading: "Choose a nosotros recipient.", context: "They prepare dinner for us.", prompt: "Which pronoun appears before preparan?", options: ["nos", "les", "los"], answer: 0, correct: "Nos marks us as the indirect beneficiaries.", incorrect: "The recipient/beneficiary is us, so use nos." },
    guided: { heading: "Clarify le.", context: "The book is given specifically to Marta.", prompt: "Which sentence keeps the pronoun and clarification?", options: ["Le doy el libro a Marta.", "La doy el libro a Marta.", "Doy le el libro Marta."], answer: 0, correct: "Le carries the indirect role; a Marta clarifies the recipient.", incorrect: "Use le before doy and retain a Marta as clarification." },
    builder: { prompt: "Build: Our professor explains the lesson to us.", tokens: ["Nuestra profesora", "nos", "explica", "la lección."], correctOrder: ["Nuestra profesora", "nos", "explica", "la lección."], answer: "Nuestra profesora nos explica la lección.", feedback: "Nos marks the learners who receive the explanation." },
    reading: { heading: "Sharing class notes.", sentences: [["El profesor nos da una guía.", "The professor gives us a guide."], ["Yo le envío mis notas a Ana.", "I send my notes to Ana."], ["Ana me escribe una pregunta.", "Ana writes me a question."], ["Después les explicamos la respuesta a nuestros amigos.", "Afterward we explain the answer to our friends."]], question: { prompt: "What does les refer to in the final line?", options: ["nuestros amigos", "the speaker", "Ana"], answer: 0, feedback: "A nuestros amigos clarifies the plural recipient les." } },
    recall: [
      { before: "Ana ", after: " escribe. (to me)", answer: "me", feedback: "Me marks the speaker as recipient." },
      { before: "", after: " damos el libro a Marta. (to her)", answer: "Le", accepted: ["le"], feedback: "Le marks Marta as the indirect recipient." },
      { before: "El profesor ", after: " explica la lección. (to us)", answer: "nos", feedback: "Nos marks us as recipients of the explanation." },
    ],
    production: { prompt: "Write five recipient sentences using me, te, le, nos, and les; clarify le and les with a-phrases.", requirements: ["Use every indirect object pronoun", "Place each before a conjugated verb", "Clarify le and les"], example: "Me escribes. Te doy café. Le envío un mensaje a Ana. Nos explican la clase. Les compro libros a mis amigos." },
    takeaway: "Use me, te, le, nos, or les before the verb to mark the recipient; add an a-phrase when identity needs clarity.",
  }),
  createCourseLesson({
    id: "11.3", title: "How GUSTAR Really Works", displayTitle: "With gustar, the pleasing thing is the grammatical subject.",
    dek: "The person experiences the reaction through an indirect object pronoun; Spanish does not make that person the actor.",
    goal: "Interpret and build gustar sentences from the Spanish relationship rather than English word order.", durationMinutes: 28, concepts: ["gustar_structure", "indirect_object_pronouns"],
    explain: [
      "Me gusta el café literally organizes the idea as coffee is pleasing to me. El café is the grammatical subject, gusta agrees with it, and me marks the experiencer. English translates the whole relationship naturally as I like coffee.",
      "Use a mí, a ti, a él/ella/usted, a nosotros, or a ellos/ellas/ustedes for emphasis or clarification, but keep the pronoun: A Ana le gusta el café. The a-phrase does not replace le.",
    ],
    examples: [["Me gusta el café.", "I like coffee."], ["A Ana le gusta bailar.", "Ana likes to dance."], ["Nos gusta la clase.", "We like the class."]],
    boundary: { heading: "English centers the liker; Spanish centers what pleases.", note: "Do not conjugate gustar to agree with the person who likes.",
      left: { label: "EXPERIENCER", question: "To whom is it pleasing?", description: "Use an indirect object pronoun for the person.", example: ["A mí me…", "To me…"] },
      right: { label: "PLEASING SUBJECT", question: "What is pleasing?", description: "Gustar agrees with the thing or action liked.", example: ["…gusta el libro.", "…the book is pleasing."] } },
    prediction: { heading: "Build I like the class.", context: "La clase is one pleasing subject; the experiencer is me.", prompt: "Which Spanish structure fits?", options: ["Me gusta la clase.", "Yo gusto la clase.", "Me gusto la clase."], answer: 0, correct: "Me marks the experiencer and gusta agrees with la clase.", incorrect: "Do not make yo the subject of gustar; use me gusta la clase." },
    guided: { heading: "Clarify Ana’s reaction.", context: "Ana likes to read.", prompt: "Which sentence keeps both the clarifier and pronoun?", options: ["A Ana le gusta leer.", "Ana gusta leer.", "A Ana gusta leer."], answer: 0, correct: "A Ana clarifies le; leer is the pleasing action.", incorrect: "Use a Ana + le + gusta + infinitive." },
    builder: { prompt: "Build: We like to practice Spanish.", tokens: ["Nos", "gusta", "practicar español."], correctOrder: ["Nos", "gusta", "practicar español."], answer: "Nos gusta practicar español.", feedback: "Nos marks us; the infinitive activity takes singular gusta." },
    reading: { heading: "Different preferences.", sentences: [["A mí me gusta estudiar temprano.", "I like to study early."], ["A Ana le gusta la biblioteca.", "Ana likes the library."], ["A nosotros nos gusta practicar juntos.", "We like to practice together."], ["A Carlos no le gusta hablar en público.", "Carlos does not like speaking in public."]], question: { prompt: "Who dislikes public speaking?", options: ["Carlos", "Ana", "the speaker"], answer: 0, feedback: "A Carlos clarifies le, and no le gusta marks the negative reaction." } },
    recall: [
      { before: "", after: " gusta el café. (to me)", answer: "Me", accepted: ["me"], feedback: "Me marks the speaker as experiencer." },
      { before: "A Ana ", after: " gusta leer.", answer: "le", feedback: "Le remains required even with a Ana." },
      { before: "", after: " gusta la clase. (to us)", answer: "Nos", accepted: ["nos"], feedback: "Nos marks us as experiencers." },
    ],
    production: { prompt: "Write four gustar reactions for yourself and other people, including one negative and one infinitive activity.", requirements: ["Use indirect object pronouns", "Clarify one third-person experiencer", "Make the pleasing thing explicit"], example: "Me gusta el café. A Ana le gusta leer. No nos gusta esperar. Les gusta la música." },
    takeaway: "Build gustar from the pleasing subject outward: it agrees with what is liked, while the indirect object pronoun marks who experiences it.",
  }),
  createCourseLesson({
    id: "11.4", title: "GUSTA vs. GUSTAN", displayTitle: "Gustar agrees with what is pleasing, not who likes it.",
    dek: "One thing or an infinitive takes gusta; plural things take gustan.",
    goal: "Choose gusta or gustan from the grammatical subject and preserve the experiencer pronoun.", durationMinutes: 26, concepts: ["gusta_gustan", "gustar_structure"],
    explain: [
      "Use gusta with one noun or an infinitive activity: Me gusta el libro; Me gusta leer. Use gustan with plural nouns: Me gustan los libros. The indirect object pronoun can change without changing this agreement logic.",
      "A list can be understood as plural when multiple separate things please someone: Me gustan el café y el té. But an infinitive phrase remains one activity even with attached details: Me gusta leer libros por la noche.",
    ],
    examples: [["Me gusta el libro.", "I like the book."], ["Me gustan los libros.", "I like the books."], ["Nos gusta leer.", "We like to read."]],
    boundary: { heading: "Count the pleasing subject, not the experiencer.", note: "Nos does not force a plural verb; los libros does.",
      left: { label: "GUSTA", question: "One thing or one activity?", description: "Use singular gusta.", example: ["Nos gusta la música.", "We like music."] },
      right: { label: "GUSTAN", question: "Multiple things?", description: "Use plural gustan.", example: ["Nos gustan las canciones.", "We like the songs."] } },
    prediction: { heading: "Agree with plural classes.", context: "The pleasing subject is las clases pequeñas.", prompt: "Which form agrees?", options: ["gustan", "gusta", "gustamos"], answer: 0, correct: "Las clases is plural, so use gustan.", incorrect: "The pleasing subject is plural; the experiencer does not determine the verb." },
    guided: { heading: "Treat an action as singular.", context: "The person likes to travel.", prompt: "Which phrase fits after le?", options: ["gusta viajar", "gustan viajar", "gusta viaja"], answer: 0, correct: "An infinitive activity takes singular gusta.", incorrect: "Use gusta + infinitive for one activity." },
    builder: { prompt: "Build: We like the small restaurants.", tokens: ["Nos", "gustan", "los restaurantes pequeños."], correctOrder: ["Nos", "gustan", "los restaurantes pequeños."], answer: "Nos gustan los restaurantes pequeños.", feedback: "Nos marks the experiencers; gustan agrees with plural restaurantes." },
    reading: { heading: "What the group enjoys.", sentences: [["A Elena le gusta la música.", "Elena likes music."], ["Le gustan las canciones tranquilas.", "She likes calm songs."], ["A nosotros nos gusta bailar.", "We like to dance."], ["También nos gustan los conciertos pequeños.", "We also like small concerts."]], question: { prompt: "Why does the final line use gustan?", options: ["Los conciertos is plural", "Nos is plural", "También requires it"], answer: 0, feedback: "The verb agrees with plural los conciertos, not with nos." } },
    recall: [
      { before: "Me ", after: " el café.", answer: "gusta", feedback: "El café is singular." },
      { before: "Le ", after: " las películas.", answer: "gustan", feedback: "Las películas is plural." },
      { before: "Nos ", after: " cocinar.", answer: "gusta", feedback: "The infinitive activity cocinar takes singular gusta." },
    ],
    production: { prompt: "Write six preference sentences contrasting singular things, plural things, and activities for several experiencers.", requirements: ["Use gusta three times", "Use gustan three times", "Let the pleasing subject control agreement"], example: "Me gusta el café. Me gustan los libros. A Ana le gusta bailar. Le gustan las clases. Nos gusta viajar. Nos gustan los museos." },
    takeaway: "Use gusta for one thing or an infinitive and gustan for multiple things, regardless of who experiences the preference.",
  }),
  createCourseLesson({
    id: "11.5", title: "Verbs Like GUSTAR", displayTitle: "The gustar structure carries reactions beyond liking.",
    dek: "Encantar, interesar, importar, molestar, faltar, and quedar organize the experiencer in the same indirect way.",
    goal: "Extend the gustar sentence model to common reactions, importance, needs, and fit.", durationMinutes: 28, concepts: ["gustar_verbs", "gusta_gustan"],
    explain: [
      "Many verbs follow the same experiencer + pleasing/affecting subject model: me encanta, me interesa, me importa, me molesta. Singular or infinitive subjects take a singular verb; plural subjects take plural forms.",
      "Faltar expresses what is lacking to someone, and quedar can express how clothing fits or what remains: Me faltan dos dólares; La camisa me queda bien. Translate the relationship, not a fixed English word order.",
    ],
    examples: [["Me encanta esta canción.", "I love this song."], ["Nos interesan las culturas.", "Cultures interest us."], ["Me faltan dos dólares.", "I am short two dollars."]],
    boundary: { heading: "The affecting subject still controls agreement.", note: "Changing the reaction verb does not change the sentence architecture.",
      left: { label: "SINGULAR", question: "One thing or activity?", description: "Use interesa, encanta, importa, molesta, falta, or queda.", example: ["Me interesa la historia.", "History interests me."] },
      right: { label: "PLURAL", question: "Multiple things?", description: "Use interesan, encantan, importan, molestan, faltan, or quedan.", example: ["Me interesan los idiomas.", "Languages interest me."] } },
    prediction: { heading: "Agree with plural languages.", context: "Several languages interest the speaker.", prompt: "Which sentence follows the model?", options: ["Me interesan los idiomas.", "Me interesa los idiomas.", "Yo intereso los idiomas."], answer: 0, correct: "Interesan agrees with plural los idiomas; me marks the experiencer.", incorrect: "Keep me and make the verb plural for los idiomas." },
    guided: { heading: "Express what is missing.", context: "The speaker needs two dollars more.", prompt: "Which structure fits?", options: ["Me faltan dos dólares.", "Yo falto dos dólares.", "Me falta dos dólares."], answer: 0, correct: "Dos dólares is plural, so faltan agrees with it.", incorrect: "Use me as experiencer and plural faltan for dos dólares." },
    builder: { prompt: "Build: The new classes matter to us.", tokens: ["Nos", "importan", "las clases nuevas."], correctOrder: ["Nos", "importan", "las clases nuevas."], answer: "Nos importan las clases nuevas.", feedback: "Nos marks us; importan agrees with plural clases." },
    reading: { heading: "Choosing a program.", sentences: [["A Marta le interesa la medicina.", "Marta is interested in medicine."], ["También le encantan los idiomas.", "She also loves languages."], ["Le importa ayudar a su comunidad.", "Helping her community matters to her."], ["Pero le faltan dos clases para terminar.", "But she is two classes short of finishing."]], question: { prompt: "What still separates Marta from finishing?", options: ["two classes", "languages", "medicine"], answer: 0, feedback: "Le faltan dos clases states what remains missing." } },
    recall: [
      { before: "Me ", after: " la historia. (interests)", answer: "interesa", feedback: "Singular la historia takes interesa." },
      { before: "Nos ", after: " los proyectos. (matter)", answer: "importan", feedback: "Plural los proyectos takes importan." },
      { before: "Le ", after: " tres dólares. (are lacking)", answer: "faltan", feedback: "Tres dólares is plural, so use faltan." },
    ],
    production: { prompt: "Write five reactions using different gustar-like verbs, with at least two plural affecting subjects.", requirements: ["Use five distinct reaction verbs", "Vary experiencer pronouns", "Control singular/plural agreement"], example: "Me encanta la clase. Nos interesan los idiomas. Le importa estudiar. Me molestan los ruidos. Les faltan dos libros." },
    takeaway: "Reuse the gustar model: an indirect object pronoun marks the experiencer, and the affecting subject controls the verb’s number.",
  }),
];
