import { createCourseLesson } from "./course-lesson-factory";

export const module09LessonDefinitions = [
  createCourseLesson({
    id: "9.1", title: "IR", displayTitle: "Ir is small, irregular, and central to movement and plans.",
    dek: "Voy, vas, va, vamos, and van connect a subject to a destination through a.",
    goal: "Conjugate ir and express movement toward places with a and al.", durationMinutes: 25, concepts: ["ir_forms"],
    explain: [
      "Ir is fully irregular in the present: voy, vas, va, vamos, van. Because the forms do not reveal the infinitive clearly, learn them as one compact set tied to the subject system.",
      "A destination normally follows a: Voy a casa; Vamos a la biblioteca. The combination a + el contracts to al: Van al mercado. There is no contraction with la, los, or las.",
    ],
    examples: [["Voy a casa.", "I am going home."], ["Vamos a la biblioteca.", "We are going to the library."], ["Ellos van al mercado.", "They are going to the market."]],
    boundary: { heading: "Location uses estar; destination uses ir + a.", note: "One places a subject; the other describes movement toward a place.",
      left: { label: "LOCATION", question: "Where is the person now?", description: "Use estar to locate an identified person.", example: ["Ana está en la biblioteca.", "Ana is in the library."] },
      right: { label: "DESTINATION", question: "Where is the person going?", description: "Use ir + a to express movement toward a place.", example: ["Ana va a la biblioteca.", "Ana is going to the library."] } },
    prediction: { heading: "Choose the nosotros form.", context: "The speaker and a friend are going downtown.", prompt: "Which form agrees with nosotros?", options: ["vamos", "van", "imos"], answer: 0, correct: "The nosotros form of ir is vamos.", incorrect: "Ir is irregular; its nosotros form is vamos." },
    guided: { heading: "Contract a + el.", context: "The destination is el centro.", prompt: "Which phrase follows voy?", options: ["al centro", "a el centro", "a la centro"], answer: 0, correct: "A + el contracts to al.", incorrect: "Before masculine singular el, combine a + el as al." },
    builder: { prompt: "Build: My friends go to the university.", tokens: ["Mis amigos", "van", "a la universidad."], correctOrder: ["Mis amigos", "van", "a la universidad."], answer: "Mis amigos van a la universidad.", feedback: "The plural subject uses van; a la stays separate." },
    reading: { heading: "Saturday movement.", sentences: [["Voy al mercado por la mañana.", "I go to the market in the morning."], ["Mi hermana va a la biblioteca.", "My sister goes to the library."], ["Después vamos a un restaurante.", "Afterward we go to a restaurant."], ["Nuestros amigos van a casa temprano.", "Our friends go home early."]], question: { prompt: "Which destination requires the contraction al?", options: ["el mercado", "la biblioteca", "un restaurante"], answer: 0, feedback: "A + el mercado becomes al mercado." } },
    recall: [
      { before: "Yo ", after: " a clase.", answer: "voy", feedback: "The yo form of ir is voy." },
      { before: "Nosotros ", after: " al centro.", answer: "vamos", feedback: "The nosotros form is vamos." },
      { before: "Ellas ", after: " a la playa.", answer: "van", feedback: "Ellas uses van." },
    ],
    production: { prompt: "Write four destination sentences for a day, using at least three forms of ir and both al and a la.", requirements: ["Use three different subjects", "Use al once", "Use a la once"], example: "Voy al café. Ana va a la clase. Vamos al centro. Ellos van a casa." },
    takeaway: "Match voy, vas, va, vamos, or van to the subject, then introduce the destination with a and contract a + el to al.",
  }),
  createCourseLesson({
    id: "9.2", title: "The Near Future", displayTitle: "A present form of ir can carry a future plan.",
    dek: "Ir + a + infinitive expresses what someone is going to do without a new tense ending.",
    goal: "Build near-future plans and questions with ir + a + infinitive.", durationMinutes: 26, concepts: ["near_future", "ir_forms"],
    explain: [
      "The near future has three parts: a conjugated form of ir, the connector a, and an infinitive. Voy a estudiar means I am going to study; vamos a comer means we are going to eat.",
      "Only ir changes for the subject. The planned action remains an infinitive because it is attached to the conjugated verb: Ana va a trabajar, not Ana va a trabaja. Time expressions can clarify the plan: mañana, esta noche, el sábado.",
    ],
    examples: [["Voy a estudiar mañana.", "I am going to study tomorrow."], ["¿Vas a venir?", "Are you going to come?"], ["Vamos a preparar la cena.", "We are going to make dinner."]],
    boundary: { heading: "Destination a and future a look alike but connect different things.", note: "After a, a place marks destination; an infinitive marks the planned action.",
      left: { label: "DESTINATION", question: "Where is the subject going?", description: "Ir + a + place expresses movement.", example: ["Voy a la biblioteca.", "I am going to the library."] },
      right: { label: "PLAN", question: "What is the subject going to do?", description: "Ir + a + infinitive expresses the near future.", example: ["Voy a estudiar.", "I am going to study."] } },
    prediction: { heading: "Keep the second verb infinitive.", context: "Ana plans to work tomorrow.", prompt: "Which sentence has all three parts?", options: ["Ana va a trabajar mañana.", "Ana va trabajar mañana.", "Ana va a trabaja mañana."], answer: 0, correct: "Va agrees with Ana, a connects, and trabajar remains infinitive.", incorrect: "Use va + a + trabajar." },
    guided: { heading: "Ask about a tú plan.", context: "You want to know whether a friend will come.", prompt: "Which question fits?", options: ["¿Vas a venir?", "¿Va a vienes?", "¿Vas venir?"], answer: 0, correct: "Vas agrees with tú; venir remains an infinitive after a.", incorrect: "Use the full frame vas a venir." },
    builder: { prompt: "Build: We are going to practice tonight.", tokens: ["Vamos", "a", "practicar", "esta noche."], correctOrder: ["Vamos", "a", "practicar", "esta noche."], answer: "Vamos a practicar esta noche.", feedback: "Vamos carries nosotros; practicar remains the planned action." },
    reading: { heading: "Tomorrow’s plan.", sentences: [["Mañana voy a trabajar temprano.", "Tomorrow I am going to work early."], ["Ana va a estudiar por la tarde.", "Ana is going to study in the afternoon."], ["Después vamos a comer juntos.", "Afterward we are going to eat together."], ["Por la noche vamos a llamar a nuestra familia.", "At night we are going to call our family."]], question: { prompt: "Which action includes both Ana and the speaker?", options: ["comer", "trabajar", "estudiar"], answer: 0, feedback: "Vamos a comer uses nosotros." } },
    recall: [
      { before: "Yo ", after: " estudiar mañana. (am going to)", answer: "voy a", feedback: "The yo near future begins voy a." },
      { before: "Ella va a ", after: " temprano. (leave)", answer: "salir", feedback: "The planned action remains the infinitive salir." },
      { before: "Nosotros ", after: " comer juntos. (are going to)", answer: "vamos a", feedback: "Nosotros uses vamos a." },
    ],
    production: { prompt: "Write a four-sentence plan for tomorrow using yo, another person, and nosotros.", requirements: ["Use ir + a + infinitive every time", "Vary the form of ir", "Include two time expressions"], example: "Voy a estudiar mañana. Ana va a trabajar. Vamos a comer a la una. Ellos van a venir por la noche." },
    takeaway: "Conjugate ir for the planner, keep a, and leave the planned action in the infinitive.",
  }),
  createCourseLesson({
    id: "9.3", title: "TENER QUE", displayTitle: "Obligation uses tener que before the required action.",
    dek: "Tener que + infinitive states what a particular person needs or has to do.",
    goal: "Express personal obligations and ask what someone has to do.", durationMinutes: 25, concepts: ["tener_que"],
    explain: [
      "Tener que + infinitive connects an obligation to a subject: Tengo que estudiar; Ana tiene que trabajar. Tener changes for the person, while the required action remains an infinitive.",
      "This is different from impersonal hay que + infinitive, which gives a general rule without naming who must act. Compare Tenemos que llegar temprano (we have to) and Hay que llegar temprano (one must/it is necessary to).",
    ],
    examples: [["Tengo que estudiar.", "I have to study."], ["Tenemos que salir temprano.", "We have to leave early."], ["Hay que practicar.", "One has to practice."]],
    boundary: { heading: "Personal obligation names the responsible subject.", note: "Tener que changes; impersonal hay que does not.",
      left: { label: "TENER QUE", question: "Who has to act?", description: "Conjugate tener for the responsible person.", example: ["Ana tiene que trabajar.", "Ana has to work."] },
      right: { label: "HAY QUE", question: "Is it a general necessity?", description: "Use unchanged hay que when no individual subject is named.", example: ["Hay que escuchar.", "One has to listen."] } },
    prediction: { heading: "Give nosotros an obligation.", context: "The speaker and friends must prepare.", prompt: "Which opening names their responsibility?", options: ["Tenemos que preparar", "Hay que preparamos", "Tienen preparar"], answer: 0, correct: "Tenemos names nosotros, que connects, and preparar remains infinitive.", incorrect: "Use tenemos que + infinitive." },
    guided: { heading: "State a general rule.", context: "Everyone should listen carefully; no individual subject is named.", prompt: "Which structure fits?", options: ["Hay que escuchar.", "Tiene que escuchas.", "Tenemos escuchar."], answer: 0, correct: "Hay que expresses impersonal necessity.", incorrect: "Without a named responsible subject, use hay que + infinitive." },
    builder: { prompt: "Build: I have to finish the project today.", tokens: ["Tengo que", "terminar", "el proyecto", "hoy."], correctOrder: ["Tengo que", "terminar", "el proyecto", "hoy."], answer: "Tengo que terminar el proyecto hoy.", feedback: "Tengo carries yo; terminar remains an infinitive after que." },
    reading: { heading: "A busy afternoon.", sentences: [["Tengo que terminar una tarea.", "I have to finish an assignment."], ["Mi compañero tiene que trabajar.", "My classmate has to work."], ["Después tenemos que comprar comida.", "Afterward we have to buy food."], ["Para el examen, hay que practicar mucho.", "For the exam, one has to practice a lot."]], question: { prompt: "Which obligation is general rather than assigned to a person?", options: ["practicing for the exam", "finishing the assignment", "working"], answer: 0, feedback: "Hay que practicar gives a general necessity." } },
    recall: [
      { before: "Yo ", after: " estudiar. (have to)", answer: "tengo que", feedback: "Yo uses tengo que." },
      { before: "Ana ", after: " salir. (has to)", answer: "tiene que", feedback: "Ana selects tiene que." },
      { before: "", after: " escuchar en clase. (One has to)", answer: "Hay que", accepted: ["hay que"], feedback: "Impersonal necessity uses hay que." },
    ],
    production: { prompt: "Write three personal obligations for different subjects and one general rule with hay que.", requirements: ["Conjugate tener for each subject", "Keep each action infinitive", "Contrast tener que with hay que"], example: "Tengo que estudiar. Ana tiene que trabajar. Tenemos que cocinar. Hay que llegar temprano." },
    takeaway: "Use tener que when a named subject carries the obligation; use hay que for general necessity.",
  }),
  createCourseLesson({
    id: "9.4", title: "High-Value Verb Patterns", displayTitle: "One conjugated verb can organize an infinitive that follows.",
    dek: "Querer, poder, necesitar, preferir, and deber create efficient messages without conjugating twice.",
    goal: "Combine high-frequency conjugated verbs with infinitives and distinguish the meanings they add.", durationMinutes: 27, concepts: ["verb_patterns"],
    explain: [
      "In a two-verb pattern with one subject, the first verb is conjugated and the second remains an infinitive: Necesito estudiar, prefiero caminar, debo salir. The first verb frames the second action as need, preference, or responsibility.",
      "Some connectors are required by the first pattern—tener que, ir a—but many high-value verbs connect directly: querer, poder, necesitar, preferir, deber + infinitive. Learn the complete frame, not just the dictionary meaning.",
    ],
    examples: [["Necesito descansar.", "I need to rest."], ["Prefiero caminar.", "I prefer to walk."], ["Debemos hablar.", "We should speak."]],
    boundary: { heading: "Some patterns connect directly; others require a connector.", note: "The first verb determines whether que or a belongs between the verbs.",
      left: { label: "DIRECT", question: "Does the frame take an infinitive directly?", description: "Querer, poder, necesitar, preferir, and deber connect without a preposition.", example: ["Quiero aprender.", "I want to learn."] },
      right: { label: "CONNECTED", question: "Does the frame include que or a?", description: "Tener que and ir a preserve their connector.", example: ["Tengo que aprender.", "I have to learn."] } },
    prediction: { heading: "Keep only one conjugated verb.", context: "The speaker needs to study.", prompt: "Which sentence uses the pattern accurately?", options: ["Necesito estudiar.", "Necesito estudio.", "Necesitar estudio."], answer: 0, correct: "Necesito carries yo; estudiar remains infinitive.", incorrect: "Conjugate the framing verb and keep the attached action infinitive." },
    guided: { heading: "Preserve a required connector.", context: "The speaker and friends are going to leave.", prompt: "Which sequence fits?", options: ["Vamos a salir.", "Vamos salir.", "Vamos que salir."], answer: 0, correct: "The near-future frame requires a between ir and the infinitive.", incorrect: "Ir uses the frame ir + a + infinitive." },
    builder: { prompt: "Build: We prefer to eat at home.", tokens: ["Preferimos", "comer", "en casa."], correctOrder: ["Preferimos", "comer", "en casa."], answer: "Preferimos comer en casa.", feedback: "Preferimos carries nosotros; comer remains an infinitive with no connector." },
    reading: { heading: "Choosing what to do.", sentences: [["Quiero salir, pero tengo que estudiar.", "I want to go out, but I have to study."], ["Mi amiga puede ayudarme.", "My friend can help me."], ["Preferimos trabajar en la biblioteca.", "We prefer to work in the library."], ["Después vamos a comer.", "Afterward we are going to eat."]], question: { prompt: "Which pattern expresses obligation?", options: ["tengo que estudiar", "puede ayudarme", "preferimos trabajar"], answer: 0, feedback: "Tener que frames estudiar as an obligation." } },
    recall: [
      { before: "Necesito ", after: " hoy. (work)", answer: "trabajar", feedback: "After necesito, the action remains infinitive." },
      { before: "Preferimos ", after: " aquí. (eat)", answer: "comer", feedback: "Preferir connects directly to an infinitive." },
      { before: "Vamos ", after: " estudiar. (going to)", answer: "a", feedback: "The near-future pattern requires a." },
    ],
    production: { prompt: "Write a connected plan using four different two-verb patterns: desire, ability, obligation, and preference or future.", requirements: ["Only the first verb is conjugated", "Use required connectors accurately", "Keep every second action infinitive"], example: "Quiero salir. Puedo ir mañana. Tengo que estudiar hoy. Prefiero trabajar temprano." },
    takeaway: "Let the first conjugated verb frame the message and keep the second action infinitive, preserving any required connector.",
  }),
  createCourseLesson({
    id: "9.5", title: "PARA + Infinitive", displayTitle: "Para + infinitive explains the purpose of an action.",
    dek: "One action answers what happened; para + infinitive answers what for.",
    goal: "Connect actions to their purpose with para + infinitive.", durationMinutes: 24, concepts: ["para_infinitive"],
    explain: [
      "Para + infinitive expresses purpose: Estudio para aprender; Trabajo para pagar la universidad. The infinitive names the intended action without creating a second conjugated clause.",
      "Do not confuse purpose para with reason porque. Para + infinitive looks forward to the goal; porque + conjugated clause explains a cause: Estudio porque tengo un examen.",
    ],
    examples: [["Estudio para aprender.", "I study in order to learn."], ["Trabajo para pagar la universidad.", "I work to pay for college."], ["Practico para hablar mejor.", "I practice to speak better."]],
    boundary: { heading: "Purpose looks toward a goal; cause looks back to a reason.", note: "The structure after the connector reveals the relationship.",
      left: { label: "PARA + INFINITIVE", question: "What is the goal?", description: "Express the intended purpose of the first action.", example: ["Leo para aprender.", "I read to learn."] },
      right: { label: "PORQUE + CLAUSE", question: "What causes or explains it?", description: "Give a reason with its own conjugated verb.", example: ["Leo porque tengo un examen.", "I read because I have an exam."] } },
    prediction: { heading: "Express a purpose.", context: "The person practices with the goal of speaking better.", prompt: "Which connector and form fit?", options: ["Practica para hablar mejor.", "Practica porque hablar mejor.", "Practica para habla mejor."], answer: 0, correct: "Para introduces the goal and hablar remains infinitive.", incorrect: "Purpose uses para + infinitive: para hablar." },
    guided: { heading: "Express a reason instead.", context: "The person studies because an exam exists tomorrow.", prompt: "Which sentence gives the cause?", options: ["Estudia porque tiene un examen.", "Estudia para tiene un examen.", "Estudia para un examen tiene."], answer: 0, correct: "Porque introduces the reason as a conjugated clause.", incorrect: "A reason with its own subject/verb uses porque + clause." },
    builder: { prompt: "Build: We travel to learn about other cultures.", tokens: ["Viajamos", "para", "conocer", "otras culturas."], correctOrder: ["Viajamos", "para", "conocer", "otras culturas."], answer: "Viajamos para conocer otras culturas.", feedback: "Para introduces the goal; conocer remains an infinitive." },
    reading: { heading: "Why the group practices.", sentences: [["Nos reunimos para practicar español.", "We meet to practice Spanish."], ["Escuchamos música para oír diferentes acentos.", "We listen to music to hear different accents."], ["Leemos para aprender palabras nuevas.", "We read to learn new words."], ["Hablamos porque queremos tener confianza.", "We speak because we want to have confidence."]], question: { prompt: "Which sentence gives a cause rather than a purpose phrase?", options: ["Hablamos porque queremos tener confianza", "Leemos para aprender", "Nos reunimos para practicar"], answer: 0, feedback: "Porque introduces a reason clause with queremos." } },
    recall: [
      { before: "Estudio ", after: " aprender.", answer: "para", feedback: "Para + infinitive expresses purpose." },
      { before: "Trabajo para ", after: " dinero. (earn)", answer: "ganar", feedback: "The action after para remains infinitive." },
      { before: "Practico ", after: " quiero mejorar. (because)", answer: "porque", feedback: "A reason clause uses porque." },
    ],
    production: { prompt: "Write three action-purpose sentences and one contrasting reason sentence.", requirements: ["Use para + infinitive three times", "Use porque + conjugated clause once", "Make each relationship logical"], example: "Estudio para aprender. Trabajo para ahorrar. Viajo para conocer. Practico porque quiero mejorar." },
    takeaway: "Use para + infinitive for an intended goal and porque + conjugated clause for an explanatory reason.",
  }),
  createCourseLesson({
    id: "9.6", title: "Time Expressions with HACER", displayTitle: "Hace connects a duration to the present or locates an event in the past.",
    dek: "Hace + time changes interpretation depending on whether the action is present or completed.",
    goal: "Express how long something has continued and how long ago a completed event occurred.", durationMinutes: 27, concepts: ["hace_time"],
    explain: [
      "Hace + duration + que + present tells how long an action has been continuing: Hace dos años que estudio español. A second common order is Estudio español desde hace dos años.",
      "Hace + duration can also mean ago with a completed past action: Llegué hace dos horas. The verb tense and word order distinguish ongoing duration from distance back to a finished event; Module 15 will supply the past forms in full.",
    ],
    examples: [["Hace dos años que estudio español.", "I have been studying Spanish for two years."], ["Vivo aquí desde hace seis meses.", "I have lived here for six months."], ["Llegué hace dos horas.", "I arrived two hours ago."]],
    boundary: { heading: "Ongoing duration and time ago use hace differently.", note: "The surrounding verb and structure determine the time relationship.",
      left: { label: "ONGOING", question: "Did it begin before and continue now?", description: "Use hace + duration + que + present, or desde hace + duration.", example: ["Hace un año que trabajo aquí.", "I have worked here for a year."] },
      right: { label: "AGO", question: "Was the event completed before now?", description: "Place hace + duration with a finished past event.", example: ["Llegué hace una hora.", "I arrived an hour ago."] } },
    prediction: { heading: "Express an ongoing activity.", context: "The speaker began studying two years ago and still studies now.", prompt: "Which structure keeps the action connected to the present?", options: ["Hace dos años que estudio.", "Estudio hace dos años atrás.", "Hace dos años estudié siempre."], answer: 0, correct: "Hace + duration + que + present expresses an activity that continues now.", incorrect: "Use hace dos años que + present for an ongoing duration." },
    guided: { heading: "Use desde hace.", context: "The speaker has lived here for six months and still lives here.", prompt: "Which phrase fits after vivo aquí?", options: ["desde hace seis meses", "hace seis meses que viví", "por seis meses atrás"], answer: 0, correct: "Desde hace + duration connects the starting distance to the present.", incorrect: "Use desde hace seis meses with the present verb vivo." },
    builder: { prompt: "Build: We have worked here for three years.", tokens: ["Hace tres años", "que", "trabajamos", "aquí."], correctOrder: ["Hace tres años", "que", "trabajamos", "aquí."], answer: "Hace tres años que trabajamos aquí.", feedback: "The present trabajamos shows that the three-year period continues now." },
    reading: { heading: "A long connection.", sentences: [["Hace cuatro años que Ana vive en Auburn.", "Ana has lived in Auburn for four years."], ["Estudia español desde hace dos años.", "She has studied Spanish for two years."], ["Trabaja en la biblioteca desde hace seis meses.", "She has worked in the library for six months."], ["Conoce a su mejor amiga desde hace tres años.", "She has known her best friend for three years."]], question: { prompt: "Which activity has continued for the shortest time?", options: ["working at the library", "studying Spanish", "living in Auburn"], answer: 0, feedback: "Six months is shorter than two or four years." } },
    recall: [
      { before: "", after: " dos años que estudio español.", answer: "Hace", accepted: ["hace"], feedback: "Hace begins the ongoing duration frame." },
      { before: "Vivo aquí ", after: " hace un año.", answer: "desde", feedback: "Desde hace + duration works with the present to show continuation." },
      { before: "Hace tres meses ", after: " trabajamos juntos.", answer: "que", feedback: "Que connects the duration frame to the present action." },
    ],
    production: { prompt: "Write four ongoing facts about study, work, residence, or relationships using both hace … que and desde hace.", requirements: ["Two hace + duration + que sentences", "Two desde hace sentences", "Use present verbs for continuing situations"], example: "Hace un año que estudio. Vivo aquí desde hace seis meses. Hace dos meses que trabajo. Conozco a Ana desde hace un año." },
    takeaway: "Use hace … que + present or desde hace for a duration that continues; a completed past verb turns hace + time into ago.",
  }),
];
