import { createCourseLesson } from "./course-lesson-factory";

export const module06LessonDefinitions = [
  createCourseLesson({
    id: "6.1", title: "Numbers You Actually Need", displayTitle: "Hear and build the numbers that organize a day.",
    dek: "Zero through thirty form a small system you can reuse for prices, ages, addresses, and time.",
    goal: "Recognize, write, and use the high-frequency numbers from zero through thirty.", durationMinutes: 24, concepts: ["numbers_basic"],
    explain: [
      "The numbers cero through quince are individual words worth learning as a sound sequence. Dieciséis through diecinueve visibly join diez + y + number, while veintiuno through veintinueve join veinte + y + number in one written word.",
      "Written accents preserve normal stress in dieciséis, veintidós, veintitrés, and veintiséis. From treinta onward, the connector y will appear as a separate word, but first make the compact 0–30 range automatic.",
    ],
    examples: [["Tengo veintidós años.", "I am twenty-two years old."], ["Cuesta dieciséis dólares.", "It costs sixteen dollars."], ["Hay treinta estudiantes.", "There are thirty students."]],
    boundary: { heading: "The twenties are one word; thirty plus units will be three.", note: "Spanish spelling reveals how the number is assembled.",
      left: { label: "20 + UNIT", question: "Below thirty?", description: "Veinti- joins directly to the unit in one word.", example: ["veinticuatro", "twenty-four"] },
      right: { label: "30", question: "At thirty?", description: "Treinta stands alone until a later unit is added with y.", example: ["treinta", "thirty"] } },
    prediction: { heading: "Recognize a compact twenty.", context: "The price is 23 dollars.", prompt: "Which spelling is standard?", options: ["veintitrés", "veinte y tres", "veinte tres"], answer: 0, correct: "Twenty-three is written as the single word veintitrés.", incorrect: "Numbers from twenty-one through twenty-nine are normally written as one word." },
    guided: { heading: "Keep the stress visible.", context: "The number is 16.", prompt: "Which spelling preserves the correct stress?", options: ["dieciséis", "dieciseis", "diez y seis"], answer: 0, correct: "Dieciséis carries a written accent on é.", incorrect: "The standard one-word spelling is dieciséis, with an accent." },
    builder: { prompt: "Build: I am twenty-five years old.", tokens: ["Tengo", "veinticinco", "años."], correctOrder: ["Tengo", "veinticinco", "años."], answer: "Tengo veinticinco años.", feedback: "Spanish states age with tener, and veinticinco is one word." },
    reading: { heading: "At the campus café.", sentences: [["Hay doce mesas.", "There are twelve tables."], ["Una ensalada cuesta nueve dólares.", "A salad costs nine dollars."], ["Un café cuesta tres dólares.", "A coffee costs three dollars."], ["Tengo veinte dólares.", "I have twenty dollars."]], question: { prompt: "How much money does the speaker have?", options: ["20 dollars", "12 dollars", "9 dollars"], answer: 0, feedback: "Tengo veinte dólares states the amount available." } },
    recall: [
      { before: "Tengo ", after: " años. (22)", answer: "veintidós", accepted: ["veintidós", "veintidos"], feedback: "Twenty-two is the single word veintidós." },
      { before: "Hay ", after: " personas. (16)", answer: "dieciséis", accepted: ["dieciséis", "dieciseis"], feedback: "Sixteen is dieciséis, with stress marked on é." },
      { before: "Cuesta ", after: " dólares. (30)", answer: "treinta", feedback: "Thirty is treinta." },
    ],
    production: { prompt: "Write three true or imagined number statements: an age, a price, and a quantity between 0 and 30.", requirements: ["Use three different numbers", "Include units or nouns", "Write accented number words accurately"], example: "Tengo veintidós años. Cuesta quince dólares. Hay ocho mesas." },
    takeaway: "Treat 0–15 as core words, see the joined patterns in 16–29, and preserve the accents that carry stress.",
  }),
  createCourseLesson({
    id: "6.2", title: "Bigger Numbers", displayTitle: "Build large numbers in meaningful groups.",
    dek: "Tens, hundreds, and thousands become manageable when each place value has a clear job.",
    goal: "Construct and understand practical numbers through the thousands.", durationMinutes: 25, concepts: ["numbers_large"],
    explain: [
      "From thirty through ninety, Spanish connects tens and units with y: treinta y cuatro, sesenta y ocho. Hundreds usually agree with a following feminine noun—doscientas personas—but mil does not change for gender.",
      "Cien means exactly one hundred; ciento begins numbers from 101 to 199: cien estudiantes, ciento cinco estudiantes. Mil is used without un for one thousand: mil dólares, not un mil dólares.",
    ],
    examples: [["treinta y cuatro", "thirty-four"], ["ciento cinco", "one hundred five"], ["dos mil veintiséis", "two thousand twenty-six"]],
    boundary: { heading: "Cien stops at 100; ciento continues.", note: "The following quantity determines the form.",
      left: { label: "EXACTLY 100", question: "Does the number end here?", description: "Use cien when nothing follows inside the number.", example: ["cien personas", "one hundred people"] },
      right: { label: "101–199", question: "Does another number follow?", description: "Use ciento before the remaining amount.", example: ["ciento veinte personas", "one hundred twenty people"] } },
    prediction: { heading: "Build 47.", context: "The number combines forty and seven.", prompt: "Which form uses the connector correctly?", options: ["cuarenta y siete", "cuarenta siete", "cuarentaysiete"], answer: 0, correct: "Tens and units above thirty connect with the separate word y.", incorrect: "Use tens + y + unit: cuarenta y siete." },
    guided: { heading: "Say 105.", context: "The number continues past one hundred.", prompt: "Which form is correct?", options: ["ciento cinco", "cien cinco", "un cien y cinco"], answer: 0, correct: "Ciento is used because another number follows.", incorrect: "Cien is only exact 100; 105 begins with ciento." },
    builder: { prompt: "Build: two thousand twenty-six", tokens: ["dos", "mil", "veintiséis"], correctOrder: ["dos", "mil", "veintiséis"], answer: "dos mil veintiséis", feedback: "Mil is a separate place-value word and veintiséis retains its accent." },
    reading: { heading: "A university profile.", sentences: [["La universidad tiene treinta y ocho edificios.", "The university has thirty-eight buildings."], ["Hay ciento veinte programas.", "There are one hundred twenty programs."], ["Estudian veintinueve mil personas.", "Twenty-nine thousand people study there."], ["La biblioteca tiene doscientas computadoras.", "The library has two hundred computers."]], question: { prompt: "How many programs are there?", options: ["120", "38", "200"], answer: 0, feedback: "Ciento veinte equals one hundred twenty." } },
    recall: [
      { before: "", after: " libros (48)", answer: "cuarenta y ocho", feedback: "Forty-eight connects the tens and unit with y." },
      { before: "", after: " estudiantes (100)", answer: "cien", feedback: "Exact one hundred uses cien." },
      { before: "", after: " personas (250)", answer: "doscientas cincuenta", feedback: "Doscientas agrees with feminine personas; cincuenta completes the number." },
    ],
    production: { prompt: "Write three useful large quantities: one between 31–99, one in the hundreds, and one in the thousands.", requirements: ["Use y only between tens and units", "Choose cien or ciento correctly", "Attach each number to a meaningful noun"], example: "Hay cuarenta y dos clases, ciento cinco profesores y tres mil estudiantes." },
    takeaway: "Assemble large numbers by place value: hundreds, thousands, tens, then y plus the final unit.",
  }),
  createCourseLesson({
    id: "6.3", title: "Dates & Calendar", displayTitle: "Dates move from the day to the larger calendar.",
    dek: "Spanish names dates with el, a cardinal number, de, the month, and optionally de plus the year.",
    goal: "Ask for and state days, dates, months, and years naturally.", durationMinutes: 25, concepts: ["dates_calendar"],
    explain: [
      "To ask the date, use ¿Qué fecha es hoy? or ¿A cuántos estamos? A complete date commonly follows el + number + de + month: el quince de marzo. The first day is often primero; other days use cardinal numbers.",
      "Days and months are normally lowercase in Spanish: lunes, agosto. To say what day it is, use Hoy es lunes. To place an event on a day, use el: La reunión es el lunes. The year follows another de: el once de agosto de dos mil veintiséis.",
    ],
    examples: [["Hoy es martes.", "Today is Tuesday."], ["Es el quince de marzo.", "It is March fifteenth."], ["La clase es el lunes.", "The class is on Monday."]],
    boundary: { heading: "Today identifies the day; an event is placed on it.", note: "El appears when the day functions as the date of an event.",
      left: { label: "TODAY", question: "What day is today?", description: "Use ser directly with the day name.", example: ["Hoy es jueves.", "Today is Thursday."] },
      right: { label: "EVENT DATE", question: "When is the event?", description: "Use el before the day or date.", example: ["El examen es el jueves.", "The exam is on Thursday."] } },
    prediction: { heading: "State a date.", context: "The date is March 15.", prompt: "Which sequence is natural?", options: ["el quince de marzo", "marzo el quince", "en quince marzo"], answer: 0, correct: "Spanish places the day before the month and connects them with de.", incorrect: "Use el + day number + de + month." },
    guided: { heading: "Name today’s day.", context: "Today is Monday; no event is being scheduled.", prompt: "Which sentence fits?", options: ["Hoy es lunes.", "Hoy está lunes.", "Hoy es el lunes de."], answer: 0, correct: "Ser identifies the day: Hoy es lunes.", incorrect: "Use ser directly with the lowercase day name." },
    builder: { prompt: "Build: The meeting is on August eleventh.", tokens: ["La reunión", "es", "el once", "de agosto."], correctOrder: ["La reunión", "es", "el once", "de agosto."], answer: "La reunión es el once de agosto.", feedback: "The event takes place on el once de agosto." },
    reading: { heading: "A week of events.", sentences: [["Hoy es miércoles.", "Today is Wednesday."], ["El examen es el viernes.", "The exam is on Friday."], ["La presentación es el doce de septiembre.", "The presentation is September twelfth."], ["Las vacaciones empiezan en diciembre.", "Vacation begins in December."]], question: { prompt: "When is the presentation?", options: ["September 12", "Friday", "December"], answer: 0, feedback: "El doce de septiembre gives the presentation date." } },
    recall: [
      { before: "Hoy ", after: " martes.", answer: "es", feedback: "Ser identifies today’s day." },
      { before: "La clase es ", after: " lunes.", answer: "el", feedback: "El places the event on Monday." },
      { before: "Es el cinco ", after: " mayo.", answer: "de", feedback: "De connects the day number to the month." },
    ],
    production: { prompt: "Write today’s day and an imagined three-event calendar with complete Spanish dates.", requirements: ["One Hoy es sentence", "At least two dates with el … de …", "Lowercase day and month names"], example: "Hoy es martes. La clase es el jueves. El viaje es el veinte de mayo." },
    takeaway: "State today with Hoy es; place an event with el; build dates as el + day + de + month.",
  }),
  createCourseLesson({
    id: "6.4", title: "Telling Time", displayTitle: "Clock time is singular at one and plural after it.",
    dek: "Es la una and son las dos organize the hour; minutes attach with y, menos, media, and cuarto.",
    goal: "Ask for, understand, and state clock times accurately.", durationMinutes: 26, concepts: ["clock_time"],
    explain: [
      "One o’clock is singular: Es la una. Every other hour is plural: Son las dos, son las nueve. To say when an event occurs, replace es/son with a: La clase es a la una; empieza a las dos.",
      "Minutes after the hour commonly use y: son las tres y diez. Media means half past and cuarto means quarter past. For the last part of the hour, menos counts down from the next hour: son las cinco menos cuarto is 4:45.",
    ],
    examples: [["Es la una.", "It is one o’clock."], ["Son las tres y media.", "It is three thirty."], ["La clase es a las nueve.", "The class is at nine."]],
    boundary: { heading: "Current time and event time use different openings.", note: "Es/son tells time; a la/a las places an event at that time.",
      left: { label: "WHAT TIME IS IT?", question: "What is the clock showing?", description: "Use es la or son las.", example: ["Son las ocho.", "It is eight o’clock."] },
      right: { label: "AT WHAT TIME?", question: "When does an event occur?", description: "Use a la or a las before the hour.", example: ["La clase es a las ocho.", "The class is at eight."] } },
    prediction: { heading: "Tell one o’clock.", context: "The clock shows exactly 1:00.", prompt: "Which sentence respects singular agreement?", options: ["Es la una.", "Son las una.", "Es las uno."], answer: 0, correct: "One o’clock uses the singular frame es la una.", incorrect: "Only one o’clock is singular: es la una." },
    guided: { heading: "Schedule an event at two.", context: "You are not telling the current time; you are stating when class begins.", prompt: "Which phrase belongs after empieza?", options: ["a las dos", "son las dos", "a la dos"], answer: 0, correct: "Events at hours other than one use a las.", incorrect: "Use a las dos to place an event at two o’clock." },
    builder: { prompt: "Build: It is four thirty.", tokens: ["Son", "las cuatro", "y media."], correctOrder: ["Son", "las cuatro", "y media."], answer: "Son las cuatro y media.", feedback: "Four is plural, and y media adds half an hour." },
    reading: { heading: "Before class.", sentences: [["—¿Qué hora es?", "What time is it?"], ["—Son las ocho y cuarto.", "It is eight fifteen."], ["—¿A qué hora es la clase?", "What time is the class?"], ["—Es a las nueve menos diez.", "It is at eight fifty."]], question: { prompt: "How much time remains before class?", options: ["35 minutes", "10 minutes", "45 minutes"], answer: 0, feedback: "8:15 to 8:50 leaves thirty-five minutes." } },
    recall: [
      { before: "", after: " la una.", answer: "Es", accepted: ["es"], feedback: "One o’clock uses singular es." },
      { before: "", after: " las seis y media.", answer: "Son", accepted: ["son"], feedback: "Hours after one use plural son las." },
      { before: "La reunión es ", after: " las tres.", answer: "a", feedback: "A las places the event at three." },
    ],
    production: { prompt: "Write the current time and schedule two events, one at 1:00 and one at another hour with minutes.", requirements: ["Use es la una correctly", "Use son las for another current time", "Use a la/a las for event time"], example: "Son las diez y cuarto. Almuerzo a la una. La reunión es a las tres y media." },
    takeaway: "Use es la una for one, son las for other hours, and a la/a las when an event occurs at that time.",
  }),
  createCourseLesson({
    id: "6.5", title: "Everyday Time", displayTitle: "Place actions within a real day.",
    dek: "Frequency, sequence, and parts of the day turn clock facts into usable routines.",
    goal: "Use common time expressions to describe when and how often actions happen.", durationMinutes: 25, concepts: ["time_expressions"],
    explain: [
      "Por la mañana, por la tarde, and por la noche describe broad parts of the day. A precise clock time uses a la or a las. Frequency words—siempre, normalmente, a veces, nunca—usually sit near the conjugated verb and show how regularly the action occurs.",
      "Sequence words organize a routine: primero, luego, después, al final. Desde … hasta … marks a span, while hace in Module 9 will later express how long ago or how long something has been happening.",
    ],
    examples: [["Estudio por la mañana.", "I study in the morning."], ["A veces trabajo por la noche.", "Sometimes I work at night."], ["La clase es de dos a cuatro.", "The class is from two to four."]],
    boundary: { heading: "Broad part of day or exact hour?", note: "Por frames a general period; a places an action at a clock time.",
      left: { label: "BROAD PERIOD", question: "Which part of the day?", description: "Use por with mañana, tarde, or noche.", example: ["Trabajo por la tarde.", "I work in the afternoon."] },
      right: { label: "EXACT TIME", question: "At what hour?", description: "Use a la or a las before the time.", example: ["Trabajo a las cuatro.", "I work at four."] } },
    prediction: { heading: "Describe a broad period.", context: "No exact hour is given; the person studies in the evening/night.", prompt: "Which phrase fits?", options: ["por la noche", "a las noche", "en noche"], answer: 0, correct: "Por la noche names a broad part of the day.", incorrect: "Use por with broad parts of the day: por la noche." },
    guided: { heading: "Express occasional frequency.", context: "The activity happens sometimes, not always.", prompt: "Which word carries that frequency?", options: ["a veces", "siempre", "nunca"], answer: 0, correct: "A veces means sometimes.", incorrect: "A veces marks occasional frequency." },
    builder: { prompt: "Build: I normally study in the morning.", tokens: ["Normalmente", "estudio", "por la mañana."], correctOrder: ["Normalmente", "estudio", "por la mañana."], answer: "Normalmente estudio por la mañana.", feedback: "Normalmente frames frequency; por la mañana gives the broad period." },
    reading: { heading: "Elena’s Tuesday.", sentences: [["Primero, Elena estudia por la mañana.", "First, Elena studies in the morning."], ["Almuerza a la una.", "She eats lunch at one."], ["Después trabaja de dos a seis.", "Afterward she works from two to six."], ["Por la noche, a veces habla con su familia.", "At night, she sometimes talks with her family."]], question: { prompt: "When does Elena work?", options: ["From two to six", "At one", "In the morning"], answer: 0, feedback: "De dos a seis marks the work time span." } },
    recall: [
      { before: "Estudio ", after: " la mañana.", answer: "por", feedback: "Por la mañana describes a broad period." },
      { before: "La clase es ", after: " las cinco.", answer: "a", feedback: "A las introduces an exact event time." },
      { before: "", after: " trabajo los sábados. (Sometimes)", answer: "A veces", accepted: ["a veces"], feedback: "A veces expresses occasional frequency." },
    ],
    production: { prompt: "Write a four-sentence weekday routine with a sequence word, a frequency word, a broad period, and an exact time.", requirements: ["Organize the sequence", "Contrast broad and exact time", "Include frequency"], example: "Primero estudio por la mañana. Siempre almuerzo a la una. Después trabajo. A veces leo por la noche." },
    takeaway: "Combine sequence, frequency, broad periods, and exact hours to turn isolated times into a coherent routine.",
  }),
];
