import { createCourseLesson } from "./course-lesson-factory";

export const module05LessonDefinitions = [
  createCourseLesson({
    id: "5.1", title: "How Spanish Questions Work", displayTitle: "A question changes the purpose, not necessarily the order.",
    dek: "Spanish can turn a statement into a yes-or-no question through intention, voice, and question marks.",
    goal: "Recognize and build yes-or-no questions without inventing an English-style helper verb.", durationMinutes: 24, concepts: ["question_structure"],
    explain: [
      "English often inserts do or does to form a question. Spanish usually keeps the conjugated verb and lets the question marks, rising intonation, and conversational purpose signal the question: Trabajas aquí. becomes ¿Trabajas aquí?",
      "The subject may follow the verb or disappear when the verb form already makes it clear: ¿Trabaja Ana aquí? and ¿Trabajas aquí? are both natural. Do not translate the English helper do; begin from the Spanish statement you already know.",
    ],
    examples: [["¿Trabajas aquí?", "Do you work here?"], ["¿Vive Marta en Bogotá?", "Does Marta live in Bogotá?"], ["¿Están listos?", "Are you all ready?"]],
    boundary: { heading: "Do not import English do into Spanish.", note: "The Spanish verb already carries person and tense.",
      left: { label: "STATEMENT", question: "What information is given?", description: "A falling statement presents the idea as information.", example: ["María estudia español.", "María studies Spanish."] },
      right: { label: "QUESTION", question: "Is the information true?", description: "Question marks and intonation ask the listener to confirm it.", example: ["¿María estudia español?", "Does María study Spanish?"] } },
    prediction: { heading: "Turn the statement into a question.", context: "Trabajas aquí is already a complete Spanish statement.", prompt: "Which version asks whether it is true?", options: ["¿Trabajas aquí?", "¿Haces trabajar aquí?", "Trabajas aquí."], answer: 0, correct: "Spanish keeps trabajas and frames it as a question.", incorrect: "Do not create a Spanish equivalent of English do. Keep trabajas and use the question frame." },
    guided: { heading: "Ask about Ana.", context: "The listener knows Ana; you want to confirm her location.", prompt: "Which is the natural question?", options: ["¿Está Ana en casa?", "¿Hace Ana está en casa?", "Ana en casa."], answer: 0, correct: "Está already carries the verb; the question needs no helper.", incorrect: "Keep the conjugated verb está and frame the complete idea as a question." },
    builder: { prompt: "Build: Does Diego live here?", tokens: ["¿Vive", "Diego", "aquí?"], correctOrder: ["¿Vive", "Diego", "aquí?"], answer: "¿Vive Diego aquí?", feedback: "The conjugated verb vive begins the question; no form of hacer is added." },
    reading: { heading: "A first meeting.", sentences: [["—¿Trabajas aquí?", "Do you work here?"], ["—Sí, trabajo en la biblioteca.", "Yes, I work in the library."], ["—¿Estudias también?", "Do you study too?"], ["—Sí, estudio historia.", "Yes, I study history."]], question: { prompt: "What does the second question ask?", options: ["Whether the person also studies", "Where the library is", "Why the person works"], answer: 0, feedback: "¿Estudias también? reuses the conjugated verb to ask for confirmation." } },
    recall: [
      { before: "¿", after: " aquí? (Do you live)", answer: "Vives", accepted: ["vives"], feedback: "Vives already contains the tú subject; the question needs no helper." },
      { before: "¿", after: " Marta español? (Does Marta study)", answer: "Estudia", accepted: ["estudia"], feedback: "Estudia agrees with Marta and becomes a question through its frame." },
      { before: "¿", after: " listos? (Are you all)", answer: "Están", accepted: ["están", "estan"], feedback: "Ustedes is understood from están." },
    ],
    production: { prompt: "Write two yes-or-no questions for a new classmate: ask about one activity and one place.", requirements: ["Two complete questions", "An opening and closing question mark", "No translated form of English do"], example: "¿Estudias español? ¿Vives cerca de la universidad?" },
    takeaway: "Build the Spanish statement first; question marks and intention can turn it into a question.",
  }),
  createCourseLesson({
    id: "5.2", title: "What, Who & Which", displayTitle: "Choose the question word from the information you need.",
    dek: "Qué, quién, and cuál do different jobs even when English translations overlap.",
    goal: "Ask for definitions, people, and selections with qué, quién, and cuál.", durationMinutes: 25, concepts: ["question_words_identity"],
    explain: [
      "Qué asks what something is or what kind of information is missing: ¿Qué estudias? Quién or quiénes asks for a person or people: ¿Quién es Ana? Cuál or cuáles asks someone to select or identify from a set: ¿Cuál prefieres?",
      "English what can hide the qué/cuál distinction. Use qué for a definition or an open category and cuál for a choice or identification among possibilities. All interrogative forms keep their written accents.",
    ],
    examples: [["¿Qué estudias?", "What do you study?"], ["¿Quién es tu profesora?", "Who is your professor?"], ["¿Cuál prefieres?", "Which one do you prefer?"]],
    boundary: { heading: "Qué opens a category; cuál selects an option.", note: "Translate the information job, not the isolated English word what.",
      left: { label: "QUÉ", question: "What is it or what kind?", description: "Ask for a definition, thing, or open category.", example: ["¿Qué es Nexo?", "What is Nexo?"] },
      right: { label: "CUÁL", question: "Which one?", description: "Ask the listener to identify or select from possibilities.", example: ["¿Cuál es tu clase?", "Which one is your class?"] } },
    prediction: { heading: "Ask for a person.", context: "You hear a name but do not know who the person is.", prompt: "Which question asks for that person’s identity?", options: ["¿Quién es Lucía?", "¿Qué es Lucía?", "¿Cuál estudia Lucía?"], answer: 0, correct: "Quién asks for the identity of a person.", incorrect: "The missing information is a person, so begin with quién." },
    guided: { heading: "Select one class.", context: "Two Spanish classes are listed and you want to know your friend’s choice.", prompt: "Which question fits the choice?", options: ["¿Cuál prefieres?", "¿Qué es una clase?", "¿Quién prefieres?"], answer: 0, correct: "Cuál asks the listener to choose from known possibilities.", incorrect: "Because the options form a set, use cuál rather than qué or quién." },
    builder: { prompt: "Build: What do you study?", tokens: ["¿Qué", "estudias?"], correctOrder: ["¿Qué", "estudias?"], answer: "¿Qué estudias?", feedback: "Qué asks for the open category of study and keeps its accent." },
    reading: { heading: "Choosing a course.", sentences: [["—¿Qué estudias?", "What do you study?"], ["—Estudio ingeniería.", "I study engineering."], ["—¿Quién es tu profesora?", "Who is your professor?"], ["—La profesora Ruiz. ¿Cuál es tu clase?", "Professor Ruiz. Which one is your class?"]], question: { prompt: "Why does the final question use cuál?", options: ["It identifies one class from available classes", "It asks for a person", "It asks for a definition"], answer: 0, feedback: "Cuál identifies the class from a relevant set of classes." } },
    recall: [
      { before: "¿", after: " es tu profesor? (Who)", answer: "Quién", accepted: ["quién", "quien"], feedback: "Quién asks for one person and normally carries a written accent in a direct question." },
      { before: "¿", after: " estudias? (What)", answer: "Qué", accepted: ["qué", "que"], feedback: "Qué asks for the open category of what you study." },
      { before: "¿", after: " prefieres, café o té? (Which)", answer: "Cuál", accepted: ["cuál", "cual"], feedback: "Cuál selects between the stated options." },
    ],
    production: { prompt: "Write three questions for a classmate: one with qué, one with quién, and one with cuál.", requirements: ["Use all three question words", "Give each question a clear information goal", "Keep question-word accents"], example: "¿Qué estudias? ¿Quién es tu profesor? ¿Cuál prefieres?" },
    takeaway: "Ask what information is missing: a thing or category, a person, or a choice.",
  }),
  createCourseLesson({
    id: "5.3", title: "Where, When & How", displayTitle: "Locate the missing circumstance.",
    dek: "Dónde, cuándo, and cómo ask for place, time, and manner.",
    goal: "Use the context question words that make plans and everyday exchanges possible.", durationMinutes: 24, concepts: ["question_words_context"],
    explain: [
      "Dónde asks for location, cuándo asks for time, and cómo asks for manner, condition, or the way something happens. Their accents distinguish interrogative words from related connecting words.",
      "Prepositions may come before the question word when the meaning requires them: ¿De dónde eres? asks origin, ¿Adónde vas? asks destination, and ¿Con quién estudias? asks companionship. Keep the preposition attached to the relationship you want to ask about.",
    ],
    examples: [["¿Dónde vives?", "Where do you live?"], ["¿Cuándo es la clase?", "When is the class?"], ["¿Cómo estás?", "How are you?"]],
    boundary: { heading: "Location and origin are related, not identical.", note: "The preposition de changes the relationship being requested.",
      left: { label: "DÓNDE", question: "Where is it?", description: "Ask for a current place or location.", example: ["¿Dónde está Ana?", "Where is Ana?"] },
      right: { label: "DE DÓNDE", question: "Where is it from?", description: "Ask for source or origin with de.", example: ["¿De dónde es Ana?", "Where is Ana from?"] } },
    prediction: { heading: "Ask for the class time.", context: "You know the course but not the day or time it meets.", prompt: "Which word asks for time?", options: ["¿Cuándo es la clase?", "¿Dónde es la clase?", "¿Cómo es la clase?"], answer: 0, correct: "Cuándo asks when the class occurs.", incorrect: "The missing circumstance is time, so use cuándo." },
    guided: { heading: "Ask about well-being.", context: "You greet a friend and want to know their condition.", prompt: "Which question is appropriate?", options: ["¿Cómo estás?", "¿Cuándo estás?", "¿Dónde estás?"], answer: 0, correct: "Cómo asks how the person is.", incorrect: "You are asking about condition, not time or place, so use cómo." },
    builder: { prompt: "Build: Where are you from?", tokens: ["¿De", "dónde", "eres?"], correctOrder: ["¿De", "dónde", "eres?"], answer: "¿De dónde eres?", feedback: "De asks for source or origin, and dónde retains its interrogative accent." },
    reading: { heading: "Making a study plan.", sentences: [["—¿Dónde estudias hoy?", "Where are you studying today?"], ["—En la biblioteca.", "In the library."], ["—¿Cuándo vas?", "When are you going?"], ["—A las cuatro. ¿Cómo llegas tú?", "At four. How are you getting there?"]], question: { prompt: "What information does cómo request?", options: ["The way the person will arrive", "The location of the library", "The time of the plan"], answer: 0, feedback: "Cómo llegas asks about the manner or means of arriving." } },
    recall: [
      { before: "¿", after: " vives? (Where)", answer: "Dónde", accepted: ["dónde", "donde"], feedback: "Dónde asks for place." },
      { before: "¿", after: " es el examen? (When)", answer: "Cuándo", accepted: ["cuándo", "cuando"], feedback: "Cuándo requests the time of the exam." },
      { before: "¿", after: " estás hoy? (How)", answer: "Cómo", accepted: ["cómo", "como"], feedback: "Cómo asks about the person’s condition." },
    ],
    production: { prompt: "Write a three-question plan that asks where, when, and how a friend will meet you.", requirements: ["One question with dónde", "One with cuándo", "One with cómo"], example: "¿Dónde nos encontramos? ¿Cuándo llegas? ¿Cómo vienes?" },
    takeaway: "Use dónde for place, cuándo for time, and cómo for manner or condition; add a preposition when the relationship requires it.",
  }),
  createCourseLesson({
    id: "5.4", title: "Why & How Much", displayTitle: "Ask for reasons and quantities precisely.",
    dek: "Por qué opens an explanation; cuánto agrees with the quantity being requested.",
    goal: "Ask why, how much, and how many while preserving accents and agreement.", durationMinutes: 25, concepts: ["question_reason_quantity"],
    explain: [
      "The direct question por qué is written as two words and carries an accent: ¿Por qué estudias español? A reason in an answer often uses porque as one unaccented word: Porque quiero viajar.",
      "Cuánto changes when it directly modifies a noun: cuánto tiempo, cuánta agua, cuántos libros, cuántas clases. If the noun is absent, context still determines whether cuánto or a plural form is natural.",
    ],
    examples: [["¿Por qué estudias español?", "Why do you study Spanish?"], ["¿Cuánto tiempo necesitas?", "How much time do you need?"], ["¿Cuántas clases tienes?", "How many classes do you have?"]],
    boundary: { heading: "Por qué asks; porque explains.", note: "Spacing and accent marks show the different jobs in writing.",
      left: { label: "POR QUÉ", question: "Why?", description: "Use the two-word accented form to request a reason.", example: ["¿Por qué vienes?", "Why are you coming?"] },
      right: { label: "PORQUE", question: "Because what?", description: "Use the one-word form to introduce the explanation.", example: ["Porque tengo tiempo.", "Because I have time."] } },
    prediction: { heading: "Ask for a reason.", context: "A friend is learning Spanish and you want their motivation.", prompt: "Which opening asks why?", options: ["¿Por qué estudias español?", "¿Porque estudias español?", "¿Cuánto estudias español?"], answer: 0, correct: "The direct question uses two words and an accent: por qué.", incorrect: "Use por qué to request a reason; porque belongs in an explanation." },
    guided: { heading: "Ask about plural books.", context: "The missing information is the number of libros.", prompt: "Which form agrees with a masculine plural noun?", options: ["¿Cuántos libros hay?", "¿Cuánto libros hay?", "¿Cuántas libros hay?"], answer: 0, correct: "Cuántos agrees with masculine plural libros.", incorrect: "The question word modifies libros, so it must be masculine plural: cuántos." },
    builder: { prompt: "Build: How many classes do you have?", tokens: ["¿Cuántas", "clases", "tienes?"], correctOrder: ["¿Cuántas", "clases", "tienes?"], answer: "¿Cuántas clases tienes?", feedback: "Cuántas agrees with the feminine plural noun clases." },
    reading: { heading: "Planning the semester.", sentences: [["—¿Cuántas clases tienes?", "How many classes do you have?"], ["—Tengo cinco.", "I have five."], ["—¿Por qué estudias español?", "Why do you study Spanish?"], ["—Porque quiero trabajar en México.", "Because I want to work in Mexico."]], question: { prompt: "Which word introduces the answer’s reason?", options: ["porque", "por qué", "cuántas"], answer: 0, feedback: "Porque is one word because it introduces, rather than requests, the reason." } },
    recall: [
      { before: "¿", after: " quieres viajar? (Why)", answer: "Por qué", accepted: ["por qué", "por que"], feedback: "The direct reason question uses por qué." },
      { before: "¿", after: " agua necesitas? (How much)", answer: "Cuánta", accepted: ["cuánta", "cuanta"], feedback: "Cuánta agrees with feminine singular agua in this question." },
      { before: "¿", after: " estudiantes hay? (How many)", answer: "Cuántos", accepted: ["cuántos", "cuantos"], feedback: "Cuántos agrees with masculine plural estudiantes." },
    ],
    production: { prompt: "Write a short question-and-answer pair: ask why someone studies Spanish, answer with porque, then ask one quantity question.", requirements: ["Use por qué in the question", "Use porque in the answer", "Make cuánto agree with its noun"], example: "¿Por qué estudias español? Porque quiero viajar. ¿Cuántos países visitas?" },
    takeaway: "Use por qué to request a reason, porque to give one, and match cuánto to the noun it measures.",
  }),
  createCourseLesson({
    id: "5.5", title: "Building Real Questions", displayTitle: "Build questions around the information gap.",
    dek: "Natural questions begin with what the listener needs to supply, then organize the rest of the sentence clearly.",
    goal: "Combine question words, prepositions, verbs, and subjects in useful connected exchanges.", durationMinutes: 27, concepts: ["question_structure", "question_words_identity", "question_words_context", "question_reason_quantity"],
    explain: [
      "A useful question is designed from the missing information. If the missing answer is a place, begin with dónde; if it is a person, begin with quién; if it is a reason, begin with por qué. Then add the conjugated verb and any subject or complement the listener needs.",
      "Spanish usually does not require an expressed subject when the verb makes it clear, but names and third-person subjects can remove ambiguity. Prepositions belong before the question word: ¿Con quién estudias? ¿A qué hora empieza? ¿De dónde son?",
    ],
    examples: [["¿Con quién estudias?", "Who do you study with?"], ["¿A qué hora empieza la clase?", "What time does the class begin?"], ["¿Cuántos estudiantes hay?", "How many students are there?"]],
    boundary: { heading: "Begin from the answer you need, not an English template.", note: "The information gap determines the question word and any preposition.",
      left: { label: "PLACE", question: "What answer would satisfy you?", description: "If en la biblioteca would answer, dónde is the missing element.", example: ["¿Dónde estudias?", "Where do you study?"] },
      right: { label: "COMPANION", question: "What relationship is missing?", description: "If con Ana would answer, preserve con before quién.", example: ["¿Con quién estudias?", "Who do you study with?"] } },
    prediction: { heading: "Design from the answer.", context: "The expected answer is Con mi hermano.", prompt: "Which question requests that exact relationship?", options: ["¿Con quién estudias?", "¿Quién estudias?", "¿Dónde estudias?"], answer: 0, correct: "Con quién preserves the companionship relationship in the answer.", incorrect: "The answer begins with con, so the question must keep con before quién." },
    guided: { heading: "Ask for a starting time.", context: "You need a clock time, not a general day.", prompt: "Which question is most precise?", options: ["¿A qué hora empieza?", "¿Cuándo persona empieza?", "¿Dónde empieza?"], answer: 0, correct: "A qué hora asks for the exact time an event begins.", incorrect: "Use a qué hora when the missing answer is a clock time." },
    builder: { prompt: "Build: Who do you speak Spanish with?", tokens: ["¿Con", "quién", "hablas", "español?"], correctOrder: ["¿Con", "quién", "hablas", "español?"], answer: "¿Con quién hablas español?", feedback: "Con appears before quién because the answer names the person you speak with." },
    reading: { heading: "Finding the conversation group.", sentences: [["—¿Dónde practica el grupo?", "Where does the group practice?"], ["—En la biblioteca.", "In the library."], ["—¿A qué hora empieza?", "What time does it start?"], ["—A las seis. ¿Con quién vienes?", "At six. Who are you coming with?"]], question: { prompt: "Which answer would fit the final question?", options: ["Con mi amiga Elena", "En la biblioteca", "A las seis"], answer: 0, feedback: "Con quién requests a companion, so Con mi amiga Elena fits." } },
    recall: [
      { before: "¿", after: " estudias? —En la biblioteca.", answer: "Dónde", accepted: ["dónde", "donde"], feedback: "The answer is a place, so the question begins with dónde." },
      { before: "¿", after: " quién practicas? —Con Mateo.", answer: "Con", accepted: ["con"], feedback: "The companion relationship requires con before quién." },
      { before: "¿A qué hora ", after: " la reunión? (begins)", answer: "empieza", feedback: "Empieza agrees with the singular event la reunión." },
    ],
    production: { prompt: "Write a four-line exchange that arranges a Spanish practice meeting. Ask about place, time, and one person or reason.", requirements: ["At least three clear questions", "A matching answer for each information gap", "At least one preposition before a question word"], example: "¿Dónde practicamos? En la biblioteca. ¿A qué hora? A las seis. ¿Con quién vienes? Con Ana." },
    takeaway: "Imagine the answer first, then choose the question word, preposition, verb, and subject that request it cleanly.",
  }),
];
