import { createCourseLesson } from "./course-lesson-factory";

export const module13LessonDefinitions = [
  createCourseLesson({
    id: "13.1", title: "Spanish Negatives", displayTitle: "Negative words occupy clear positions around the verb.",
    dek: "No, nada, nadie, nunca, tampoco, and ningún reject different parts of a message.",
    goal: "Choose common negative words by meaning and place them naturally.", durationMinutes: 26, concepts: ["negative_words"],
    explain: [
      "No negates a verb, nada means nothing/not anything, nadie means nobody/not anybody, nunca means never, and tampoco means neither/not either. Ningún, ninguna, and ningunos/ningunas negate nouns, though singular is common for countable categories: No tengo ningún libro.",
      "A negative word can appear before the verb by itself—Nadie viene; Nunca trabajo los domingos—or after a verb already preceded by no—No viene nadie; No trabajo nunca los domingos. The next lesson makes that agreement system explicit.",
    ],
    examples: [["Nadie viene.", "Nobody is coming."], ["No tengo nada.", "I do not have anything."], ["Yo tampoco trabajo hoy.", "I am not working today either."]],
    boundary: { heading: "Choose the negative from what is being rejected.", note: "Person, thing, time, addition, and noun category need different words.",
      left: { label: "NADIE", question: "Is any person involved?", description: "Use nadie for nobody/not anybody.", example: ["No conozco a nadie.", "I do not know anybody."] },
      right: { label: "NADA", question: "Is any thing involved?", description: "Use nada for nothing/not anything.", example: ["No necesito nada.", "I do not need anything."] } },
    prediction: { heading: "Reject a person.", context: "The speaker does not know anybody at the event.", prompt: "Which word completes No conozco a ___?", options: ["nadie", "nada", "nunca"], answer: 0, correct: "Nadie refers to a person; personal a remains before it.", incorrect: "The missing referent is a person, so use a nadie." },
    guided: { heading: "Agree with a negative addition.", context: "A friend says No trabajo hoy, and the speaker does not work either.", prompt: "Which response fits?", options: ["Yo tampoco.", "Yo también.", "Yo nada."], answer: 0, correct: "Tampoco agrees with a negative statement.", incorrect: "Use tampoco for neither/not either." },
    builder: { prompt: "Build: I never buy anything here.", tokens: ["No", "compro", "nunca", "nada aquí."], correctOrder: ["No", "compro", "nunca", "nada aquí."], answer: "No compro nunca nada aquí.", feedback: "No licenses the post-verb negative words nunca and nada." },
    reading: { heading: "A quiet Sunday.", sentences: [["Los domingos no trabajo nunca.", "On Sundays I never work."], ["No veo a nadie por la mañana.", "I do not see anyone in the morning."], ["No compro nada.", "I do not buy anything."], ["Mi compañera tampoco sale.", "My roommate does not go out either."]], question: { prompt: "Who else stays in?", options: ["the roommate", "nobody", "a coworker"], answer: 0, feedback: "Tampoco sale says the roommate does not go out either." } },
    recall: [
      { before: "No conozco a ", after: ". (anyone)", answer: "nadie", feedback: "Nadie refers to people." },
      { before: "No necesito ", after: ". (anything)", answer: "nada", feedback: "Nada refers to things." },
      { before: "Yo ", after: " voy. (not either)", answer: "tampoco", feedback: "Tampoco continues a negative statement." },
    ],
    production: { prompt: "Write six negative sentences using no, nadie, nada, nunca, tampoco, and ningún/ninguna.", requirements: ["Use every target negative", "Match each word to its meaning", "Include one personal a + nadie"], example: "No trabajo. Nadie viene. No veo a nadie. No compro nada. Nunca salgo. Ana tampoco. No tengo ningún libro." },
    takeaway: "Choose the negative word from what you reject, then place it before the verb or after a verb already negated by no.",
  }),
  createCourseLesson({
    id: "13.2", title: "Double Negatives", displayTitle: "Spanish negative agreement reinforces one negative meaning.",
    dek: "Two negative words in the same clause do not cancel; their position determines whether no is required.",
    goal: "Build negative agreement before and after the verb without importing English logic.", durationMinutes: 26, concepts: ["double_negation", "negative_words"],
    explain: [
      "When nadie, nada, nunca, or a similar negative appears after the verb, no normally precedes the verb: No viene nadie; No quiero nada; No voy nunca. The words reinforce one negative clause.",
      "When the negative word appears before the verb, it carries the negative force alone: Nadie viene; Nada cambia; Nunca voy. Do not add no after a pre-verb negative: Nadie no viene would not express the basic intended meaning.",
    ],
    examples: [["No viene nadie.", "Nobody is coming."], ["Nadie viene.", "Nobody is coming."], ["Nunca compro nada allí.", "I never buy anything there."]],
    boundary: { heading: "The first negative’s position controls no.", note: "Before the verb it can stand alone; after the verb it needs pre-verb no.",
      left: { label: "PRE-VERB", question: "Does a negative begin the clause?", description: "Do not add a second no before the verb.", example: ["Nadie trabaja.", "Nobody works."] },
      right: { label: "POST-VERB", question: "Does the negative follow the verb?", description: "Place no before the verb.", example: ["No trabaja nadie.", "Nobody works."] } },
    prediction: { heading: "Place nadie after the verb.", context: "The sentence means nobody lives here.", prompt: "Which structure is complete?", options: ["No vive nadie aquí.", "Vive nadie aquí.", "No nadie vive aquí."], answer: 0, correct: "Post-verb nadie requires no before vive.", incorrect: "If nadie follows the verb, begin the clause with no." },
    guided: { heading: "Begin with nunca.", context: "The negative word comes before the verb.", prompt: "Which sentence means I never work Sundays?", options: ["Nunca trabajo los domingos.", "Nunca no trabajo los domingos.", "Trabajo nunca los domingos."], answer: 0, correct: "Pre-verb nunca carries the negative force without no.", incorrect: "When nunca precedes the verb, do not add no." },
    builder: { prompt: "Build: We do not see anyone or hear anything.", tokens: ["No", "vemos a nadie", "ni oímos", "nada."], correctOrder: ["No", "vemos a nadie", "ni oímos", "nada."], answer: "No vemos a nadie ni oímos nada.", feedback: "No licenses the post-verb negative words; ni connects the second negative idea." },
    reading: { heading: "An empty office.", sentences: [["Hoy no viene nadie.", "Today nobody is coming."], ["Nadie responde los mensajes.", "Nobody answers the messages."], ["No hay nada en el calendario.", "There is nothing on the calendar."], ["Nunca trabajamos aquí los domingos.", "We never work here on Sundays."]], question: { prompt: "Why does the second line omit no?", options: ["Nadie appears before the verb", "The sentence is positive", "Responder cannot be negated"], answer: 0, feedback: "Pre-verb nadie supplies the clause’s negative force." } },
    recall: [
      { before: "", after: " viene nadie.", answer: "No", accepted: ["no"], feedback: "Post-verb nadie requires pre-verb no." },
      { before: "Nadie ", after: " hoy. (works)", answer: "trabaja", feedback: "Nadie already negates the clause; use the verb without no." },
      { before: "No quiero ", after: ". (anything)", answer: "nada", feedback: "No before quiero licenses post-verb nada." },
    ],
    production: { prompt: "Write four meaning pairs that move nadie, nada, or nunca from before the verb to after it without changing the meaning.", requirements: ["Pre-verb negative without no", "Post-verb negative with no", "Keep each pair semantically equivalent"], example: "Nadie viene / No viene nadie. Nunca trabajo / No trabajo nunca." },
    takeaway: "A negative before the verb can stand alone; a negative after the verb joins no in one reinforced negative clause.",
  }),
  createCourseLesson({
    id: "13.3", title: "Core Prepositions", displayTitle: "Prepositions encode relationships, not one-to-one English words.",
    dek: "A, de, en, con, sin, por, and para connect movement, source, location, company, means, cause, and purpose.",
    goal: "Choose core prepositions from the relationship between ideas.", durationMinutes: 28, concepts: ["core_prepositions"],
    explain: [
      "A marks destination, time, and some recipients; de marks source, origin, possession, and material; en marks location or position. Con and sin express with and without. Por and para divide several English for relationships.",
      "Use por for cause, route, exchange, means, and duration in many contexts; use para for purpose, recipient, destination, deadline, and intended use. These are relationship families, not a permanent list of translated words.",
    ],
    examples: [["Voy a la biblioteca.", "I go to the library."], ["Vengo de Cuba.", "I come from Cuba."], ["Estudio para aprender.", "I study in order to learn."]],
    boundary: { heading: "Cause and purpose separate por from para.", note: "Ask whether the phrase explains why from behind or what goal lies ahead.",
      left: { label: "POR", question: "What cause, path, or means explains it?", description: "Use por for the reason behind an action or the route through something.", example: ["Trabajo por necesidad.", "I work because of necessity."] },
      right: { label: "PARA", question: "What goal, recipient, or destination is intended?", description: "Use para for the endpoint or purpose.", example: ["Trabajo para viajar.", "I work in order to travel."] } },
    prediction: { heading: "Express destination.", context: "The speaker is going toward Mexico.", prompt: "Which preposition follows voy?", options: ["a", "de", "en"], answer: 0, correct: "Ir uses a for destination: voy a México.", incorrect: "Movement toward a destination uses a." },
    guided: { heading: "Express a goal.", context: "The person practices in order to improve.", prompt: "Which connector belongs before mejorar?", options: ["para", "por", "de"], answer: 0, correct: "Para + infinitive expresses the intended goal.", incorrect: "Use para when the following action is the purpose." },
    builder: { prompt: "Build: I travel by train from Madrid to Barcelona.", tokens: ["Viajo", "en tren", "de Madrid", "a Barcelona."], correctOrder: ["Viajo", "en tren", "de Madrid", "a Barcelona."], answer: "Viajo en tren de Madrid a Barcelona.", feedback: "En marks the means here; de and a frame source and destination." },
    reading: { heading: "A package for Ana.", sentences: [["Este paquete es para Ana.", "This package is for Ana."], ["Viene de su familia en Colombia.", "It comes from her family in Colombia."], ["Llega por correo.", "It arrives by mail."], ["Ana abre el paquete con cuidado.", "Ana opens the package carefully."]], question: { prompt: "Which preposition marks the intended recipient?", options: ["para", "de", "por"], answer: 0, feedback: "Para Ana identifies the package’s recipient." } },
    recall: [
      { before: "Voy ", after: " la universidad.", answer: "a", feedback: "A marks destination." },
      { before: "Soy ", after: " Cuba.", answer: "de", feedback: "De marks origin." },
      { before: "Estudio ", after: " aprender.", answer: "para", feedback: "Para + infinitive marks purpose." },
    ],
    production: { prompt: "Write a connected travel or delivery description using a, de, en, con, sin, por, and para.", requirements: ["Use all seven prepositions", "Make each relationship meaningful", "Include one por/para contrast"], example: "Voy de Auburn a Miami en carro con Ana. Viajo sin prisa por la costa para visitar a mi familia." },
    takeaway: "Choose a preposition from the relationship—source, destination, position, company, means, cause, or purpose—not from one English word.",
  }),
  createCourseLesson({
    id: "13.4", title: "Before, After & Instead Of", displayTitle: "A connector can point to a noun or open an infinitive action.",
    dek: "Antes de, después de, and en vez de organize sequence and alternatives without creating a new conjugated clause.",
    goal: "Use sequence and alternative connectors with nouns and infinitives.", durationMinutes: 26, concepts: ["sequence_prepositions"],
    explain: [
      "Antes de means before, después de means after, and en vez de means instead of. Before a second action with the same understood subject, use an infinitive: Antes de salir, estudio; Después de comer, trabajo.",
      "The de remains part of each connector whether a noun or infinitive follows: antes de la clase, después de estudiar. Cuando can introduce a conjugated clause when a subject/time relationship needs it: Cuando Ana llega, comemos.",
    ],
    examples: [["Antes de salir, estudio.", "Before leaving, I study."], ["Después de la clase, trabajo.", "After class, I work."], ["En vez de conducir, camino.", "Instead of driving, I walk."]],
    boundary: { heading: "Infinitive phrase or conjugated clause?", note: "Use de + infinitive for an attached action; use cuando when a full clause is needed.",
      left: { label: "DE + INFINITIVE", question: "Is the second action packaged without a new subject?", description: "Use antes/después/en vez de + infinitive.", example: ["Después de comer, estudio.", "After eating, I study."] },
      right: { label: "CUANDO + CLAUSE", question: "Does a full subject-verb idea follow?", description: "Use cuando with a conjugated verb.", example: ["Cuando Ana come, estudio.", "When Ana eats, I study."] } },
    prediction: { heading: "Keep the action infinitive.", context: "The person studies before leaving.", prompt: "Which structure is standard?", options: ["Estudia antes de salir.", "Estudia antes que sale.", "Estudia antes de sale."], answer: 0, correct: "Antes de takes the infinitive salir.", incorrect: "Keep de and use the infinitive after it." },
    guided: { heading: "Express an alternative.", context: "The person walks instead of driving.", prompt: "Which connector fits?", options: ["en vez de conducir", "después conducir", "antes que conduce"], answer: 0, correct: "En vez de + infinitive expresses the alternative.", incorrect: "Use en vez de followed by the infinitive." },
    builder: { prompt: "Build: After studying, we eat.", tokens: ["Después de", "estudiar,", "comemos."], correctOrder: ["Después de", "estudiar,", "comemos."], answer: "Después de estudiar, comemos.", feedback: "Después de introduces the packaged action estudiar." },
    reading: { heading: "A changed routine.", sentences: [["Antes de la clase, tomo café.", "Before class, I drink coffee."], ["Después de hablar con Ana, estudio.", "After speaking with Ana, I study."], ["En vez de trabajar en casa, voy a la biblioteca.", "Instead of working at home, I go to the library."], ["Cuando la biblioteca cierra, regreso a casa.", "When the library closes, I return home."]], question: { prompt: "Which line contains a full conjugated time clause?", options: ["Cuando la biblioteca cierra", "Después de hablar con Ana", "Antes de la clase"], answer: 0, feedback: "Cuando introduces the subject la biblioteca and conjugated verb cierra." } },
    recall: [
      { before: "Antes ", after: " salir, estudio.", answer: "de", feedback: "Antes de is the complete connector." },
      { before: "Después de ", after: ", trabajamos. (eat)", answer: "comer", feedback: "The action after de remains infinitive." },
      { before: "", after: " de conducir, camino. (Instead)", answer: "En vez", accepted: ["en vez"], feedback: "En vez de introduces an alternative." },
    ],
    production: { prompt: "Write a five-step routine using antes de, después de, en vez de, and one cuando clause.", requirements: ["Keep infinitives after de", "Use a noun after one connector", "Use a full clause after cuando"], example: "Antes de clase, leo. Después de estudiar, como. En vez de conducir, camino. Cuando llego, descanso." },
    takeaway: "Keep de in the connector and follow it with a noun or infinitive; use cuando when you need a full conjugated clause.",
  }),
  createCourseLesson({
    id: "13.5", title: "Connecting Thoughts", displayTitle: "Connectors turn correct sentences into a coherent point.",
    dek: "Y, pero, porque, por eso, aunque, además, and entonces make relationships between ideas explicit.",
    goal: "Connect clauses through addition, contrast, reason, result, concession, and sequence.", durationMinutes: 28, concepts: ["clause_connectors"],
    explain: [
      "Y and además add information; pero contrasts it. Porque introduces a reason, while por eso introduces a result: Estudio porque tengo un examen. Tengo un examen; por eso estudio. Entonces moves a sequence or conclusion forward.",
      "Aunque introduces a fact that does not prevent the main idea: Aunque estoy cansado, estudio. The connector does not replace the sentence logic; choose it only after you know how the second thought relates to the first.",
    ],
    examples: [["Trabajo y estudio.", "I work and study."], ["Estoy cansada, pero estudio.", "I am tired, but I study."], ["Tengo un examen; por eso practico.", "I have an exam; therefore I practice."]],
    boundary: { heading: "Reason and result point in opposite directions.", note: "Porque looks back to the cause; por eso points forward to the consequence.",
      left: { label: "PORQUE", question: "Why is the first idea true?", description: "Introduce the cause or explanation.", example: ["Estudio porque tengo un examen.", "I study because I have an exam."] },
      right: { label: "POR ESO", question: "What happens as a result?", description: "Introduce the consequence of the first idea.", example: ["Tengo un examen; por eso estudio.", "I have an exam; therefore I study."] } },
    prediction: { heading: "Add a contrasting fact.", context: "The speaker is tired but continues studying.", prompt: "Which connector marks the contrast?", options: ["pero", "y", "porque"], answer: 0, correct: "Pero connects two ideas that pull in different directions.", incorrect: "Use pero when the second fact contrasts with the first." },
    guided: { heading: "Introduce a result.", context: "It is raining; as a consequence, the group stays home.", prompt: "Which connector points to the consequence?", options: ["por eso", "porque", "aunque"], answer: 0, correct: "Por eso introduces the result of the rain.", incorrect: "Use por eso before the consequence; porque would introduce the cause." },
    builder: { prompt: "Build: Although I am tired, I have to study.", tokens: ["Aunque", "estoy cansado,", "tengo que", "estudiar."], correctOrder: ["Aunque", "estoy cansado,", "tengo que", "estudiar."], answer: "Aunque estoy cansado, tengo que estudiar.", feedback: "Aunque concedes the tiredness without letting it cancel the obligation." },
    reading: { heading: "Why Elena keeps practicing.", sentences: [["Elena trabaja y estudia.", "Elena works and studies."], ["Está ocupada, pero practica español cada día.", "She is busy, but she practices Spanish every day."], ["Quiere estudiar en México; por eso habla con sus amigos.", "She wants to study in Mexico; therefore she speaks with her friends."], ["Aunque comete errores, no deja de hablar.", "Although she makes mistakes, she does not stop speaking."]], question: { prompt: "What is the result of Elena wanting to study in Mexico?", options: ["She speaks with her friends", "She stops practicing", "She works less"], answer: 0, feedback: "Por eso points to habla con sus amigos as the result." } },
    recall: [
      { before: "Estoy cansado, ", after: " estudio.", answer: "pero", feedback: "Pero marks contrast." },
      { before: "Estudio ", after: " tengo un examen.", answer: "porque", feedback: "Porque introduces the reason." },
      { before: "Tengo un examen; ", after: " estudio.", answer: "por eso", feedback: "Por eso introduces the consequence." },
    ],
    production: { prompt: "Write one connected paragraph of six sentences explaining a goal, challenge, reason, result, and concession.", requirements: ["Use at least five different connectors", "Distinguish porque from por eso", "Make the paragraph advance one clear point"], example: "Estudio y trabajo. Estoy ocupado, pero practico. Quiero viajar; por eso aprendo español. Aunque es difícil, continúo porque me importa." },
    takeaway: "Name the relationship between ideas first—addition, contrast, cause, result, or concession—then choose the connector that makes it visible.",
  }),
];
