import { createCourseLesson } from "./course-lesson-factory";

export const module10LessonDefinitions = [
  createCourseLesson({
    id: "10.1", title: "What Is an Object?", displayTitle: "The direct object receives the action directly.",
    dek: "Finding who acts and what receives the action prepares the sentence for object pronouns.",
    goal: "Identify subjects, verbs, and direct objects in present-tense sentences.", durationMinutes: 25, concepts: ["direct_objects"],
    explain: [
      "The subject performs the action; the direct object answers what? or whom? directly after that action. In Ana compra el libro, Ana is the subject, compra is the verb, and el libro is what she buys.",
      "Not every sentence has a direct object. Ana vive en Miami has a location but no thing receiving vivir. Test the relationship through meaning, not by assuming that any noun after a verb is an object.",
    ],
    examples: [["Ana compra el libro.", "Ana buys the book."], ["Vemos la película.", "We watch the movie."], ["Marta vive en Lima.", "Marta lives in Lima."]],
    boundary: { heading: "An object receives an action; a location situates it.", note: "Ask what the verb acts on.",
      left: { label: "DIRECT OBJECT", question: "What does the subject act on?", description: "The noun completes a transitive action.", example: ["Leo el libro.", "I read the book."] },
      right: { label: "LOCATION", question: "Where does the action occur?", description: "A place phrase adds context but does not receive the action.", example: ["Leo en casa.", "I read at home."] } },
    prediction: { heading: "Find what is bought.", context: "In Elena compra una mochila, the action is compra.", prompt: "Which element receives that action?", options: ["una mochila", "Elena", "compra"], answer: 0, correct: "Una mochila answers what Elena buys.", incorrect: "Ask ¿Qué compra Elena? The answer una mochila is the direct object." },
    guided: { heading: "Decide whether an object exists.", context: "The sentence is Mis amigos viven en Bogotá.", prompt: "What role does en Bogotá have?", options: ["location, not a direct object", "direct object", "subject"], answer: 0, correct: "Bogotá locates vivir; it does not receive an action.", incorrect: "Vivir does not act on Bogotá. En Bogotá is a location phrase." },
    builder: { prompt: "Build: We prepare dinner.", tokens: ["Nosotros", "preparamos", "la cena."], correctOrder: ["Nosotros", "preparamos", "la cena."], answer: "Nosotros preparamos la cena.", feedback: "Nosotros performs preparar; la cena is what receives the action." },
    reading: { heading: "Preparing for class.", sentences: [["El profesor escribe una pregunta.", "The professor writes a question."], ["Los estudiantes leen la pregunta.", "The students read the question."], ["Ana busca una respuesta.", "Ana looks for an answer."], ["Después todos hablan en clase.", "Afterward everyone speaks in class."]], question: { prompt: "Which sentence has a location but no direct object?", options: ["Todos hablan en clase", "Ana busca una respuesta", "El profesor escribe una pregunta"], answer: 0, feedback: "En clase locates hablar; no object receives the action." } },
    recall: [
      { before: "Ana compra ", after: ". (the book; direct object)", answer: "el libro", feedback: "El libro is what Ana buys." },
      { before: "Vemos ", after: ". (the movie; direct object)", answer: "la película", accepted: ["la película", "la pelicula"], feedback: "La película receives the action of ver." },
      { before: "Leo ", after: ". (at home; location)", answer: "en casa", feedback: "En casa is a location, not a direct object." },
    ],
    production: { prompt: "Write three sentences with clear direct objects and one sentence with only a location phrase. Label the subject and object mentally.", requirements: ["Three actions with recipients", "One intransitive/location contrast", "Vary the subjects"], example: "Ana compra el pan. Yo leo el libro. Vemos la película. Marta vive en Lima." },
    takeaway: "Find the direct object by asking what or whom receives the verb’s action; do not confuse it with place or other context.",
  }),
  createCourseLesson({
    id: "10.2", title: "The Personal A", displayTitle: "A specific person can be a direct object without looking like a thing.",
    dek: "Spanish places a before specific human direct objects while their grammatical role remains direct.",
    goal: "Use the personal a with specific people and avoid it with ordinary thing objects.", durationMinutes: 26, concepts: ["personal_a", "direct_objects"],
    explain: [
      "When a direct object is a specific person—or sometimes a personalized animal—Spanish normally places a before it: Veo a Elena; Buscamos al profesor. The a does not make the person an indirect object; it marks a human direct object.",
      "Ordinary thing objects do not take personal a: Veo la película. Non-specific people after verbs such as buscar may omit it when no particular individual is meant: Buscamos un profesor de español.",
    ],
    examples: [["Veo a Elena.", "I see Elena."], ["Buscamos al profesor.", "We are looking for the professor."], ["Veo la película.", "I watch the movie."]],
    boundary: { heading: "Specific person or ordinary thing?", note: "The semantic nature and specificity of the object guide personal a.",
      left: { label: "PERSON", question: "Is a specific person receiving the action?", description: "Place personal a before the person.", example: ["Conozco a Marta.", "I know Marta."] },
      right: { label: "THING", question: "Is the object an ordinary thing?", description: "Do not add personal a.", example: ["Conozco la ciudad.", "I know the city."] } },
    prediction: { heading: "Mark a known person.", context: "The speaker visits their grandmother.", prompt: "Which sentence marks the specific human object?", options: ["Visito a mi abuela.", "Visito mi abuela.", "Visito a la ciudad."], answer: 0, correct: "Mi abuela is a specific person, so personal a appears.", incorrect: "A specific human direct object normally requires personal a." },
    guided: { heading: "Leave a thing unmarked.", context: "The speaker sees a movie.", prompt: "Which sentence is standard?", options: ["Veo la película.", "Veo a la película.", "A veo la película."], answer: 0, correct: "A movie is a thing, so no personal a appears.", incorrect: "Personal a does not mark ordinary thing objects." },
    builder: { prompt: "Build: We are looking for the doctor.", tokens: ["Buscamos", "al", "médico."], correctOrder: ["Buscamos", "al", "médico."], answer: "Buscamos al médico.", feedback: "A + el contracts to al before the specific person el médico." },
    reading: { heading: "At the airport.", sentences: [["Busco a mi hermano.", "I am looking for my brother."], ["Mi hermano busca su maleta.", "My brother is looking for his suitcase."], ["Vemos al conductor cerca de la puerta.", "We see the driver near the door."], ["El conductor lleva las maletas.", "The driver carries the suitcases."]], question: { prompt: "Which direct object is a thing and therefore has no personal a?", options: ["su maleta", "mi hermano", "el conductor"], answer: 0, feedback: "Su maleta is a thing; the specific people use a or al." } },
    recall: [
      { before: "Veo ", after: " Ana.", answer: "a", feedback: "Ana is a specific human direct object." },
      { before: "Buscamos ", after: " profesor.", answer: "al", feedback: "A + el profesor contracts to al." },
      { before: "Leo ", after: " libro.", answer: "el", feedback: "El libro is a thing object and takes no personal a." },
    ],
    production: { prompt: "Write four object sentences: two with specific people and two with things.", requirements: ["Use personal a for both people", "Use al once", "Omit personal a with things"], example: "Veo a Elena. Busco al profesor. Leo el libro. Compro la comida." },
    takeaway: "Use personal a before a specific human direct object, but remember that the person still receives the action directly.",
  }),
  createCourseLesson({
    id: "10.3", title: "Direct Object Pronouns", displayTitle: "A direct object pronoun replaces information already identified.",
    dek: "Lo, la, los, and las preserve the object’s gender and number while removing repetition.",
    goal: "Replace known direct objects with matching pronouns.", durationMinutes: 27, concepts: ["direct_object_pronouns", "direct_objects"],
    explain: [
      "Once a direct object is identified, lo, la, los, or las can replace it: Compro el libro → Lo compro. The pronoun agrees with the grammatical gender and number of the replaced noun, not with the subject.",
      "Lo can also replace a masculine person and la a feminine person: Veo a Carlos → Lo veo; Veo a Ana → La veo. The personal a disappears because the full noun phrase has been replaced by the pronoun.",
    ],
    examples: [["Compro el libro. Lo compro.", "I buy the book. I buy it."], ["Veo a Ana. La veo.", "I see Ana. I see her."], ["Preparamos las cenas. Las preparamos.", "We prepare the dinners. We prepare them."]],
    boundary: { heading: "The pronoun follows the object, not the subject.", note: "Ask what noun is being replaced.",
      left: { label: "MASCULINE", question: "Is the known object masculine?", description: "Use lo or los according to number.", example: ["Los libros: los leo.", "The books: I read them."] },
      right: { label: "FEMININE", question: "Is the known object feminine?", description: "Use la or las according to number.", example: ["La carta: la leo.", "The letter: I read it."] } },
    prediction: { heading: "Replace a feminine singular object.", context: "The known object is la mochila.", prompt: "Which pronoun replaces it in ___ compro?", options: ["La", "Lo", "Las"], answer: 0, correct: "La matches feminine singular la mochila.", incorrect: "Match the replaced object’s gender and number: la mochila → la." },
    guided: { heading: "Replace plural people.", context: "The speaker sees a group of male or mixed friends: Veo a mis amigos.", prompt: "Which replacement is correct?", options: ["Los veo.", "Les veo.", "Lo veo."], answer: 0, correct: "Mis amigos is masculine/mixed plural direct object, so use los.", incorrect: "For the direct object in this course’s general Latin American model, use los." },
    builder: { prompt: "Build: I read them. (the letters)", tokens: ["Las", "leo."], correctOrder: ["Las", "leo."], answer: "Las leo.", feedback: "Las replaces feminine plural las cartas and precedes leo." },
    reading: { heading: "Packing for class.", sentences: [["Necesito los libros. Los pongo en la mochila.", "I need the books. I put them in the backpack."], ["Busco la computadora y la encuentro.", "I look for the computer and find it."], ["Veo a mis amigas y las saludo.", "I see my friends and greet them."], ["Después preparo el café. Lo llevo conmigo.", "Afterward I prepare the coffee. I take it with me."]], question: { prompt: "What does la replace in the second line?", options: ["la computadora", "la mochila", "mis amigas"], answer: 0, feedback: "The feminine singular pronoun la replaces la computadora." } },
    recall: [
      { before: "El libro: ", after: " leo.", answer: "lo", feedback: "El libro is masculine singular, so use lo." },
      { before: "La carta: ", after: " escribo.", answer: "la", feedback: "La carta is feminine singular, so use la." },
      { before: "Los mensajes: ", after: " recibimos.", answer: "los", feedback: "Los mensajes is masculine plural, so use los." },
    ],
    production: { prompt: "Write four two-sentence pairs: name an object, then replace it with lo, la, los, or las.", requirements: ["Use all four pronouns", "Make each pronoun match its object", "Include one human direct object"], example: "Compro el libro. Lo leo. Veo a Ana. La saludo. Busco los cafés. Los encuentro. Preparo las cenas. Las sirvo." },
    takeaway: "Replace an identified direct object with lo, la, los, or las according to that object’s gender and number.",
  }),
  createCourseLesson({
    id: "10.4", title: "Where Pronouns Go", displayTitle: "Object pronouns stand before a conjugated verb or attach to an infinitive.",
    dek: "With one verb the position is fixed; with a conjugated verb plus infinitive, Spanish offers two equivalent placements.",
    goal: "Place direct object pronouns correctly in single- and two-verb patterns.", durationMinutes: 27, concepts: ["object_pronoun_position", "direct_object_pronouns"],
    explain: [
      "Before a single conjugated verb, the direct object pronoun comes first: Lo compro; No la veo. The negative no stands before the pronoun: No lo necesito.",
      "With a conjugated verb plus infinitive, either place the pronoun before the conjugated verb or attach it to the infinitive: Lo quiero comprar = Quiero comprarlo. Do not place the pronoun loose between the two verbs.",
    ],
    examples: [["Lo necesito.", "I need it."], ["La voy a comprar.", "I am going to buy it."], ["Voy a comprarla.", "I am going to buy it."]],
    boundary: { heading: "Two legal positions, one pronoun.", note: "In a two-verb unit, keep the pronoun at an outer edge.",
      left: { label: "BEFORE", question: "Before the conjugated verb?", description: "Place the pronoun before the full verb unit.", example: ["Lo quiero leer.", "I want to read it."] },
      right: { label: "ATTACHED", question: "Attached to the infinitive?", description: "Join the pronoun directly to the infinitive.", example: ["Quiero leerlo.", "I want to read it."] } },
    prediction: { heading: "Place a pronoun with one verb.", context: "The known object is la carta and the action is escribo.", prompt: "Which order is standard?", options: ["La escribo.", "Escribo la.", "Es la escribo."], answer: 0, correct: "With one conjugated verb, la appears before escribo.", incorrect: "Place the object pronoun before the single conjugated verb." },
    guided: { heading: "Use a two-verb position.", context: "The known object is el libro; the speaker wants to read it.", prompt: "Which sentence is well formed?", options: ["Quiero leerlo.", "Quiero lo leer.", "Quierolo leer."], answer: 0, correct: "Lo attaches to the infinitive leer.", incorrect: "Attach lo to leer or move it before quiero; do not leave it between the verbs." },
    builder: { prompt: "Build: We are going to prepare them. (the dinners)", tokens: ["Vamos a", "prepararlas."], correctOrder: ["Vamos a", "prepararlas."], answer: "Vamos a prepararlas.", feedback: "Las attaches to the infinitive preparar." },
    reading: { heading: "Finding a book.", sentences: [["Necesito el libro, pero no lo encuentro.", "I need the book, but I cannot find it."], ["Ana lo va a buscar.", "Ana is going to look for it."], ["También puede comprarlo en línea.", "She can also buy it online."], ["Al final lo encuentra en la biblioteca.", "In the end she finds it in the library."]], question: { prompt: "Which line attaches lo to an infinitive?", options: ["puede comprarlo", "lo va a buscar", "no lo encuentro"], answer: 0, feedback: "Comprar remains infinitive and carries the attached pronoun lo." } },
    recall: [
      { before: "El café: ", after: " necesito.", answer: "lo", feedback: "With one conjugated verb, lo precedes necesito." },
      { before: "La tarea: Quiero terminar", after: ".", answer: "la", feedback: "Attached to terminar, la produces terminarla." },
      { before: "Los libros: No ", after: " voy a comprar.", answer: "los", feedback: "No precedes the pronoun; los precedes voy." },
    ],
    production: { prompt: "Write four pronoun sentences: one single verb, one negative, and the two equivalent positions with an infinitive.", requirements: ["Pronoun before a conjugated verb", "No before the pronoun", "Show both two-verb positions"], example: "Lo compro. No lo necesito. Lo quiero leer. Quiero leerlo." },
    takeaway: "Place the pronoun before a conjugated verb; with an infinitive, either keep it before the verb unit or attach it to the infinitive.",
  }),
];
