import { createCourseLesson } from "./course-lesson-factory";

export const module07LessonDefinitions = [
  createCourseLesson({
    id: "7.1", title: "What an Infinitive Is", displayTitle: "The infinitive names an action before anyone performs it.",
    dek: "Hablar, comer, and vivir are dictionary forms; their endings tell you which present-tense pattern to use.",
    goal: "Recognize AR, ER, and IR infinitives and separate the verb stem from its ending.", durationMinutes: 24, concepts: ["infinitive_structure"],
    explain: [
      "An infinitive is the unconjugated name of an action: hablar, comer, vivir. It does not yet say who performs the action or when. Its final two letters place it in the -ar, -er, or -ir family.",
      "To prepare a regular present form, remove the infinitive ending and keep the stem: habl-ar, com-er, viv-ir. The next lessons attach endings that encode the subject. Do not remove only the final r; the full -ar, -er, or -ir ending is replaced.",
    ],
    examples: [["hablar → habl-", "to speak → stem"], ["comer → com-", "to eat → stem"], ["vivir → viv-", "to live → stem"]],
    boundary: { heading: "An infinitive names; a conjugated verb makes a claim.", note: "The ending tells you whether a subject has been encoded.",
      left: { label: "INFINITIVE", question: "What action?", description: "The dictionary form names the action without a subject.", example: ["estudiar", "to study"] },
      right: { label: "CONJUGATED", question: "Who does it?", description: "A present form links the action to a subject.", example: ["estudio", "I study"] } },
    prediction: { heading: "Find the verb family.", context: "The infinitive is aprender.", prompt: "Which part is the regular stem?", options: ["aprend-", "aprende-", "aprende-r"], answer: 0, correct: "Remove the full -er ending to reveal aprend-.", incorrect: "The infinitive ending is -er, so the stem is aprend-." },
    guided: { heading: "Recognize an IR verb.", context: "Only one option remains an unconjugated -ir infinitive.", prompt: "Which word names the action to open?", options: ["abrir", "abro", "abre"], answer: 0, correct: "Abrir is the infinitive; abro and abre already encode subjects.", incorrect: "Look for the complete -ir ending: abrir." },
    builder: { prompt: "Build the analysis: escribir = stem escrib- + ending -ir", tokens: ["escrib-", "+", "-ir"], correctOrder: ["escrib-", "+", "-ir"], answer: "escrib- + -ir", feedback: "Removing the full -ir ending leaves the stem escrib-." },
    reading: { heading: "Three goals.", sentences: [["Quiero hablar español.", "I want to speak Spanish."], ["Necesito comer ahora.", "I need to eat now."], ["Prefiero vivir cerca.", "I prefer to live nearby."], ["Hablar, comer y vivir son infinitivos.", "Hablar, comer, and vivir are infinitives."]], question: { prompt: "Why do hablar, comer, and vivir remain infinitives after the first verb?", options: ["They name the attached action without a new subject", "They describe past events", "They are nouns"], answer: 0, feedback: "After a conjugated verb such as quiero, the second action often remains an infinitive." } },
    recall: [
      { before: "hablar → ", after: " (stem)", answer: "habl", accepted: ["habl", "habl-"], feedback: "Remove -ar to get habl-." },
      { before: "comer → ", after: " (family)", answer: "-er", accepted: ["er", "-er"], feedback: "Comer belongs to the -er family." },
      { before: "vivir → ", after: " (stem)", answer: "viv", accepted: ["viv", "viv-"], feedback: "Remove -ir to get viv-." },
    ],
    production: { prompt: "Write six infinitives you expect to use often, two from each verb family, and separate each stem from its ending.", requirements: ["Two -ar infinitives", "Two -er infinitives", "Two -ir infinitives"], example: "habl-ar, estudi-ar; com-er, aprend-er; viv-ir, escrib-ir" },
    takeaway: "The infinitive names the action; remove its full family ending to prepare the stem for conjugation.",
  }),
  createCourseLesson({
    id: "7.2", title: "AR Verbs", displayTitle: "One AR pattern creates six useful present forms.",
    dek: "Replace -ar with endings that identify who performs the present action.",
    goal: "Conjugate regular -ar verbs for yo, tú, usted/él/ella, nosotros, and ustedes/ellos/ellas.", durationMinutes: 27, concepts: ["present_ar"],
    explain: [
      "Regular -ar verbs use -o, -as, -a, -amos, and -an for the subject system emphasized in this course: hablo, hablas, habla, hablamos, hablan. The same ending serves usted/él/ella, and -an serves ustedes/ellos/ellas.",
      "Spanish often omits the subject pronoun because the ending carries it. Trabajo can mean I work without yo; hablamos already means we speak. Include a pronoun when contrast or clarity makes it useful.",
    ],
    examples: [["Yo hablo español.", "I speak Spanish."], ["Ana trabaja aquí.", "Ana works here."], ["Estudiamos juntos.", "We study together."]],
    boundary: { heading: "The verb ending carries the subject.", note: "Do not keep the infinitive ending beside a present ending.",
      left: { label: "INFINITIVE", question: "Is the action unnamed by subject?", description: "Hablar still means to speak.", example: ["Quiero hablar.", "I want to speak."] },
      right: { label: "PRESENT", question: "Who speaks now?", description: "Replace -ar with the subject ending.", example: ["Hablo español.", "I speak Spanish."] } },
    prediction: { heading: "Conjugate for nosotros.", context: "The verb is estudiar and the subject is we.", prompt: "Which form replaces -ar with -amos?", options: ["estudiamos", "estudian", "estudiaramos"], answer: 0, correct: "Nosotros uses estudiamos.", incorrect: "Remove -ar and add -amos: estudiamos." },
    guided: { heading: "Match a third-person subject.", context: "La profesora is one ella subject.", prompt: "Which form agrees?", options: ["explica", "explicas", "explican"], answer: 0, correct: "One third-person subject selects the -a form.", incorrect: "La profesora is singular third person, so use explica." },
    builder: { prompt: "Build: We practice Spanish every day.", tokens: ["Practicamos", "español", "todos los días."], correctOrder: ["Practicamos", "español", "todos los días."], answer: "Practicamos español todos los días.", feedback: "Practicamos includes the nosotros subject in its -amos ending." },
    reading: { heading: "A language class.", sentences: [["Yo estudio español.", "I study Spanish."], ["La profesora explica la gramática.", "The professor explains the grammar."], ["Mis amigos practican conmigo.", "My friends practice with me."], ["Todos hablamos en clase.", "We all speak in class."]], question: { prompt: "Which form has nosotros built into it?", options: ["hablamos", "explica", "practican"], answer: 0, feedback: "The -amos ending in hablamos identifies nosotros." } },
    recall: [
      { before: "Yo ", after: " español. (hablar)", answer: "hablo", feedback: "Yo replaces -ar with -o." },
      { before: "Tú ", after: " mucho. (estudiar)", answer: "estudias", feedback: "Tú replaces -ar with -as." },
      { before: "Ellos ", after: " aquí. (trabajar)", answer: "trabajan", feedback: "Ellos uses the plural -an ending." },
    ],
    production: { prompt: "Describe a study group with four regular -ar verbs and at least three different subjects.", requirements: ["Use yo, nosotros, and a third-person subject", "Conjugate every -ar verb", "Write connected present actions"], example: "Yo estudio español. Ana practica conmigo. Hablamos y trabajamos juntos." },
    takeaway: "Remove -ar and let -o, -as, -a, -amos, or -an identify the present-tense subject.",
  }),
  createCourseLesson({
    id: "7.3", title: "ER Verbs", displayTitle: "ER verbs share a pattern with one important nosotros vowel.",
    dek: "Como, comes, come, comemos, and comen extend the same subject logic to -er verbs.",
    goal: "Conjugate regular -er verbs and distinguish their endings from the -ar pattern.", durationMinutes: 26, concepts: ["present_er"],
    explain: [
      "Regular -er verbs use -o, -es, -e, -emos, and -en: aprendo, aprendes, aprende, aprendemos, aprenden. The subject system is familiar; the family vowel changes from a to e.",
      "Yo still ends in -o, but tú uses -es rather than -as, one third-person subject uses -e rather than -a, and nosotros uses -emos. Keep the stem stable in regular verbs.",
    ],
    examples: [["Aprendo español.", "I learn Spanish."], ["Comes temprano.", "You eat early."], ["Leemos mucho.", "We read a lot."]],
    boundary: { heading: "The family vowel separates AR and ER endings.", note: "The subject is the same; the infinitive family selects a or e.",
      left: { label: "AR", question: "Does the infinitive end in -ar?", description: "Tú and one third person use -as and -a.", example: ["Tú hablas.", "You speak."] },
      right: { label: "ER", question: "Does the infinitive end in -er?", description: "Tú and one third person use -es and -e.", example: ["Tú comes.", "You eat."] } },
    prediction: { heading: "Conjugate aprender for nosotros.", context: "Aprender is a regular -er verb.", prompt: "Which form uses the -emos ending?", options: ["aprendemos", "aprendamos", "aprenden"], answer: 0, correct: "Nosotros -er verbs use -emos.", incorrect: "Remove -er and add -emos: aprendemos." },
    guided: { heading: "Match tú with comer.", context: "The subject is one familiar listener.", prompt: "Which form is correct?", options: ["comes", "comas", "come"], answer: 0, correct: "Tú uses the regular -er ending -es.", incorrect: "For present indicative tú, remove -er and add -es." },
    builder: { prompt: "Build: We read in the library.", tokens: ["Leemos", "en", "la biblioteca."], correctOrder: ["Leemos", "en", "la biblioteca."], answer: "Leemos en la biblioteca.", feedback: "Leemos uses the nosotros -emos ending." },
    reading: { heading: "Lunch and study.", sentences: [["Mis amigos comen a la una.", "My friends eat at one."], ["Yo como con ellos.", "I eat with them."], ["Después leemos en la biblioteca.", "Afterward we read in the library."], ["Todos aprendemos juntos.", "We all learn together."]], question: { prompt: "Who is included in aprendemos?", options: ["The speaker and others", "Only the speaker", "One friend"], answer: 0, feedback: "The -emos ending identifies nosotros: the speaker plus others." } },
    recall: [
      { before: "Yo ", after: " a las doce. (comer)", answer: "como", feedback: "Yo replaces -er with -o." },
      { before: "Ella ", after: " español. (aprender)", answer: "aprende", feedback: "One third-person subject uses -e." },
      { before: "Ustedes ", after: " mucho. (leer)", answer: "leen", feedback: "Ustedes uses the plural -en ending." },
    ],
    production: { prompt: "Write four connected sentences about eating, reading, learning, or understanding using regular -er verbs.", requirements: ["At least three subject forms", "One nosotros form in -emos", "No -ar endings on -er stems"], example: "Yo aprendo español. Mi amiga lee mucho. Comemos juntos y comprendemos la lección." },
    takeaway: "Regular ER verbs keep the stem and use -o, -es, -e, -emos, or -en.",
  }),
  createCourseLesson({
    id: "7.4", title: "IR Verbs", displayTitle: "IR verbs mostly follow ER verbs, except nosotros.",
    dek: "Vivo, vives, vive, vivimos, and viven make the small ER/IR difference easy to control.",
    goal: "Conjugate regular -ir verbs and distinguish the nosotros ending -imos.", durationMinutes: 25, concepts: ["present_ir"],
    explain: [
      "Regular -ir verbs use -o, -es, -e, -imos, and -en. Four endings match the -er pattern; nosotros is the visible difference: comemos but vivimos.",
      "This similarity reduces memorization, but the infinitive still matters. First identify whether the verb ends in -er or -ir, then choose -emos or -imos for nosotros. Examples include vivir, escribir, abrir, and recibir.",
    ],
    examples: [["Vivo cerca.", "I live nearby."], ["Escribes mensajes.", "You write messages."], ["Abrimos a las ocho.", "We open at eight."]],
    boundary: { heading: "ER and IR separate clearly in nosotros.", note: "The infinitive family selects the middle vowel.",
      left: { label: "ER NOSOTROS", question: "Which family?", description: "Regular -er verbs use -emos.", example: ["comemos", "we eat"] },
      right: { label: "IR NOSOTROS", question: "Which family?", description: "Regular -ir verbs use -imos.", example: ["vivimos", "we live"] } },
    prediction: { heading: "Conjugate vivir for nosotros.", context: "The infinitive belongs to the -ir family.", prompt: "Which form preserves that family vowel?", options: ["vivimos", "vivemos", "viven"], answer: 0, correct: "Nosotros -ir verbs use -imos.", incorrect: "Remove -ir and add -imos: vivimos." },
    guided: { heading: "Match ustedes with escribir.", context: "The subject is plural and uses the same third-person plural form as ellos/ellas.", prompt: "Which form fits?", options: ["escriben", "escribimos", "escribe"], answer: 0, correct: "Ustedes selects escriben.", incorrect: "The plural ustedes/ellos/ellas ending is -en." },
    builder: { prompt: "Build: We live near the university.", tokens: ["Vivimos", "cerca de", "la universidad."], correctOrder: ["Vivimos", "cerca de", "la universidad."], answer: "Vivimos cerca de la universidad.", feedback: "Vivimos identifies nosotros with the -imos ending." },
    reading: { heading: "A shared apartment.", sentences: [["Vivo con dos amigos.", "I live with two friends."], ["Ellos escriben para el periódico.", "They write for the newspaper."], ["Recibimos mensajes todos los días.", "We receive messages every day."], ["Por la mañana abrimos las ventanas.", "In the morning we open the windows."]], question: { prompt: "Which two actions include the speaker and the friends?", options: ["recibimos and abrimos", "vivo and escriben", "vivo and recibimos"], answer: 0, feedback: "Both -imos forms encode nosotros." } },
    recall: [
      { before: "Yo ", after: " aquí. (vivir)", answer: "vivo", feedback: "Yo replaces -ir with -o." },
      { before: "Nosotros ", after: " correos. (escribir)", answer: "escribimos", feedback: "Nosotros -ir verbs use -imos." },
      { before: "Ellas ", after: " la puerta. (abrir)", answer: "abren", feedback: "Ellas uses the plural -en ending." },
    ],
    production: { prompt: "Describe where people live and what they write, open, or receive in four regular -ir sentences.", requirements: ["Use at least three subjects", "Include one -imos form", "Keep the regular stem stable"], example: "Vivo en Auburn. Mis amigos viven cerca. Escribimos mensajes y recibimos respuestas." },
    takeaway: "IR verbs match ER endings except for nosotros: -ir becomes -imos.",
  }),
  createCourseLesson({
    id: "7.5", title: "Negating Actions", displayTitle: "One no before the conjugated verb negates the action.",
    dek: "Spanish negation is structurally direct: keep the subject relationship and place no before the verb.",
    goal: "Negate present-tense actions and answer yes-or-no questions naturally.", durationMinutes: 24, concepts: ["present_negation"],
    explain: [
      "To make a basic present sentence negative, place no immediately before the conjugated verb: Trabajo becomes No trabajo. If a subject is expressed, no still sits beside the verb: Ana no trabaja hoy.",
      "A short negative answer often uses two instances of no with different jobs: No, no vivo aquí. The first responds to the question; the second negates the sentence. Do not move no to the end as English sometimes moves not.",
    ],
    examples: [["No trabajo hoy.", "I am not working today."], ["Ana no vive aquí.", "Ana does not live here."], ["No, no comemos carne.", "No, we do not eat meat."]],
    boundary: { heading: "Response no and sentence no are separate.", note: "A comma separates the answer from the negative statement.",
      left: { label: "ANSWER", question: "Is the response yes or no?", description: "The first no answers the question and takes a comma.", example: ["No,", "No,"] },
      right: { label: "NEGATION", question: "Does the action happen?", description: "The second no sits immediately before the conjugated verb.", example: ["no estudio hoy.", "I am not studying today."] } },
    prediction: { heading: "Negate the action.", context: "The positive sentence is Marta trabaja aquí.", prompt: "Which version says she does not work here?", options: ["Marta no trabaja aquí.", "Marta trabaja no aquí.", "No Marta trabaja aquí."], answer: 0, correct: "No belongs immediately before trabaja.", incorrect: "Keep the subject and place no directly before the conjugated verb." },
    guided: { heading: "Answer a yes-or-no question.", context: "Someone asks ¿Vives aquí? and the truthful answer is negative.", prompt: "Which full response is natural?", options: ["No, no vivo aquí.", "No vivo, no aquí.", "No, vivo no aquí."], answer: 0, correct: "The first no answers; the second negates vivo.", incorrect: "Use No, then build the negative sentence no vivo aquí." },
    builder: { prompt: "Build: We do not eat here.", tokens: ["No", "comemos", "aquí."], correctOrder: ["No", "comemos", "aquí."], answer: "No comemos aquí.", feedback: "No stands directly before the conjugated verb comemos." },
    reading: { heading: "Changing plans.", sentences: [["—¿Trabajas hoy?", "Are you working today?"], ["—No, no trabajo.", "No, I am not working."], ["—¿Estudias en la biblioteca?", "Are you studying in the library?"], ["—No estudio allí; estudio en casa.", "I do not study there; I study at home."]], question: { prompt: "Where does the speaker study?", options: ["At home", "At the library", "At work"], answer: 0, feedback: "No estudio allí rejects the library; estudio en casa gives the actual place." } },
    recall: [
      { before: "Ana ", after: " vive aquí. (does not)", answer: "no", feedback: "No belongs before the conjugated verb vive." },
      { before: "", after: " hablamos inglés en clase. (We do not)", answer: "No", accepted: ["no"], feedback: "Beginning with no negates hablamos." },
      { before: "No, ", after: " como carne. (I do not)", answer: "no", feedback: "The second no negates como after the response no." },
    ],
    production: { prompt: "Write three pairs of contrasting present actions: say what a person does not do, then what they do instead.", requirements: ["Place no before each negated verb", "Conjugate for at least two subjects", "Give a positive alternative"], example: "No estudio por la noche; estudio por la mañana. Ana no vive aquí; vive en Opelika." },
    takeaway: "Keep no beside the conjugated verb; in No, no…, the first no answers and the second negates.",
  }),
  createCourseLesson({
    id: "7.6", title: "Building Present-Tense Sentences", displayTitle: "A complete present sentence coordinates subject, action, and context.",
    dek: "AR, ER, and IR patterns now work together inside connected messages rather than isolated charts.",
    goal: "Build affirmative and negative present-tense sentences across all three regular families.", durationMinutes: 28, concepts: ["present_ar", "present_er", "present_ir", "present_negation", "present_sentence"],
    explain: [
      "Begin with the intended subject, identify the infinitive family, remove its ending, and attach the present ending. Then add the information the action needs—an object, place, time, or companion. The verb ending may make the subject pronoun unnecessary.",
      "Connected Spanish varies subjects and verb families: Yo trabajo, mi amiga aprende, y juntos escribimos. Negation changes the claim without changing the conjugation process: no trabajamos. Read the full sentence at the end to check both agreement and meaning.",
    ],
    examples: [["Trabajo en la biblioteca.", "I work in the library."], ["Mi amiga aprende español.", "My friend learns Spanish."], ["Juntos escribimos mensajes.", "Together we write messages."]],
    boundary: { heading: "Conjugation and sentence meaning are two connected decisions.", note: "A correct ending is not enough if it belongs to the wrong subject or family.",
      left: { label: "FORM", question: "Who performs the action?", description: "The subject and infinitive family determine the ending.", example: ["Nosotros comemos", "We eat"] },
      right: { label: "MESSAGE", question: "What else matters?", description: "Objects, place, time, and negation complete the intended claim.", example: ["No comemos aquí hoy.", "We are not eating here today."] } },
    prediction: { heading: "Coordinate family and subject.", context: "The infinitive is vivir and the subject is mis amigos.", prompt: "Which form begins the sentence?", options: ["Mis amigos viven", "Mis amigos vivimos", "Mis amigos vivenemos"], answer: 0, correct: "The plural third-person -ir form is viven.", incorrect: "Mis amigos uses the ellos form: remove -ir and add -en." },
    guided: { heading: "Build a negative nosotros sentence.", context: "The action is trabajar and the meaning is we do not work on Sundays.", prompt: "Which opening is accurate?", options: ["No trabajamos", "No trabajan", "Trabajamos no"], answer: 0, correct: "No precedes the nosotros form trabajamos.", incorrect: "Conjugate trabajar for nosotros, then place no before it." },
    builder: { prompt: "Build: My friends study and I work.", tokens: ["Mis amigos", "estudian", "y yo", "trabajo."], correctOrder: ["Mis amigos", "estudian", "y yo", "trabajo."], answer: "Mis amigos estudian y yo trabajo.", feedback: "Each verb agrees with its own subject inside the connected sentence." },
    reading: { heading: "A productive morning.", sentences: [["Yo trabajo en una cafetería.", "I work in a café."], ["Mi amiga Elena estudia medicina.", "My friend Elena studies medicine."], ["Al mediodía comemos juntas.", "At noon we eat together."], ["Después escribimos en la biblioteca, pero no hablamos mucho.", "Afterward we write in the library, but we do not talk much."]], question: { prompt: "Which actions include both people?", options: ["comemos and escribimos", "trabajo and estudia", "estudia and hablamos"], answer: 0, feedback: "The -emos and -imos endings mark nosotros in comemos and escribimos." } },
    recall: [
      { before: "Nosotros ", after: " español. (practicar)", answer: "practicamos", feedback: "The -ar nosotros ending is -amos." },
      { before: "El profesor ", after: " mucho. (leer)", answer: "lee", feedback: "One third-person -er subject uses -e; leer contracts to lee." },
      { before: "Mis amigas no ", after: " aquí. (vivir)", answer: "viven", feedback: "Mis amigas uses the plural -ir form viven; no remains before it." },
    ],
    production: { prompt: "Write a six-sentence weekday portrait using at least two AR, two ER, and two IR verbs, with one negative contrast.", requirements: ["Use all three regular families", "Vary the subjects", "Include one no + conjugated verb"], example: "Trabajo por la mañana. Ana estudia. Comemos a la una. Ella lee. Vivimos cerca. No escribimos por la noche." },
    takeaway: "Choose the subject, identify the infinitive family, attach its ending, then complete and verify the full present-time message.",
  }),
];
