import { createCourseLesson } from "./course-lesson-factory";

export const module12LessonDefinitions = [
  createCourseLesson({
    id: "12.1", title: "Doing Something to Yourself", displayTitle: "A reflexive pronoun sends the action back to the subject.",
    dek: "Me, te, se, nos, and se show that the subject also receives the action.",
    goal: "Recognize reflexive infinitives and match reflexive pronouns to subjects.", durationMinutes: 26, concepts: ["reflexive_pronouns"],
    explain: [
      "A reflexive infinitive ends in -se: lavar → lavarse. When conjugated, the -se moves and changes to match the subject: me lavo, te lavas, se lava, nos lavamos, se lavan.",
      "The reflexive pronoun is not decoration. Compare Ana lava el carro, where the car receives the action, with Ana se lava, where Ana acts on herself. The subject and reflexive pronoun must refer to the same person or group.",
    ],
    examples: [["Me lavo.", "I wash myself."], ["Ana se prepara.", "Ana gets herself ready."], ["Nos cuidamos.", "We take care of ourselves."]],
    boundary: { heading: "Ask who receives the action.", note: "The verb may be the same while the object relationship changes.",
      left: { label: "NONREFLEXIVE", question: "Does another object receive it?", description: "Name the object directly.", example: ["Ana lava el carro.", "Ana washes the car."] },
      right: { label: "REFLEXIVE", question: "Does the action return to the subject?", description: "Use the matching reflexive pronoun.", example: ["Ana se lava.", "Ana washes herself."] } },
    prediction: { heading: "Match yo.", context: "The speaker prepares themself.", prompt: "Which pronoun matches yo?", options: ["me", "se", "te"], answer: 0, correct: "Yo matches me: me preparo.", incorrect: "Use the pronoun that refers back to yo: me." },
    guided: { heading: "Separate object relationships.", context: "Ana washes the dishes, not herself.", prompt: "Which sentence is accurate?", options: ["Ana lava los platos.", "Ana se lava los platos a sí misma.", "Ana me lava los platos."], answer: 0, correct: "Los platos is the direct object, so no reflexive meaning is needed.", incorrect: "Because the dishes receive the action, use nonreflexive lavar." },
    builder: { prompt: "Build: We prepare ourselves for class.", tokens: ["Nos", "preparamos", "para la clase."], correctOrder: ["Nos", "preparamos", "para la clase."], answer: "Nos preparamos para la clase.", feedback: "Nos refers back to the nosotros subject." },
    reading: { heading: "Before leaving.", sentences: [["Me preparo temprano.", "I get ready early."], ["Mi hermano se lava la cara.", "My brother washes his face."], ["Nos miramos en el espejo.", "We look at ourselves in the mirror."], ["Después salimos de casa.", "Afterward we leave home."]], question: { prompt: "Which pronoun refers to the speaker and brother together?", options: ["nos", "me", "se"], answer: 0, feedback: "Nos refers back to a nosotros subject." } },
    recall: [
      { before: "Yo ", after: " preparo.", answer: "me", feedback: "Yo pairs with me." },
      { before: "Tú ", after: " lavas.", answer: "te", feedback: "Tú pairs with te." },
      { before: "Nosotros ", after: " cuidamos.", answer: "nos", feedback: "Nosotros pairs with nos." },
    ],
    production: { prompt: "Write five reflexive sentences, one for each pronoun pattern me, te, se, nos, and plural se.", requirements: ["Match subject and pronoun", "Conjugate each verb", "Include one nonreflexive contrast"], example: "Me preparo. Te lavas. Ana se cuida. Nos miramos. Ellos se preparan. Ana lava el carro." },
    takeaway: "Use a reflexive pronoun when the subject also receives the action, and make that pronoun refer to the same subject.",
  }),
  createCourseLesson({
    id: "12.2", title: "Daily Routine", displayTitle: "Reflexive verbs organize what people do to begin and end a day.",
    dek: "Levantarse, ducharse, vestirse, and acostarse become a connected routine when pronouns and forms agree.",
    goal: "Describe a daily routine with common reflexive verbs, sequence, and time.", durationMinutes: 28, concepts: ["daily_routine", "reflexive_pronouns"],
    explain: [
      "Common routine verbs include despertarse, levantarse, ducharse, vestirse, cepillarse, and acostarse. Some also change stems: me despierto, te vistes, se acuesta; nosotros keeps the unchanging stem in nos despertamos and nos acostamos.",
      "A reflexive pronoun often appears even when a body part follows: Me lavo las manos, not mis manos in the neutral pattern. The pronoun identifies whose body is involved; the definite article names the body part.",
    ],
    examples: [["Me levanto a las siete.", "I get up at seven."], ["Ana se viste rápido.", "Ana gets dressed quickly."], ["Nos acostamos tarde.", "We go to bed late."]],
    boundary: { heading: "Spanish normally uses the article with body parts.", note: "The reflexive pronoun already identifies the possessor.",
      left: { label: "SPANISH PATTERN", question: "Is the body part understood as the subject’s?", description: "Use reflexive pronoun + definite article.", example: ["Me lavo las manos.", "I wash my hands."] },
      right: { label: "ENGLISH TRANSFER", question: "Are you translating the possessive literally?", description: "Avoid replacing the neutral article with a possessive unnecessarily.", example: ["Me lavo mis manos.", "Literal transfer to avoid here."] } },
    prediction: { heading: "Build a yo routine.", context: "The speaker wakes up at six; despertarse changes e→ie.", prompt: "Which sentence is accurate?", options: ["Me despierto a las seis.", "Se despierto a las seis.", "Me despertamos a las seis."], answer: 0, correct: "Me matches yo and despierto carries the stem change.", incorrect: "Use me + the yo form despierto." },
    guided: { heading: "Wash a body part.", context: "The speaker washes their face.", prompt: "Which neutral pattern is preferred?", options: ["Me lavo la cara.", "Lavo mi cara me.", "Me lavo mi cara."], answer: 0, correct: "Me identifies the person and la marks the body part.", incorrect: "Use the reflexive pronoun and definite article: me lavo la cara." },
    builder: { prompt: "Build: We go to bed at eleven.", tokens: ["Nos", "acostamos", "a las once."], correctOrder: ["Nos", "acostamos", "a las once."], answer: "Nos acostamos a las once.", feedback: "Nosotros keeps the original stem in acostamos." },
    reading: { heading: "Marisol’s morning.", sentences: [["Marisol se despierta a las seis.", "Marisol wakes up at six."], ["Se levanta y se ducha.", "She gets up and showers."], ["Después se viste y se cepilla los dientes.", "Afterward she gets dressed and brushes her teeth."], ["Sale de casa a las siete.", "She leaves home at seven."]], question: { prompt: "What happens immediately before Marisol leaves?", options: ["She gets dressed and brushes her teeth", "She wakes up", "She showers only"], answer: 0, feedback: "The third line gives the last routine actions before salir." } },
    recall: [
      { before: "Yo ", after: " levanto a las siete.", answer: "me", feedback: "Yo pairs with me." },
      { before: "Ana se ", after: " a las once. (goes to bed)", answer: "acuesta", feedback: "Acostarse changes o→ue in se acuesta." },
      { before: "Nos lavamos ", after: " manos.", answer: "las", feedback: "Use the definite article with the body part." },
    ],
    production: { prompt: "Write an eight-step morning or evening routine with sequence words and at least two exact times.", requirements: ["Use six reflexive verbs", "Include one body-part phrase", "Organize the actions in sequence"], example: "Me despierto a las seis. Luego me levanto. Me ducho, me visto y me lavo la cara. Al final me voy a las siete." },
    takeaway: "Match reflexive pronouns to each subject, preserve stem-change patterns, and use definite articles for routine body parts.",
  }),
  createCourseLesson({
    id: "12.3", title: "Reflexive Pronoun Position", displayTitle: "Reflexive pronouns use the same outer-edge positions as object pronouns.",
    dek: "Before a conjugated verb or attached to an infinitive, the pronoun stays connected to its verb unit.",
    goal: "Place reflexive pronouns in single- and two-verb structures.", durationMinutes: 26, concepts: ["reflexive_position", "object_pronoun_position"],
    explain: [
      "Before one conjugated verb, place the reflexive pronoun first: Me levanto; No se prepara. With a conjugated verb plus infinitive, place it before the conjugated verb or attach it to the infinitive: Me voy a preparar = Voy a prepararme.",
      "The pronoun must still match the subject even when attached: Vamos a levantarnos, not levantarse. Written accents may be needed with other attached verb forms later, but infinitive attachment simply joins the words.",
    ],
    examples: [["Me quiero levantar.", "I want to get up."], ["Quiero levantarme.", "I want to get up."], ["Vamos a prepararnos.", "We are going to get ready."]],
    boundary: { heading: "Keep the pronoun on an outer edge of the verb unit.", note: "Both placements are grammatical and mean the same thing.",
      left: { label: "BEFORE", question: "Before the conjugated verb?", description: "Place the matching pronoun before the entire unit.", example: ["Nos vamos a preparar.", "We are going to get ready."] },
      right: { label: "ATTACHED", question: "Attached to the infinitive?", description: "Join the matching pronoun to the infinitive.", example: ["Vamos a prepararnos.", "We are going to get ready."] } },
    prediction: { heading: "Attach a yo pronoun.", context: "The speaker wants to get up.", prompt: "Which attached form is correct?", options: ["Quiero levantarme.", "Quiero me levantar.", "Quiero levantarte."], answer: 0, correct: "Me attaches to levantar and still matches yo.", incorrect: "Attach the matching me to the infinitive: levantarme." },
    guided: { heading: "Move the pronoun before the unit.", context: "Nosotros are going to prepare ourselves.", prompt: "Which pre-verb version matches Vamos a prepararnos?", options: ["Nos vamos a preparar.", "Vamos nos a preparar.", "Se vamos a preparar."], answer: 0, correct: "Nos moves before the conjugated verb vamos.", incorrect: "Place nos before the entire conjugated verb unit." },
    builder: { prompt: "Build: Ana needs to get ready.", tokens: ["Ana", "necesita", "prepararse."], correctOrder: ["Ana", "necesita", "prepararse."], answer: "Ana necesita prepararse.", feedback: "Se matches Ana and attaches to the infinitive preparar." },
    reading: { heading: "A rushed morning.", sentences: [["Me tengo que levantar temprano.", "I have to get up early."], ["Mi hermana quiere quedarse en casa.", "My sister wants to stay home."], ["Pero va a prepararse para la clase.", "But she is going to get ready for class."], ["Al final nos vamos a ir juntas.", "In the end we are going to leave together."]], question: { prompt: "Which line attaches the reflexive pronoun to an infinitive?", options: ["va a prepararse", "me tengo que levantar", "nos vamos a ir"], answer: 0, feedback: "Se is attached directly to preparar." } },
    recall: [
      { before: "Quiero levantar", after: ". (myself)", answer: "me", feedback: "Me attaches to levantar: levantarme." },
      { before: "", after: " vamos a preparar. (ourselves)", answer: "Nos", accepted: ["nos"], feedback: "Nos appears before the conjugated verb unit." },
      { before: "Ana necesita vestir", after: ". (herself)", answer: "se", feedback: "Se attaches to vestir: vestirse." },
    ],
    production: { prompt: "Write four pairs that express the same two-verb idea twice: pronoun before the conjugated verb, then attached to the infinitive.", requirements: ["Use me, te, se, and nos", "Keep the same meaning within each pair", "Match every pronoun to its subject"], example: "Me quiero levantar / Quiero levantarme. Nos vamos a preparar / Vamos a prepararnos." },
    takeaway: "Place the matching reflexive pronoun before the conjugated verb or attach it to the infinitive; never leave it between the verbs.",
  }),
  createCourseLesson({
    id: "12.4", title: "Emotions & Changes", displayTitle: "Some reflexive verbs present a change into a new state.",
    dek: "Ponerse, sentirse, and quedarse connect events to reactions and resulting conditions.",
    goal: "Describe emotional and situational changes with common reflexive verbs.", durationMinutes: 27, concepts: ["reflexive_change", "reflexive_pronouns"],
    explain: [
      "Ponerse + adjective often means to become or get into a state: Me pongo nervioso. Sentirse describes how someone feels and stem-changes e→ie outside nosotros: se siente feliz, nos sentimos bien.",
      "Quedarse can express remaining or ending up in a state/place: Se queda en casa; Nos quedamos sorprendidos. The adjective must still agree with the subject. Choose the verb from the change or resulting relationship, not a single English translation.",
    ],
    examples: [["Me pongo nerviosa.", "I get nervous."], ["Ana se siente mejor.", "Ana feels better."], ["Nos quedamos en casa.", "We stay at home."]],
    boundary: { heading: "State and change into a state are different claims.", note: "Estar presents the condition; ponerse highlights entering it.",
      left: { label: "STATE", question: "How is the person?", description: "Use estar to present the current condition.", example: ["Estoy nervioso.", "I am nervous."] },
      right: { label: "CHANGE", question: "Does the person become that way?", description: "Use ponerse to highlight the transition.", example: ["Me pongo nervioso.", "I get nervous."] } },
    prediction: { heading: "Express a reaction change.", context: "Ana becomes happy when her friend arrives.", prompt: "Which sentence highlights the change?", options: ["Ana se pone contenta.", "Ana está ponerse contenta.", "Ana pone contenta."], answer: 0, correct: "Se pone presents Ana entering the state; contenta agrees with her.", incorrect: "Use ponerse reflexively and make the adjective agree: se pone contenta." },
    guided: { heading: "Describe how nosotros feel.", context: "The group feels well.", prompt: "Which form keeps the original stem?", options: ["Nos sentimos bien.", "Nos sientimos bien.", "Se sentimos bien."], answer: 0, correct: "Nosotros uses nos sentimos without the stem change.", incorrect: "Match nosotros with nos and use sentimos." },
    builder: { prompt: "Build: They stay calm.", tokens: ["Ellos", "se quedan", "tranquilos."], correctOrder: ["Ellos", "se quedan", "tranquilos."], answer: "Ellos se quedan tranquilos.", feedback: "Se refers to ellos; tranquilos agrees with the plural masculine/mixed subject." },
    reading: { heading: "Before a presentation.", sentences: [["Antes de hablar, me pongo nerviosa.", "Before speaking, I get nervous."], ["Mi compañero se siente tranquilo.", "My classmate feels calm."], ["Cuando empezamos, nos sentimos mejor.", "When we begin, we feel better."], ["Al final todos se quedan contentos.", "In the end everyone remains happy."]], question: { prompt: "When does the speaker’s condition improve?", options: ["when the presentation begins", "before speaking", "after everyone leaves"], answer: 0, feedback: "Cuando empezamos, nos sentimos mejor marks the improvement." } },
    recall: [
      { before: "Yo ", after: " pongo nervioso.", answer: "me", feedback: "Yo matches me in ponerse." },
      { before: "Ana se ", after: " feliz. (feels)", answer: "siente", feedback: "Sentirse changes e→ie in se siente." },
      { before: "Nosotros nos ", after: " en casa. (stay)", answer: "quedamos", feedback: "Nosotros uses quedamos." },
    ],
    production: { prompt: "Describe three emotional changes and one resulting state around an event.", requirements: ["Use ponerse", "Use sentirse", "Use quedarse and adjective agreement"], example: "Me pongo nerviosa. Ana se siente tranquila. Nos sentimos mejor. Al final nos quedamos contentas." },
    takeaway: "Use ponerse for entering a state, sentirse for experienced feeling, and quedarse for remaining or ending up.",
  }),
  createCourseLesson({
    id: "12.5", title: "Each Other", displayTitle: "A plural reflexive pronoun can express reciprocal action.",
    dek: "Nos and se may mean ourselves or each other; context and reinforcement make the relationship clear.",
    goal: "Interpret and produce reciprocal actions with nos and se.", durationMinutes: 26, concepts: ["reciprocal_reflexive"],
    explain: [
      "With plural subjects, nos and se can show that participants act on one another: Nos ayudamos means we help each other; Ana y Luis se escriben means they write to each other.",
      "Context usually resolves reciprocal versus reflexive meaning. Add el uno al otro, la una a la otra, or mutuamente when clarity or emphasis matters. A genuinely self-directed plural action remains possible: Nos miramos en el espejo can mean we look at ourselves.",
    ],
    examples: [["Nos ayudamos.", "We help each other."], ["Ellas se escriben.", "They write to each other."], ["Los amigos se apoyan mutuamente.", "The friends support each other."]],
    boundary: { heading: "Plural pronouns allow two directions of meaning.", note: "Use context or a reciprocal phrase to disambiguate.",
      left: { label: "REFLEXIVE", question: "Does each person act on themself?", description: "The action returns separately to each subject.", example: ["Nos miramos en el espejo.", "We look at ourselves in the mirror."] },
      right: { label: "RECIPROCAL", question: "Do participants act on one another?", description: "The action moves between members of the plural subject.", example: ["Nos miramos y sonreímos.", "We look at each other and smile."] } },
    prediction: { heading: "Express mutual help.", context: "Two friends help one another.", prompt: "Which sentence uses reciprocal se?", options: ["Los amigos se ayudan.", "Los amigos ayudan se mismos.", "Los amigos los ayudan."], answer: 0, correct: "With the plural subject, se ayudan can express mutual action.", incorrect: "Use the plural reciprocal pronoun se before ayudan." },
    guided: { heading: "Make reciprocity explicit.", context: "The context could be ambiguous; you want to say they write to each other.", prompt: "Which reinforcement is clear?", options: ["Se escriben el uno al otro.", "Se escriben a sí solo.", "Los escriben mutuamente ellos."], answer: 0, correct: "El uno al otro explicitly marks reciprocal direction.", incorrect: "Use se + plural verb and a reciprocal phrase such as el uno al otro." },
    builder: { prompt: "Build: We support each other.", tokens: ["Nos", "apoyamos", "mutuamente."], correctOrder: ["Nos", "apoyamos", "mutuamente."], answer: "Nos apoyamos mutuamente.", feedback: "Nos with a plural subject and mutuamente makes the reciprocal meaning explicit." },
    reading: { heading: "A strong study partnership.", sentences: [["Ana y yo estudiamos juntas.", "Ana and I study together."], ["Nos hacemos preguntas.", "We ask each other questions."], ["Cuando una no entiende, nos ayudamos.", "When one does not understand, we help each other."], ["También nos enviamos mensajes antes de los exámenes.", "We also send each other messages before exams."]], question: { prompt: "What happens when one person does not understand?", options: ["They help each other", "They stop studying", "They call the professor"], answer: 0, feedback: "Nos ayudamos expresses reciprocal help." } },
    recall: [
      { before: "Ana y yo ", after: " ayudamos. (each other)", answer: "nos", feedback: "A nosotros subject uses reciprocal nos." },
      { before: "Ellos ", after: " escriben. (each other)", answer: "se", feedback: "A plural third-person subject uses reciprocal se." },
      { before: "Nos apoyamos ", after: ". (mutually)", answer: "mutuamente", feedback: "Mutuamente makes the reciprocal meaning explicit." },
    ],
    production: { prompt: "Write five sentences about relationships in a family, friendship, or team using reciprocal nos/se.", requirements: ["Use nos and se", "Make one reciprocal meaning explicit", "Choose actions that logically move between people"], example: "Nos ayudamos. Mis amigos se escriben. Nos escuchamos mutuamente. Ellos se llaman. Nos apoyamos." },
    takeaway: "With plural subjects, nos or se can send an action between participants; use context or a reciprocal phrase to make that direction clear.",
  }),
];
