import { createCourseLesson } from "./course-lesson-factory";

export const module14LessonDefinitions = [
  createCourseLesson({
    id: "14.1", title: "Why the Subjunctive Exists", displayTitle: "The subjunctive presents an idea through someone’s stance toward it.",
    dek: "A second clause becomes desired, doubted, evaluated, or emotionally framed rather than simply asserted.",
    goal: "Recognize the two-clause relationship that motivates the present subjunctive.", durationMinutes: 28, concepts: ["subjunctive_purpose"],
    explain: [
      "The indicative presents information as an assertion: Ana estudia. The subjunctive often appears when another subject wants, doubts, evaluates, or reacts to that idea: Quiero que Ana estudie. The speaker is not merely reporting Ana’s study; the clause is inside a desire.",
      "A common frame has subject one + trigger + que + subject two + subjunctive. If both actions belong to the same subject, Spanish usually uses an infinitive instead: Quiero estudiar versus Quiero que Ana estudie.",
    ],
    examples: [["Sé que Ana estudia.", "I know Ana studies."], ["Quiero que Ana estudie.", "I want Ana to study."], ["Quiero estudiar.", "I want to study."]],
    boundary: { heading: "Assertion and stance are different sentence jobs.", note: "The trigger and subject relationship determine the mood.",
      left: { label: "INDICATIVE", question: "Is the clause asserted as information?", description: "Use the indicative after certainty and reporting.", example: ["Sé que viene.", "I know that she is coming."] },
      right: { label: "SUBJUNCTIVE", question: "Is the clause desired, doubted, or evaluated?", description: "Use the subjunctive inside the stance.", example: ["Quiero que venga.", "I want her to come."] } },
    prediction: { heading: "Spot the two-subject frame.", context: "I want Ana to study has yo as the wanter and Ana as the student.", prompt: "Which structure makes that relationship visible?", options: ["Quiero que Ana estudie.", "Quiero Ana estudiar.", "Quiero que Ana estudia."], answer: 0, correct: "Que opens the second subject’s clause, and desire places estudie in the subjunctive.", incorrect: "With different subjects, use quiero que + second subject + subjunctive." },
    guided: { heading: "Keep one subject compact.", context: "The speaker both wants and studies.", prompt: "Which form avoids an unnecessary second clause?", options: ["Quiero estudiar.", "Quiero que yo estudie.", "Quiero que estudio."], answer: 0, correct: "One subject normally uses querer + infinitive.", incorrect: "When the subject stays the same, use the infinitive directly." },
    builder: { prompt: "Build: We hope that Elena comes.", tokens: ["Esperamos", "que Elena", "venga."], correctOrder: ["Esperamos", "que Elena", "venga."], answer: "Esperamos que Elena venga.", feedback: "Esperamos frames Elena’s coming as a hope, so venga is subjunctive." },
    reading: { heading: "Planning a group project.", sentences: [["Sabemos que Marta trabaja mucho.", "We know Marta works a lot."], ["Queremos que descanse hoy.", "We want her to rest today."], ["Es importante que todos participen.", "It is important that everyone participate."], ["Yo prefiero trabajar por la mañana.", "I prefer to work in the morning."]], question: { prompt: "Why does the final line use an infinitive?", options: ["The same subject prefers and works", "Preferir never uses que", "Morning blocks the subjunctive"], answer: 0, feedback: "When one subject carries both actions, preferir + infinitive is natural." } },
    recall: [
      { before: "Quiero ", after: " temprano. (to arrive; same subject)", answer: "llegar", feedback: "One subject uses the infinitive." },
      { before: "Quiero ", after: " Ana llegue temprano. (that)", answer: "que", feedback: "Que opens the second subject’s desired clause." },
      { before: "Sé que Ana ", after: ". (studies; asserted)", answer: "estudia", feedback: "Sé que asserts information, so use indicative estudia." },
    ],
    production: { prompt: "Write four pairs contrasting one-subject infinitives with two-subject que clauses after desire, hope, or preference.", requirements: ["Show same-subject infinitives", "Show changed-subject subjunctive clauses", "Underline the stance through meaning"], example: "Quiero estudiar / Quiero que Ana estudie. Esperamos salir / Esperamos que ellos salgan." },
    takeaway: "Use the subjunctive when a second subject’s action sits inside a desire, doubt, reaction, or evaluation; keep an infinitive when the subject stays the same.",
  }),
  createCourseLesson({
    id: "14.2", title: "Forming the Present Subjunctive", displayTitle: "Start from the present yo form, then switch the family vowel.",
    dek: "The yo stem exposes irregularities; opposite endings create the present subjunctive.",
    goal: "Form regular and common irregular present subjunctive forms.", durationMinutes: 30, concepts: ["subjunctive_forms"],
    explain: [
      "Begin with the present indicative yo form, remove -o, and add opposite-family endings. AR verbs take -e, -es, -e, -emos, -en; ER/IR verbs take -a, -as, -a, -amos, -an: hablo → hable; como → coma; vivo → viva.",
      "The yo-form method carries irregular stems into the whole paradigm: tengo → tenga, hago → haga, conozco → conozca. Six highly irregular anchors are sea, esté, vaya, haya, sepa, and dé. Spelling changes preserve sound: buscar → busque.",
    ],
    examples: [["hablo → hable", "I speak → that I/you/he/she speak"], ["tengo → tenga", "I have → that I/you/he/she have"], ["voy → vaya", "I go → that I/you/he/she go"],],
    boundary: { heading: "The infinitive family takes the opposite thematic vowel.", note: "Start from yo so irregular stems remain visible.",
      left: { label: "AR → E", question: "Does the infinitive end in -ar?", description: "Use e-family subjunctive endings.", example: ["hablar → hable", "to speak → speak"] },
      right: { label: "ER/IR → A", question: "Does it end in -er or -ir?", description: "Use a-family subjunctive endings.", example: ["comer → coma", "to eat → eat"] } },
    prediction: { heading: "Form tener for ella.", context: "The indicative yo form is tengo.", prompt: "Which subjunctive form preserves teng- and adds -a?", options: ["tenga", "tene", "tiene"], answer: 0, correct: "Tengo supplies teng-, and an -er verb takes the opposite vowel a.", incorrect: "Begin from tengo, remove -o, and add -a: tenga." },
    guided: { heading: "Form nosotros hablar.", context: "Hablar is an -ar verb and the subject is nosotros.", prompt: "Which opposite-vowel ending fits?", options: ["hablemos", "hablamos", "hablamas"], answer: 0, correct: "AR subjunctive nosotros uses -emos: hablemos.", incorrect: "Use the e-family nosotros ending -emos." },
    builder: { prompt: "Build: It is important that we look for the answer.", tokens: ["Es importante", "que", "busquemos", "la respuesta."], correctOrder: ["Es importante", "que", "busquemos", "la respuesta."], answer: "Es importante que busquemos la respuesta.", feedback: "Buscar changes c→qu to preserve the hard k sound before e." },
    reading: { heading: "What the professor requests.", sentences: [["La profesora quiere que hablemos español.", "The professor wants us to speak Spanish."], ["Pide que hagamos preguntas.", "She asks that we ask questions."], ["Es importante que tengamos paciencia.", "It is important that we have patience."], ["También espera que vayamos a la práctica.", "She also hopes we go to practice."]], question: { prompt: "Which form comes from irregular indicative hago?", options: ["hagamos", "tengamos", "vayamos"], answer: 0, feedback: "Hago supplies the subjunctive stem hag-." } },
    recall: [
      { before: "Quiero que Ana ", after: ". (hablar)", answer: "hable", feedback: "Hablar takes the e-family ending -e." },
      { before: "Es importante que nosotros ", after: ". (comer)", answer: "comamos", feedback: "Comer takes the opposite-vowel -amos ending." },
      { before: "Espero que ellos ", after: ". (ir)", answer: "vayan", feedback: "Ir uses the irregular subjunctive stem vay-." },
    ],
    production: { prompt: "Create a mini formation table with six verbs, then use each in a complete triggered subjunctive sentence.", requirements: ["Two AR, two ER/IR, and two irregular verbs", "Derive regular stems from yo", "Use at least three subject forms"], example: "hablo→hable: Quiero que hable. tengo→tenga: Espero que tenga tiempo. voy→vaya: Es bueno que vaya." },
    takeaway: "Take the present yo stem, remove -o, add the opposite family endings, and learn sea, esté, vaya, haya, sepa, and dé as anchors.",
  }),
  createCourseLesson({
    id: "14.3", title: "Wants & Influence", displayTitle: "A person’s will can frame what another person should do.",
    dek: "Querer, esperar, pedir, recomendar, necesitar, and insistir activate a two-subject subjunctive relationship.",
    goal: "Express wants, requests, recommendations, and influence across two clauses.", durationMinutes: 29, concepts: ["subjunctive_influence", "subjunctive_forms"],
    explain: [
      "When one subject wants or influences another subject’s action, use trigger + que + subjunctive: La profesora recomienda que estudiemos. Mis padres quieren que llame. The second action is presented as desired or directed, not reported as a fact.",
      "When the subject does not change, use the infinitive: Recomiendo estudiar; Quiero llamar. With pedir, the person requested often appears as an indirect object: Le pido a Ana que venga.",
    ],
    examples: [["Quiero que vengas.", "I want you to come."], ["La profesora recomienda que estudiemos.", "The professor recommends that we study."], ["Le pido a Ana que llame.", "I ask Ana to call."]],
    boundary: { heading: "Subject continuity decides infinitive versus que + subjunctive.", note: "The trigger alone is not enough; track who performs each action.",
      left: { label: "SAME SUBJECT", question: "Does one person do both actions?", description: "Use the infinitive directly.", example: ["Quiero descansar.", "I want to rest."] },
      right: { label: "NEW SUBJECT", question: "Does another person perform the second action?", description: "Use que + subjunctive.", example: ["Quiero que descanses.", "I want you to rest."] } },
    prediction: { heading: "Change the actor.", context: "The professor wants the students to participate.", prompt: "Which form captures the influence?", options: ["Quiere que participen.", "Quiere participar.", "Quiere que participan."], answer: 0, correct: "The students are a second subject, so participen is subjunctive.", incorrect: "Use que + subjunctive when the desired action belongs to another subject." },
    guided: { heading: "Keep one actor compact.", context: "The speaker recommends studying; no second subject is named.", prompt: "Which structure is natural?", options: ["Recomiendo estudiar.", "Recomiendo que estudio.", "Recomiendo que estudiar."], answer: 0, correct: "The generic/same-subject action can remain an infinitive.", incorrect: "Without a new subject, use recomendar + infinitive." },
    builder: { prompt: "Build: We ask Carlos to arrive early.", tokens: ["Le pedimos", "a Carlos", "que llegue", "temprano."], correctOrder: ["Le pedimos", "a Carlos", "que llegue", "temprano."], answer: "Le pedimos a Carlos que llegue temprano.", feedback: "Le/a Carlos identifies the person influenced; llegue presents the requested action." },
    reading: { heading: "Preparing a community event.", sentences: [["Queremos que todos participen.", "We want everyone to participate."], ["La directora pide que lleguemos temprano.", "The director asks us to arrive early."], ["Recomienda que Ana traiga la comida.", "She recommends that Ana bring the food."], ["Yo prefiero preparar las mesas.", "I prefer to prepare the tables."]], question: { prompt: "Why does the last line use preparar?", options: ["The speaker both prefers and prepares", "Preferir blocks subjunctive", "Tables are plural"], answer: 0, feedback: "There is no subject change, so the second action stays infinitive." } },
    recall: [
      { before: "Quiero que tú ", after: ". (come)", answer: "vengas", feedback: "A second-subject desire uses subjunctive vengas." },
      { before: "Recomendamos ", after: " más. (study; same subject/general)", answer: "estudiar", feedback: "Without a new subject, use the infinitive." },
      { before: "La profesora pide que nosotros ", after: ". (write)", answer: "escribamos", feedback: "A request directed at nosotros uses escribamos." },
    ],
    production: { prompt: "Write six influence messages involving family, school, or community, with four changed subjects and two same-subject infinitives.", requirements: ["Use four different influence triggers", "Track both subjects", "Contrast subjunctive clauses with infinitives"], example: "Quiero que vengas. La profesora pide que estudiemos. Recomiendo practicar. Prefiero ayudar." },
    takeaway: "Use an infinitive when the actor stays the same; use que + subjunctive when one person wants, requests, or influences another person’s action.",
  }),
  createCourseLesson({
    id: "14.4", title: "Emotion, Doubt & Evaluation", displayTitle: "Reactions and uncertainty frame a clause instead of simply asserting it.",
    dek: "Emotion, doubt, denial, and impersonal evaluation commonly place the second idea in the subjunctive.",
    goal: "Use the present subjunctive after emotional, doubtful, and evaluative triggers.", durationMinutes: 30, concepts: ["subjunctive_reactions", "subjunctive_purpose"],
    explain: [
      "Emotion triggers include Me alegra que, Me preocupa que, and Siento que when it means I am sorry that. Doubt and denial include Dudo que and No creo que. Evaluations include Es importante/bueno/posible que.",
      "Certainty usually asserts the clause with indicative: Creo que viene; Es verdad que estudia. Negated belief often suspends assertion: No creo que venga. Meaning and stance—not the surface word que by itself—choose the mood.",
    ],
    examples: [["Me alegra que estés aquí.", "I am glad you are here."], ["Dudo que venga.", "I doubt that she is coming."], ["Creo que viene.", "I think she is coming."]],
    boundary: { heading: "Belief asserts; denied belief opens uncertainty.", note: "Negation changes the speaker’s stance toward the second clause.",
      left: { label: "CREO QUE", question: "Does the speaker present it as believed?", description: "Use indicative for the asserted belief.", example: ["Creo que Ana viene.", "I think Ana is coming."] },
      right: { label: "NO CREO QUE", question: "Does the speaker withhold belief?", description: "Use subjunctive for the doubted possibility.", example: ["No creo que Ana venga.", "I do not think Ana is coming."] } },
    prediction: { heading: "React emotionally.", context: "The speaker is happy that a friend is present.", prompt: "Which form fits after Me alegra que?", options: ["estés", "estás", "estar"], answer: 0, correct: "The friend’s presence is framed as the cause of an emotional reaction.", incorrect: "An emotional reaction to a second subject’s clause uses subjunctive estés." },
    guided: { heading: "Assert a belief.", context: "The speaker thinks Ana is studying and presents that as a belief.", prompt: "Which clause follows Creo que?", options: ["Ana estudia", "Ana estudie", "Ana estudiar"], answer: 0, correct: "Positive belief normally asserts with indicative estudia.", incorrect: "Creo que presents the idea as believed information, so use indicative." },
    builder: { prompt: "Build: It is important that we have time.", tokens: ["Es importante", "que", "tengamos", "tiempo."], correctOrder: ["Es importante", "que", "tengamos", "tiempo."], answer: "Es importante que tengamos tiempo.", feedback: "The evaluation frames the second clause; tengamos comes from tengo." },
    reading: { heading: "Waiting for good news.", sentences: [["Creo que Marta viene hoy.", "I think Marta is coming today."], ["Pero dudo que llegue antes de las seis.", "But I doubt she will arrive before six."], ["Me alegra que pueda visitar.", "I am glad she can visit."], ["Es importante que tengamos tiempo para hablar.", "It is important that we have time to talk."]], question: { prompt: "Which line asserts the speaker’s belief as information?", options: ["Creo que Marta viene hoy", "Dudo que llegue", "Es importante que tengamos"], answer: 0, feedback: "Creo que takes indicative viene because the belief is asserted." } },
    recall: [
      { before: "Me alegra que tú ", after: " aquí. (be)", answer: "estés", accepted: ["estés", "estes"], feedback: "Emotion frames the presence with subjunctive estés." },
      { before: "No creo que Ana ", after: ". (come)", answer: "venga", feedback: "Denied belief uses subjunctive venga." },
      { before: "Creo que Ana ", after: ". (comes)", answer: "viene", feedback: "Positive belief asserts with indicative viene." },
    ],
    production: { prompt: "Write six reactions to one uncertain event: two emotions, two evaluations, one doubt, and one positive belief.", requirements: ["Use subjunctive after reactions/doubt", "Use indicative after positive belief", "Keep the event coherent across sentences"], example: "Me alegra que venga. Es bueno que pueda venir. Dudo que llegue temprano. Creo que llega a las seis." },
    takeaway: "Use subjunctive when a clause is emotionally framed, doubted, denied, or evaluated; use indicative when it is asserted as believed or known information.",
  }),
  createCourseLesson({
    id: "14.5", title: "High-Value Connectors", displayTitle: "Some connectors frame an event as pending, conditional, or intended.",
    dek: "Para que, antes de que, sin que, and a menos que create useful subjunctive clauses with their own subjects.",
    goal: "Use high-value subjunctive connectors and contrast them with same-subject infinitive phrases.", durationMinutes: 30, concepts: ["subjunctive_connectors", "subjunctive_purpose"],
    explain: [
      "Para que expresses purpose across different subjects: Hablo despacio para que entiendas. Antes de que, sin que, and a menos que also introduce non-asserted or conditional clauses and take the subjunctive.",
      "When the subject remains the same, compact purpose and sequence with an infinitive: Estudio para aprender; Como antes de salir. When a second subject appears, use para que or antes de que + subjunctive.",
    ],
    examples: [["Hablo despacio para que entiendas.", "I speak slowly so that you understand."], ["Llama antes de que salgamos.", "Call before we leave."], ["No voy a menos que vengas.", "I am not going unless you come."]],
    boundary: { heading: "Subject continuity again selects infinitive or clause.", note: "Para and antes de package one subject; para que and antes de que open another subject’s action.",
      left: { label: "SAME SUBJECT", question: "Does one subject perform both actions?", description: "Use para/antes de + infinitive.", example: ["Estudio para aprender.", "I study to learn."] },
      right: { label: "NEW SUBJECT", question: "Does another subject carry the goal or event?", description: "Use para que/antes de que + subjunctive.", example: ["Explico para que aprendas.", "I explain so that you learn."] } },
    prediction: { heading: "Express another person’s goal.", context: "The speaker explains slowly so that the listener understands.", prompt: "Which connector and form fit?", options: ["para que entiendas", "para entender", "porque entiendes"], answer: 0, correct: "The goal belongs to a second subject, so use para que + subjunctive.", incorrect: "Different subjects require para que and the subjunctive entiendas." },
    guided: { heading: "Keep one subject compact.", context: "The speaker studies in order to learn.", prompt: "Which structure is natural?", options: ["Estudio para aprender.", "Estudio para que aprendo.", "Estudio para que aprenda yo."], answer: 0, correct: "One subject uses para + infinitive.", incorrect: "Because the subject does both actions, use para + infinitive." },
    builder: { prompt: "Build: We leave before Ana arrives.", tokens: ["Salimos", "antes de que", "Ana llegue."], correctOrder: ["Salimos", "antes de que", "Ana llegue."], answer: "Salimos antes de que Ana llegue.", feedback: "Ana is a second subject in a pending event, so llegue is subjunctive." },
    reading: { heading: "Organizing a surprise.", sentences: [["Llegamos temprano para preparar la sala.", "We arrive early to prepare the room."], ["Hablamos bajo para que Ana no oiga.", "We speak quietly so Ana does not hear."], ["Terminamos antes de que ella llegue.", "We finish before she arrives."], ["No empezamos a menos que todos estén listos.", "We do not begin unless everyone is ready."]], question: { prompt: "Which purpose phrase keeps one subject and uses an infinitive?", options: ["para preparar la sala", "para que Ana no oiga", "antes de que ella llegue"], answer: 0, feedback: "The same nosotros subject arrives and prepares, so para + infinitive is enough." } },
    recall: [
      { before: "Hablo despacio ", after: " entiendas. (so that)", answer: "para que", feedback: "A second subject’s goal uses para que." },
      { before: "Estudio para ", after: ". (learn; same subject)", answer: "aprender", feedback: "The same subject uses para + infinitive." },
      { before: "Salimos antes de que Ana ", after: ". (arrive)", answer: "llegue", feedback: "Antes de que introduces subjunctive llegue." },
    ],
    production: { prompt: "Write a six-sentence plan using para, para que, antes de, antes de que, sin que, and a menos que.", requirements: ["Contrast same and changed subjects", "Use subjunctive after que connectors", "Keep infinitives after preposition-only connectors"], example: "Voy para ayudar. Explico para que entiendas. Como antes de salir. Salgo antes de que vengas. Trabajo sin que Ana sepa. No voy a menos que puedas." },
    takeaway: "Use infinitive connectors when the subject stays the same and que + subjunctive connectors when another subject’s pending action enters the relationship.",
  }),
];
