import { createCourseLesson } from "./course-lesson-factory";

export const module15LessonDefinitions = [
  createCourseLesson({
    id: "15.1", title: "Finished Events", displayTitle: "The preterite advances a story through bounded events.",
    dek: "A completed action is viewed as a whole with a beginning, endpoint, or countable occurrence.",
    goal: "Recognize when a past message presents an event as completed and bounded.", durationMinutes: 27, concepts: ["preterite_function"],
    explain: [
      "The preterite presents a past action as a completed whole: Ayer trabajé; La clase empezó a las nueve; Visité México tres veces. Time limits, completed sequences, and counted occurrences often support this view.",
      "The preterite does not simply mean short or sudden. Trabajé allí durante diez años can use the preterite when the ten-year period is presented as finished. Aspect is the speaker’s view of the event, not its objective length.",
    ],
    examples: [["Ayer trabajé.", "Yesterday I worked."], ["La clase empezó a las nueve.", "The class started at nine."], ["Viví allí durante diez años.", "I lived there for ten years."]],
    boundary: { heading: "Completed does not mean brief.", note: "Look for a bounded whole, not a stopwatch.",
      left: { label: "BOUNDED", question: "Is the event viewed from start to endpoint?", description: "Use the preterite to move the completed sequence forward.", example: ["Trabajé allí diez años.", "I worked there for ten years."] },
      right: { label: "UNBOUNDED", question: "Is the past situation background or ongoing?", description: "The imperfect will present it from inside, without an endpoint.", example: ["Trabajaba allí entonces.", "I was working there then."] } },
    prediction: { heading: "Identify a completed event.", context: "Ayer and the finished visit frame the action as a whole.", prompt: "Which sentence presents the completed visit?", options: ["Ayer visité a Ana.", "Ayer visitaba a Ana cada día.", "Visito a Ana ayer."], answer: 0, correct: "Visité presents yesterday’s visit as completed.", incorrect: "The single completed event uses the preterite: visité." },
    guided: { heading: "Reject the duration shortcut.", context: "A person finished a ten-year residence in Peru.", prompt: "Can the preterite present that long period as complete?", options: ["Yes: Viví en Perú diez años.", "No: preterite is only for seconds.", "Only if the person still lives there."], answer: 0, correct: "The endpoint, not shortness, makes the period bounded.", incorrect: "A long duration can be preterite when presented as finished." },
    builder: { prompt: "Build: Yesterday we finished the project.", tokens: ["Ayer", "terminamos", "el proyecto."], correctOrder: ["Ayer", "terminamos", "el proyecto."], answer: "Ayer terminamos el proyecto.", feedback: "Ayer and terminar present a completed endpoint." },
    reading: { heading: "A completed morning.", sentences: [["Ayer llegué temprano.", "Yesterday I arrived early."], ["Preparé café y abrí la oficina.", "I made coffee and opened the office."], ["A las nueve empezó la reunión.", "At nine the meeting began."], ["Terminamos todo al mediodía.", "We finished everything at noon."]], question: { prompt: "Which event supplies the final endpoint?", options: ["Terminamos todo", "Llegué temprano", "Empezó la reunión"], answer: 0, feedback: "Terminamos marks the sequence’s completion at noon." } },
    recall: [
      { before: "Ayer ", after: " el proyecto. (I finished)", answer: "terminé", accepted: ["terminé", "termine"], feedback: "Ayer frames the finished yo event." },
      { before: "La clase ", after: " a las nueve. (began)", answer: "empezó", accepted: ["empezó", "empezo"], feedback: "The beginning is a bounded event." },
      { before: "", after: " allí diez años. (I lived; finished period)", answer: "Viví", accepted: ["viví", "vivi"], feedback: "The ten-year span is presented as completed." },
    ],
    production: { prompt: "Write a six-event timeline of a completed day with clear sequence markers and endpoints.", requirements: ["Every event is bounded", "Include one longer completed duration", "Use time expressions to order the sequence"], example: "Ayer llegué a las ocho. Trabajé toda la mañana. Almorcé, terminé el proyecto y salí a las cinco." },
    takeaway: "Use the preterite to view a past action as a bounded whole, regardless of whether that whole lasted a minute or ten years.",
  }),
  createCourseLesson({
    id: "15.2", title: "Regular Preterite: AR", displayTitle: "Regular AR verbs mark completed events with accented singular forms.",
    dek: "-é, -aste, -ó, -amos, and -aron carry regular AR verbs through a finished sequence.",
    goal: "Form and use regular -ar preterite verbs for the course subject system.", durationMinutes: 28, concepts: ["preterite_ar"],
    explain: [
      "Remove -ar and add -é, -aste, -ó, -amos, or -aron: hablé, hablaste, habló, hablamos, hablaron. The accents on yo and one third-person forms distinguish stress and often meaning.",
      "The nosotros preterite form matches the present in regular -ar verbs: hablamos can mean we speak or we spoke. Time context resolves it: Hoy hablamos español versus Ayer hablamos español.",
    ],
    examples: [["Hablé con Ana.", "I spoke with Ana."], ["Marta trabajó ayer.", "Marta worked yesterday."], ["Estudiamos anoche.", "We studied last night."]],
    boundary: { heading: "Written accents separate yo and third-person singular endings.", note: "Without them, the word’s stress and grammatical signal change.",
      left: { label: "YO -É", question: "Did I complete the action?", description: "Use an accented final é.", example: ["Hablé.", "I spoke."] },
      right: { label: "ÉL/ELLA -Ó", question: "Did one third person complete it?", description: "Use an accented final ó.", example: ["Habló.", "He/she spoke."] } },
    prediction: { heading: "Conjugate trabajar for ella.", context: "The action finished yesterday.", prompt: "Which form uses the third-person -ó ending?", options: ["trabajó", "trabajo", "trabajé"], answer: 0, correct: "Ella uses trabajó with a written accent.", incorrect: "Remove -ar and add accented -ó." },
    guided: { heading: "Use nosotros with context.", context: "Last night we studied.", prompt: "Which sentence is accurate?", options: ["Anoche estudiamos.", "Anoche estudiaron nosotros.", "Anoche estudiémos."], answer: 0, correct: "Estudiamos is the regular nosotros form; anoche establishes past time.", incorrect: "Use estudiamos and let anoche resolve the time." },
    builder: { prompt: "Build: Yesterday they prepared dinner.", tokens: ["Ayer", "prepararon", "la cena."], correctOrder: ["Ayer", "prepararon", "la cena."], answer: "Ayer prepararon la cena.", feedback: "Ellos/ellas/ustedes regular -ar preterite uses -aron." },
    reading: { heading: "A community dinner.", sentences: [["Ayer compré la comida.", "Yesterday I bought the food."], ["Ana preparó las mesas.", "Ana prepared the tables."], ["Cocinamos durante dos horas.", "We cooked for two hours."], ["Al final todos limpiaron la sala.", "In the end everyone cleaned the room."]], question: { prompt: "Which form could also be present without the time context?", options: ["cocinamos", "compré", "preparó"], answer: 0, feedback: "Regular -ar nosotros looks the same in present and preterite; context resolves it." } },
    recall: [
      { before: "Yo ", after: " con Ana. (hablar, past)", answer: "hablé", accepted: ["hablé", "hable"], feedback: "The yo preterite ending is accented -é." },
      { before: "Ella ", after: " ayer. (trabajar)", answer: "trabajó", accepted: ["trabajó", "trabajo"], feedback: "One third person uses accented -ó." },
      { before: "Ellos ", after: " la cena. (preparar)", answer: "prepararon", feedback: "Plural third person uses -aron." },
    ],
    production: { prompt: "Write a completed eight-action event using every regular -ar preterite ending represented in this course.", requirements: ["Use yo, tú, one third person, nosotros, and plural third person", "Keep accents on -é/-ó", "Order the events"], example: "Llegué temprano. Tú preparaste café. Ana organizó la sala. Hablamos y todos ayudaron." },
    takeaway: "Remove -ar and use -é, -aste, -ó, -amos, or -aron; preserve accents and let context resolve nosotros.",
  }),
  createCourseLesson({
    id: "15.3", title: "Regular Preterite: ER/IR", displayTitle: "ER and IR verbs share one completed-event pattern.",
    dek: "-í, -iste, -ió, -imos, and -ieron carry both families in the regular preterite.",
    goal: "Form and use regular -er and -ir preterite verbs.", durationMinutes: 28, concepts: ["preterite_er_ir"],
    explain: [
      "Regular -er and -ir verbs share preterite endings: -í, -iste, -ió, -imos, -ieron. Comer becomes comí, comiste, comió, comimos, comieron; vivir becomes viví, viviste, vivió, vivimos, vivieron.",
      "Yo and one third-person singular retain written accents. Regular -ir nosotros again matches its present form—vivimos—so past-time context such as el año pasado or ayer is decisive.",
    ],
    examples: [["Comí con Ana.", "I ate with Ana."], ["Elena escribió el mensaje.", "Elena wrote the message."], ["Vivimos allí en 2020.", "We lived there in 2020."]],
    boundary: { heading: "ER and IR differ in the present but converge in the preterite.", note: "One ending set reduces the new load.",
      left: { label: "ER", question: "Does the infinitive end in -er?", description: "Attach the shared i-family endings.", example: ["comer → comieron", "to eat → they ate"] },
      right: { label: "IR", question: "Does the infinitive end in -ir?", description: "Attach the same shared endings.", example: ["vivir → vivieron", "to live → they lived"] } },
    prediction: { heading: "Conjugate escribir for ella.", context: "The message was completed yesterday.", prompt: "Which form uses -ió?", options: ["escribió", "escribí", "escribía"], answer: 0, correct: "One third-person regular -ir preterite uses -ió.", incorrect: "Remove -ir and add accented -ió." },
    guided: { heading: "Conjugate comer for ellos.", context: "The group finished dinner.", prompt: "Which shared plural ending fits?", options: ["comieron", "comeron", "comían"], answer: 0, correct: "Regular -er/-ir plural third person uses -ieron.", incorrect: "Attach the shared ending -ieron: comieron." },
    builder: { prompt: "Build: Last year we lived in Mexico.", tokens: ["El año pasado", "vivimos", "en México."], correctOrder: ["El año pasado", "vivimos", "en México."], answer: "El año pasado vivimos en México.", feedback: "The time phrase makes the otherwise ambiguous vivimos clearly past." },
    reading: { heading: "After the assignment.", sentences: [["Ayer escribimos un ensayo.", "Yesterday we wrote an essay."], ["Después comí con mis compañeros.", "Afterward I ate with my classmates."], ["Ana recibió una buena noticia.", "Ana received good news."], ["Todos aprendieron mucho.", "Everyone learned a lot."]], question: { prompt: "Who received good news?", options: ["Ana", "the speaker", "everyone"], answer: 0, feedback: "Ana recibió names the recipient of the completed event." } },
    recall: [
      { before: "Yo ", after: " temprano. (comer, past)", answer: "comí", accepted: ["comí", "comi"], feedback: "Yo uses accented -í." },
      { before: "Ella ", after: " una carta. (escribir)", answer: "escribió", accepted: ["escribió", "escribio"], feedback: "One third person uses -ió." },
      { before: "Ellos ", after: " aquí. (vivir)", answer: "vivieron", feedback: "Plural third person uses -ieron." },
    ],
    production: { prompt: "Write an eight-event completed sequence using both ER and IR verbs across five subject forms.", requirements: ["Use both verb families", "Preserve -í and -ió accents", "Include a time phrase with nosotros"], example: "Ayer comí temprano. Tú escribiste. Ana recibió un mensaje. Vivimos allí un año. Ellos aprendieron mucho." },
    takeaway: "Regular ER and IR verbs share -í, -iste, -ió, -imos, and -ieron in the preterite.",
  }),
  createCourseLesson({
    id: "15.4", title: "Essential Irregular Preterites", displayTitle: "Irregular preterite stems use one compact set of unaccented endings.",
    dek: "Tuv-, estuv-, pud-, pus-, sup-, quis-, vin-, hic-, dij-, traj-, and fu- carry high-frequency completed events.",
    goal: "Use the most important irregular preterite stems and endings in context.", durationMinutes: 31, concepts: ["preterite_irregular"],
    explain: [
      "Most strong irregulars use -e, -iste, -o, -imos, -ieron without written accents: tuve, tuviste, tuvo, tuvimos, tuvieron. Common stems include estuv-, pud-, pus-, sup-, quis-, vin-, anduv-, dij-, traj-, and hic- (with hizo in third-person singular).",
      "Ser and ir share fui, fuiste, fue, fuimos, fueron; context reveals whether the meaning is was or went. Decir and traer use -eron rather than -ieron after their j stems: dijeron, trajeron. Learn the stem through useful messages, not an isolated list.",
    ],
    examples: [["Tuve tiempo.", "I had time."], ["Ana hizo la cena.", "Ana made dinner."], ["Fuimos al museo.", "We went to the museum."]],
    boundary: { heading: "Strong irregular endings are unaccented.", note: "The irregular stem already carries the stress pattern.",
      left: { label: "REGULAR", question: "Does the verb keep its regular stem?", description: "Yo and third singular often carry written accents.", example: ["hablé / habló", "I spoke / she spoke"] },
      right: { label: "STRONG IRREGULAR", question: "Does it use a special preterite stem?", description: "Use the unaccented irregular ending set.", example: ["tuve / tuvo", "I had / she had"] } },
    prediction: { heading: "Use the hacer third-person form.", context: "Ana made dinner yesterday.", prompt: "Which preterite form is correct?", options: ["hizo", "hico", "hació"], answer: 0, correct: "Hacer uses hizo in third-person singular.", incorrect: "The irregular preterite form is hizo." },
    guided: { heading: "Interpret fue from context.", context: "Ana fue al museo names a destination with al.", prompt: "What does fue mean here?", options: ["went", "was", "did"], answer: 0, correct: "The destination phrase al museo selects the ir meaning went.", incorrect: "Because a destination follows, fue comes from ir here." },
    builder: { prompt: "Build: They brought the food and put it on the table.", tokens: ["Trajeron", "la comida", "y la pusieron", "en la mesa."], correctOrder: ["Trajeron", "la comida", "y la pusieron", "en la mesa."], answer: "Trajeron la comida y la pusieron en la mesa.", feedback: "Traer uses trajeron; poner uses the irregular stem pus- plus -ieron." },
    reading: { heading: "A difficult trip.", sentences: [["Ayer fuimos al aeropuerto.", "Yesterday we went to the airport."], ["Tuvimos un problema con los boletos.", "We had a problem with the tickets."], ["La empleada pudo ayudarnos.", "The employee was able to help us."], ["Al final hicimos el viaje.", "In the end we made the trip."]], question: { prompt: "Who succeeded in helping?", options: ["the employee", "the travelers", "nobody"], answer: 0, feedback: "Pudo in this completed context presents successful ability." } },
    recall: [
      { before: "Yo ", after: " tiempo. (tener, past)", answer: "tuve", feedback: "Tener uses tuv- + -e." },
      { before: "Ana ", after: " la cena. (hacer, past)", answer: "hizo", feedback: "The third-person form is hizo." },
      { before: "Ellos ", after: " la verdad. (decir, past)", answer: "dijeron", feedback: "The j-stem uses -eron: dijeron." },
    ],
    production: { prompt: "Write a ten-event past account using at least eight essential irregular preterite verbs.", requirements: ["Use strong irregular stems", "Keep their endings unaccented", "Make fui/fue meaning clear from context"], example: "Fui al centro. Tuve un problema. Pude llamar. Ana vino, trajo ayuda y puso todo en orden. Después hicimos la tarea." },
    takeaway: "Learn the irregular stem, add -e/-iste/-o/-imos/-ieron without accents, and use context to interpret shared fui/fue forms.",
  }),
  createCourseLesson({
    id: "15.5", title: "Spelling & Stem Changes", displayTitle: "Past spelling changes preserve sound; IR stem changes stay limited.",
    dek: "Yo spelling shifts and third-person IR changes protect pronunciation while keeping the event completed.",
    goal: "Apply common preterite spelling and third-person stem changes.", durationMinutes: 29, concepts: ["preterite_spelling"],
    explain: [
      "In the yo preterite, -car changes c→qu, -gar changes g→gu, and -zar changes z→c before é: busqué, llegué, empecé. These are spelling adjustments that preserve the infinitive’s sound, not new meanings.",
      "Some -ir stem-changing verbs change only in third-person preterite forms and reduce the change: pedir → pidió/pidieron; dormir → durmió/durmieron. Other forms use the regular stem: pedí, pediste, pedimos.",
    ],
    examples: [["Busqué el libro.", "I looked for the book."], ["Llegué temprano.", "I arrived early."], ["Ellos pidieron café.", "They ordered coffee."]],
    boundary: { heading: "Spelling protection and stem change occur in different places.", note: "Identify the infinitive ending and subject before applying either pattern.",
      left: { label: "YO SPELLING", question: "Does -car/-gar/-zar meet accented é?", description: "Change spelling only to preserve sound.", example: ["buscar → busqué", "to look for → I looked for"] },
      right: { label: "IR THIRD PERSON", question: "Is it an eligible -ir verb in third person?", description: "Use e→i or o→u in singular/plural third person.", example: ["dormir → durmieron", "to sleep → they slept"] } },
    prediction: { heading: "Preserve the hard g sound.", context: "The yo preterite of llegar ends in -é.", prompt: "Which spelling is correct?", options: ["llegué", "llegé", "llegó"], answer: 0, correct: "Gu preserves the hard g sound before é.", incorrect: "Use g→gu before é: llegué." },
    guided: { heading: "Apply an IR third-person change.", context: "The subject is ellos and the verb is pedir.", prompt: "Which completed form fits?", options: ["pidieron", "pedieron", "piedieron"], answer: 0, correct: "Pedir changes e→i in the third-person plural preterite.", incorrect: "Eligible -ir verbs use the reduced e→i change: pidieron." },
    builder: { prompt: "Build: I began the class and they repeated the question.", tokens: ["Empecé", "la clase", "y ellos repitieron", "la pregunta."], correctOrder: ["Empecé", "la clase", "y ellos repitieron", "la pregunta."], answer: "Empecé la clase y ellos repitieron la pregunta.", feedback: "Empezar changes z→c before é; repetir changes e→i in third-person plural." },
    reading: { heading: "At the restaurant.", sentences: [["Llegué al restaurante a las ocho.", "I arrived at the restaurant at eight."], ["Busqué una mesa tranquila.", "I looked for a quiet table."], ["Mis amigos pidieron la cena.", "My friends ordered dinner."], ["Después todos durmieron bien.", "Afterward everyone slept well."]], question: { prompt: "Which form preserves a hard c sound through qu?", options: ["busqué", "llegué", "pidieron"], answer: 0, feedback: "Buscar changes c→qu before the yo ending é." } },
    recall: [
      { before: "Yo ", after: " temprano. (llegar, past)", answer: "llegué", accepted: ["llegué", "llegue"], feedback: "G→gu preserves the sound before é." },
      { before: "Yo ", after: " a las nueve. (empezar, past)", answer: "empecé", accepted: ["empecé", "empece"], feedback: "Z→c before é produces empecé." },
      { before: "Ellos ", after: " ocho horas. (dormir, past)", answer: "durmieron", feedback: "Dormir changes o→u in third-person plural preterite." },
    ],
    production: { prompt: "Write six completed events using two -car, two -gar/-zar, and two third-person stem-changing IR verbs.", requirements: ["Preserve sound in yo spelling", "Limit IR changes to third person", "Keep all events clearly completed"], example: "Busqué el libro. Practiqué. Llegué temprano. Empecé. Ana pidió café. Ellos durmieron." },
    takeaway: "Protect pronunciation with yo spelling changes, and limit reduced IR stem changes to third-person preterite forms.",
  }),
  createCourseLesson({
    id: "15.6", title: "Telling What Happened", displayTitle: "A preterite narrative is a chain of completed changes.",
    dek: "Sequence markers, varied subjects, objects, and pronouns turn forms into a comprehensible event line.",
    goal: "Narrate a coherent sequence of completed past events with regular and irregular preterites.", durationMinutes: 32, concepts: ["preterite_narration", "preterite_ar", "preterite_er_ir", "preterite_irregular", "preterite_spelling"],
    explain: [
      "A completed-event narrative answers what happened next. Use primero, luego, después, entonces, de repente, and al final to make the sequence visible, but let each verb carry a meaningful change: llegué, vi, hablé, decidimos, fuimos.",
      "Pronouns prevent needless repetition: Vi a Ana y la saludé. Time phrases anchor the scene, while preterite verbs advance it. The imperfect in Module 16 will later supply background; for now, keep the event line clear and bounded.",
    ],
    examples: [["Primero llegué a la plaza.", "First I arrived at the plaza."], ["Vi a Ana y la saludé.", "I saw Ana and greeted her."], ["Al final fuimos a comer.", "In the end we went to eat."]],
    boundary: { heading: "A list of forms is not yet a story.", note: "Events must change the situation and connect causally or temporally.",
      left: { label: "ISOLATED", question: "Are events merely listed?", description: "Correct verbs without relationships feel disconnected.", example: ["Llegué. Comí. Salí.", "I arrived. I ate. I left."] },
      right: { label: "CONNECTED", question: "Does each event lead to the next?", description: "Use sequence, reference, and consequence.", example: ["Llegué tarde, así que comí rápido y salí.", "I arrived late, so I ate quickly and left."] } },
    prediction: { heading: "Advance the sequence.", context: "The speaker arrived, saw Ana, and next greeted her.", prompt: "Which continuation preserves reference and completion?", options: ["La saludé.", "Le saludar.", "La saludaba siempre."], answer: 0, correct: "La replaces Ana as direct object and saludé advances the completed sequence.", incorrect: "Use the direct object pronoun la and the completed yo form saludé." },
    guided: { heading: "Close the event line.", context: "A story needs an explicit final event.", prompt: "Which marker and verb provide closure?", options: ["Al final regresamos a casa.", "Mientras en casa.", "Siempre regresar."], answer: 0, correct: "Al final plus regresamos supplies a completed endpoint.", incorrect: "Use a sequence marker and a conjugated completed event." },
    builder: { prompt: "Build: Suddenly it rained, so we returned home.", tokens: ["De repente", "llovió,", "así que", "regresamos a casa."], correctOrder: ["De repente", "llovió,", "así que", "regresamos a casa."], answer: "De repente llovió, así que regresamos a casa.", feedback: "The sudden event causes the completed response." },
    reading: { heading: "A surprising afternoon.", sentences: [["Ayer fui al centro con Ana.", "Yesterday I went downtown with Ana."], ["Primero compramos un regalo.", "First we bought a gift."], ["Después vimos a Carlos y lo invitamos a comer.", "Afterward we saw Carlos and invited him to eat."], ["De repente empezó a llover, así que entramos en un café.", "Suddenly it began to rain, so we entered a café."], ["Al final pasamos tres horas hablando.", "In the end we spent three hours talking."]], question: { prompt: "What caused the group to enter a café?", options: ["It began to rain", "They bought a gift", "They saw Carlos"], answer: 0, feedback: "Así que links the rain to the completed decision to enter the café." } },
    recall: [
      { before: "Ayer ", after: " al centro. (I went)", answer: "fui", feedback: "Fui from ir begins the completed sequence." },
      { before: "Vimos a Carlos y ", after: " invitamos. (him)", answer: "lo", feedback: "Lo replaces Carlos as the direct object." },
      { before: "De repente ", after: " a llover. (began)", answer: "empezó", accepted: ["empezó", "empezo"], feedback: "Empezó presents the sudden completed onset." },
    ],
    production: { prompt: "Tell a twelve-event story about a completed day, using sequence, one cause/result, regular and irregular verbs, and object pronouns.", requirements: ["At least twelve bounded events", "At least four sequence connectors", "Two pronoun references and one cause/result link"], example: "Ayer fui al centro. Primero compré café. Vi a Ana y la saludé. Después hablamos. De repente llovió, así que entramos. Al final regresamos." },
    takeaway: "Make each preterite event change the situation, connect it to what came before, and keep known people or things active through pronouns.",
  }),
];
