import { createCourseLesson } from "./course-lesson-factory";

export const module16LessonDefinitions = [
  createCourseLesson({
    id: "16.1", title: "The Other Past Tense", displayTitle: "The imperfect presents a past world from the inside.",
    dek: "Background, ongoing conditions, habits, and descriptions stay open while events unfold.",
    goal: "Recognize the imperfect as an unbounded past viewpoint rather than a second translation of was/were.", durationMinutes: 28, concepts: ["imperfect_function"],
    explain: [
      "The imperfect presents a past situation without focusing on its endpoint: Vivía en Cuba; Hacía calor; Eran las ocho. It builds the world that was already in progress, habitual, descriptive, or relevant as background.",
      "Preterite and imperfect are viewpoints, not objective event categories. Viví en Cuba diez años views the period as completed; Vivía en Cuba cuando conocí a Ana places the listener inside that ongoing residence when another event occurs.",
    ],
    examples: [["Vivía en Cuba.", "I was living in Cuba."], ["Hacía calor.", "It was hot."], ["Eran las ocho.", "It was eight o’clock."]],
    boundary: { heading: "A finished whole and an inside view can describe the same real period.", note: "The speaker chooses the perspective needed by the story.",
      left: { label: "PRETERITE", question: "Is the period bounded as a whole?", description: "Present the completed span and its endpoint.", example: ["Viví allí diez años.", "I lived there for ten years."] },
      right: { label: "IMPERFECT", question: "Is the period background to another moment?", description: "Place the listener inside the ongoing past situation.", example: ["Vivía allí cuando llamó Ana.", "I was living there when Ana called."] } },
    prediction: { heading: "Create background.", context: "The story opens by describing the weather before anything happens.", prompt: "Which sentence gives that open background?", options: ["Hacía frío.", "Hizo frío ayer por una hora.", "Hace frío ayer."], answer: 0, correct: "Hacía frío presents the weather as background.", incorrect: "Use imperfect hacía for an open past condition." },
    guided: { heading: "View a residence from inside.", context: "The speaker was living in Mexico when they met Carlos.", prompt: "Which form provides the background?", options: ["Vivía en México", "Viví en México diez años", "Vivo en México"], answer: 0, correct: "Vivía places the listener inside the residence when the event occurs.", incorrect: "Use the imperfect for the ongoing background situation." },
    builder: { prompt: "Build: It was late and everyone was tired.", tokens: ["Era tarde", "y todos", "estaban cansados."], correctOrder: ["Era tarde", "y todos", "estaban cansados."], answer: "Era tarde y todos estaban cansados.", feedback: "Both clauses describe the background condition." },
    reading: { heading: "Before the phone rang.", sentences: [["Era una noche tranquila.", "It was a quiet night."], ["Hacía frío y llovía.", "It was cold and raining."], ["Yo estudiaba en mi cuarto.", "I was studying in my room."], ["De repente sonó el teléfono.", "Suddenly the phone rang."]], question: { prompt: "Which line moves the story out of background and into an event?", options: ["Sonó el teléfono", "Hacía frío", "Yo estudiaba"], answer: 0, feedback: "The preterite sonó marks the completed event that interrupts the background." } },
    recall: [
      { before: "", after: " frío. (It was; background weather)", answer: "Hacía", accepted: ["hacía", "hacia"], feedback: "Imperfect hacía describes background weather." },
      { before: "Yo ", after: " en Cuba cuando llamó Ana. (was living)", answer: "vivía", accepted: ["vivía", "vivia"], feedback: "Vivía provides the ongoing background." },
      { before: "", after: " las ocho. (It was eight)", answer: "Eran", accepted: ["eran"], feedback: "Past clock time uses imperfect eran." },
    ],
    production: { prompt: "Open a past story with six background sentences about time, weather, place, people, emotions, and an ongoing action.", requirements: ["No completed event yet", "Use at least four imperfect verbs", "Create one coherent scene"], example: "Eran las ocho. Hacía frío. Estábamos en casa. Ana estaba cansada. Yo leía y ella escuchaba música." },
    takeaway: "Use the imperfect to place the listener inside an open past situation that describes, repeats, or remains in progress.",
  }),
  createCourseLesson({
    id: "16.2", title: "Forming the Imperfect", displayTitle: "Two regular ending sets and three irregular verbs build the imperfect.",
    dek: "AR verbs use -aba; ER/IR verbs use -ía; ser, ir, and ver stand apart.",
    goal: "Form regular and irregular imperfect verbs for the course subject system.", durationMinutes: 29, concepts: ["imperfect_forms"],
    explain: [
      "Regular -ar endings are -aba, -abas, -aba, -ábamos, -aban: hablaba, hablabas, hablábamos. Regular -er/-ir endings are -ía, -ías, -ía, -íamos, -ían: comía, vivías, escribíamos. The í accents remain in every form; -ábamos carries its own accent.",
      "Only three verbs are fully irregular: ser → era, eras, era, éramos, eran; ir → iba, ibas, iba, íbamos, iban; ver → veía, veías, veía, veíamos, veían. Subject pronouns remain optional when context is clear.",
    ],
    examples: [["Hablábamos cada día.", "We used to speak every day."], ["Ana vivía aquí.", "Ana used to live here."], ["Íbamos al parque.", "We used to go to the park."]],
    boundary: { heading: "AR and ER/IR remain separate in the imperfect.", note: "Unlike the preterite, ER and IR share while AR keeps aba.",
      left: { label: "AR", question: "Does the infinitive end in -ar?", description: "Use the aba ending set.", example: ["trabajar → trabajaba", "to work → was working"] },
      right: { label: "ER/IR", question: "Does it end in -er or -ir?", description: "Use the accented ía ending set.", example: ["vivir → vivía", "to live → was living"] } },
    prediction: { heading: "Conjugate hablar for nosotros.", context: "The action was habitual in the past.", prompt: "Which form keeps the written accent?", options: ["hablábamos", "hablabamos", "hablían"], answer: 0, correct: "Nosotros -ar imperfect uses -ábamos.", incorrect: "Remove -ar and add accented -ábamos." },
    guided: { heading: "Use irregular ir.", context: "They used to go to the park.", prompt: "Which form agrees with ellos?", options: ["iban", "ían", "fueron"], answer: 0, correct: "The irregular imperfect of ir uses iban.", incorrect: "Ir has the irregular imperfect set iba, ibas, iba, íbamos, iban." },
    builder: { prompt: "Build: We used to see our friends every week.", tokens: ["Veíamos", "a nuestros amigos", "cada semana."], correctOrder: ["Veíamos", "a nuestros amigos", "cada semana."], answer: "Veíamos a nuestros amigos cada semana.", feedback: "Ver uses the irregular-looking but related imperfect veíamos." },
    reading: { heading: "A childhood summer.", sentences: [["Cada verano íbamos a Cuba.", "Every summer we used to go to Cuba."], ["Vivíamos con mis abuelos.", "We lived with my grandparents."], ["Mi abuelo preparaba el desayuno.", "My grandfather used to prepare breakfast."], ["Por la tarde veíamos a nuestros primos.", "In the afternoon we used to see our cousins."]], question: { prompt: "Which imperfect verb comes from ser, ir, or ver?", options: ["íbamos and veíamos", "vivíamos only", "preparaba only"], answer: 0, feedback: "Íbamos comes from irregular ir and veíamos from ver." } },
    recall: [
      { before: "Nosotros ", after: " español. (hablar, imperfect)", answer: "hablábamos", accepted: ["hablábamos", "hablabamos"], feedback: "AR nosotros uses -ábamos." },
      { before: "Ella ", after: " aquí. (vivir, imperfect)", answer: "vivía", accepted: ["vivía", "vivia"], feedback: "ER/IR singular uses -ía." },
      { before: "Ellos ", after: " al parque. (ir, imperfect)", answer: "iban", feedback: "Ir uses the irregular form iban." },
    ],
    production: { prompt: "Create a complete imperfect chart in meaningful sentences for one AR, one ER, one IR, and the irregular verbs ser, ir, and ver.", requirements: ["Use every course subject form", "Preserve all written accents", "Keep contexts habitual or descriptive"], example: "Yo hablaba; tú hablabas; Ana hablaba; hablábamos; ellos hablaban. Era tarde. Íbamos al parque. Veíamos amigos." },
    takeaway: "Use aba endings for AR, accented ía endings for ER/IR, and learn era, iba, and veía as the three irregular anchors.",
  }),
  createCourseLesson({
    id: "16.3", title: "What Things Used to Be Like", displayTitle: "Description gives a past scene texture before events change it.",
    dek: "The imperfect describes people, places, time, weather, age, and conditions as part of the story world.",
    goal: "Create rich past descriptions with ser, estar, tener, haber, and descriptive verbs.", durationMinutes: 29, concepts: ["imperfect_description"],
    explain: [
      "Use imperfect forms to describe what people and places were like: La casa era pequeña; las ventanas estaban abiertas; había un jardín. Age uses tener—Tenía diez años—and clock time uses ser—Eran las tres.",
      "Descriptions are not less important than events. They establish what the listener needs to understand later changes. Agreement remains active: calles tranquilas, amigos contentos, puertas abiertas.",
    ],
    examples: [["La casa era pequeña.", "The house was small."], ["Había un jardín grande.", "There was a large garden."], ["Yo tenía diez años.", "I was ten years old."]],
    boundary: { heading: "Existence and location remain distinct in the past.", note: "The hay/estar distinction becomes había/estaba.",
      left: { label: "HABÍA", question: "What existed in the scene?", description: "Introduce existence with impersonal había.", example: ["Había un parque.", "There was a park."] },
      right: { label: "ESTABA", question: "Where was the identified thing?", description: "Locate it with estar in the imperfect.", example: ["El parque estaba cerca.", "The park was nearby."] } },
    prediction: { heading: "Introduce something in the past scene.", context: "A large tree existed beside the house.", prompt: "Which verb introduces it?", options: ["Había un árbol grande.", "Estaba un árbol grande.", "Fue un árbol grande."], answer: 0, correct: "Impersonal había introduces what existed.", incorrect: "Use había to introduce existence in a past scene." },
    guided: { heading: "State a past age.", context: "The speaker was eight years old.", prompt: "Which structure preserves Spanish age logic?", options: ["Tenía ocho años.", "Era ocho años.", "Estaba ocho."], answer: 0, correct: "Age continues to use tener, here in imperfect tenía.", incorrect: "Use imperfect tener + number + años." },
    builder: { prompt: "Build: The streets were quiet and there were many trees.", tokens: ["Las calles", "eran tranquilas", "y había", "muchos árboles."], correctOrder: ["Las calles", "eran tranquilas", "y había", "muchos árboles."], answer: "Las calles eran tranquilas y había muchos árboles.", feedback: "Eran describes identified streets; había introduces the trees." },
    reading: { heading: "The neighborhood before.", sentences: [["Mi barrio era pequeño y tranquilo.", "My neighborhood was small and quiet."], ["Había una plaza en el centro.", "There was a plaza downtown."], ["La escuela estaba cerca de mi casa.", "The school was near my house."], ["Yo tenía nueve años y mis amigos eran muy curiosos.", "I was nine and my friends were very curious."]], question: { prompt: "What does estaba do in the third line?", options: ["locates the identified school", "introduces a new school", "states the speaker’s age"], answer: 0, feedback: "La escuela is identified and estaba locates it." } },
    recall: [
      { before: "La casa ", after: " pequeña. (was)", answer: "era", feedback: "Ser in imperfect describes what the house was like." },
      { before: "", after: " un parque. (There was)", answer: "Había", accepted: ["había", "habia"], feedback: "Había introduces existence in the past." },
      { before: "Yo ", after: " diez años. (was age ten)", answer: "tenía", accepted: ["tenía", "tenia"], feedback: "Past age uses imperfect tener." },
    ],
    production: { prompt: "Describe a childhood home, school, or neighborhood in eight sentences before narrating any event.", requirements: ["Use era/estaba/había/tenía", "Include time or weather", "Maintain noun/adjective agreement"], example: "La casa era pequeña. Estaba cerca del parque. Había tres habitaciones. Yo tenía ocho años. Las calles eran tranquilas." },
    takeaway: "Use the imperfect to build a past scene through identity, condition, existence, location, age, time, weather, and agreement.",
  }),
  createCourseLesson({
    id: "16.4", title: "Habits & Ongoing Background", displayTitle: "Repeated and in-progress past actions create patterns behind the event line.",
    dek: "Cada día, siempre, mientras, and a menudo invite the listener into recurring or ongoing past activity.",
    goal: "Describe past habits and actions in progress with the imperfect.", durationMinutes: 28, concepts: ["imperfect_habit"],
    explain: [
      "Use the imperfect for repeated past patterns whose individual endpoints are not the focus: Cada verano viajábamos; Siempre comía con mi familia. Frequency expressions support the habitual view but do not mechanically force a tense.",
      "Mientras often coordinates simultaneous background actions: Mientras yo estudiaba, Ana cocinaba. A completed event can enter that open scene: Mientras estudiaba, sonó el teléfono. The ongoing action uses imperfect; the interrupting event uses preterite.",
    ],
    examples: [["Cada verano viajábamos.", "Every summer we used to travel."], ["Siempre comía con mi familia.", "I always ate with my family."], ["Mientras estudiaba, sonó el teléfono.", "While I was studying, the phone rang."]],
    boundary: { heading: "Ongoing background and interrupting event do different work.", note: "The word mientras opens the scene; aspect chooses how each action is viewed.",
      left: { label: "ONGOING", question: "What was already in progress?", description: "Use the imperfect for the open activity.", example: ["Estudiaba…", "I was studying…"] },
      right: { label: "EVENT", question: "What happened inside that activity?", description: "Use the preterite for the bounded change.", example: ["…cuando sonó el teléfono.", "…when the phone rang."] } },
    prediction: { heading: "Express a past habit.", context: "Every Saturday the family visited the grandparents.", prompt: "Which form presents the repeated pattern?", options: ["Visitábamos a mis abuelos.", "Visitamos una vez.", "Visitaremos."], answer: 0, correct: "Visitábamos presents the repeated past habit.", incorrect: "Use imperfect for the recurring pattern." },
    guided: { heading: "Separate background from interruption.", context: "Ana was cooking when Carlos arrived.", prompt: "Which tense pairing fits?", options: ["Ana cocinaba cuando Carlos llegó.", "Ana cocinó cuando Carlos llegaba always.", "Ana cocina cuando Carlos llegó."], answer: 0, correct: "Cocinaba is ongoing background; llegó is the bounded arrival.", incorrect: "Use imperfect for what was in progress and preterite for the interrupting event." },
    builder: { prompt: "Build: While we studied, our friends prepared dinner.", tokens: ["Mientras", "estudiábamos,", "nuestros amigos", "preparaban la cena."], correctOrder: ["Mientras", "estudiábamos,", "nuestros amigos", "preparaban la cena."], answer: "Mientras estudiábamos, nuestros amigos preparaban la cena.", feedback: "Both simultaneous actions remain open background, so both use imperfect." },
    reading: { heading: "Summer habits.", sentences: [["Cada verano visitábamos a mis abuelos.", "Every summer we visited my grandparents."], ["Por la mañana mi abuelo hacía café.", "In the morning my grandfather made coffee."], ["Mientras él cocinaba, nosotros jugábamos afuera.", "While he cooked, we played outside."], ["Un día empezó a llover y todos entramos.", "One day it began to rain and we all went inside."]], question: { prompt: "Which line changes from habitual background to a specific event?", options: ["Un día empezó a llover", "Cada verano visitábamos", "Mientras él cocinaba"], answer: 0, feedback: "Un día and the preterite mark a specific bounded change." } },
    recall: [
      { before: "Cada verano ", after: " a Cuba. (we used to travel)", answer: "viajábamos", accepted: ["viajábamos", "viajabamos"], feedback: "The repeated summer pattern uses imperfect." },
      { before: "Mientras yo ", after: ", Ana cocinaba. (study)", answer: "estudiaba", feedback: "Two simultaneous open actions use imperfect." },
      { before: "Estudiaba cuando ", after: " el teléfono. (rang)", answer: "sonó", accepted: ["sonó", "sono"], feedback: "The bounded ringing event uses preterite." },
    ],
    production: { prompt: "Write a ten-sentence portrait of past habits, then add one specific event that interrupts the pattern.", requirements: ["At least six imperfect habits/background actions", "One mientras pairing", "A clear preterite interruption"], example: "Cada verano viajábamos. Siempre comíamos juntos. Mientras mi abuelo cocinaba, jugábamos. Un día sonó el teléfono y todo cambió." },
    takeaway: "Use imperfect for recurring or in-progress past patterns and preterite for the bounded event that enters or changes them.",
  }),
  createCourseLesson({
    id: "16.5", title: "Preterite vs. Imperfect", displayTitle: "The past tense choice is a storytelling decision about viewpoint.",
    dek: "Preterite moves the event line; imperfect builds the world, habits, and ongoing conditions around it.",
    goal: "Choose between preterite and imperfect from the narrative job of each verb.", durationMinutes: 32, concepts: ["preterite_imperfect", "preterite_function", "imperfect_function"],
    explain: [
      "Use the preterite for bounded events that begin, end, occur, or change the story. Use the imperfect for background description, time, age, weather, habitual patterns, and actions viewed in progress. Both can describe real past actions; the viewpoint creates the difference.",
      "Do not reduce the contrast to completed versus incomplete in reality. Supe la verdad means I found out/came to know; sabía la verdad means I knew it as an ongoing state. Quise can present an attempted/intended bounded event; quería presents an ongoing desire.",
    ],
    examples: [["Llovía cuando llegué.", "It was raining when I arrived."], ["Sabía la verdad.", "I knew the truth."], ["Supe la verdad ayer.", "I found out the truth yesterday."]],
    boundary: { heading: "The same verb can change interpretation with viewpoint.", note: "Aspect shapes how the listener enters the situation.",
      left: { label: "IMPERFECT", question: "State or ongoing perspective?", description: "Present knowledge, desire, or ability from inside.", example: ["Conocía a Ana.", "I knew Ana."] },
      right: { label: "PRETERITE", question: "Change or bounded realization?", description: "Present becoming acquainted or finding out as an event.", example: ["Conocí a Ana ayer.", "I met Ana yesterday."] } },
    prediction: { heading: "Place arrival inside weather.", context: "Rain was already in progress when the speaker arrived.", prompt: "Which pairing shows background plus event?", options: ["Llovía cuando llegué.", "Llovió cuando llegaba always.", "Llueve cuando llegué."], answer: 0, correct: "Llovía supplies background; llegué advances the event line.", incorrect: "Use imperfect for ongoing weather and preterite for the bounded arrival." },
    guided: { heading: "Express finding out.", context: "Yesterday the speaker learned the truth at a specific moment.", prompt: "Which form presents that change in knowledge?", options: ["Supe la verdad ayer.", "Sabía la verdad ayer desde siempre.", "Sé la verdad ayer."], answer: 0, correct: "Supe presents the bounded realization/finding out.", incorrect: "Use preterite supe for the event of coming to know." },
    builder: { prompt: "Build: We were eating when Ana called.", tokens: ["Comíamos", "cuando", "Ana llamó."], correctOrder: ["Comíamos", "cuando", "Ana llamó."], answer: "Comíamos cuando Ana llamó.", feedback: "Comíamos is the open activity; llamó is the completed event." },
    reading: { heading: "The unexpected visitor.", sentences: [["Era tarde y hacía frío.", "It was late and cold."], ["Yo leía mientras Ana cocinaba.", "I was reading while Ana cooked."], ["De repente alguien tocó la puerta.", "Suddenly someone knocked on the door."], ["Abrimos y vimos a Carlos.", "We opened it and saw Carlos."], ["No sabíamos que venía.", "We did not know he was coming."]], question: { prompt: "Which verbs advance the event line?", options: ["tocó, abrimos, vimos", "era, hacía, leía", "sabíamos, venía"], answer: 0, feedback: "The preterite sequence marks the knock, opening, and seeing as bounded events." } },
    recall: [
      { before: "", after: " cuando llegué. (It was raining)", answer: "Llovía", accepted: ["llovía", "llovia"], feedback: "The weather is ongoing background." },
      { before: "Ayer ", after: " la verdad. (I found out)", answer: "supe", feedback: "Supe presents the bounded change in knowledge." },
      { before: "Cuando era niño, ", after: " al parque cada día. (I used to go)", answer: "iba", feedback: "A repeated childhood habit uses imperfect iba." },
    ],
    production: { prompt: "Write a twelve-sentence story that alternates scene-building imperfects and event-line preterites intentionally.", requirements: ["Time/weather/description background", "One habitual past pattern", "At least five bounded events and one interpretation-changing verb"], example: "Era tarde y llovía. Yo estudiaba cuando sonó el teléfono. Contesté y supe la noticia. Antes no sabía nada. Salí y fui a casa de Ana." },
    takeaway: "Choose preterite to move through bounded changes and imperfect to keep the listener inside background, habit, description, or ongoing state.",
  }),
  createCourseLesson({
    id: "16.6", title: "Pronouns Working Together", displayTitle: "Indirect and direct object pronouns form one ordered unit.",
    dek: "The recipient comes first, the thing second, and le/les becomes se before lo/la/los/las.",
    goal: "Combine indirect and direct object pronouns in present and past sentences.", durationMinutes: 30, concepts: ["combined_pronouns", "indirect_object_pronouns", "direct_object_pronouns"],
    explain: [
      "When both objects are pronouns, the order is indirect then direct: me lo, te la, nos los. Le or les changes to se before lo, la, los, or las: Le di el libro → Se lo di. The se here is not reflexive; it replaces le to avoid le lo.",
      "The pronoun unit goes before a conjugated verb or attaches to an infinitive: Se lo quiero dar = Quiero dárselo. With a completed past verb, placement remains before: Se lo di ayer.",
    ],
    examples: [["Ana me lo dio.", "Ana gave it to me."], ["Se la enviamos.", "We sent it to him/her/them."], ["Quiero dárselo.", "I want to give it to him/her/them."]],
    boundary: { heading: "Se can be reflexive or a changed recipient pronoun.", note: "The second pronoun and sentence meaning reveal its role.",
      left: { label: "REFLEXIVE SE", question: "Does the action return to the subject?", description: "Se refers back to the subject.", example: ["Ana se prepara.", "Ana gets ready."] },
      right: { label: "RECIPIENT SE", question: "Does lo/la/los/las follow?", description: "Se replaces le/les before a direct object pronoun.", example: ["Ana se lo da.", "Ana gives it to him/her/them."] } },
    prediction: { heading: "Replace both objects.", context: "Doy el libro a Ana: el libro → lo, a Ana → le.", prompt: "Which combined form avoids le lo?", options: ["Se lo doy.", "Le lo doy.", "Lo le doy."], answer: 0, correct: "Indirect comes first and le changes to se before lo.", incorrect: "Use se + lo before doy." },
    guided: { heading: "Keep me before la.", context: "Ana sends the letter to me: la carta → la, to me → me.", prompt: "Which order is correct?", options: ["Ana me la envía.", "Ana la me envía.", "Ana se la envía a mí."], answer: 0, correct: "Me precedes the direct object pronoun la.", incorrect: "Order the unit indirect then direct: me la." },
    builder: { prompt: "Build: We gave them to her yesterday. (the keys)", tokens: ["Se", "las", "dimos", "ayer."], correctOrder: ["Se", "las", "dimos", "ayer."], answer: "Se las dimos ayer.", feedback: "Se replaces le; las replaces the feminine plural keys; both precede dimos." },
    reading: { heading: "Returning borrowed things.", sentences: [["Ana me prestó dos libros.", "Ana lent me two books."], ["Ayer se los devolví.", "Yesterday I returned them to her."], ["Carlos nos pidió las llaves.", "Carlos asked us for the keys."], ["También se las dimos.", "We gave them to him too."]], question: { prompt: "What does las replace in the final line?", options: ["las llaves", "Ana", "dos libros"], answer: 0, feedback: "Las replaces the feminine plural direct object las llaves." } },
    recall: [
      { before: "Le doy el libro → ", after: " doy.", answer: "Se lo", accepted: ["se lo"], feedback: "Le changes to se and lo replaces el libro." },
      { before: "Ana envía la carta a mí → Ana ", after: " envía.", answer: "me la", feedback: "Indirect me comes before direct la." },
      { before: "Les dimos las llaves → ", after: " dimos.", answer: "Se las", accepted: ["se las"], feedback: "Les becomes se before direct object las." },
    ],
    production: { prompt: "Write six two-object transformations: begin with full nouns, then replace both objects with pronouns in present and past.", requirements: ["Indirect pronoun before direct", "Change le/les to se", "Use singular and plural direct objects"], example: "Doy el libro a Ana → Se lo doy. Enviamos las cartas a ellos → Se las enviamos. Ana me dio el café → Me lo dio." },
    takeaway: "Order combined pronouns indirect + direct, change le/les to se before lo/la/los/las, and place the unit at the edge of the verb phrase.",
  }),
  createCourseLesson({
    id: "16.7", title: "Tell a Story", displayTitle: "A complete story builds a world, moves through events, and reflects on their meaning.",
    dek: "Imperfect background, preterite events, pronoun cohesion, and connectors now work as one narrative system.",
    goal: "Plan, write, and revise a coherent past narrative with controlled viewpoints and connected reference.", durationMinutes: 35, concepts: ["past_narration", "preterite_imperfect", "combined_pronouns", "clause_connectors"],
    explain: [
      "A strong beginner narrative has three layers. Orientation establishes when, where, who, and what the scene was like with the imperfect. The event line uses preterite verbs to change the situation. Reflection or closure explains the result and why the experience matters.",
      "Use pronouns only after their referents are clear, vary connectors by relationship, and reread every tense choice as a viewpoint decision. The goal is not maximum complexity; it is a story the listener can enter, follow, and remember.",
    ],
    examples: [["Era sábado y hacía sol.", "It was Saturday and sunny."], ["De repente recibí un mensaje.", "Suddenly I received a message."], ["Al final entendí por qué ese día fue importante.", "In the end I understood why that day was important."]],
    boundary: { heading: "Narrative layers cooperate instead of competing.", note: "Background slows to orient; events advance; reflection closes the meaning.",
      left: { label: "SCENE", question: "What was already true?", description: "Use imperfect description, time, habit, and ongoing action.", example: ["La plaza estaba llena.", "The plaza was full."] },
      right: { label: "EVENT LINE", question: "What changed next?", description: "Use bounded preterite events and clear sequence.", example: ["Entonces vi a Ana.", "Then I saw Ana."] } },
    prediction: { heading: "Choose an opening layer.", context: "The story needs weather, time, and ongoing activity before the first event.", prompt: "Which opening orients the listener?", options: ["Era tarde, llovía y yo caminaba a casa.", "Llegué, vi, salí.", "Mañana estaba ayer."], answer: 0, correct: "The imperfect opening builds time, weather, and ongoing movement.", incorrect: "Use coherent imperfect background before the event line." },
    guided: { heading: "Advance from the scene.", context: "While the speaker was walking, a friend suddenly called.", prompt: "Which sentence adds the bounded change?", options: ["De repente Ana llamó.", "Ana llamaba cada día only.", "Ana llama ayer."], answer: 0, correct: "De repente and llamó move the story into a completed event.", incorrect: "Use a preterite event to change the established scene." },
    builder: { prompt: "Build: I saw the letter, read it, and gave it to Ana.", tokens: ["Vi la carta,", "la leí", "y se la di", "a Ana."], correctOrder: ["Vi la carta,", "la leí", "y se la di", "a Ana."], answer: "Vi la carta, la leí y se la di a Ana.", feedback: "La keeps reference to the letter; se la combines Ana as recipient with the known object." },
    reading: { heading: "The day the community came together.", sentences: [["Era domingo y hacía mucho calor.", "It was Sunday and very hot."], ["En la iglesia todos preparaban una comida para la comunidad.", "At church everyone was preparing a meal for the community."], ["De repente se fue la luz, pero nadie salió.", "Suddenly the power went out, but nobody left."], ["Un vecino trajo un generador y nos lo prestó.", "A neighbor brought a generator and lent it to us."], ["Entonces terminamos la comida y la compartimos con todos.", "Then we finished the meal and shared it with everyone."], ["Al final comprendí que una dificultad también podía unirnos.", "In the end I understood that a difficulty could also bring us together."]], question: { prompt: "What is the story’s central change?", options: ["A power outage becomes a moment of cooperation", "The speaker leaves church", "The food is never finished"], answer: 0, feedback: "The outage interrupts the background, but the neighbor’s help and group response create the meaningful result." } },
    recall: [
      { before: "Era domingo y ", after: " calor. (it was hot)", answer: "hacía", accepted: ["hacía", "hacia"], feedback: "Imperfect hacía establishes weather background." },
      { before: "De repente se ", after: " la luz. (went out)", answer: "fue", feedback: "The preterite event changes the scene." },
      { before: "El vecino trajo un generador y nos ", after: " prestó. (it)", answer: "lo", feedback: "Lo replaces the known generator as direct object." },
    ],
    production: { prompt: "Write a 180–250 word story about a memorable day: orient the scene, develop at least eight events, use cohesive pronouns, and close with why it mattered.", requirements: ["Imperfect orientation and at least eight preterite events", "Clear connector relationships and pronoun reference", "A reflective final meaning"], example: "Era verano y visitaba a mi familia en Cuba. Una tarde empezó a llover… Al final entendí por qué ese día quedó conmigo.", minimumCharacters: 180 },
    takeaway: "Orient with imperfect background, advance with preterite events, maintain reference with pronouns, and close by showing why the experience matters.",
  }),
];
