import type { LessonDefinition } from "@/content/schemas";

export const lesson41: LessonDefinition = {
  id: "4.1",
  moduleId: "module-04",
  title: "ESTAR: How and Where",
  displayTitle: "Say how someone is—and where they are.",
  dek: "Meet estar as one verb with two connected jobs, then make its present forms usable.",
  goal: "Use estoy, estás, está, estamos, and están to describe states and locate identified people or things, with correct adjective agreement.",
  durationMinutes: 26,
  concepts: ["estar_forms", "estar_state", "estar_location", "adjective_agreement"],
  blocks: [
    {
      id: "l41-meaning-problem",
      type: "prose",
      conceptIds: ["estar_state", "estar_location"],
      eyebrow: "Start with meaning",
      heading: "English uses “to be” for messages that Spanish organizes more precisely.",
      paragraphs: [
        "You already know that ser can identify or classify: Soy estudiante tells what the speaker is. This lesson adds estar, but estar is not simply a second spelling of the same English verb.",
        "Estar lets you answer two practical questions about an identified subject: How is the person or thing? Where is the person or thing? Estoy cansado answers how. Estoy en casa answers where.",
        "The form changes with the subject, but the meaning decision comes first. Before choosing estoy or está, decide whether the sentence is presenting a state or a location.",
      ],
      spanish: [
        { text: "Soy estudiante.", translation: "I am a student." },
        { text: "Estoy cansado.", translation: "I am tired." },
        { text: "Estoy en casa.", translation: "I am at home." },
      ],
    },
    {
      id: "l41-retrieve-ser",
      type: "choice",
      conceptIds: ["ser_classification", "estar_state"],
      eyebrow: "A retrieval bridge",
      heading: "Soy estudiante.",
      context: "This familiar sentence establishes what the speaker is.",
      prompt: "Which question does the sentence answer?",
      options: [
        { id: "what", label: "What am I?" },
        { id: "how", label: "How am I?" },
        { id: "where", label: "Where am I?" },
      ],
      correctOptionId: "what",
      correctFeedback: "Soy estudiante classifies the speaker. Estar will take over when the claim answers how or where.",
      incorrectFeedback: "Estudiante names what the speaker is; it does not describe a state or location.",
    },
    {
      id: "l41-mental-model",
      type: "comparison",
      conceptIds: ["estar_state", "estar_location"],
      eyebrow: "The mental model",
      heading: "One verb, two questions: HOW and WHERE.",
      sides: [
        {
          label: "HOW",
          question: "What state is the subject in?",
          description: "Use estar for a condition, feeling, or state presented in the moment or context.",
          examples: [
            { text: "Lucía está cansada.", translation: "Lucía is tired." },
            { text: "Estamos bien.", translation: "We are well." },
          ],
        },
        {
          label: "WHERE",
          question: "Where is the identified subject?",
          description: "Use estar to place a known person, object, or place in a location.",
          examples: [
            { text: "Lucía está en la escuela.", translation: "Lucía is at school." },
            { text: "Los libros están aquí.", translation: "The books are here." },
          ],
        },
      ],
      note: "Do not reduce this to temporary. A location may be very stable and still uses estar because the sentence answers where.",
    },
    {
      id: "l41-forms",
      type: "prose",
      conceptIds: ["estar_forms"],
      eyebrow: "Meaning, then form",
      heading: "The subject selects the exact form of estar.",
      paragraphs: [
        "After you choose the estar family, match the form to who or what the sentence is about. Spanish often leaves the subject pronoun unstated because the verb form already carries useful information.",
        "Estoy can only point to yo. Estás points to tú. Está works with él, ella, usted, or one named person or thing. Estamos is the nosotros form. Están works with ellos, ellas, ustedes, or any plural subject.",
        "The written accents in estás, está, and están are part of the forms. They are not optional decoration.",
      ],
      points: [
        { label: "YO", title: "estoy", description: "Estoy bien. Estoy en casa." },
        { label: "TÚ", title: "estás", description: "Estás cansada. Estás aquí." },
        { label: "ÉL / ELLA / USTED", title: "está", description: "Ana está contenta. Usted está en la escuela." },
        { label: "NOSOTROS", title: "estamos", description: "Estamos bien. Estamos en casa." },
        { label: "ELLOS / USTEDES", title: "están", description: "Mis amigos están aquí. Ustedes están contentos." },
      ],
      spanish: [
        { text: "Estoy aquí.", translation: "I am here." },
        { text: "Usted está bien.", translation: "You are well." },
        { text: "Ustedes están en casa.", translation: "You all are at home." },
      ],
    },
    {
      id: "l41-predict-yo",
      type: "choice",
      conceptIds: ["estar_forms", "estar_state"],
      eyebrow: "Predict the form",
      heading: "I am tired today.",
      context: "The sentence describes the speaker’s state, so the verb family is estar. Now match the form to yo.",
      prompt: "Which form completes the sentence?",
      sentence: { before: "Yo ", after: " cansado hoy." },
      options: [
        { id: "estoy", label: "estoy" },
        { id: "esta", label: "está" },
        { id: "estan", label: "están" },
      ],
      correctOptionId: "estoy",
      correctFeedback: "Yo selects estoy: Yo estoy cansado hoy.",
      incorrectFeedback: "The state meaning chooses estar, and the subject yo narrows the form to estoy.",
    },
    {
      id: "l41-predict-plural",
      type: "choice",
      conceptIds: ["estar_forms", "estar_location"],
      eyebrow: "Change the subject",
      heading: "My friends are here.",
      context: "Mis amigos is a plural subject. Aquí supplies their location.",
      prompt: "Which form agrees with mis amigos?",
      sentence: { before: "Mis amigos ", after: " aquí." },
      options: [
        { id: "esta", label: "está" },
        { id: "estamos", label: "estamos" },
        { id: "estan", label: "están" },
      ],
      correctOptionId: "estan",
      correctFeedback: "Mis amigos is they, so it selects están.",
      incorrectFeedback: "Choose from the plural subject, not from the location word aquí: mis amigos están.",
    },
    {
      id: "l41-agreement",
      type: "prose",
      conceptIds: ["estar_state", "adjective_agreement"],
      eyebrow: "A second agreement decision",
      heading: "A state adjective must also match the subject.",
      paragraphs: [
        "When a state is expressed with an adjective, the verb and adjective each do a different agreement job. The subject selects the estar form, and the adjective reflects gender and number when the adjective changes that way.",
        "Ana está cansada uses singular está and feminine cansada. Ana y Luis están cansados uses plural están and the plural form cansados for a mixed group.",
        "Some adjectives, such as triste, do not change for masculine or feminine singular, but they still become plural: tristes.",
      ],
      spanish: [
        { text: "Ana está cansada.", translation: "Ana is tired." },
        { text: "Luis está cansado.", translation: "Luis is tired." },
        { text: "Ana y Luis están cansados.", translation: "Ana and Luis are tired." },
      ],
    },
    {
      id: "l41-predict-agreement",
      type: "choice",
      conceptIds: ["estar_forms", "estar_state", "adjective_agreement"],
      eyebrow: "Coordinate both choices",
      heading: "Lucía and Marta are happy.",
      context: "Lucía y Marta is a feminine plural subject.",
      prompt: "Which complete predicate matches the subject?",
      sentence: { before: "Lucía y Marta ", after: "." },
      options: [
        { id: "esta-contenta", label: "está contenta" },
        { id: "estan-contentas", label: "están contentas" },
        { id: "estamos-contentos", label: "estamos contentos" },
      ],
      correctOptionId: "estan-contentas",
      correctFeedback: "The plural subject selects están, and two women are contentas.",
      incorrectFeedback: "Make both parts agree: plural están and feminine plural contentas.",
    },
    {
      id: "l41-location-boundary",
      type: "prose",
      conceptIds: ["estar_location"],
      eyebrow: "A useful boundary",
      heading: "Location is a job, not a promise that something will move.",
      paragraphs: [
        "The temporary shortcut fails quickly with location. A school can remain in the same city for a century, but La escuela está en la ciudad still uses estar because the sentence places an identified school somewhere.",
        "For now, use estar when the listener can identify the subject and the sentence tells where that subject is. Lesson 4.5 will later contrast this with introducing that something exists using hay.",
      ],
      spanish: [
        { text: "La escuela está en la ciudad.", translation: "The school is in the city." },
        { text: "Madrid está en España.", translation: "Madrid is in Spain." },
      ],
    },
    {
      id: "l41-how-where-sort",
      type: "sort",
      conceptIds: ["estar_state", "estar_location"],
      eyebrow: "Guided practice",
      heading: "Sort the meaning before choosing a form.",
      prompt: "Choose a meaning, then place it under the question it answers.",
      buckets: [
        { id: "how", label: "HOW?", hint: "state or condition" },
        { id: "where", label: "WHERE?", hint: "location of an identified subject" },
      ],
      items: [
        { id: "l41-sort-tired", label: "tired", answer: "how" },
        { id: "l41-sort-at-home", label: "at home", answer: "where" },
        { id: "l41-sort-well", label: "well", answer: "how" },
        { id: "l41-sort-here", label: "here", answer: "where" },
        { id: "l41-sort-sick", label: "sick", answer: "how" },
        { id: "l41-sort-school", label: "at school", answer: "where" },
      ],
    },
    {
      id: "l41-builder",
      type: "builder",
      conceptIds: ["estar_forms", "estar_state", "adjective_agreement"],
      eyebrow: "Build from the subject",
      heading: "Put the complete state sentence together.",
      prompt: "Build: We are happy today.",
      tokens: ["Estamos", "contentos", "hoy."],
      correctOrder: ["Estamos", "contentos", "hoy."],
      answer: "Estamos contentos hoy.",
      feedback: "Estamos carries the nosotros subject, and contentos agrees with the group.",
    },
    {
      id: "l41-decision-routine",
      type: "prose",
      conceptIds: ["estar_forms", "estar_state", "estar_location", "adjective_agreement"],
      eyebrow: "A repeatable routine",
      heading: "Make three small decisions instead of one large guess.",
      paragraphs: [
        "Read the complete idea before touching the verb. The words after the blank often show whether the sentence answers how or where, but the subject determines the form.",
        "If the sentence describes a state with an adjective, make one final agreement check after the verb is settled.",
      ],
      points: [
        { label: "01", title: "Name the job", description: "Is the sentence describing a state or giving a location?" },
        { label: "02", title: "Find the subject", description: "Yo, tú, one person or thing, nosotros, or a plural subject?" },
        { label: "03", title: "Choose the estar form", description: "Estoy, estás, está, estamos, or están." },
        { label: "04", title: "Check the adjective", description: "If there is a state adjective, make its gender and number fit the subject." },
      ],
    },
    {
      id: "l41-reading",
      type: "reading",
      conceptIds: ["estar_forms", "estar_state", "estar_location", "adjective_agreement"],
      eyebrow: "Read in context",
      heading: "A family at the end of the day.",
      instructions: "Read the connected Spanish and listen to any sentence. Answer from the text before revealing the translation.",
      sentences: [
        { id: "l41-r1", text: "Estoy en casa con mi familia.", translation: "I am at home with my family." },
        { id: "l41-r2", text: "Mi hermana Elena está cansada.", translation: "My sister Elena is tired." },
        { id: "l41-r3", text: "Mis padres están en la cocina.", translation: "My parents are in the kitchen." },
        { id: "l41-r4", text: "Estamos contentos, pero estamos cansados.", translation: "We are happy, but we are tired." },
        { id: "l41-r5", text: "El perro está aquí también.", translation: "The dog is here too." },
      ],
      questions: [
        {
          id: "l41-q1",
          prompt: "Where is the family?",
          options: [{ id: "casa", label: "En casa" }, { id: "escuela", label: "En la escuela" }],
          correctOptionId: "casa",
          feedback: "The opening sentence places the speaker at home with the family.",
          conceptIds: ["estar_location"],
        },
        {
          id: "l41-q2",
          prompt: "How is Elena?",
          options: [{ id: "cansada", label: "Cansada" }, { id: "contentos", label: "Contentos" }],
          correctOptionId: "cansada",
          feedback: "Elena está cansada gives Elena’s state and agrees with her name.",
          conceptIds: ["estar_state", "adjective_agreement"],
        },
        {
          id: "l41-q3",
          prompt: "Which form locates mis padres?",
          options: [{ id: "esta", label: "está" }, { id: "estan", label: "están" }],
          correctOptionId: "estan",
          feedback: "Mis padres is plural, so the text uses están.",
          conceptIds: ["estar_forms", "estar_location"],
        },
      ],
    },
    {
      id: "l41-synthesis",
      type: "prose",
      conceptIds: ["estar_forms", "estar_state", "estar_location"],
      eyebrow: "Bring the system together",
      heading: "The same form can carry HOW or WHERE because the rest of the sentence supplies the job.",
      paragraphs: [
        "Elena está cansada and El perro está aquí share the form está because each subject is singular. The state adjective cansada answers how; the location word aquí answers where.",
        "This is why memorizing está as one English phrase is fragile. Read the complete claim, identify the job, and then match the form to the subject.",
      ],
      spanish: [
        { text: "Elena está cansada.", translation: "Elena is tired." },
        { text: "El perro está aquí.", translation: "The dog is here." },
      ],
    },
    {
      id: "l41-controlled-recall",
      type: "fill",
      conceptIds: ["estar_forms", "estar_state", "estar_location", "adjective_agreement"],
      eyebrow: "Recall without choices",
      heading: "Retrieve the forms from the complete sentence.",
      prompt: "Type the missing form. Accents matter in the model answer, but an unaccented attempt is accepted while you build keyboard fluency.",
      items: [
        { id: "l41-fill-1", before: "Yo ", after: " bien.", accepted: ["estoy"], answer: "estoy", conceptIds: ["estar_forms", "estar_state"], feedback: "Yo selects estoy; bien gives the state." },
        { id: "l41-fill-2", before: "Ana ", after: " en casa.", accepted: ["está", "esta"], answer: "está", conceptIds: ["estar_forms", "estar_location"], feedback: "One named person selects está, and en casa gives the location." },
        { id: "l41-fill-3", before: "Nosotros ", after: " cansados.", accepted: ["estamos"], answer: "estamos", conceptIds: ["estar_forms", "estar_state"], feedback: "Nosotros selects estamos." },
        { id: "l41-fill-4", before: "Mis amigas ", after: " contentas.", accepted: ["están", "estan"], answer: "están", conceptIds: ["estar_forms", "estar_state"], feedback: "The plural subject selects están; contentas already agrees." },
        { id: "l41-fill-5", before: "Usted ", after: " aquí.", accepted: ["está", "esta"], answer: "está", conceptIds: ["estar_forms", "estar_location"], feedback: "Usted uses the third-person singular form está." },
      ],
    },
    {
      id: "l41-original-writing",
      type: "free-write",
      conceptIds: ["estar_forms", "estar_state", "estar_location", "adjective_agreement"],
      eyebrow: "Produce your own Spanish",
      heading: "Say how you are and where you are.",
      prompt: "Write two complete Spanish sentences about yourself or an imagined person: one state and one location.",
      requirements: ["Use a correct form of estar", "Include one state word", "Include one location expression", "Write two separate ideas"],
      example: "Estoy contenta hoy. Estoy en casa con mi familia.",
      minimumCharacters: 28,
      evaluation: {
        minimumIdeas: 2,
        requiredGroups: [
          { accepted: ["estoy", "estás", "estas", "está", "esta", "estamos", "están", "estan"], missingFeedback: "Use a form of estar in your description." },
          { accepted: ["cansado", "cansada", "cansados", "cansadas", "contento", "contenta", "contentos", "contentas", "triste", "tristes", "enfermo", "enferma", "bien"], missingFeedback: "Add a state such as cansado, contenta, triste, enfermo, or bien." },
          { accepted: ["aquí", "aqui", "en casa", "en la escuela", "en la ciudad", "en el restaurante"], missingFeedback: "Add a location such as aquí, en casa, or en la escuela." },
        ],
        successFeedback: "Your writing uses estar for both jobs and keeps state and location as separate ideas.",
      },
    },
    {
      id: "l41-final-retrieval",
      type: "fill",
      conceptIds: ["estar_forms", "estar_state", "estar_location"],
      eyebrow: "Final retrieval",
      heading: "Choose from meaning, then retrieve the form.",
      prompt: "Complete each sentence without returning to the chart.",
      items: [
        { id: "l41-final-1", before: "Tú ", after: " cansada.", accepted: ["estás", "estas"], answer: "estás", conceptIds: ["estar_forms", "estar_state"], feedback: "Tú selects estás; cansada gives the state." },
        { id: "l41-final-2", before: "El libro ", after: " aquí.", accepted: ["está", "esta"], answer: "está", conceptIds: ["estar_forms", "estar_location"], feedback: "The identified singular book is located with está." },
        { id: "l41-final-3", before: "Ustedes ", after: " bien.", accepted: ["están", "estan"], answer: "están", conceptIds: ["estar_forms", "estar_state"], feedback: "Ustedes selects están." },
      ],
    },
    {
      id: "l41-summary",
      type: "summary",
      conceptIds: ["estar_forms", "estar_state", "estar_location", "adjective_agreement"],
      eyebrow: "Keep this decision path",
      heading: "Meaning chooses the job. The subject chooses the form.",
      message: "Use estar to answer how or where, then coordinate the subject, verb, and any state adjective.",
      ideas: [
        { label: "HOW", question: "What state is the subject in?", uses: ["estar", "state adjective", "agreement"] },
        { label: "WHERE", question: "Where is the identified subject?", uses: ["estar", "location expression"] },
        { label: "FORM", question: "Who or what is the subject?", uses: ["estoy", "estás", "está", "estamos", "están"] },
      ],
    },
  ],
  completion: {
    title: "You can use estar for HOW and WHERE.",
    message: "You selected a state or location meaning, matched estar to the subject, and coordinated adjective agreement when the sentence needed it.",
  },
};
