import type { LessonDefinition } from "@/content/schemas";

export const lesson42: LessonDefinition = {
  id: "4.2",
  moduleId: "module-04",
  title: "Where Things Are",
  displayTitle: "Place people and things in the world.",
  dek: "Turn estar + location into a reliable sentence pattern without losing the meaning behind it.",
  goal: "Locate identified people, places, and things with estar; choose singular or plural forms from the subject; and build useful location descriptions with aquí and en.",
  durationMinutes: 24,
  concepts: ["estar_forms", "estar_location"],
  blocks: [
    {
      id: "l42-retrieve-location",
      type: "prose",
      conceptIds: ["estar_forms", "estar_location"],
      eyebrow: "Retrieve before adding",
      heading: "A location sentence answers one focused question: where is this identified subject?",
      paragraphs: [
        "Lesson 4.1 introduced two jobs for estar. Here we concentrate on location until the pattern becomes easy to retrieve: identified subject + estar + location.",
        "The subject may be a person, an object, or even a place. What matters is that the listener can identify what you are locating: el libro, mis amigos, la escuela, Madrid.",
        "Do not choose the verb form from the location phrase. Está and están both work with en la mesa; the subject decides which one the sentence needs.",
      ],
      spanish: [
        { text: "El libro está aquí.", translation: "The book is here." },
        { text: "Mis amigos están en casa.", translation: "My friends are at home." },
        { text: "La escuela está en la ciudad.", translation: "The school is in the city." },
      ],
    },
    {
      id: "l42-retrieve-form",
      type: "choice",
      conceptIds: ["estar_forms", "estar_location"],
      eyebrow: "Quick retrieval",
      heading: "The books are on the table.",
      context: "Los libros is plural. En la mesa is where they are.",
      prompt: "Which form locates the books?",
      sentence: { before: "Los libros ", after: " en la mesa." },
      options: [
        { id: "esta", label: "está" },
        { id: "estan", label: "están" },
        { id: "estamos", label: "estamos" },
      ],
      correctOptionId: "estan",
      correctFeedback: "Los libros is plural, so the location sentence uses están.",
      incorrectFeedback: "Ignore the singular noun inside en la mesa. The subject is los libros, so choose están.",
    },
    {
      id: "l42-reference",
      type: "prose",
      conceptIds: ["estar_location"],
      eyebrow: "What counts as identified?",
      heading: "Articles, names, and possessives help the listener know what you mean.",
      paragraphs: [
        "El libro points to the book the conversation already makes identifiable. Mi libro identifies it through ownership. Ana identifies a person by name. Each can be located with estar.",
        "This is a reference decision, not a claim that the object is visually present. You can say Mi escuela está en Bogotá while speaking from another country because the school is still an identified place with a location.",
        "Later, hay will let you introduce that an unidentified thing exists. For now, keep the location pattern centered on a known subject.",
      ],
      points: [
        { label: "ARTICLE", title: "el libro / la escuela", description: "A definite article points to an identifiable thing or place." },
        { label: "POSSESSION", title: "mi casa / tus libros", description: "A possessive identifies the subject through its relationship to someone." },
        { label: "NAME", title: "Ana / Bogotá", description: "A proper name directly identifies the person or place." },
      ],
      spanish: [
        { text: "Mi libro está en casa.", translation: "My book is at home." },
        { text: "Ana está en la escuela.", translation: "Ana is at school." },
        { text: "Bogotá está en Colombia.", translation: "Bogotá is in Colombia." },
      ],
    },
    {
      id: "l42-subject-head",
      type: "comparison",
      conceptIds: ["estar_forms", "estar_location"],
      eyebrow: "Singular or plural",
      heading: "Read the subject before the location phrase.",
      sides: [
        {
          label: "ONE",
          question: "Is the identified subject singular?",
          description: "A singular named person, object, or place selects está.",
          examples: [
            { text: "El restaurante está aquí.", translation: "The restaurant is here." },
            { text: "La mesa está en la cocina.", translation: "The table is in the kitchen." },
          ],
        },
        {
          label: "MORE THAN ONE",
          question: "Is the identified subject plural?",
          description: "A plural subject selects están, even when the location contains a singular noun.",
          examples: [
            { text: "Los libros están aquí.", translation: "The books are here." },
            { text: "Mis amigos están en la escuela.", translation: "My friends are at school." },
          ],
        },
      ],
      note: "In Los libros están en la mesa, mesa is not the subject. It belongs to the location phrase en la mesa.",
    },
    {
      id: "l42-predict-subject",
      type: "choice",
      conceptIds: ["estar_forms", "estar_location"],
      eyebrow: "Find the controlling noun",
      heading: "My friends are in the restaurant.",
      context: "The sentence contains two nouns, but only mis amigos is the subject being located.",
      prompt: "Which form belongs after mis amigos?",
      sentence: { before: "Mis amigos ", after: " en el restaurante." },
      options: [
        { id: "esta", label: "está" },
        { id: "estan", label: "están" },
      ],
      correctOptionId: "estan",
      correctFeedback: "Mis amigos controls the verb, so the form is están. Restaurante only names the location.",
      incorrectFeedback: "Do not let el restaurante pull the verb into singular. The subject mis amigos is plural.",
    },
    {
      id: "l42-location-language",
      type: "prose",
      conceptIds: ["estar_location"],
      eyebrow: "Useful location language",
      heading: "Aquí stands alone. En introduces a place.",
      paragraphs: [
        "Aquí means here and can complete the location directly: El libro está aquí. En introduces the place that contains or situates the subject: en casa, en la escuela, en la ciudad, en la mesa.",
        "English may translate en as in, at, or on depending on the place. Avoid choosing from the English preposition one word at a time. Learn each Spanish location as a usable expression.",
        "At this stage, en la mesa is the course expression for locating something on the table. The goal is to control the location pattern, not to study every spatial preposition at once.",
      ],
      spanish: [
        { text: "El libro está aquí.", translation: "The book is here." },
        { text: "Ana está en casa.", translation: "Ana is at home." },
        { text: "Los libros están en la mesa.", translation: "The books are on the table." },
      ],
    },
    {
      id: "l42-predict-en",
      type: "choice",
      conceptIds: ["estar_location"],
      eyebrow: "Complete the location",
      heading: "The school is in the city.",
      context: "La ciudad names the place that contains the school.",
      prompt: "Which location expression completes the sentence?",
      sentence: { before: "La escuela está ", after: " la ciudad." },
      options: [
        { id: "en", label: "en" },
        { id: "aqui", label: "aquí" },
        { id: "es", label: "es" },
      ],
      correctOptionId: "en",
      correctFeedback: "En introduces the place: La escuela está en la ciudad.",
      incorrectFeedback: "The blank needs the location connector before la ciudad: en la ciudad.",
    },
    {
      id: "l42-form-sort",
      type: "sort",
      conceptIds: ["estar_forms", "estar_location"],
      eyebrow: "Guided practice",
      heading: "Let the subject choose está, están, or estamos.",
      prompt: "Choose a subject, then place it under the form it selects.",
      buckets: [
        { id: "esta", label: "ESTÁ", hint: "one person, place, or thing" },
        { id: "estan", label: "ESTÁN", hint: "a plural subject" },
        { id: "estamos", label: "ESTAMOS", hint: "we / nosotros" },
      ],
      items: [
        { id: "l42-sort-book", label: "el libro", answer: "esta" },
        { id: "l42-sort-friends", label: "mis amigos", answer: "estan" },
        { id: "l42-sort-we", label: "nosotros", answer: "estamos" },
        { id: "l42-sort-school", label: "la escuela", answer: "esta" },
        { id: "l42-sort-tables", label: "las mesas", answer: "estan" },
        { id: "l42-sort-ana-luis", label: "Ana y Luis", answer: "estan" },
      ],
    },
    {
      id: "l42-builder",
      type: "builder",
      conceptIds: ["estar_forms", "estar_location"],
      eyebrow: "Build the pattern",
      heading: "Keep the subject and location in their roles.",
      prompt: "Build: The books are on the table.",
      tokens: ["Los libros", "están", "en la mesa."],
      correctOrder: ["Los libros", "están", "en la mesa."],
      answer: "Los libros están en la mesa.",
      feedback: "Los libros is the identified plural subject, están agrees with it, and en la mesa supplies the location.",
    },
    {
      id: "l42-stability",
      type: "prose",
      conceptIds: ["estar_location"],
      eyebrow: "Reject the shortcut",
      heading: "A permanent address still answers WHERE.",
      paragraphs: [
        "La escuela está en la ciudad may describe a location that never changes during your lifetime. It still uses estar because the sentence is locating the school.",
        "Likewise, Bogotá está en Colombia and Madrid está en España use estar. Geography gives especially clear evidence that location and temporariness are different ideas.",
        "A dependable question is more useful than a vague timeline: where is the identified person, place, or thing?",
      ],
      spanish: [
        { text: "Bogotá está en Colombia.", translation: "Bogotá is in Colombia." },
        { text: "Madrid está en España.", translation: "Madrid is in Spain." },
      ],
    },
    {
      id: "l42-reading",
      type: "reading",
      conceptIds: ["estar_forms", "estar_location"],
      eyebrow: "Read a connected scene",
      heading: "A small school library.",
      instructions: "Read and listen to the scene. Track each identified subject and the place assigned to it before revealing the translation.",
      sentences: [
        { id: "l42-r1", text: "La escuela está en el centro de la ciudad.", translation: "The school is in the city center." },
        { id: "l42-r2", text: "La biblioteca está en la escuela.", translation: "The library is in the school." },
        { id: "l42-r3", text: "Los libros están en las mesas.", translation: "The books are on the tables." },
        { id: "l42-r4", text: "La profesora está aquí con dos estudiantes.", translation: "The teacher is here with two students." },
        { id: "l42-r5", text: "Nosotros estamos en la biblioteca también.", translation: "We are in the library too." },
      ],
      questions: [
        {
          id: "l42-q1",
          prompt: "Where is the library?",
          options: [{ id: "school", label: "En la escuela" }, { id: "tables", label: "En las mesas" }],
          correctOptionId: "school",
          feedback: "The second sentence places the library inside the school.",
          conceptIds: ["estar_location"],
        },
        {
          id: "l42-q2",
          prompt: "What subject selects están?",
          options: [{ id: "books", label: "Los libros" }, { id: "teacher", label: "La profesora" }],
          correctOptionId: "books",
          feedback: "Los libros is plural and therefore appears with están.",
          conceptIds: ["estar_forms"],
        },
        {
          id: "l42-q3",
          prompt: "Which form locates the speaker’s group?",
          options: [{ id: "estamos", label: "estamos" }, { id: "estan", label: "están" }],
          correctOptionId: "estamos",
          feedback: "Nosotros selects estamos.",
          conceptIds: ["estar_forms", "estar_location"],
        },
      ],
    },
    {
      id: "l42-synthesis",
      type: "prose",
      conceptIds: ["estar_forms", "estar_location"],
      eyebrow: "A compact location algorithm",
      heading: "Identify, count, locate.",
      paragraphs: [
        "First identify the subject being placed. Then decide whether it is yo, tú, one third-person subject, nosotros, or a plural third-person subject. Finally attach the location with aquí or en + place.",
        "This order prevents a noun inside the location phrase from controlling the verb. In Los libros están en la mesa, libros—not mesa—selects están.",
      ],
      points: [
        { label: "IDENTIFY", title: "What are you locating?", description: "Find the complete subject before the verb." },
        { label: "COUNT", title: "Which estar form fits?", description: "Match the form to the subject’s person and number." },
        { label: "LOCATE", title: "Where is it?", description: "Finish with aquí or a learned en + place expression." },
      ],
    },
    {
      id: "l42-controlled-recall",
      type: "fill",
      conceptIds: ["estar_forms", "estar_location"],
      eyebrow: "Recall without choices",
      heading: "Complete the location network.",
      prompt: "Type the missing estar form or location connector.",
      items: [
        { id: "l42-fill-1", before: "La casa ", after: " en la ciudad.", accepted: ["está", "esta"], answer: "está", conceptIds: ["estar_forms", "estar_location"], feedback: "La casa is singular, so it selects está." },
        { id: "l42-fill-2", before: "Los restaurantes ", after: " aquí.", accepted: ["están", "estan"], answer: "están", conceptIds: ["estar_forms", "estar_location"], feedback: "Los restaurantes is plural, so it selects están." },
        { id: "l42-fill-3", before: "Nosotros ", after: " en casa.", accepted: ["estamos"], answer: "estamos", conceptIds: ["estar_forms", "estar_location"], feedback: "Nosotros selects estamos." },
        { id: "l42-fill-4", before: "El libro está ", after: " la mesa.", accepted: ["en"], answer: "en", conceptIds: ["estar_location"], feedback: "En introduces la mesa as the location." },
        { id: "l42-fill-5", before: "Ana y Luis ", after: " en la escuela.", accepted: ["están", "estan"], answer: "están", conceptIds: ["estar_forms", "estar_location"], feedback: "Two named people make a plural subject: están." },
      ],
    },
    {
      id: "l42-original-writing",
      type: "free-write",
      conceptIds: ["estar_forms", "estar_location"],
      eyebrow: "Map a real or imagined place",
      heading: "Write two connected locations.",
      prompt: "Locate one singular subject and one plural subject in a room, school, home, or city.",
      requirements: ["Use está with a singular subject", "Use están with a plural subject", "Include aquí or en + a place", "Write two complete ideas"],
      example: "Mi escuela está en la ciudad. Los libros están en la biblioteca.",
      minimumCharacters: 38,
      evaluation: {
        minimumIdeas: 2,
        requiredGroups: [
          { accepted: ["está", "esta"], missingFeedback: "Add está to locate one singular subject." },
          { accepted: ["están", "estan"], missingFeedback: "Add están to locate one plural subject." },
          { accepted: ["aquí", "aqui", "en casa", "en la escuela", "en la ciudad", "en la mesa", "en las mesas", "en la biblioteca", "en el restaurante"], missingFeedback: "Include a clear location with aquí or a learned en + place expression." },
        ],
        successFeedback: "Your two location sentences distinguish singular está from plural están and keep each place expression attached to the right subject.",
      },
    },
    {
      id: "l42-final-retrieval",
      type: "fill",
      conceptIds: ["estar_forms", "estar_location"],
      eyebrow: "Final retrieval",
      heading: "Do not let the nearest noun choose the verb.",
      prompt: "Complete the forms from the subjects at the beginning of each sentence.",
      items: [
        { id: "l42-final-1", before: "La mesa ", after: " en la cocina.", accepted: ["está", "esta"], answer: "está", conceptIds: ["estar_forms", "estar_location"], feedback: "La mesa is the singular subject: está." },
        { id: "l42-final-2", before: "Mis amigos ", after: " en el restaurante.", accepted: ["están", "estan"], answer: "están", conceptIds: ["estar_forms", "estar_location"], feedback: "Mis amigos controls the verb even though restaurante is singular." },
        { id: "l42-final-3", before: "Bogotá ", after: " en Colombia.", accepted: ["está", "esta"], answer: "está", conceptIds: ["estar_forms", "estar_location"], feedback: "A named city is an identified singular place, so the location uses está." },
      ],
    },
    {
      id: "l42-summary",
      type: "summary",
      conceptIds: ["estar_forms", "estar_location"],
      eyebrow: "Keep the pattern",
      heading: "The subject controls the form; the location completes the claim.",
      message: "Use estar for the location of an identified person, place, or thing—even when the location is stable.",
      ideas: [
        { label: "SUBJECT", question: "What identified thing are you locating?", uses: ["name", "definite article", "possessive"] },
        { label: "FORM", question: "Is the subject singular, plural, or nosotros?", uses: ["está", "están", "estamos"] },
        { label: "PLACE", question: "Where is the subject?", uses: ["aquí", "en casa", "en + place"] },
      ],
    },
  ],
  completion: {
    title: "You can locate identified people and things.",
    message: "You kept the subject separate from its location, selected singular or plural estar, and used aquí and en + place to build connected descriptions.",
  },
};
