import type { LessonDefinition } from "@/content/schemas";

export const lesson43: LessonDefinition = {
  id: "4.3",
  moduleId: "module-04",
  title: "SER vs. ESTAR",
  displayTitle: "Two ways to say “to be.”",
  dek: "Learn what each verb lets you say, then choose from meaning instead of a shortcut.",
  goal: "Choose ser or estar in identity, classification, origin, state, and location sentences—including the event-location exception—and explain the reason.",
  durationMinutes: 28,
  concepts: [
    "ser_identity",
    "ser_classification",
    "ser_origin",
    "estar_state",
    "estar_location",
    "ser_vs_estar_selection",
  ],
  blocks: [
    {
      id: "english-problem",
      type: "prose",
      conceptIds: ["ser_vs_estar_selection"],
      eyebrow: "Start with meaning",
      heading: "English hides a distinction that Spanish makes visible.",
      paragraphs: [
        "English asks one verb—am, is, or are—to carry several different kinds of meaning. I am a student identifies what I am. I am at home tells where I am. The English verb looks the same even though the message has changed.",
        "Spanish does not package those messages in the same way. It normally uses ser for identity, classification, and origin, and estar for a state or the location of an identified person, place, or thing.",
        "That means the choice is not a translation puzzle. You are not looking for the Spanish word that equals am. You are deciding what claim the sentence is making, then choosing the verb that carries that claim.",
        "Listen to the pair below. The subject is the same. Only the job of the sentence changes.",
      ],
      spanish: [
        { text: "Soy estudiante.", translation: "I am a student." },
        { text: "Estoy en casa.", translation: "I am at home." },
      ],
    },
    {
      id: "warmup-ser",
      type: "choice",
      conceptIds: ["ser_identity"],
      eyebrow: "Recall before explanation",
      heading: "Begin with the message you already recognize.",
      prompt: "What job is the sentence doing?",
      sentence: { before: "Soy estudiante", after: "." },
      options: [
        { id: "identity", label: "It identifies or classifies" },
        { id: "location", label: "It gives a location" },
      ],
      correctOptionId: "identity",
      correctFeedback: "Estudiante tells what kind of person the speaker is. That identity or classification job belongs with ser.",
      incorrectFeedback: "Look beyond soy and read estudiante. It answers what the speaker is, not where the speaker is.",
    },
    {
      id: "warmup-estar",
      type: "choice",
      conceptIds: ["estar_location"],
      heading: "Now let the message change.",
      prompt: "What job is this sentence doing?",
      sentence: { before: "Estoy en casa", after: "." },
      options: [
        { id: "identity", label: "It identifies or classifies" },
        { id: "location", label: "It gives a location" },
      ],
      correctOptionId: "location",
      correctFeedback: "En casa answers where the speaker is. The location of a person uses estar.",
      incorrectFeedback: "En casa does not tell what the speaker is. It answers where, so this sentence needs estar.",
    },
    {
      id: "mental-model",
      type: "comparison",
      conceptIds: ["ser_identity", "ser_classification", "ser_origin", "estar_state", "estar_location"],
      eyebrow: "The mental model",
      heading: "Ask what the sentence is trying to establish.",
      note: "The useful contrast is the job of the sentence—not whether the situation feels permanent or temporary.",
      sides: [
        {
          label: "SER",
          question: "What or who is it? Where is it from?",
          description: "Use ser to establish identity, put someone or something in a category, describe a relationship, or state origin.",
          examples: [
            { text: "Ana es mi hermana.", translation: "Ana is my sister." },
            { text: "Elena es doctora.", translation: "Elena is a doctor." },
            { text: "Somos de México.", translation: "We are from Mexico." },
          ],
        },
        {
          label: "ESTAR",
          question: "How is it? Where is it?",
          description: "Use estar to present a state or to locate an identified person, place, or thing.",
          examples: [
            { text: "Ana está cansada.", translation: "Ana is tired." },
            { text: "Estamos bien.", translation: "We are well." },
            { text: "El libro está en la mesa.", translation: "The book is on the table." },
          ],
        },
      ],
    },
    {
      id: "claim-not-subject",
      type: "prose",
      conceptIds: ["ser_vs_estar_selection"],
      eyebrow: "A more precise question",
      heading: "The subject does not choose the verb. The claim does.",
      paragraphs: [
        "There is no person who always goes with ser and no place that always goes with estar. The same subject can appear with either verb because a speaker can make different claims about it.",
        "Ana can be identified as a student, located in the library, and described as tired. Those facts can all be true at once. Spanish chooses a verb sentence by sentence, according to the one idea being presented now.",
      ],
      points: [
        { label: "What or who?", title: "Establish identity or a category", description: "Use ser: Ana es estudiante." },
        { label: "Where?", title: "Locate a known person or thing", description: "Use estar: Ana está en la biblioteca." },
        { label: "How?", title: "Present a state", description: "Use estar: Ana está cansada." },
        { label: "From where?", title: "State origin", description: "Use ser: Ana es de Colombia." },
      ],
    },
    {
      id: "ser-jobs",
      type: "prose",
      conceptIds: ["ser_identity", "ser_classification", "ser_origin"],
      eyebrow: "Inside SER",
      heading: "Ser establishes what someone or something is in the conversation.",
      paragraphs: [
        "Identity can name a person or describe a relationship: Ana es mi hermana. Classification places the subject in a useful category: Elena es doctora. Origin connects the subject to a source or place with de: Somos de México.",
        "Professions normally appear without un or una immediately after ser. English says Elena is a doctor, but the neutral Spanish sentence is Elena es doctora—not Elena es una doctora.",
        "These are different details, but they perform the same broad job: they establish who or what the subject is for this sentence.",
      ],
      spanish: [
        { text: "Ana es mi hermana.", translation: "Ana is my sister." },
        { text: "Elena es doctora.", translation: "Elena is a doctor." },
        { text: "Somos de México.", translation: "We are from Mexico." },
      ],
    },
    {
      id: "prediction-doctor",
      type: "choice",
      conceptIds: ["ser_classification", "ser_vs_estar_selection"],
      eyebrow: "Check the idea",
      heading: "Elena is a doctor.",
      context: "The sentence tells us Elena’s profession. It is not saying how she feels or where she is.",
      prompt: "Choose the form that matches the job of the sentence.",
      sentence: { before: "Elena ", after: " doctora." },
      options: [
        { id: "es", label: "es" },
        { id: "esta", label: "está" },
      ],
      correctOptionId: "es",
      correctFeedback: "Doctora classifies what Elena is, so the sentence uses ser: Elena es doctora.",
      incorrectFeedback: "This sentence establishes Elena’s profession. It does not present her state or location, so it needs ser.",
    },
    {
      id: "prediction-origin",
      type: "choice",
      conceptIds: ["ser_origin", "ser_vs_estar_selection"],
      heading: "Mateo is from Peru.",
      context: "De Perú states Mateo’s origin. The preposition de is a strong signal because origin is one of the jobs of ser.",
      prompt: "Which verb carries that meaning?",
      sentence: { before: "Mateo ", after: " de Perú." },
      options: [
        { id: "es", label: "es" },
        { id: "esta", label: "está" },
      ],
      correctOptionId: "es",
      correctFeedback: "Origin uses ser: Mateo es de Perú.",
      incorrectFeedback: "De Perú answers where Mateo is from, not where he is now. Origin uses ser.",
    },
    {
      id: "estar-jobs",
      type: "prose",
      conceptIds: ["estar_state", "estar_location", "adjective_agreement"],
      eyebrow: "Inside ESTAR",
      heading: "Estar presents a condition or places something on the map.",
      paragraphs: [
        "A state answers how the subject is: cansada, bien, enfermo, listo. A location answers where an identified person, place, or thing is: en casa, aquí, en la mesa, en México.",
        "When a state uses an adjective, agreement still matters. Elena está cansada uses cansada because Elena is feminine. Diego está cansado uses cansado because Diego is masculine. The choice of estar does not remove the agreement system you already learned.",
        "For location, imagine that the listener can identify the subject and you are placing it somewhere: the book, my parents, Madrid, the school. Lesson 4.5 will later separate this job from saying that something exists with hay.",
      ],
      spanish: [
        { text: "Elena está cansada.", translation: "Elena is tired." },
        { text: "Los libros están en la mesa.", translation: "The books are on the table." },
        { text: "Estamos bien.", translation: "We are well." },
      ],
    },
    {
      id: "prediction-tired",
      type: "choice",
      conceptIds: ["estar_state", "ser_vs_estar_selection"],
      eyebrow: "Change the claim",
      heading: "Elena worked for twelve hours and is tired.",
      context: "Now the sentence is not classifying Elena. It tells us how she is after a long day.",
      prompt: "Which form matches the meaning?",
      sentence: { before: "Elena ", after: " cansada." },
      options: [
        { id: "es", label: "es" },
        { id: "esta", label: "está" },
      ],
      correctOptionId: "esta",
      correctFeedback: "Cansada presents Elena’s state, so the sentence uses estar: Elena está cansada.",
      incorrectFeedback: "The sentence answers how Elena is after working. That state uses estar here.",
    },
    {
      id: "meaning-and-form",
      type: "prose",
      conceptIds: ["ser_vs_estar_selection", "estar_forms"],
      eyebrow: "Two decisions, in order",
      heading: "Meaning chooses the verb family. The subject chooses the form.",
      paragraphs: [
        "Choosing ser or estar is only the first decision. After the meaning chooses the verb family, the subject determines its form.",
        "The high-value forms are ser: soy, eres, es, somos, son; and estar: estoy, estás, está, estamos, están. Do not choose between es and está until you know the job. Then match the chosen verb to who or what the sentence is about.",
      ],
      points: [
        { label: "01", title: "Read the whole idea", description: "Decide whether the sentence establishes what, origin, a state, or a location." },
        { label: "02", title: "Choose ser or estar", description: "Let that meaning select the verb family before you think about an ending." },
        { label: "03", title: "Match the subject", description: "Choose soy or estoy for yo, es or está for one third-person subject, and the correct plural form for nosotros or ellos." },
        { label: "04", title: "Check the rest", description: "Keep adjective and number agreement aligned with the subject." },
      ],
      spanish: [
        { text: "Yo soy estudiante. Yo estoy en casa.", translation: "I am a student. I am at home." },
        { text: "Somos vecinos. Estamos en el centro.", translation: "We are neighbors. We are downtown." },
      ],
    },
    {
      id: "madrid-contrast",
      type: "comparison",
      conceptIds: ["ser_classification", "estar_location", "ser_vs_estar_selection"],
      eyebrow: "One subject, two questions",
      heading: "Madrid does not change. The claim does.",
      note: "The city is the same in both sentences. Ser classifies it; estar locates it.",
      sides: [
        {
          label: "WHAT",
          question: "What is Madrid?",
          description: "A city. The sentence puts Madrid in a category, so it uses ser.",
          examples: [{ text: "Madrid es una ciudad.", translation: "Madrid is a city." }],
        },
        {
          label: "WHERE",
          question: "Where is Madrid?",
          description: "In Spain. The sentence locates a known place, so it uses estar.",
          examples: [{ text: "Madrid está en España.", translation: "Madrid is in Spain." }],
        },
      ],
    },
    {
      id: "permanence-trap",
      type: "prose",
      conceptIds: ["ser_classification", "estar_location", "ser_vs_estar_selection"],
      eyebrow: "Retire the shortcut",
      heading: "Permanent versus temporary predicts the wrong verb.",
      paragraphs: [
        "Madrid’s location in Spain is extremely stable, yet Spanish says Madrid está en España because the sentence is doing the location job.",
        "A role can be limited to one day and still use ser: Ana es la coordinadora hoy. The sentence establishes Ana’s role, even though hoy makes the situation short-lived.",
        "Time can add context, but it does not define the verb. Ask what the sentence presents as identity, classification, origin, state, or location.",
      ],
      spanish: [
        { text: "Madrid está en España.", translation: "Madrid is in Spain." },
        { text: "Ana es la coordinadora hoy.", translation: "Ana is the coordinator today." },
      ],
    },
    {
      id: "event-location",
      type: "prose",
      conceptIds: ["ser_vs_estar_selection"],
      eyebrow: "One precise boundary",
      heading: "People and things are located with estar. Events take place with ser.",
      paragraphs: [
        "Estar locates identified people, objects, and places: La oficina está en el centro. But a scheduled event uses ser to say where or when it takes place: La reunión es en la oficina. La clase es a las nueve.",
        "This is not the permanent-versus-temporary rule returning in disguise. It is a difference in what is being located. An office is a place that has a location. A meeting is an event that takes place at a location and time.",
        "Keep the boundary narrow for now: where a person or thing is uses estar; where or when an event occurs uses ser.",
      ],
      spanish: [
        { text: "La oficina está en el centro.", translation: "The office is downtown." },
        { text: "La reunión es en la oficina.", translation: "The meeting is at the office." },
        { text: "La clase es a las nueve.", translation: "The class is at nine." },
      ],
    },
    {
      id: "prediction-event",
      type: "choice",
      conceptIds: ["ser_vs_estar_selection"],
      eyebrow: "Apply the boundary",
      heading: "The meeting is in the conference room.",
      context: "La reunión is an event. The sentence says where that event takes place.",
      prompt: "Which form completes the event sentence?",
      sentence: { before: "La reunión ", after: " en la sala de conferencias." },
      options: [
        { id: "es", label: "es" },
        { id: "esta", label: "está" },
      ],
      correctOptionId: "es",
      correctFeedback: "A meeting is an event, so its location uses ser: La reunión es en la sala de conferencias.",
      incorrectFeedback: "Estar would locate an identified person, place, or thing. This subject is an event, so use ser for where it takes place.",
    },
    {
      id: "decision-routine",
      type: "prose",
      conceptIds: ["ser_vs_estar_selection"],
      eyebrow: "A routine you can reuse",
      heading: "Do not stare at the blank. Read beyond it.",
      paragraphs: [
        "The words after the blank usually reveal the job: estudiante classifies, de Perú states origin, cansada presents a state, and en casa locates a person or thing. Context can also identify an event.",
        "Use the same short routine whenever both verbs seem possible.",
      ],
      points: [
        { label: "Read", title: "Take in the complete sentence", description: "Include the subject, the words after the verb, and any context around it." },
        { label: "Name", title: "Say the job in plain English", description: "Identity, classification, origin, state, location, or event details." },
        { label: "Choose", title: "Select the verb family", description: "Ser for identity, classification, origin, and events; estar for state and the location of people or things." },
        { label: "Match", title: "Conjugate for the subject", description: "Only after meaning is settled should you choose the exact form." },
      ],
    },
    {
      id: "meaning-sort",
      type: "sort",
      conceptIds: ["ser_classification", "ser_origin", "estar_state", "estar_location", "ser_vs_estar_selection"],
      eyebrow: "Guided practice",
      heading: "Sort the meaning before building the Spanish.",
      prompt: "Choose a meaning, then place it under the question it answers.",
      buckets: [
        { id: "ser", label: "SER", hint: "What is it? Where from?" },
        { id: "estar", label: "ESTAR", hint: "How or where is it?" },
      ],
      items: [
        { id: "teacher", label: "a teacher", answer: "ser" },
        { id: "kitchen", label: "in the kitchen", answer: "estar" },
        { id: "tired", label: "tired", answer: "estar" },
        { id: "friends", label: "friends", answer: "ser" },
        { id: "cuba", label: "from Cuba", answer: "ser" },
        { id: "school", label: "at school", answer: "estar" },
      ],
    },
    {
      id: "builder-school",
      type: "builder",
      conceptIds: ["estar_location", "ser_vs_estar_selection"],
      eyebrow: "Move into Spanish",
      heading: "Build after the meaning is settled.",
      prompt: "Build: We are at school.",
      tokens: ["la escuela", "estamos", "en"],
      correctOrder: ["estamos", "en", "la escuela"],
      answer: "Estamos en la escuela.",
      feedback: "The sentence locates nosotros, so it uses estar. Nosotros then selects estamos.",
    },
    {
      id: "reading-lucia",
      type: "reading",
      conceptIds: ["ser_identity", "ser_origin", "estar_state", "estar_location"],
      eyebrow: "Observe the system in context",
      heading: "One person, several true sentences.",
      instructions: "Read the Spanish as a connected portrait of Lucía. Tap any sentence to hear it, then answer before revealing the translation.",
      sentences: [
        { id: "r1", text: "Lucía es estudiante.", translation: "Lucía is a student." },
        { id: "r2", text: "Es de Colombia.", translation: "She is from Colombia." },
        { id: "r3", text: "Su universidad está en Miami.", translation: "Her university is in Miami." },
        { id: "r4", text: "Hoy Lucía está cansada, pero está bien.", translation: "Today Lucía is tired, but she is well." },
        { id: "r5", text: "Sus amigos están en la universidad.", translation: "Her friends are at the university." },
      ],
      questions: [
        {
          id: "rq1",
          prompt: "¿De dónde es Lucía?",
          options: [
            { id: "colombia", label: "Colombia" },
            { id: "miami", label: "Miami" },
          ],
          correctOptionId: "colombia",
          feedback: "Es de Colombia states Lucía’s origin, so it uses ser.",
          conceptIds: ["ser_origin"],
        },
        {
          id: "rq2",
          prompt: "¿Dónde está su universidad?",
          options: [
            { id: "colombia", label: "Colombia" },
            { id: "miami", label: "Miami" },
          ],
          correctOptionId: "miami",
          feedback: "Está en Miami locates the identified university.",
          conceptIds: ["estar_location"],
        },
        {
          id: "rq3",
          prompt: "Why does Lucía está cansada use estar?",
          options: [
            { id: "identity", label: "It identifies Lucía" },
            { id: "state", label: "It presents her state" },
          ],
          correctOptionId: "state",
          feedback: "Cansada describes how Lucía is, and its -a ending agrees with Lucía.",
          conceptIds: ["estar_state", "adjective_agreement"],
        },
      ],
    },
    {
      id: "context-synthesis",
      type: "prose",
      conceptIds: ["ser_identity", "ser_origin", "estar_state", "estar_location", "ser_vs_estar_selection"],
      eyebrow: "What the reading showed",
      heading: "Ser and estar cooperate. They are not competing descriptions.",
      paragraphs: [
        "The reading did not ask whether Lucía is fundamentally one kind of person or another. It assembled a fuller picture: what she is, where she is from, where her university and friends are, and how she feels today.",
        "Each sentence selected one job. Ser established student identity and Colombian origin. Estar located the university and friends and presented Lucía’s state. The verbs work together because the meanings are different.",
        "This is the habit to carry forward: decide what you want the listener to understand from this sentence—not what seems generally true about the subject.",
      ],
    },
    {
      id: "controlled-recall",
      type: "fill",
      conceptIds: ["ser_identity", "ser_origin", "estar_state", "estar_location", "ser_vs_estar_selection"],
      eyebrow: "Support disappears",
      heading: "Retrieve the verb and the form.",
      prompt: "Type the complete verb form. Accents are encouraged; a missing accent will not hide conceptual understanding in this prototype.",
      items: [
        {
          id: "f1",
          before: "Mi hermana ",
          after: " estudiante.",
          accepted: ["es"],
          answer: "es",
          conceptIds: ["ser_identity"],
          feedback: "Estudiante identifies what she is, so the sentence uses es.",
        },
        {
          id: "f2",
          before: "Mis padres ",
          after: " en casa.",
          accepted: ["están", "estan"],
          answer: "están",
          conceptIds: ["estar_location"],
          feedback: "En casa gives their location; mis padres selects the plural form están.",
        },
        {
          id: "f3",
          before: "Yo ",
          after: " cansado hoy.",
          accepted: ["estoy"],
          answer: "estoy",
          conceptIds: ["estar_state"],
          feedback: "Cansado presents a state, and yo selects estoy.",
        },
        {
          id: "f4",
          before: "Nosotros ",
          after: " amigos.",
          accepted: ["somos"],
          answer: "somos",
          conceptIds: ["ser_identity"],
          feedback: "Amigos identifies the relationship, and nosotros selects somos.",
        },
        {
          id: "f5",
          before: "Mis vecinos ",
          after: " de Guatemala.",
          accepted: ["son"],
          answer: "son",
          conceptIds: ["ser_origin"],
          feedback: "De Guatemala states origin, and the plural subject selects son.",
        },
      ],
    },
    {
      id: "original-writing",
      type: "free-write",
      conceptIds: ["ser_identity", "ser_classification", "estar_state", "estar_location", "ser_vs_estar_selection"],
      eyebrow: "Original Spanish",
      heading: "Use both verbs to build one fuller picture.",
      prompt: "Write two sentences about one person: identify, classify, or state the person’s origin with ser; then say how the person is today or where the person is with estar.",
      requirements: ["One complete idea with ser", "One complete idea with estar", "Forms that match the subject"],
      example: "Mi hermano es estudiante. Hoy está cansado.",
      minimumCharacters: 24,
    },
    {
      id: "final-retrieval",
      type: "fill",
      conceptIds: ["ser_classification", "estar_location", "ser_vs_estar_selection"],
      eyebrow: "Before you go",
      heading: "Retrieve the boundaries one last time.",
      prompt: "No choices. Name the job silently, then type the form.",
      items: [
        {
          id: "final1",
          before: "El libro ",
          after: " en la mesa.",
          accepted: ["está", "esta"],
          answer: "está",
          conceptIds: ["estar_location"],
          feedback: "The sentence locates an identified object, so it uses estar.",
        },
        {
          id: "final2",
          before: "María ",
          after: " profesora.",
          accepted: ["es"],
          answer: "es",
          conceptIds: ["ser_classification"],
          feedback: "Profesora classifies what María is, so it uses ser.",
        },
        {
          id: "final3",
          before: "La clase ",
          after: " en el salón tres.",
          accepted: ["es"],
          answer: "es",
          conceptIds: ["ser_vs_estar_selection"],
          feedback: "La clase is an event. Its location uses ser because the class takes place in room three.",
        },
      ],
    },
    {
      id: "keep-this-idea",
      type: "summary",
      conceptIds: ["ser_vs_estar_selection"],
      eyebrow: "Keep this idea",
      heading: "Let the intended meaning choose the verb.",
      message: "Read the whole sentence, name its job, choose the verb family, and only then match the form to the subject.",
      ideas: [
        { label: "SER", question: "What or who? From where? Which event?", uses: ["identity", "classification", "origin", "event details"] },
        { label: "ESTAR", question: "How? Where is the person or thing?", uses: ["state", "location"] },
      ],
    },
  ],
  completion: {
    title: "You can choose from the claim, not a shortcut.",
    message: "You separated identity, classification, origin, state, and location; matched the verb to its subject; and handled the event-location boundary.",
  },
};
