import type { LessonDefinition } from "@/content/schemas";

export const lesson44: LessonDefinition = {
  id: "4.4",
  moduleId: "module-04",
  title: "When SER and ESTAR Change Meaning",
  displayTitle: "The verb changes the picture.",
  dek: "With a small group of adjectives, ser and estar guide the listener toward different interpretations.",
  goal: "Interpret and produce the high-value contrasts aburrido/aburrida, listo/lista, and seguro/segura with ser or estar, using context and agreement rather than translation alone.",
  durationMinutes: 25,
  concepts: ["ser_estar_meaning_change", "ser_vs_estar_selection", "ser_classification", "estar_state", "adjective_agreement"],
  blocks: [
    {
      id: "l44-problem",
      type: "prose",
      conceptIds: ["ser_estar_meaning_change", "ser_vs_estar_selection"],
      eyebrow: "Start with interpretation",
      heading: "The adjective does not carry the whole meaning by itself.",
      paragraphs: [
        "In English, one adjective often has to be replaced by a different word when the interpretation changes: boring versus bored, clever versus ready, safe versus sure. Spanish can keep the same adjective and let the verb help frame the claim.",
        "Diego es aburrido presents boring as a description of Diego: he bores people. Diego está aburrido presents Diego’s state: he feels bored.",
        "The verb is not mechanically changing a dictionary definition. Ser and estar contribute their usual perspectives—classification or characteristic with ser, state or condition with estar—and context completes the interpretation.",
      ],
      spanish: [
        { text: "Diego es aburrido.", translation: "Diego is boring." },
        { text: "Diego está aburrido.", translation: "Diego is bored." },
      ],
    },
    {
      id: "l44-predict-aburrido",
      type: "choice",
      conceptIds: ["ser_estar_meaning_change", "estar_state"],
      eyebrow: "Predict from the situation",
      heading: "There is nothing to do, and Diego feels bored.",
      context: "The sentence presents Diego’s current state, not the effect his personality has on other people.",
      prompt: "Which verb completes the intended meaning?",
      sentence: { before: "Diego ", after: " aburrido." },
      options: [
        { id: "es", label: "es" },
        { id: "esta", label: "está" },
      ],
      correctOptionId: "esta",
      correctFeedback: "Estar frames aburrido as Diego’s state: he is bored.",
      incorrectFeedback: "Es aburrido would describe Diego as boring. The context says he feels bored, so use está.",
    },
    {
      id: "l44-aburrido-contrast",
      type: "comparison",
      conceptIds: ["ser_estar_meaning_change", "ser_classification", "estar_state"],
      eyebrow: "Contrast one",
      heading: "Aburrido: causing boredom or experiencing it.",
      sides: [
        {
          label: "SER + ABURRIDO",
          question: "What kind of person or thing is it?",
          description: "The subject is presented as boring—as something that causes boredom.",
          examples: [
            { text: "Diego es aburrido.", translation: "Diego is boring." },
            { text: "La película es aburrida.", translation: "The movie is boring." },
          ],
        },
        {
          label: "ESTAR + ABURRIDO",
          question: "How does the person feel?",
          description: "The person is in the state of feeling bored.",
          examples: [
            { text: "Diego está aburrido.", translation: "Diego is bored." },
            { text: "Las estudiantes están aburridas.", translation: "The students are bored." },
          ],
        },
      ],
      note: "Agreement still applies: película is aburrida; las estudiantes are aburridas.",
    },
    {
      id: "l44-predict-movie",
      type: "choice",
      conceptIds: ["ser_estar_meaning_change", "ser_classification", "adjective_agreement"],
      eyebrow: "Apply the contrast",
      heading: "The movie is boring.",
      context: "The movie causes boredom; it is not a person experiencing the feeling.",
      prompt: "Which complete phrase expresses that meaning?",
      sentence: { before: "La película ", after: "." },
      options: [
        { id: "es-aburrida", label: "es aburrida" },
        { id: "esta-aburrida", label: "está aburrida" },
        { id: "es-aburrido", label: "es aburrido" },
      ],
      correctOptionId: "es-aburrida",
      correctFeedback: "Ser presents the movie as boring, and aburrida agrees with película.",
      incorrectFeedback: "Choose ser for something that causes boredom, then make aburrida agree with la película.",
    },
    {
      id: "l44-listo",
      type: "prose",
      conceptIds: ["ser_estar_meaning_change", "ser_classification", "estar_state"],
      eyebrow: "Contrast two",
      heading: "Listo can describe ability or readiness.",
      paragraphs: [
        "Ana es lista describes Ana as clever or intelligent. Ser frames listo as a characteristic attributed to the person.",
        "Ana está lista says Ana is ready. Estar frames listo as the state of being prepared for the next action.",
        "Context usually confirms the intended reading. Para salir—ready to leave—strongly supports the readiness meaning and therefore estar.",
      ],
      spanish: [
        { text: "Ana es lista.", translation: "Ana is clever." },
        { text: "Ana está lista para salir.", translation: "Ana is ready to leave." },
        { text: "Estamos listos.", translation: "We are ready." },
      ],
    },
    {
      id: "l44-predict-listo",
      type: "choice",
      conceptIds: ["ser_estar_meaning_change", "estar_state", "adjective_agreement"],
      eyebrow: "Read the context",
      heading: "We are ready.",
      context: "The group is prepared to begin. This is a state of readiness.",
      prompt: "Which phrase fits the meaning and subject?",
      sentence: { before: "Nosotros ", after: "." },
      options: [
        { id: "somos-listos", label: "somos listos" },
        { id: "estamos-listos", label: "estamos listos" },
        { id: "estan-listos", label: "están listos" },
      ],
      correctOptionId: "estamos-listos",
      correctFeedback: "Readiness uses estar, nosotros selects estamos, and listos agrees with the group.",
      incorrectFeedback: "The intended meaning is ready, not clever. Use estar and match nosotros: estamos listos.",
    },
    {
      id: "l44-seguro",
      type: "comparison",
      conceptIds: ["ser_estar_meaning_change", "ser_classification", "estar_state"],
      eyebrow: "Contrast three",
      heading: "Seguro: safe or certain.",
      sides: [
        {
          label: "SER + SEGURO",
          question: "Is the person, place, or thing safe?",
          description: "Ser frames safety as a quality of the subject in the context.",
          examples: [
            { text: "El barrio es seguro.", translation: "The neighborhood is safe." },
            { text: "La escuela es segura.", translation: "The school is safe." },
          ],
        },
        {
          label: "ESTAR + SEGURO",
          question: "Is someone certain or sure?",
          description: "With a person, estar seguro commonly expresses certainty.",
          examples: [
            { text: "Estoy seguro.", translation: "I am sure." },
            { text: "Ana está segura.", translation: "Ana is sure." },
          ],
        },
      ],
      note: "Context can support other readings, but safe with ser and sure with estar is the high-value contrast to control now.",
    },
    {
      id: "l44-predict-seguro",
      type: "choice",
      conceptIds: ["ser_estar_meaning_change", "estar_state", "adjective_agreement"],
      eyebrow: "Use the intended claim",
      heading: "María is sure.",
      context: "María feels certain about an answer. The sentence does not evaluate whether María is safe.",
      prompt: "Which phrase expresses certainty?",
      sentence: { before: "María ", after: "." },
      options: [
        { id: "es-segura", label: "es segura" },
        { id: "esta-segura", label: "está segura" },
        { id: "esta-seguro", label: "está seguro" },
      ],
      correctOptionId: "esta-segura",
      correctFeedback: "Estar seguro expresses certainty, and segura agrees with María.",
      incorrectFeedback: "The meaning is certain, so choose estar; the adjective must be feminine segura for María.",
    },
    {
      id: "l44-not-magic",
      type: "prose",
      conceptIds: ["ser_estar_meaning_change", "ser_vs_estar_selection"],
      eyebrow: "A precise caution",
      heading: "Do not memorize two English words and stop reading the sentence.",
      paragraphs: [
        "The pairs boring/bored, clever/ready, and safe/sure are useful summaries. They are not automatic substitutions that erase context.",
        "Ser and estar still contribute their broader jobs. Ser presents a classification or attributed quality. Estar presents a state or condition. The adjective and surrounding words help the listener settle on the intended interpretation.",
        "This is why para salir matters in Ana está lista para salir and why a place subject supports safe in El barrio es seguro.",
      ],
      points: [
        { label: "CONTEXT", title: "What situation is being described?", description: "Look for clues such as para salir, no hay nada que hacer, or a place being evaluated." },
        { label: "PERSPECTIVE", title: "Quality or state?", description: "Ser attributes a quality; estar presents the subject in a state or condition." },
        { label: "AGREEMENT", title: "Who has the adjective?", description: "After choosing the meaning, make the adjective fit the subject." },
      ],
    },
    {
      id: "l44-meaning-sort",
      type: "sort",
      conceptIds: ["ser_estar_meaning_change"],
      eyebrow: "Guided practice",
      heading: "Sort interpretations, not isolated verbs.",
      prompt: "Choose an English interpretation, then place it under the Spanish perspective that expresses it.",
      buckets: [
        { id: "ser", label: "SER + ADJECTIVE", hint: "attributed quality or classification" },
        { id: "estar", label: "ESTAR + ADJECTIVE", hint: "state, readiness, or certainty" },
      ],
      items: [
        { id: "l44-sort-boring", label: "boring", answer: "ser" },
        { id: "l44-sort-bored", label: "bored", answer: "estar" },
        { id: "l44-sort-clever", label: "clever", answer: "ser" },
        { id: "l44-sort-ready", label: "ready", answer: "estar" },
        { id: "l44-sort-safe", label: "safe", answer: "ser" },
        { id: "l44-sort-sure", label: "sure", answer: "estar" },
      ],
    },
    {
      id: "l44-builder",
      type: "builder",
      conceptIds: ["ser_estar_meaning_change", "estar_state", "adjective_agreement"],
      eyebrow: "Build from context",
      heading: "Express readiness, not intelligence.",
      prompt: "Build: Ana is ready to leave.",
      tokens: ["Ana", "está", "lista", "para salir."],
      correctOrder: ["Ana", "está", "lista", "para salir."],
      answer: "Ana está lista para salir.",
      feedback: "Para salir confirms readiness, so estar frames lista as prepared rather than clever.",
    },
    {
      id: "l44-reading",
      type: "reading",
      conceptIds: ["ser_estar_meaning_change", "ser_vs_estar_selection", "adjective_agreement"],
      eyebrow: "Read a scene, not a word list",
      heading: "Before a neighborhood event.",
      instructions: "Use each surrounding sentence to decide how the adjective is being interpreted. Listen before revealing the translation.",
      sentences: [
        { id: "l44-r1", text: "El barrio es seguro y tranquilo.", translation: "The neighborhood is safe and calm." },
        { id: "l44-r2", text: "Ana y Luis están listos para la reunión.", translation: "Ana and Luis are ready for the meeting." },
        { id: "l44-r3", text: "Luis es listo y organiza todo muy bien.", translation: "Luis is clever and organizes everything very well." },
        { id: "l44-r4", text: "Ana está segura de la dirección.", translation: "Ana is sure of the address." },
        { id: "l44-r5", text: "Los niños están aburridos, pero la música no es aburrida.", translation: "The children are bored, but the music is not boring." },
      ],
      questions: [
        {
          id: "l44-q1",
          prompt: "What does están listos mean here?",
          options: [{ id: "ready", label: "They are ready" }, { id: "clever", label: "They are clever" }],
          correctOptionId: "ready",
          feedback: "The meeting context and estar frame listos as ready.",
          conceptIds: ["ser_estar_meaning_change"],
        },
        {
          id: "l44-q2",
          prompt: "Why does Luis es listo use ser?",
          options: [{ id: "ability", label: "It attributes cleverness" }, { id: "ready", label: "It says he is ready now" }],
          correctOptionId: "ability",
          feedback: "The following idea about organizing well supports cleverness as an attributed quality.",
          conceptIds: ["ser_estar_meaning_change", "ser_classification"],
        },
        {
          id: "l44-q3",
          prompt: "Who or what is boring?",
          options: [{ id: "music", label: "The music" }, { id: "children", label: "The children" }],
          correctOptionId: "music",
          feedback: "The children experience boredom; the music is evaluated as not boring.",
          conceptIds: ["ser_estar_meaning_change"],
        },
      ],
    },
    {
      id: "l44-synthesis",
      type: "prose",
      conceptIds: ["ser_estar_meaning_change", "ser_vs_estar_selection"],
      eyebrow: "Synthesize the contrast",
      heading: "The verb asks the listener to view the adjective through a particular lens.",
      paragraphs: [
        "Ser asks the listener to treat the adjective as an attributed quality or classification: boring, clever, safe. Estar asks the listener to treat it as a state or condition: bored, ready, sure.",
        "You still need context and agreement. The interpretation is a collaboration among the verb, adjective, subject, and surrounding situation.",
      ],
      spanish: [
        { text: "La película es aburrida, y nosotros estamos aburridos.", translation: "The movie is boring, and we are bored." },
        { text: "Luis es listo, y está listo para empezar.", translation: "Luis is clever, and he is ready to begin." },
      ],
    },
    {
      id: "l44-controlled-recall",
      type: "fill",
      conceptIds: ["ser_estar_meaning_change", "ser_vs_estar_selection", "adjective_agreement"],
      eyebrow: "Recall without labels",
      heading: "Let the English meaning and context select the verb.",
      prompt: "Type the missing form of ser or estar.",
      items: [
        { id: "l44-fill-1", before: "Diego ", after: " aburrido. (He is bored.)", accepted: ["está", "esta"], answer: "está", conceptIds: ["ser_estar_meaning_change", "estar_state"], feedback: "Bored is Diego’s state, so use está." },
        { id: "l44-fill-2", before: "La película ", after: " aburrida. (It is boring.)", accepted: ["es"], answer: "es", conceptIds: ["ser_estar_meaning_change", "ser_classification"], feedback: "The movie is evaluated as boring, so use es." },
        { id: "l44-fill-3", before: "Nosotros ", after: " listos para salir.", accepted: ["estamos"], answer: "estamos", conceptIds: ["ser_estar_meaning_change", "estar_state"], feedback: "Para salir signals readiness; nosotros selects estamos." },
        { id: "l44-fill-4", before: "El barrio ", after: " seguro.", accepted: ["es"], answer: "es", conceptIds: ["ser_estar_meaning_change", "ser_classification"], feedback: "The sentence evaluates the neighborhood as safe, so use es." },
        { id: "l44-fill-5", before: "María ", after: " segura de la respuesta.", accepted: ["está", "esta"], answer: "está", conceptIds: ["ser_estar_meaning_change", "estar_state"], feedback: "Segura de la respuesta expresses certainty, so use está." },
      ],
    },
    {
      id: "l44-original-writing",
      type: "free-write",
      conceptIds: ["ser_estar_meaning_change", "ser_vs_estar_selection", "adjective_agreement"],
      eyebrow: "Produce a real contrast",
      heading: "Keep one adjective and change the interpretation.",
      prompt: "Write two connected sentences using the same target adjective—aburrido, listo, or seguro—once with ser and once with estar.",
      requirements: ["Use one form of ser", "Use one form of estar", "Repeat the same target adjective with agreement", "Make the two meanings clear from context"],
      example: "Luis es listo. Está listo para la clase.",
      minimumCharacters: 30,
      evaluation: {
        minimumIdeas: 2,
        requiredGroups: [
          { accepted: ["soy", "eres", "es", "somos", "son"], missingFeedback: "Use a form of ser for the attributed quality." },
          { accepted: ["estoy", "estás", "estas", "está", "esta", "estamos", "están", "estan"], missingFeedback: "Use a form of estar for the state or condition." },
          { accepted: ["aburrido", "aburrida", "aburridos", "aburridas", "listo", "lista", "listos", "listas", "seguro", "segura", "seguros", "seguras"], missingFeedback: "Use aburrido, listo, or seguro in forms that agree with the subjects." },
        ],
        successFeedback: "Your contrast uses the verb and context together to change how the repeated adjective is understood.",
      },
    },
    {
      id: "l44-final-retrieval",
      type: "fill",
      conceptIds: ["ser_estar_meaning_change"],
      eyebrow: "Final retrieval",
      heading: "Recover all three high-value contrasts.",
      prompt: "Complete each sentence from the intended interpretation.",
      items: [
        { id: "l44-final-1", before: "La clase ", after: " aburrida. (boring)", accepted: ["es"], answer: "es", conceptIds: ["ser_estar_meaning_change"], feedback: "Something that causes boredom is presented with ser." },
        { id: "l44-final-2", before: "Ana ", after: " lista para salir. (ready)", accepted: ["está", "esta"], answer: "está", conceptIds: ["ser_estar_meaning_change"], feedback: "Readiness is presented as a state with estar." },
        { id: "l44-final-3", before: "Yo ", after: " seguro. (sure)", accepted: ["estoy"], answer: "estoy", conceptIds: ["ser_estar_meaning_change"], feedback: "Certainty uses estar seguro; yo selects estoy." },
      ],
    },
    {
      id: "l44-summary",
      type: "summary",
      conceptIds: ["ser_estar_meaning_change", "ser_vs_estar_selection"],
      eyebrow: "Keep the interpretations connected",
      heading: "Verb, adjective, and context create the meaning together.",
      message: "Use these three pairs as controlled examples of a larger principle: ser attributes a quality; estar presents a state or condition.",
      ideas: [
        { label: "ABURRIDO", question: "Cause boredom or experience it?", uses: ["ser = boring", "estar = bored"] },
        { label: "LISTO", question: "Clever or prepared?", uses: ["ser = clever", "estar = ready"] },
        { label: "SEGURO", question: "Safe or certain?", uses: ["ser = safe", "estar = sure"] },
      ],
    },
  ],
  completion: {
    title: "You can hear the meaning the verb adds.",
    message: "You interpreted aburrido, listo, and seguro through ser or estar, used context to confirm the reading, and maintained agreement in your own contrast.",
  },
};
