import type { LessonDefinition } from "@/content/schemas";

export const lesson45: LessonDefinition = {
  id: "4.5",
  moduleId: "module-04",
  title: "HAY vs. ESTAR",
  displayTitle: "Introduce what exists. Then locate what is known.",
  dek: "Hay and estar can both appear with places, but they answer different questions about reference.",
  goal: "Use hay to present existence or presence, use estar to locate an identified subject, keep hay unchanged with singular and plural nouns, and connect the two perspectives in a short description.",
  durationMinutes: 27,
  concepts: ["hay_existence", "hay_vs_estar", "estar_location", "estar_forms"],
  blocks: [
    {
      id: "l45-problem",
      type: "prose",
      conceptIds: ["hay_existence", "hay_vs_estar", "estar_location"],
      eyebrow: "Start with the information job",
      heading: "A place phrase does not automatically mean the sentence should use estar.",
      paragraphs: [
        "Compare There is a restaurant in the city with The restaurant is in the city center. Both sentences mention location, but they do different work in the conversation.",
        "The first introduces the existence or presence of a restaurant. Spanish uses hay: Hay un restaurante en la ciudad. The second assumes the restaurant is identifiable and tells where it is. Spanish uses estar: El restaurante está en el centro.",
        "The key decision is not whether a location appears. Ask whether you are presenting that something exists or locating a subject the listener can already identify.",
      ],
      spanish: [
        { text: "Hay un restaurante en la ciudad.", translation: "There is a restaurant in the city." },
        { text: "El restaurante está en el centro.", translation: "The restaurant is downtown." },
      ],
    },
    {
      id: "l45-predict-first",
      type: "choice",
      conceptIds: ["hay_existence", "hay_vs_estar"],
      eyebrow: "Predict the job",
      heading: "There are two books on the table.",
      context: "The listener has not been told about the books yet. The sentence presents that they are present.",
      prompt: "Which opening expresses existence?",
      sentence: { before: "", after: " dos libros en la mesa." },
      options: [
        { id: "hay", label: "Hay" },
        { id: "estan", label: "Están" },
        { id: "son", label: "Son" },
      ],
      correctOptionId: "hay",
      correctFeedback: "Hay introduces that two books are present. No identified subject appears before the verb.",
      incorrectFeedback: "The books are being introduced, not referred back to as los libros. Use hay for existence.",
    },
    {
      id: "l45-hay-form",
      type: "prose",
      conceptIds: ["hay_existence"],
      eyebrow: "Meet hay",
      heading: "Hay is one impersonal form for both singular and plural existence.",
      paragraphs: [
        "Hay comes from the verb haber, but at this level its most useful job is a complete pattern: hay + what exists or is present. It often corresponds to there is or there are.",
        "The form does not change when the following noun becomes plural. Hay un libro and Hay dos libros both use hay. The noun phrase tells you how many; hay remains hay.",
        "Because hay is impersonal here, do not create a plural form to agree with dos libros. Forms such as han do other grammatical work and do not replace hay in this pattern.",
      ],
      points: [
        { label: "ONE", title: "Hay un libro.", description: "There is one book." },
        { label: "MORE", title: "Hay dos libros.", description: "There are two books; hay does not become plural." },
        { label: "NO", title: "No hay libros.", description: "No before hay says that books are not present." },
      ],
      spanish: [
        { text: "Hay una escuela.", translation: "There is a school." },
        { text: "Hay tres restaurantes.", translation: "There are three restaurants." },
        { text: "No hay libros aquí.", translation: "There are no books here." },
      ],
    },
    {
      id: "l45-predict-number",
      type: "choice",
      conceptIds: ["hay_existence"],
      eyebrow: "Keep the form stable",
      heading: "There are three restaurants.",
      context: "The noun phrase is plural, but existential hay does not agree with it.",
      prompt: "Which form completes the sentence?",
      sentence: { before: "", after: " tres restaurantes." },
      options: [
        { id: "hay", label: "Hay" },
        { id: "han", label: "Han" },
        { id: "estan", label: "Están" },
      ],
      correctOptionId: "hay",
      correctFeedback: "Hay remains unchanged with tres restaurantes.",
      incorrectFeedback: "The number lives in tres restaurantes. The existential form itself stays hay.",
    },
    {
      id: "l45-reference-shift",
      type: "comparison",
      conceptIds: ["hay_existence", "hay_vs_estar", "estar_location"],
      eyebrow: "The central contrast",
      heading: "Introduce it with hay. Locate it with estar.",
      sides: [
        {
          label: "HAY",
          question: "What exists or is present?",
          description: "Present something as new information, often with an indefinite noun phrase, a number, or no article.",
          examples: [
            { text: "Hay un libro en la mesa.", translation: "There is a book on the table." },
            { text: "Hay estudiantes en la biblioteca.", translation: "There are students in the library." },
          ],
        },
        {
          label: "ESTAR",
          question: "Where is the identified subject?",
          description: "Refer to a known person or thing as the subject, then give its location.",
          examples: [
            { text: "El libro está aquí.", translation: "The book is here." },
            { text: "Los estudiantes están en la biblioteca.", translation: "The students are in the library." },
          ],
        },
      ],
      note: "The article shift is a helpful clue, not the definition. The underlying difference is new existence versus identified location.",
    },
    {
      id: "l45-predict-reference",
      type: "choice",
      conceptIds: ["hay_vs_estar", "estar_location", "estar_forms"],
      eyebrow: "Follow the reference",
      heading: "You already mentioned a restaurant. Now say it is here.",
      context: "El restaurante refers back to the identified restaurant and becomes the subject of the location sentence.",
      prompt: "Which form completes the second sentence?",
      sentence: { before: "El restaurante ", after: " aquí." },
      options: [
        { id: "hay", label: "hay" },
        { id: "esta", label: "está" },
        { id: "estan", label: "están" },
      ],
      correctOptionId: "esta",
      correctFeedback: "The identified singular subject el restaurante is located with está.",
      incorrectFeedback: "Hay would introduce existence again. El restaurante is already identified, so locate it with está.",
    },
    {
      id: "l45-location-with-hay",
      type: "prose",
      conceptIds: ["hay_existence", "hay_vs_estar"],
      eyebrow: "A common source of confusion",
      heading: "Hay can include a place and still express existence.",
      paragraphs: [
        "Hay un libro en la mesa includes en la mesa, but its main information job is still to announce that a book is present there. A location phrase does not force estar.",
        "El libro está en la mesa begins with an identified subject. Its main information job is to locate that particular book.",
        "Ask what the listener learns first: that a thing exists, or where a known thing is. This question remains reliable even when both sentences mention the same place.",
      ],
      spanish: [
        { text: "Hay un libro en la mesa.", translation: "There is a book on the table." },
        { text: "El libro está en la mesa.", translation: "The book is on the table." },
      ],
    },
    {
      id: "l45-predict-place",
      type: "choice",
      conceptIds: ["hay_existence", "hay_vs_estar"],
      eyebrow: "Choose the information job",
      heading: "There is a school in the city.",
      context: "The school is new information. The sentence announces its existence in the city.",
      prompt: "Which form belongs at the beginning?",
      sentence: { before: "", after: " una escuela en la ciudad." },
      options: [
        { id: "hay", label: "Hay" },
        { id: "esta", label: "Está" },
        { id: "es", label: "Es" },
      ],
      correctOptionId: "hay",
      correctFeedback: "Hay introduces una escuela as something that exists in the city.",
      incorrectFeedback: "Una escuela is being introduced, not used as an identified subject. Choose hay.",
    },
    {
      id: "l45-article-clue",
      type: "prose",
      conceptIds: ["hay_existence", "hay_vs_estar", "estar_location"],
      eyebrow: "Clue, not command",
      heading: "Un and el often reveal the reference shift, but meaning remains in charge.",
      paragraphs: [
        "Hay un restaurante often introduces a restaurant. El restaurante está aquí then uses a definite article because both speakers can identify the restaurant being located.",
        "Hay also works with numbers and bare plurals: Hay dos libros; Hay estudiantes. Estar also works with names and possessives: Ana está aquí; Mi libro está en casa.",
        "So articles help you notice the pattern, but do not memorize un equals hay and el equals estar as an absolute rule. Ask the existence-or-location question first.",
      ],
      points: [
        { label: "NEW", title: "Hay un restaurante.", description: "The restaurant enters the conversation as new information." },
        { label: "KNOWN", title: "El restaurante está aquí.", description: "The now-identifiable restaurant becomes the subject being located." },
        { label: "OTHER CLUES", title: "Hay dos libros. Ana está aquí.", description: "Numbers, bare plurals, names, and possessives show why the article is only a clue." },
      ],
    },
    {
      id: "l45-job-sort",
      type: "sort",
      conceptIds: ["hay_existence", "hay_vs_estar", "estar_location"],
      eyebrow: "Guided practice",
      heading: "Sort the information the listener receives.",
      prompt: "Choose a message, then place it under the question it answers.",
      buckets: [
        { id: "existence", label: "WHAT IS PRESENT?", hint: "introduce existence with hay" },
        { id: "location", label: "WHERE IS IT?", hint: "locate an identified subject with estar" },
      ],
      items: [
        { id: "l45-sort-a-book", label: "There is a book", answer: "existence" },
        { id: "l45-sort-the-book", label: "The book is here", answer: "location" },
        { id: "l45-sort-students", label: "There are students", answer: "existence" },
        { id: "l45-sort-my-friends", label: "My friends are at school", answer: "location" },
        { id: "l45-sort-no-restaurants", label: "There are no restaurants", answer: "existence" },
        { id: "l45-sort-ana", label: "Ana is at home", answer: "location" },
      ],
    },
    {
      id: "l45-builder",
      type: "builder",
      conceptIds: ["hay_existence", "hay_vs_estar"],
      eyebrow: "Introduce first",
      heading: "Build the opening of a two-sentence description.",
      prompt: "Build: There is a restaurant in the city.",
      tokens: ["Hay", "un restaurante", "en la ciudad."],
      correctOrder: ["Hay", "un restaurante", "en la ciudad."],
      answer: "Hay un restaurante en la ciudad.",
      feedback: "Hay introduces un restaurante, and en la ciudad adds where that existence is relevant.",
    },
    {
      id: "l45-decision-routine",
      type: "prose",
      conceptIds: ["hay_existence", "hay_vs_estar", "estar_forms", "estar_location"],
      eyebrow: "A repeatable routine",
      heading: "Decide reference before choosing the verb.",
      paragraphs: [
        "If the sentence presents that something exists or is present, use hay and do not change it for number. If the sentence begins from an identifiable subject and asks where it is, use estar and match the form to that subject.",
        "A connected description often moves naturally from one perspective to the other: introduce, then locate.",
      ],
      points: [
        { label: "01", title: "Is this new existence?", description: "Use hay for what exists or is present." },
        { label: "02", title: "Or is the subject already identified?", description: "Use estar to locate the known person, place, or thing." },
        { label: "03", title: "Does the form agree?", description: "Hay stays hay; estar changes to match its subject." },
        { label: "04", title: "Can the ideas connect?", description: "Introduce with hay, then refer back with a definite or otherwise identified subject + estar." },
      ],
    },
    {
      id: "l45-reading",
      type: "reading",
      conceptIds: ["hay_existence", "hay_vs_estar", "estar_location", "estar_forms"],
      eyebrow: "Read the reference shift",
      heading: "A new neighborhood.",
      instructions: "Notice when each place first enters the description and when it becomes an identified subject. Listen before opening the translation.",
      sentences: [
        { id: "l45-r1", text: "Hay una escuela en el barrio.", translation: "There is a school in the neighborhood." },
        { id: "l45-r2", text: "La escuela está en el centro.", translation: "The school is downtown." },
        { id: "l45-r3", text: "Hay dos restaurantes cerca de la escuela.", translation: "There are two restaurants near the school." },
        { id: "l45-r4", text: "Los restaurantes están en una calle tranquila.", translation: "The restaurants are on a quiet street." },
        { id: "l45-r5", text: "No hay una biblioteca, pero hay muchos libros en la escuela.", translation: "There is no library, but there are many books in the school." },
      ],
      questions: [
        {
          id: "l45-q1",
          prompt: "Why does the first sentence use hay?",
          options: [{ id: "introduces", label: "It introduces a school" }, { id: "locates-known", label: "It locates an identified school" }],
          correctOptionId: "introduces",
          feedback: "Una escuela enters the description as new existence.",
          conceptIds: ["hay_existence", "hay_vs_estar"],
        },
        {
          id: "l45-q2",
          prompt: "Why does the next sentence use está?",
          options: [{ id: "known-school", label: "La escuela is now identified" }, { id: "singular-hay", label: "Hay changes for singular" }],
          correctOptionId: "known-school",
          feedback: "La escuela refers back to the introduced school and locates that identified subject.",
          conceptIds: ["hay_vs_estar", "estar_location"],
        },
        {
          id: "l45-q3",
          prompt: "Why does hay stay singular-looking before muchos libros?",
          options: [{ id: "unchanged", label: "Hay does not agree with number" }, { id: "books-singular", label: "Libros is singular" }],
          correctOptionId: "unchanged",
          feedback: "Existential hay stays hay whether one thing or many things follow.",
          conceptIds: ["hay_existence"],
        },
      ],
    },
    {
      id: "l45-synthesis",
      type: "prose",
      conceptIds: ["hay_existence", "hay_vs_estar", "estar_location"],
      eyebrow: "Bring the perspectives together",
      heading: "Hay opens a reference. Estar continues it.",
      paragraphs: [
        "Hay una escuela asks the listener to add a school to the shared picture. La escuela está en el centro then takes that school as known and places it more precisely.",
        "This introduce-then-locate sequence is one of the most useful ways to build connected beginner Spanish. It turns two short sentences into a coherent description rather than two isolated grammar demonstrations.",
      ],
      spanish: [
        { text: "Hay un libro en la mesa. El libro está aquí.", translation: "There is a book on the table. The book is here." },
        { text: "Hay dos restaurantes. Los restaurantes están en el centro.", translation: "There are two restaurants. The restaurants are downtown." },
      ],
    },
    {
      id: "l45-controlled-recall",
      type: "fill",
      conceptIds: ["hay_existence", "hay_vs_estar", "estar_forms", "estar_location"],
      eyebrow: "Recall without choices",
      heading: "Choose existence or identified location.",
      prompt: "Type hay or the correct form of estar.",
      items: [
        { id: "l45-fill-1", before: "", after: " un restaurante en la ciudad.", accepted: ["hay"], answer: "Hay", conceptIds: ["hay_existence"], feedback: "Un restaurante is introduced as new existence: hay." },
        { id: "l45-fill-2", before: "El restaurante ", after: " en el centro.", accepted: ["está", "esta"], answer: "está", conceptIds: ["hay_vs_estar", "estar_location"], feedback: "El restaurante is identified and singular, so locate it with está." },
        { id: "l45-fill-3", before: "", after: " tres libros en la mesa.", accepted: ["hay"], answer: "Hay", conceptIds: ["hay_existence"], feedback: "Hay remains unchanged before the plural phrase tres libros." },
        { id: "l45-fill-4", before: "Los libros ", after: " aquí.", accepted: ["están", "estan"], answer: "están", conceptIds: ["hay_vs_estar", "estar_forms", "estar_location"], feedback: "The identified plural books are located with están." },
        { id: "l45-fill-5", before: "No ", after: " una biblioteca.", accepted: ["hay"], answer: "hay", conceptIds: ["hay_existence"], feedback: "No hay says that a library is not present." },
      ],
    },
    {
      id: "l45-original-writing",
      type: "free-write",
      conceptIds: ["hay_existence", "hay_vs_estar", "estar_location", "estar_forms"],
      eyebrow: "Produce connected Spanish",
      heading: "Introduce something, then locate it.",
      prompt: "Write two connected sentences about a room, home, school, or city. First introduce something with hay; then refer back to it and locate it with estar.",
      requirements: ["Begin one idea with hay", "Refer back with an identified subject", "Use a correct form of estar", "Include a clear location"],
      example: "Hay una biblioteca en mi escuela. La biblioteca está en el centro de la escuela.",
      minimumCharacters: 42,
      evaluation: {
        minimumIdeas: 2,
        requiredGroups: [
          { accepted: ["hay"], missingFeedback: "Use hay to introduce what exists or is present." },
          { accepted: ["estoy", "estás", "estas", "está", "esta", "estamos", "están", "estan"], missingFeedback: "Use a form of estar to locate the now-identified subject." },
          { accepted: ["aquí", "aqui", "en casa", "en la escuela", "en la ciudad", "en la mesa", "en el centro", "en el barrio", "en la biblioteca", "en el restaurante"], missingFeedback: "Add a clear place expression to the description." },
        ],
        successFeedback: "Your description introduces existence with hay and then shifts naturally to an identified subject + estar location.",
      },
    },
    {
      id: "l45-final-retrieval",
      type: "fill",
      conceptIds: ["hay_existence", "hay_vs_estar", "estar_location"],
      eyebrow: "Final retrieval",
      heading: "Keep reference—not the article alone—in charge.",
      prompt: "Complete the connected pairs.",
      items: [
        { id: "l45-final-1", before: "", after: " una escuela. La escuela está aquí.", accepted: ["hay"], answer: "Hay", conceptIds: ["hay_existence", "hay_vs_estar"], feedback: "The first sentence introduces the school with hay." },
        { id: "l45-final-2", before: "Hay dos libros. Los libros ", after: " en la mesa.", accepted: ["están", "estan"], answer: "están", conceptIds: ["hay_vs_estar", "estar_location"], feedback: "The second sentence locates the now-identified plural books with están." },
        { id: "l45-final-3", before: "No ", after: " restaurantes aquí.", accepted: ["hay"], answer: "hay", conceptIds: ["hay_existence"], feedback: "No hay expresses that restaurants are not present." },
      ],
    },
    {
      id: "l45-summary",
      type: "summary",
      conceptIds: ["hay_existence", "hay_vs_estar", "estar_forms", "estar_location"],
      eyebrow: "Keep the reference path",
      heading: "Existence first. Identified location second.",
      message: "Hay presents what exists or is present and never changes for number. Estar locates an identifiable subject and agrees with it.",
      ideas: [
        { label: "HAY", question: "What exists or is present?", uses: ["hay un/una", "hay numbers", "hay bare plurals", "no hay"] },
        { label: "ESTAR", question: "Where is the known subject?", uses: ["identified subject", "está", "están", "location"] },
        { label: "CONNECT", question: "How does the description advance?", uses: ["introduce", "refer back", "locate"] },
      ],
    },
  ],
  completion: {
    title: "You can introduce a world and then map it.",
    message: "You used hay for existence, kept it unchanged with plural nouns, shifted to identified subjects with estar, and produced a connected introduce-then-locate description.",
  },
};
