import type { LessonDefinition } from "@/content/schemas";

export const stage01Checkpoint: LessonDefinition = {
  id: "stage-01-checkpoint",
  moduleId: "stage-01",
  title: "Build Spanish",
  displayTitle: "Bring the foundations together.",
  dek: "Read, interpret, construct, recall, and produce across the ideas from Stage I’s four modules.",
  goal: "Demonstrate control of noun and adjective agreement, ser for identity and origin, estar for states and locations, and hay for existence in connected beginner Spanish.",
  durationMinutes: 32,
  concepts: [
    "gender_agreement",
    "adjective_agreement",
    "ser_identity",
    "ser_classification",
    "ser_origin",
    "estar_forms",
    "estar_state",
    "estar_location",
    "ser_vs_estar_selection",
    "ser_estar_meaning_change",
    "hay_existence",
    "hay_vs_estar",
  ],
  experience: {
    kind: "checkpoint",
    contextLabel: "Stage I · Checkpoint",
    openingMarker: "I / 04",
    returnHref: "/module/4",
    returnLabel: "Module 4",
  },
  blocks: [
    {
      id: "s1-orientation",
      type: "prose",
      conceptIds: ["gender_agreement", "adjective_agreement", "ser_vs_estar_selection", "hay_vs_estar"],
      eyebrow: "How this checkpoint works",
      heading: "The labels disappear; the meaning has to guide you.",
      paragraphs: [
        "This checkpoint combines the foundations from Modules 1–4. You will not complete one isolated section for articles, another for agreement, and another for verbs. Real sentences require those decisions to cooperate.",
        "Read and listen for the message first. Then control the noun phrase, choose ser, estar, or hay from the information job, and make every form agree where agreement applies.",
        "Your first attempts and unsupported recall determine the recommendation at the end. A lower result recommends review but remains a soft gate: it never erases the Spanish you produced or traps you in the checkpoint.",
      ],
      points: [
        { label: "COMPREHEND", title: "Follow connected Spanish", description: "Use the whole context rather than hunting for an isolated trigger word." },
        { label: "CONTROL", title: "Coordinate the sentence", description: "Articles, nouns, adjectives, and verbs must support the same subject and meaning." },
        { label: "RECALL", title: "Retrieve without choices", description: "Later tasks remove labels and visible options." },
        { label: "PRODUCE", title: "Create your own description", description: "Finish by connecting identity, state, location, and existence." },
      ],
    },
    {
      id: "s1-reading",
      type: "reading",
      conceptIds: ["gender_agreement", "adjective_agreement", "ser_identity", "ser_origin", "estar_state", "estar_location", "hay_existence", "hay_vs_estar"],
      eyebrow: "Integrated comprehension",
      heading: "Lucía’s new school.",
      instructions: "Read the whole portrait once. Listen to each line, answer from the Spanish, and reveal the translation only after committing to an interpretation.",
      sentences: [
        { id: "s1-r1", text: "Lucía es una estudiante colombiana.", translation: "Lucía is a Colombian student." },
        { id: "s1-r2", text: "Es de Bogotá, pero ahora está en Miami.", translation: "She is from Bogotá, but now she is in Miami." },
        { id: "s1-r3", text: "Hay una escuela grande cerca de su casa.", translation: "There is a large school near her home." },
        { id: "s1-r4", text: "La escuela está en una calle tranquila.", translation: "The school is on a quiet street." },
        { id: "s1-r5", text: "Los profesores son amables y los estudiantes están contentos.", translation: "The teachers are kind and the students are happy." },
        { id: "s1-r6", text: "Hoy Lucía está cansada, pero está lista para la clase.", translation: "Today Lucía is tired, but she is ready for class." },
      ],
      questions: [
        {
          id: "s1-q1",
          prompt: "Where is Lucía from?",
          options: [{ id: "bogota", label: "De Bogotá" }, { id: "miami", label: "De Miami" }],
          correctOptionId: "bogota",
          feedback: "Es de Bogotá gives Lucía’s origin; está en Miami gives her current location.",
          conceptIds: ["ser_origin", "ser_vs_estar_selection"],
        },
        {
          id: "s1-q2",
          prompt: "What does hay introduce?",
          options: [{ id: "school", label: "A school" }, { id: "lucia", label: "Lucía’s location" }],
          correctOptionId: "school",
          feedback: "Hay una escuela introduces the school as new existence in the scene.",
          conceptIds: ["hay_existence", "hay_vs_estar"],
        },
        {
          id: "s1-q3",
          prompt: "Why does the next sentence use está?",
          options: [{ id: "known", label: "La escuela is now identified" }, { id: "identity", label: "It classifies the school" }],
          correctOptionId: "known",
          feedback: "The introduced school becomes an identified subject whose location is given with estar.",
          conceptIds: ["estar_location", "hay_vs_estar"],
        },
        {
          id: "s1-q4",
          prompt: "What does está lista mean in the final sentence?",
          options: [{ id: "ready", label: "She is ready" }, { id: "clever", label: "She is clever" }],
          correctOptionId: "ready",
          feedback: "Estar + lista frames readiness in the class context.",
          conceptIds: ["ser_estar_meaning_change", "estar_state"],
        },
      ],
    },
    {
      id: "s1-listening-context",
      type: "prose",
      conceptIds: ["ser_classification", "estar_state", "estar_location", "hay_existence"],
      eyebrow: "Short listening check",
      heading: "Listen for the information job before reading the translation.",
      paragraphs: [
        "Play the three Spanish lines at natural speed. Keep your eyes on the subject and ask what each verb contributes: description, location, or existence.",
      ],
      spanish: [
        { text: "La biblioteca es moderna.", translation: "The library is modern." },
        { text: "Está en el centro de la escuela.", translation: "It is in the center of the school." },
        { text: "Hay muchos libros interesantes.", translation: "There are many interesting books." },
      ],
    },
    {
      id: "s1-listening-choice",
      type: "choice",
      conceptIds: ["ser_classification", "estar_location", "hay_existence"],
      eyebrow: "Interpret the sequence",
      heading: "What progression did the three lines create?",
      context: "The first describes the library, the second locates it, and the third presents books inside the scene.",
      prompt: "Choose the correct information sequence.",
      options: [
        { id: "describe-locate-introduce", label: "describe → locate → introduce" },
        { id: "locate-introduce-origin", label: "locate → introduce → origin" },
        { id: "introduce-state-identity", label: "introduce → state → identity" },
      ],
      correctOptionId: "describe-locate-introduce",
      correctFeedback: "Es moderna describes, está en el centro locates, and hay muchos libros introduces what is present.",
      incorrectFeedback: "Follow the jobs in order: ser attributes moderna, estar gives the library’s location, and hay presents books.",
    },
    {
      id: "s1-verb-sort",
      type: "sort",
      conceptIds: ["ser_identity", "ser_classification", "ser_origin", "estar_state", "estar_location", "hay_existence"],
      eyebrow: "Mixed control",
      heading: "Sort the intended claims before retrieving forms.",
      prompt: "Choose an English message and place it under the verb family that carries its main information job.",
      buckets: [
        { id: "ser", label: "SER", hint: "identity, classification, or origin" },
        { id: "estar", label: "ESTAR", hint: "state or identified location" },
        { id: "hay", label: "HAY", hint: "existence or presence" },
      ],
      items: [
        { id: "s1-sort-teacher", label: "She is a teacher", answer: "ser" },
        { id: "s1-sort-from-peru", label: "They are from Peru", answer: "ser" },
        { id: "s1-sort-tired", label: "We are tired", answer: "estar" },
        { id: "s1-sort-books-here", label: "The books are here", answer: "estar" },
        { id: "s1-sort-a-school", label: "There is a school", answer: "hay" },
        { id: "s1-sort-three-restaurants", label: "There are three restaurants", answer: "hay" },
      ],
    },
    {
      id: "s1-agreement-builder",
      type: "builder",
      conceptIds: ["gender_agreement", "adjective_agreement", "ser_classification"],
      eyebrow: "Agreement in a complete claim",
      heading: "Build a plural description whose parts cooperate.",
      prompt: "Build: The schools are modern.",
      tokens: ["Las escuelas", "son", "modernas."],
      correctOrder: ["Las escuelas", "son", "modernas."],
      answer: "Las escuelas son modernas.",
      feedback: "Las, escuelas, and modernas all mark feminine plural, while son agrees with the plural subject.",
    },
    {
      id: "s1-control-bridge",
      type: "prose",
      conceptIds: ["gender_agreement", "adjective_agreement", "ser_vs_estar_selection", "hay_vs_estar"],
      eyebrow: "Before support disappears",
      heading: "Run the whole sentence through one decision chain.",
      paragraphs: [
        "Begin with the noun phrase: article, noun, and number establish the subject. Then decide the information job and choose ser, estar, or hay. If an adjective follows, make it agree with the subject.",
        "Hay is the exception to the subject-agreement step because existential hay is impersonal and unchanged. The noun phrase after it can still show singular, plural, and adjective agreement: Hay una escuela moderna; Hay dos escuelas modernas.",
      ],
      points: [
        { label: "REFERENCE", title: "Build or identify the noun phrase", description: "Un/una may introduce; el/la/los/las, names, and possessives often identify." },
        { label: "MEANING", title: "Name the sentence’s job", description: "Identity, classification, origin, state, location, or existence." },
        { label: "FORM", title: "Choose and conjugate", description: "Match ser or estar to the subject; keep existential hay unchanged." },
        { label: "AGREEMENT", title: "Check descriptive words", description: "Make adjectives reflect the subject’s gender and number where their forms change." },
      ],
    },
    {
      id: "s1-mixed-control",
      type: "fill",
      conceptIds: ["gender_agreement", "adjective_agreement", "ser_identity", "ser_classification", "ser_origin", "estar_state", "estar_location", "hay_existence", "hay_vs_estar"],
      eyebrow: "Unsupported sentence control",
      heading: "Complete the mixed foundations.",
      prompt: "Type the missing article, verb, or adjective form. Use the whole sentence to decide.",
      items: [
        { id: "s1-fill-1", before: "Ana ", after: " doctora.", accepted: ["es"], answer: "es", conceptIds: ["ser_classification"], feedback: "A profession classifies Ana, so use es; neutral profession statements omit the article." },
        { id: "s1-fill-2", before: "Nosotros ", after: " de México.", accepted: ["somos"], answer: "somos", conceptIds: ["ser_origin"], feedback: "Origin uses ser, and nosotros selects somos." },
        { id: "s1-fill-3", before: "Lucía ", after: " cansada hoy.", accepted: ["está", "esta"], answer: "está", conceptIds: ["estar_state", "adjective_agreement"], feedback: "Cansada presents Lucía’s state, so use está." },
        { id: "s1-fill-4", before: "Los libros ", after: " en la mesa.", accepted: ["están", "estan"], answer: "están", conceptIds: ["estar_location", "estar_forms"], feedback: "The identified plural books are located with están." },
        { id: "s1-fill-5", before: "", after: " una biblioteca en la escuela.", accepted: ["hay"], answer: "Hay", conceptIds: ["hay_existence"], feedback: "The sentence introduces a library with hay." },
        { id: "s1-fill-6", before: "La biblioteca ", after: " en el centro.", accepted: ["está", "esta"], answer: "está", conceptIds: ["hay_vs_estar", "estar_location"], feedback: "The now-identified library is located with está." },
        { id: "s1-fill-7", before: "", after: " escuelas modernas.", accepted: ["las"], answer: "Las", conceptIds: ["gender_agreement", "adjective_agreement"], feedback: "Escuelas modernas is feminine plural, so the definite article is las." },
        { id: "s1-fill-8", before: "Mis amigas están ", after: ". (happy)", accepted: ["contentas"], answer: "contentas", conceptIds: ["adjective_agreement", "estar_state"], feedback: "Contentas agrees with the feminine plural subject mis amigas." },
      ],
    },
    {
      id: "s1-recall-setup",
      type: "prose",
      conceptIds: ["ser_vs_estar_selection", "hay_vs_estar", "adjective_agreement"],
      eyebrow: "Final recall",
      heading: "Now retrieve the system without category headings.",
      paragraphs: [
        "The next items mix old and new decisions deliberately. Translate the intended message into a Spanish structure instead of searching for the lesson that taught it.",
        "A successful answer does not need a long explanation, but your internal decision should remain precise: what is the subject, what claim is being made, and what must agree?",
      ],
    },
    {
      id: "s1-final-recall",
      type: "fill",
      conceptIds: ["ser_identity", "ser_origin", "estar_state", "estar_location", "hay_existence", "hay_vs_estar", "ser_estar_meaning_change"],
      eyebrow: "Retrieve from the message",
      heading: "Five ideas, no visible choices.",
      prompt: "Complete each Spanish sentence from its meaning or context.",
      items: [
        { id: "s1-final-1", before: "Yo ", after: " estudiante.", accepted: ["soy"], answer: "soy", conceptIds: ["ser_identity", "ser_classification"], feedback: "Student classifies the speaker, so yo selects soy." },
        { id: "s1-final-2", before: "María ", after: " de Perú.", accepted: ["es"], answer: "es", conceptIds: ["ser_origin"], feedback: "Origin uses ser: María es de Perú." },
        { id: "s1-final-3", before: "Ustedes ", after: " listos para la clase.", accepted: ["están", "estan"], answer: "están", conceptIds: ["estar_state", "ser_estar_meaning_change"], feedback: "Listos para la clase means ready; ustedes selects están." },
        { id: "s1-final-4", before: "", after: " dos restaurantes. Los restaurantes están aquí.", accepted: ["hay"], answer: "Hay", conceptIds: ["hay_existence", "hay_vs_estar"], feedback: "The first sentence introduces the restaurants; the second locates them." },
        { id: "s1-final-5", before: "La reunión ", after: " en la escuela.", accepted: ["es"], answer: "es", conceptIds: ["ser_vs_estar_selection"], feedback: "A scheduled event takes place at a location with ser." },
      ],
    },
    {
      id: "s1-original-production",
      type: "free-write",
      conceptIds: ["gender_agreement", "adjective_agreement", "ser_identity", "ser_origin", "estar_state", "estar_location", "hay_existence", "hay_vs_estar"],
      eyebrow: "Original Stage I production",
      heading: "Create a connected four-sentence portrait.",
      prompt: "Describe yourself, another person, or an imagined place. Include identity or origin, a state, a location, and something that exists in the scene.",
      requirements: ["Use a form of ser", "Use a form of estar", "Use hay", "Include an agreeing adjective", "Write at least four connected ideas"],
      example: "Lucía es estudiante y es de Colombia. Está contenta hoy. Está en una escuela nueva. Hay una biblioteca grande en la escuela.",
      minimumCharacters: 72,
      evaluation: {
        minimumIdeas: 4,
        requiredGroups: [
          { accepted: ["soy", "eres", "es", "somos", "son"], missingFeedback: "Add ser for identity, classification, or origin." },
          { accepted: ["estoy", "estás", "estas", "está", "esta", "estamos", "están", "estan"], missingFeedback: "Add estar for a state or identified location." },
          { accepted: ["hay"], missingFeedback: "Use hay to introduce something that exists in the scene." },
          { accepted: ["cansado", "cansada", "cansados", "cansadas", "contento", "contenta", "contentos", "contentas", "moderno", "moderna", "modernos", "modernas", "grande", "grandes", "tranquilo", "tranquila", "tranquilos", "tranquilas"], missingFeedback: "Include a descriptive adjective in a form that fits its noun or subject." },
        ],
        successFeedback: "Your portrait connects the core Stage I systems: reference and agreement, ser, estar, and hay all contribute distinct information.",
      },
    },
    {
      id: "s1-summary",
      type: "summary",
      conceptIds: ["gender_agreement", "adjective_agreement", "ser_vs_estar_selection", "hay_vs_estar"],
      eyebrow: "Stage I decision map",
      heading: "Build meaning in layers.",
      message: "A strong beginner sentence coordinates reference, agreement, and verb meaning rather than solving each word in isolation.",
      ideas: [
        { label: "NOUN PHRASE", question: "Who or what is in the message?", uses: ["article", "gender", "number", "reference"] },
        { label: "SER", question: "Who, what, or from where?", uses: ["identity", "classification", "origin", "event details"] },
        { label: "ESTAR", question: "How or where is the identified subject?", uses: ["state", "location", "agreement"] },
        { label: "HAY", question: "What exists or is present?", uses: ["introduction", "singular or plural", "no agreement"] },
      ],
    },
  ],
  completion: {
    title: "You are ready for Stage II.",
    message: "Your first attempts, unsupported recall, and original production show that the Stage I systems can work together in connected Spanish.",
    reviewTitle: "Review first—recommended.",
    reviewMessage: "You completed the checkpoint and kept your original evidence. A short mixed review is recommended before Stage II, but the checkpoint remains a soft gate.",
  },
};
